### ISSUE TITLE
Welcome

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#100]
![image](https://user-images.githubusercontent.com/44541791/128583884-adb7102a-ec52-43aa-8882-d9de72f89593.png)

Dinheiro: Undefined ? 

iris/config/gerais/config.json
![image](https://user-images.githubusercontent.com/44541791/128583925-99bba307-17cd-4d04-9508-b339a6379664.png)

Iris/config.json
![image](https://user-images.githubusercontent.com/44541791/128583964-4bee9fe8-75c8-4462-8c1e-769906600723.png)
acho esse level UP
await gaming.addValue(user, Number(config.Rei_Dinheiro), nivel, 'money')

aquele pastar
iris/config/gerais/level.json
nao aparece 'money'
![image](https://user-images.githubusercontent.com/44541791/128583996-b1ce6875-f6a7-4061-8cb2-1dca9e040d40.png)

**Comment by KillovSky** [comment]
O sistema não foi moldado pra esse outro dado e não possui esse parametro "money", logo não posso garantir suporte a algo desse tipo, em especial, você pode adicionar sim propriedades lá, mas precisa remoldar a maioria dos comandos de `addValue` e `getValue`, ou seja, seu erro é basicamente uma falha de programação para algo que você digitou incorretamente, procure os locais que você mexeu e deverá achar o erro.
Para isso funcionar, precisará refazer a `functions.js` e a `config.js` para suportar esses valores, e isso é algo que não posso ajudar a fazer.

**Comment by maradona4** [comment]
Ok, agr funcionar 'money' level salvou

**Comment by maradona4** [comment]
![image](https://user-images.githubusercontent.com/44541791/128644683-482b6be4-8178-4cd7-aadc-fe39af8ce1e7.png)

Eu encontrar acho faltam aqui, "money"
agora funcionar salvou ;)
