### ISSUE TITLE
logs console

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#101]
eu queria saber como q faz para aparecer as mensagens no console tb

**Comment by KillovSky** [comment]
Mensagens enormes demais seriam um problemão, mas, basta inserir isso na `config.js` junto aos `ifs` do começo do código...

```javascript
try { console.log(`\nMensagem > "${chats}" \n`) } catch (e) {}
```

...molde como quiser, após isso as mensagens vão aparecer, mas pode causar problemas, tenha cuidado.

**Comment by dodouuglas** [comment]
> Mensagens enormes demais seriam um problemão, mas, basta inserir isso na `config.js` junto aos `ifs` do começo do código...
> 
> ```js
> try { console.log(`\nMensagem > "${chats}" \n`) } catch (e) {}
> ```
> 
> ...molde como quiser, após isso as mensagens vão aparecer, mas pode causar problemas, tenha cuidado.

como faz isso na nova versao?

**Comment by KillovSky** [comment]
Troque `chats` por `body` e prontinho.
