### ISSUE TITLE
mensagens apagadas 

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#102]
eu nao estou conseguindo defenir `isMedia e isImage` no arquivo inde.js para pegar imagens tb para descriptografar e mandar

**Comment by KillovSky** [comment]
Mostre seu código, afinal, não sei exatamente o que você deseja criar.

**Comment by dodouuglas** [comment]
eu sei eu to fazendo primeiro para ele mandar no meu pv ai dps vou fazer para ele mandar aonde a mensagem foi apagada

**Comment by KillovSky** [comment]
> eu sei eu to fazendo primeiro para ele mandar no meu pv ai dps vou fazer para ele mandar aonde a mensagem foi apagada
> 

Pra isso eu pedi seu código, preciso ver onde está o problema que você obteve.

**Comment by dodouuglas** [comment]
`kill.onMessageDeleted(async (msg) => { 
	 const { type, id, from, t, sender, author, isGroupMsg, chat, chatId, caption, isMedia, mimetype, quotedMsg, quotedMsgObj, mentionedJidList } = msg
		//console.log(`mensagem apagada\n mensagem: ${msg.body}\n de: ${msg.from}\n para: ${msg.to}\n`)
		kill.sendText(ownerNumber[0],`Mensagem apag1ada\n mensagem: ${msg.body}\n de: ${msg.from}\n para: ${msg.to}\n`)
	})`

**Comment by PedroBatistop** [comment]
#99
