### ISSUE TITLE
Akinator

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#103]
![image](https://user-images.githubusercontent.com/44541791/128639065-ab135265-4ab8-4553-a6d4-166357fea860.png)

comandos akinator
![image](https://user-images.githubusercontent.com/44541791/128639096-17ec9633-3ebc-428f-823c-f5b05f025b3a.png)

**Comment by PedroBatistop** [comment]
Você mudou alguma coisa na const args? Se sim, tente desfazer a alteração. Qual foi o comando usado para resultar nesse erro?

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/128639065-ab135265-4ab8-4553-a6d4-166357fea860.png)
> 
> comandos akinator
> ![image](https://user-images.githubusercontent.com/44541791/128639096-17ec9633-3ebc-428f-823c-f5b05f025b3a.png)
> 

Alguém usou o comando sem argumentos (nada além de `/akinator`), por isso ativou o erro, o que **NÃO DEVERIA** acontecer, por isso, você fez alguma alteração? Está com versões antigas da Íris? Não? Então insira isso acima do `try`.

```javascript
if (args.length == 0) return await kill.reply(from, mess.noargs() + 'tipo de resposta.', id)
```

E deverá corrigir.

**Comment by maradona4** [comment]
eu peguei aquele arquivo Iris 3.1.1
dps Eu uso NPM I e NPM UPDATE

n sei tudos mudou

**Comment by maradona4** [comment]
agr funcionar obg sem erro
