### ISSUE TITLE
trocar foto do bot

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#104]
kiria um script q a cada 1 dia ele mude a ft do bot mas n to conseguindo affs

**Comment by KillovSky** [comment]
> kiria um script q a cada 1 dia ele mude a ft do bot mas n to conseguindo affs

Meio dificil te responder isso pois é algo grande pra construir e te entregar, mas basicamente, use isso de base para começar na `config.js`, não é recomendado, pois existem infinitas formas de fazer melhor mas pode funcionar.

```javascript
// Coloque acima da module exports
var jaChanged = 0

// Coloque nos ifs
if (jaChanged == 0) {
     jaChanged = 1
     (Insira seu script pra mudar fotos aqui)
     await sleep(86400000) // 1 dia em milissegundos
     jaChanged = 0
}
```

Explicação:

A variavel `jaChanged` controla se já foi trocado a foto.
A `if` verifica o `jaChanged`, rodando apenas se ela tiver valor **0**.
A mudança da `jaChanged` para 1 diz que a foto foi editada no momento.
A `sleep` espera 1 dia para dizer que a foto pode ser mudada novamente, definindo a `isChanged` como 0, que significa "já passou 1 dia, mude a foto de novo".

Boa sorte.

**Comment by PedroBatistop** [comment]
(NÃO OFICIAL)
Crie um arquivo nomeado `lastchanged.json` na pasta Utilidades.
Adicione o seguinte código na `config.js`:
```
		var lastchanged = JSON.parse(fs.readFileSync(`./lib/config/Utilidades/lastchanged.json`))
		if (Date.now() - Number(lastchanged) > 24*60*60*1000 ) {
			console.log(Date.now() - lastchanged)
			const novafoto = await fs.readFileSync(`./lib/media/img/suafoto.png`)
			await kill.setProfilePic(`data:image/png;base64,${novafoto.toString('base64')}`)
			await fs.writeFileSync(`./lib/config/Utilidades/lastchanged.json`, JSON.stringify(Date.now()))
		}
```

Isso mudará a foto a cada 24 horas

**Comment by dodouuglas** [comment]
e q tipo eu fiz uma constante e coloquei as fotos tipo "./foto1.jpg" ai eu queria colocar uma lista de fotos q a cada 1 dia ele muda

**Comment by PedroBatistop** [comment]
```
		var profmeg = Math.floor(Math.random() * 46) + 1
		var lastchanged = JSON.parse(fs.readFileSync(`./Pedro/Textos/lastchanged.json`))
		if (Date.now() - Number(lastchanged) > 24*60*60*1000 ) {
			const novafoto = await fs.readFileSync(`./Pedro/Media/megumin/fotos megumin/perfil/foto (${profmeg}).png`)
			await kill.setProfilePic(`data:image/png;base64,${novafoto.toBuffer().toString('base64')}`)
			await fs.writeFileSync(`./Pedro/Textos/lastchanged.json`, JSON.stringify(Date.now()))
			console.log(color('[FOTO ALTERADA]', 'red'))
		}
```
as fotos devem ter o nome no seuinte formato:

foto (1).png
foto (2).png
foto (3).png
...

mude o "46" do profmeg para o número total de fotos na pasta

**Comment by dodouuglas** [comment]
deu o error `novafoto.toBuffer is not a function`

**Comment by PedroBatistop** [comment]
> deu o error `novafoto.toBuffer is not a function`

Códigos atualizados. Apague a lastchanged.json antiga.

**Comment by PedroBatistop** [comment]
Se quiser, além de mudar automaticamente no tempo determinado, também mudra a foto por comando:

```
case 'fotop':
if (!isOwner) return await kill.reply(from, mess.sodono(), id)
const novafoto = await fs.readFileSync(`./lib/media/img/suafoto (${getrphoto()}).png`)
await kill.setProfilePic(`data:image/png;base64,${novafoto.toString('base64')}`)
lastchanged[0].profile = Date.now()
await fs.writeFileSync(`./lib/config/Utilidades/lastchanged.json`, JSON.stringify(lastchanged))
console.log(color('[FOTO DO PERFIL ALTERADA]', 'red'))
break

case 'fotog':
if (!isOwner) return await kill.reply(from, mess.sodono(), id)
var novafoto = await fs.readFileSync(`./lib/media/img/suafoto2 (${getrphoto()}).png`)
await kill.setGroupIcon('sua-id@g.us', `data:image/png;base64,${novafoto.toString('base64')}`)
lastchanged[0].group = Date.now()
await fs.writeFileSync(`./lib/config/Utilidades/lastchanged.json`, JSON.stringify(lastchanged))
console.log(color('[FOTO DO GRUPO ALTERADA]', 'red'))
break
```

**Comment by dodouuglas** [comment]
> Se quiser, além de mudar automaticamente no tempo determinado, também mudra a foto por comando:
> 
> ```
> case 'fotop':
> if (!isOwner) return await kill.reply(from, mess.sodono(), id)
> const novafoto = await fs.readFileSync(`./lib/media/img/suafoto (${getrphoto()}).png`)
> await kill.setProfilePic(`data:image/png;base64,${novafoto.toString('base64')}`)
> lastchanged[0].profile = Date.now()
> await fs.writeFileSync(`./lib/config/Utilidades/lastchanged.json`, JSON.stringify(lastchanged))
> console.log(color('[FOTO DO PERFIL ALTERADA]', 'red'))
> break
> 
> case 'fotog':
> if (!isOwner) return await kill.reply(from, mess.sodono(), id)
> var novafoto = await fs.readFileSync(`./lib/media/img/suafoto2 (${getrphoto()}).png`)
> await kill.setGroupIcon('sua-id@g.us', `data:image/png;base64,${novafoto.toString('base64')}`)
> lastchanged[0].group = Date.now()
> await fs.writeFileSync(`./lib/config/Utilidades/lastchanged.json`, JSON.stringify(lastchanged))
> console.log(color('[FOTO DO GRUPO ALTERADA]', 'red'))
> break
> ```
ReferenceError: getphoto is not defined

**Comment by dodouuglas** [comment]
conseguir pqp kkk
