### ISSUE TITLE
iris does not give welcome message

### ISSUE THREAD

**Issue by bennyJCc** [KillovSky/iris#105]
iris does not give a welcome message, when someone enters through a link from any group, it helps

**Comment by PedroBatistop** [comment]
Is welcome activated in the group? (use /welcome on)

When the person joins the group is anything shown on the console?

Have you tried restarting the bot or leaving the group and re-entering with the bot?

Does this only happen when the person enters through the link?

**Comment by bennyJCc** [comment]
> ¿Está activada la bienvenida en el grupo? (uso / bienvenida)
> yes
> Cuando la persona se une al grupo, ¿se muestra algo en la consola?
> the console does not show anything
> ¿Ha intentado reiniciar el bot o abandonar el grupo y volver a ingresar con el bot?
> yes and many times I even deleted and cloned it again and that
> ¿Esto solo sucede cuando la persona ingresa a través del enlace?
   when it enters through the link and when I add it either manually or with the command "/ add"

**Comment by bennyJCc** [comment]
> ¿Está activada la bienvenida en el grupo? (uso / bienvenida)
> yes 
> Cuando la persona se une al grupo, ¿se muestra algo en la consola?
> when it is by link and also when I do it manually either with the command "/ add"
> ¿Ha intentado reiniciar el bot o abandonar el grupo y volver a ingresar con el bot?
> Yes I did, I even deleted it and cloned it again
> ¿Esto solo sucede cuando la persona ingresa a través del enlace?
     when it enters through the link and when I add it either manually or with the command "/ add"

**Comment by KillovSky** [comment]
> > ¿Está activada la bienvenida en el grupo? (uso / bienvenida)
> > yes 
> > Cuando la persona se une al grupo, ¿se muestra algo en la consola?
> > when it is by link and also when I do it manually either with the command "/ add"
> > ¿Ha intentado reiniciar el bot o abandonar el grupo y volver a ingresar con el bot?
> > Yes I did, I even deleted it and cloned it again
> > ¿Esto solo sucede cuando la persona ingresa a través del enlace?
>      when it enters through the link and when I add it either manually or with the command "/ add"
> 

Pode me mostrar seu terminal? Desconfio que seja um erro com o `getProfilePic`, isso quer dizer que a Iris esta falhando em obter fotos das pessoas que você adiciona.
Também pode ser uma mudança na `wa-automate`, é raro mas pode acontecer, iremos analisar essa segunda opção.

**Comment by bennyJCc** [comment]
> > > ¿Está activada la bienvenida en el grupo? (uso / bienvenida) 
> > > yes 
> > > Cuando la persona se une al grupo, ¿se muestra algo en la consola? 
> > > cuando es por enlace y también cuando lo hago manualmente ya sea con el comando "/ agregar" 
> > > ¿Ha intentado reiniciar el bot o abandonar el grupo y volver a ingresar con el bot? 
> > > Sí lo hice, incluso lo borré y lo 
> > > cloné de nuevo ¿Esto solo sucede cuando la persona ingresa a través del enlace? 
> > > cuando entra por el enlace y cuando lo agrego ya sea manualmente o con el comando "/ agregar"
> 
> Pode me mostrar seu terminal? Desconfio que seja um erro com o `getProfilePic`, isso quer dizer que a Iris esta falhando em obter fotos das pessoas que você adiciona.
> Também pode ser uma mudança na `wa-automate`, é raro mas pode acontecer, iremos analisar essa segunda opção.
> 
> (¿Puedes mostrar tu terminal? Tal vez esto sea un error `getProfilePic`, esto significa que Iris no puede obtener las fotos de perfil de los usuarios que has agregado.
> También puede ser un cambio en el `wa-automate`sistema, es raro pero puede suceder, verificaremos esta posibilidad. )

una pregunta. y como veo sobre la terminal y eso? , 7u7

**Comment by bennyJCc** [comment]
> > > ¿Está activada la bienvenida en el grupo? (uso / bienvenida) 
> > > yes 
> > > Cuando la persona se une al grupo, ¿se muestra algo en la consola? 
> > > cuando es por enlace y también cuando lo hago manualmente ya sea con el comando "/ agregar" 
> > > ¿Ha intentado reiniciar el bot o abandonar el grupo y volver a ingresar con el bot? 
> > > Sí lo hice, incluso lo borré y lo 
> > > cloné de nuevo ¿Esto solo sucede cuando la persona ingresa a través del enlace? 
> > > cuando entra por el enlace y cuando lo agrego ya sea manualmente o con el comando "/ agregar"
> 
> Pode me mostrar seu terminal? Desconfio que seja um erro com o `getProfilePic`, isso quer dizer que a Iris esta falhando em obter fotos das pessoas que você adiciona.
> Também pode ser uma mudança na `wa-automate`, é raro mas pode acontecer, iremos analisar essa segunda opção.
> 
> (¿Puedes mostrar tu terminal? Tal vez esto sea un error `getProfilePic`, esto significa que Iris no puede obtener las fotos de perfil de los usuarios que has agregado.
> También puede ser un cambio en el `wa-automate`sistema, es raro pero puede suceder, verificaremos esta posibilidad. )

Como posso mostrar o terminal?

**Comment by KillovSky** [comment]
> > > > ¿Está activada la bienvenida en el grupo? (uso / bienvenida) 
> > > > yes 
> > > > Cuando la persona se une al grupo, ¿se muestra algo en la consola? 
> > > > cuando es por enlace y también cuando lo hago manualmente ya sea con el comando "/ agregar" 
> > > > ¿Ha intentado reiniciar el bot o abandonar el grupo y volver a ingresar con el bot? 
> > > > Sí lo hice, incluso lo borré y lo 
> > > > cloné de nuevo ¿Esto solo sucede cuando la persona ingresa a través del enlace? 
> > > > cuando entra por el enlace y cuando lo agrego ya sea manualmente o con el comando "/ agregar"
> > 
> > Pode me mostrar seu terminal? Desconfio que seja um erro com o `getProfilePic`, isso quer dizer que a Iris esta falhando em obter fotos das pessoas que você adiciona.
> > Também pode ser uma mudança na `wa-automate`, é raro mas pode acontecer, iremos analisar essa segunda opção.
> > 
> > (¿Puedes mostrar tu terminal? Tal vez esto sea un error `getProfilePic`, esto significa que Iris no puede obtener las fotos de perfil de los usuarios que has agregado.
> > También puede ser un cambio en el `wa-automate`sistema, es raro pero puede suceder, verificaremos esta posibilidad. )
> 
> Como posso mostrar o terminal?
> 

Tire um print da tela na hora que alguém for adicionado.

**Comment by luizrn** [comment]
estou com o mesmo problema, nao mostra nada no console, não da erro, nada, ja tentei fazer os procedimentos do  #75 e do #107 , sera que pode ser algum problema com o wa-automate

**Comment by KillovSky** [comment]
> estou com o mesmo problema, nao mostra nada no console, não da erro, nada, ja tentei fazer os procedimentos do  #75 e do #107 , sera que pode ser algum problema com o wa-automate

Se não aparecer a `console.log` do `welcome`, e por que ele não está ativado, ou seja, no console deve aparecer a mensagem do `welcome` mesmo falhando no envio no WhatsApp, caso contrario significa que ele não está ligado.

**Comment by EvertonCdC** [comment]
aqui também não está funcionando, está o código original, não da erro no console e nem nada do tipo, a pessoa pode entrar pelo link, ser add por alguém e pelo bot que ele não manda msg

**Comment by EndervorHero** [comment]
Same here!
 I have it activated, since the last update it doesn´t work, I think it maybe due to the new automate wa system or the error with the profile photo, but it doesn't give an error message...its weird

**Comment by KillovSky** [comment]
Meio estranho, vou dar uma olhada sobre o novo sistema da wa-automate.

**Comment by wesley0209** [comment]
Eu reparei que acontece isso depois que usa o /greet

**Comment by KillovSky** [comment]
> Eu reparei que acontece isso depois que usa o /greet 

Entendo, o greet me funcionava perfeito, vou olhar sobre quandi obter tempo, agradeço.

**Comment by EvertonCdC** [comment]
o bot até começa a digitar, mas não realiza o envio da msg
