### ISSUE TITLE
Welcome/Bye

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#107]
![image](https://user-images.githubusercontent.com/44541791/128755859-07460089-c580-4b0b-aa43-1c9dd6657ff1.png)

Ele entrou, ele tem perfil foto
quais problema erro?

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/128755859-07460089-c580-4b0b-aa43-1c9dd6657ff1.png)
> 
> Ele entrou, ele tem perfil foto
> quais problema erro?

Você editou alguma coisa? O erro me diz que foi uma falha no envio da mensagem, o sistema de welcome padrão não tem erros na mensagem.

Mas caso seja algo mais profundo como a foto, siga o procedimento da #75, faça ele na `index.js`, na var `profile`.

(Basta inserir isso no `if` de la.)

`profile == 'ERROR: 401'`

Desfaça qualquer alteração que você tenha feito na mensagem e teste.

**Comment by maradona4** [comment]
Vlz agr funcionar
