### ISSUE TITLE
Bomb

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#108]
![image](https://user-images.githubusercontent.com/44541791/128757892-fbdf2a67-fdf5-4b70-a533-33499e200f70.png)

como bomb Ex eu uso: /bomb 554196... 1

ele(a) mandou erro bot

**Comment by KillovSky** [comment]
Erro relacionado a uma exports que falta que já corrigi no update que irei fazer em breve, basta esperar - o que pode demorar muito - ou ajustar você mesmo.
Abra a `case 'bomb':` e apague a `mess.bombstd()` e no lugar dela insira uma mensagem dizendo que o bomb foi executado, isso corrige.
