### ISSUE TITLE
Reload

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#109]
![image](https://user-images.githubusercontent.com/44541791/128787968-c565cc35-5aca-4672-a301-2ba043a291e2.png)

Bot nao funcionar reload?

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/128787968-c565cc35-5aca-4672-a301-2ba043a291e2.png)
> 
> Bot nao funcionar reload?

Bug com relação a `wa-automate`, não é algo que posso corrigir, mas tenha certeza que esta com os módulos atualizados com o `npm update`.
