### ISSUE TITLE
Bug comando (darkmode)

### ISSUE THREAD

**Issue by LucasAllen1233** [KillovSky/iris#111]
Olá não estou conseguindo usar o seguinte comando o darkmode que no caso seria o darkmode do (whatsapp web) porém ele diz (FALHAR AO INICIADO NO whatsapp normal) e no cmd ele aparece uma linha com vários erros vou anexar os 2 aq,  https://imgur.com/tL7Kfa7        https://imgur.com/CGASQOD   print no config.js: https://imgur.com/ZBJCdbl

**Comment by KillovSky** [comment]
> Olá não estou conseguindo usar o seguinte comando o darkmode que no caso seria o darkmode do (whatsapp web) porém ele diz (FALHAR AO INICIADO NO whatsapp normal) e no cmd ele aparece uma linha com vários erros vou anexar os 2 aq,  https://imgur.com/tL7Kfa7        https://imgur.com/CGASQOD   print no config.js: https://imgur.com/ZBJCdbl

Desfaça todas as modificações que você fez na `case`, está tudo **incorreto**, a `off` deveria ser `false` e `disabled`, não os parametros atuais da sua print (no código da Íris está correto).

**Comment by maradona4** [comment]
![image](https://user-images.githubusercontent.com/44541791/128951570-2914a612-2a2b-4465-a6c7-cd6ef0936932.png)

Estranho, nao sei  nunca modificar aqui "DarkMode"
antes eu tinha baixar 
github beta 3.1.1
npm i , dps npm update, n sei tudos mudar

**Comment by maradona4** [comment]
assim separar arquivo

Download/Iris-Main [COR TELA PRETO]
Mateus/Iris [COR AZUL]

**Comment by KillovSky** [comment]
O código em si já está perfeito, mas ali no print dele o código foi reescrito incorretamente, se algum outro problema aparecer no código e ele estiver ok, é relacionado aos `patches.json` da `Wa-Automate` ou uma atualização grave no `Web WhatsApp`, isso é corrigido por eles, quando corrigido basta rodar `npm update`.
