### ISSUE TITLE
Perfil

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#112]
![image](https://user-images.githubusercontent.com/44541791/128954187-bc811e16-1fee-49e7-bf33-e861528e6112.png)

Console log
![image](https://user-images.githubusercontent.com/44541791/128954242-22537634-2968-407b-8120-7e49a625b643.png)
Tem problema cmd /perfil

Aquele Index.js > bem vindo/bye, agora funcionar sem perfil/perfil

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/128954187-bc811e16-1fee-49e7-bf33-e861528e6112.png)
> 
> Console log
> ![image](https://user-images.githubusercontent.com/44541791/128954242-22537634-2968-407b-8120-7e49a625b643.png)
> Tem problema cmd /perfil
> 
> Aquele Index.js > bem vindo/bye, agora funcionar sem perfil/perfil

Tente inserir isso no `if`:

```javascript
pic == 'ERROR: 401'
```

Embora o status de erro seja 400, que significa problema no servidor, o nosso servidor é o proprio `WhatsApp`, com algumas relações com o servidor da `Wa-Automate`, acontece com todos? Se não, tente recolocar sua foto de perfil.

**Comment by maradona4** [comment]
Ok, agr funcionar perfil
