### ISSUE TITLE
BUG  CMD

### ISSUE THREAD

**Issue by PANINOBR** [KillovSky/iris#116]
Olá sempre que eu uso algum comando ele dá um erro, eu tenho que digitar 2 vezes o mesmo comando para ele reconhecer e (funcionar) isso acontece as vezes não toda (hora) mas creio eu que talvez seja alguma falta de update que não fiz no npm (cmd) ou preciso modificar algo no config.json? erro abaixo

![image](https://user-images.githubusercontent.com/48421679/129332601-e0ded881-7357-4ae3-9370-f18c7b1adb27.png)

**Comment by KillovSky** [comment]
> Olá sempre que eu uso algum comando ele dá um erro, eu tenho que digitar 2 vezes o mesmo comando para ele reconhecer e (funcionar) isso acontece as vezes não toda (hora) mas creio eu que talvez seja alguma falta de update que não fiz no npm (cmd) ou preciso modificar algo no config.json? erro abaixo
> 
> ![image](https://user-images.githubusercontent.com/48421679/129332601-e0ded881-7357-4ae3-9370-f18c7b1adb27.png)
> 

A linha `157` não use nenhuma `id`, mostre a sua linha `157`.

**Comment by wesley0209** [comment]
O meu tbm esta assim 
![IMG_20210813_094614](https://user-images.githubusercontent.com/83685462/129359304-b43db36a-5552-449d-832a-a4cbe493ad28.jpg)
![IMG_20210813_094711](https://user-images.githubusercontent.com/83685462/129359319-ec5a5494-893f-432e-b30b-dcd24399f785.jpg)

**Comment by tiagopy2000** [comment]
o meu tbm, ela não consegue ler as prioridades do id,

![image](https://user-images.githubusercontent.com/61856308/129359522-5c17393b-7f29-42fa-93e4-769c08a6d2a4.png)

em avisos de whatsapp, ela reporta esse erro 
![image](https://user-images.githubusercontent.com/61856308/129359717-2d3890aa-f3df-43cd-b9c6-595b84fa2f62.png)

**Comment by tiagopy2000** [comment]
opa estou voltando aki pra avisa


![image](https://user-images.githubusercontent.com/61856308/129365930-22e70954-d264-4769-98e5-6e5c63d7d0f1.png)

com a remoção disso na linha 

153 q antes era const randomMember = isGroupMsg ? aMemberS.id : user

e agr ficou assim : 	const randomMember = isGroupMsg ? aMemberS : user

Lucas se pude da uma olhada e ver se isso não vai altera nada na iris, vlw

**Comment by KillovSky** [comment]
Entendo, obrigado a todos, vou fazer a correção pra próxima atualizacão gigante.

**Comment by PedroBatistop** [comment]
Está acontecendo a mesma coisa aqui.

**Comment by tiagopy2000** [comment]
tentou tira o id da linha 153 ?

**Comment by PedroBatistop** [comment]
> opa estou voltando aki pra avisa
> 
> ![image](https://user-images.githubusercontent.com/61856308/129365930-22e70954-d264-4769-98e5-6e5c63d7d0f1.png)
> 
> com a remoção disso na linha
> 
> 153 q antes era const randomMember = isGroupMsg ? aMemberS.id : user
> 
> e agr ficou assim : const randomMember = isGroupMsg ? aMemberS : user
> 
> pra mim resolveu o erro e todos os comandos estão funcionando normalmente
> 
> Lucas se pude da uma olhada e ver se isso não vai altera nada na iris, vlw

Os comandos que usam randomMember param de funcionar!

**Comment by PedroBatistop** [comment]
Após atualizar os módulos e realizar vários testes nenhum erro voltou a ocorrer, mantendo o "id" em `const randomMember = isGroupMsg ? aMemberS.id : user`. Tenham certeza de manter seus módulos atualizados com `npm update`. A retirada do "id" resultará em erros nos comandos que pegam usuários aleatórios, como o /random.

**Comment by tiagopy2000** [comment]
ou porem mesmo com o npm update, ela continuou com o erro, vou tentar novamente e dou retorno

**Comment by tiagopy2000** [comment]
Ok, vlw vou da uma olhada

**Comment by PANINOBR** [comment]
Então necessariamente precisaria colocar o const randomMember = isGroupMsg ? aMemberS.id : user, e logo o npm update para verificar se funcionou

**Comment by PedroBatistop** [comment]
> Então necessariamente precisaria colocar o const randomMember = isGroupMsg ? aMemberS.id : user, e logo o npm update para verificar se funcionou

Não, o `npm update` vai manter seus módulos atualizados e eliminar qualquer problema de incompatibilidade de versões, ao alterar a constante os comandos que dependem dela pararão de funcionar.
