### ISSUE TITLE
MutePv nem Muteall reconhecido

### ISSUE THREAD

**Issue by PANINOBR** [KillovSky/iris#117]
Não sei se é bug ao certo ou falha de algum cmd que precisa ativar, mas acontece da seguinte maneira /mutepv seria para bloquear um número certo? já que diz que necessitaria de um 'ID' peguei id de um grupo pelo cmd /grupos e dei /mutepv on e o id do grupo diz que o comando foi ativado mas quando uso comandos no grupo o bot ainda está liberado todos conseguem usar os 'comandos' ainda, help

![image](https://user-images.githubusercontent.com/48421679/129403011-7e3bbc38-5a48-4a89-ab0d-1619d43785fe.png)

**Comment by PANINOBR** [comment]
Nem !mutepv, nem !muteall funciona help

**Comment by PANINOBR** [comment]
Foto no 'config.js' abaixo

![image](https://user-images.githubusercontent.com/48421679/129404558-e7ed5243-bc5d-4c86-9c20-b0ed7163f26a.png)

**Comment by KillovSky** [comment]
Você está tentando mutar si mesmo? A Íris não ignora o dono, mas de qualquer forma em si, o muteall deveria funcionar pois ele não é de arquivos, ele usa uma var diretamente, meio dificil entender a causa do problema, no seu console é exibido a mensagem dizendo que está mutado?

Sobre o 'ID de grupo', ele não funciona no mutepv, mas uma melhoria para mutar 'a distancia' vai acontecer, até lá, para mutar grupos use `/mute on`.

**Comment by PANINOBR** [comment]
@KillovSky Entendo, agora usei !mute on e !muteall on no grupo funcionou, só o /mutepv mesmo, enfim espero que numa próxima atualização você consiga colocar uma opção como 'bloquear grupos através do id' print do console abaixo

![image](https://user-images.githubusercontent.com/48421679/129427788-2b486c88-278c-45df-9fb7-629dbcae29d5.png)
