### ISSUE TITLE
erro na ativação

### ISSUE THREAD

**Issue by KingBot422** [KillovSky/iris#118]
ao realizar todas as api e config necessarias.... ao dar o npm i, instala corretamente tudo... mas ao dar o npm start, da uma serie de erross....... ja fiz um teste de apagar a pasta node modules... instalar novamente através do comando npm i.... mas ainda permanece o erro....
![image](https://user-images.githubusercontent.com/88904502/129421450-032894ae-784c-405e-9494-d9b91e3cd831.png)
![image](https://user-images.githubusercontent.com/88904502/129421490-5640ad21-3dbf-42d6-b420-d740c8d26af0.png)

**Comment by KillovSky** [comment]
> ao realizar todas as api e config necessarias.... ao dar o npm i, instala corretamente tudo... mas ao dar o npm start, da uma serie de erross....... ja fiz um teste de apagar a pasta node modules... instalar novamente através do comando npm i.... mas ainda permanece o erro....
> ![image](https://user-images.githubusercontent.com/88904502/129421450-032894ae-784c-405e-9494-d9b91e3cd831.png)
> ![image](https://user-images.githubusercontent.com/88904502/129421490-5640ad21-3dbf-42d6-b420-d740c8d26af0.png)
> 

Você configurou a sua `config.json` incorretamente, revise-a, tenha plena certeza de **NUNCA APAGAR** as aspas e as virgulas das linhas que a tem no final.
