### ISSUE TITLE
error no xvideos

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#119]
![image](https://user-images.githubusercontent.com/79427063/129422888-3681dc09-02a2-4d03-b85e-44e82ab009f7.png)

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/79427063/129422888-3681dc09-02a2-4d03-b85e-44e82ab009f7.png)
> 

Bem, ai basicamente diz que não achou nenhum resultado pra busca - eu deveria ter colocado um try-catch ou verificador mas ok - acontece sempre ou apenas algumas vezes/só essa?
