### ISSUE TITLE
Falha Geral

### ISSUE THREAD

**Issue by wesley0209** [KillovSky/iris#120]
Geralmente acontece quando usa o comando /play, pode me ajudar ?

![IMG_20210814_075446](https://user-images.githubusercontent.com/83685462/129444122-1b07209e-7880-43f5-a31e-312bdc02b924.jpg)

**Comment by KillovSky** [comment]
> Geralmente acontece quando usa o comando /play, pode me ajudar ?
> 
> ![IMG_20210814_075446](https://user-images.githubusercontent.com/83685462/129444122-1b07209e-7880-43f5-a31e-312bdc02b924.jpg)
> 

É literalmente o que diz ai, houve um erro relacionado a sua sessão do WhatsApp Web, aparentemente a página fechou, isso é bem raro de ocorrer - a menos que tenha editado algo e saiu errado, como esquecer de por um break  - de todo modo, mantenha seus módulos atualizados com o `npm update`.

P.S: Isso ocorre com frequência?

**Comment by wesley0209** [comment]
> > Geralmente acontece quando usa o comando /play, pode me ajudar ?
> > ![IMG_20210814_075446](https://user-images.githubusercontent.com/83685462/129444122-1b07209e-7880-43f5-a31e-312bdc02b924.jpg)
> 
> É literalmente o que diz ai, houve um erro relacionado a sua sessão do WhatsApp Web, aparentemente a página fechou, isso é bem raro de ocorrer - a menos que tenha editado algo e saiu errado, como esquecer de por um break - de todo modo, mantenha seus módulos atualizados com o `npm update`.
> 
> P.S: Isso ocorre com frequência?

Sim. Acontece frequentemente

**Comment by KillovSky** [comment]
> > > Geralmente acontece quando usa o comando /play, pode me ajudar ?
> > > ![IMG_20210814_075446](https://user-images.githubusercontent.com/83685462/129444122-1b07209e-7880-43f5-a31e-312bdc02b924.jpg)
> > 
> > É literalmente o que diz ai, houve um erro relacionado a sua sessão do WhatsApp Web, aparentemente a página fechou, isso é bem raro de ocorrer - a menos que tenha editado algo e saiu errado, como esquecer de por um break - de todo modo, mantenha seus módulos atualizados com o `npm update`.
> > 
> > P.S: Isso ocorre com frequência?
> 
> Sim. Acontece frequentemente

Verifique se você possui os requisitos do comando `/Play`.

- Ffmpeg
- Visual C++
- Python
- Chrome

O `Chrome` é **SUPER ESSENCIAL** para os comandos de mídia, sua falta **pode** causar um erro desses, certifique-se de ter todos instalados.

**Comment by wesley0209** [comment]
> > > > Geralmente acontece quando usa o comando /play, pode me ajudar ?
> > > > ![IMG_20210814_075446](https://user-images.githubusercontent.com/83685462/129444122-1b07209e-7880-43f5-a31e-312bdc02b924.jpg)
> > > 
> > > 
> > > É literalmente o que diz ai, houve um erro relacionado a sua sessão do WhatsApp Web, aparentemente a página fechou, isso é bem raro de ocorrer - a menos que tenha editado algo e saiu errado, como esquecer de por um break - de todo modo, mantenha seus módulos atualizados com o `npm update`.
> > > P.S: Isso ocorre com frequência?
> > 
> > 
> > Sim. Acontece frequentemente
> 
> Verifique se você possui os requisitos do comando `/Play`.
> 
> * Ffmpeg
> * Visual C++
> * Python
> * Chrome
> 
> O `Chrome` é **SUPER ESSENCIAL** para os comandos de mídia, sua falta **pode** causar um erro desses, certifique-se de ter todos instalados.

faltava o python, obrigado, voce e 10
