### ISSUE TITLE
Whatsapp Beta

### ISSUE THREAD

**Issue by wesley0209** [KillovSky/iris#121]
Conectei o bot com o WhatsApp beta mas ele n reconhece nenhum comando. 

![IMG_20210814_132814](https://user-images.githubusercontent.com/83685462/129452967-90e9217d-77d7-483c-b77d-1b98c8397b1f.jpg)

**Comment by KillovSky** [comment]
> Conectei o bot com o WhatsApp beta mas ele n reconhece nenhum comando. 
> 
> ![IMG_20210814_132814](https://user-images.githubusercontent.com/83685462/129452967-90e9217d-77d7-483c-b77d-1b98c8397b1f.jpg)
> 

Erro referente a `wa-automate`, não a Íris, de toda forma, apague a `iris.data` & desconecte do WhatsApp Web no celular, reinicie a Iris e tente escanear o QR-Code novamente, se persistir tente entrar e sair do grupo.
