### ISSUE TITLE
Erro em alguns comandos

### ISSUE THREAD

**Issue by EmanuelPeixoto** [KillovSky/iris#122]
/gtav O servidor negou o upload da foto, tente novamente dentro de uns minutos.
![Screenshot_7](https://user-images.githubusercontent.com/86881881/129456582-c98d0f56-7772-47ce-91b6-fbd2d8953268.png)

**Comment by KillovSky** [comment]
Mude a linha:

```javascript
const getWastedPic = await decryptMedia(wantedPict, uaOverride)
```

Para:

```javascript
const getWastedPic = await decryptMedia(wastedPict, uaOverride)
```

Peço desculpas por um erro tão obvio, irei corrigir assim que puder no código.
