### ISSUE TITLE
Tem como fazer rodar comandos pelo whatsapp do bot?

### ISSUE THREAD

**Issue by EmanuelPeixoto** [KillovSky/iris#123]
https://github.com/KillovSky/iris/blob/main/config.js#L200

eu vi essa linha aqui, mas n sei oq faz pra funcionar

**Comment by KillovSky** [comment]
Sim, você pode rodar comandos pelo WhatsApp da Íris sem precisar de um segundo número, basta entrar em um chat consigo mesmo, não esqueça de ativar esse sistema na `index.js`, a ativação por lá é **ESSENCIAL**.

Como faço isso? É simples!
Crie um link `wa.me` com seu número e entre nele pelo WhatsApp!

`wa.me/seuNúmero`

Por exemplo:

`wa.me/+551092837465`

Quando acessar, você estará em um chat com você mesmo, basta rodar os comandos ai ;)
