### ISSUE TITLE
Fake Status (Question)

### ISSUE THREAD

**Issue by EndervorHero** [KillovSky/iris#124]
Hello 

Wa Automate have the function to send fake status in the replys like Baileys? I thinks it looks cool n.n

When the next update comes out? i'm exciting lol

Good Luck!

**Comment by KillovSky** [comment]
> Hello 
> 
> Wa Automate have the function to send fake status in the replys like Baileys? I thinks it looks cool n.n
> 
> When the next update comes out? i'm exciting lol
> 
> Good Luck!

A wa-automate diz que pode marcar a mensagem usando a sua ID, a gente coloca a `id` no final dos comandos `kill`, mas referenciando a mensagem atual, se acharmos a ID do status, que desconfio ser `status@broadcast` ou algo assim, podemos sem problemas marcar um status, mas até o momento, não tenho uma ideia de como.
