### ISSUE TITLE
Gerador

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#125]
![image](https://user-images.githubusercontent.com/44541791/129478193-90088cbe-6b36-4931-8e7e-74d83c94ca13.png)

**Comment by KillovSky** [comment]
Foi um erro de digito meu, desculpe, entre na config e procure por `lib/scripts`, deixe apenas `lib`, isso deve corrigir o `gerador` e a `news`.

**Comment by maradona4** [comment]
Valeu agora funcionar 
![image](https://user-images.githubusercontent.com/44541791/129480247-e9984926-0f67-4e15-83e3-10b5726b4fa8.png)
![image](https://user-images.githubusercontent.com/44541791/129480252-5711f1f2-0bfb-4050-bfba-a64ec5fb0702.png)

**Comment by PANINOBR** [comment]
Tava com o mesmo erro, thank @KillovSky 

![image](https://user-images.githubusercontent.com/48421679/129480402-e236e0fa-f2f5-4811-a691-3f6f087d179f.png)
