### ISSUE TITLE
cmd /video [yt link]

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#126]
![image](https://user-images.githubusercontent.com/44541791/129482077-1c56d1df-21ab-4729-9a80-8c23a35d870b.png)

pq ultrapassa 16 mb limite?

**Comment by maradona4** [comment]
a vdd eu leia .-.

esse id: #70

**Comment by maradona4** [comment]
![image](https://user-images.githubusercontent.com/44541791/129484411-0e7fd639-4ba2-4950-be1d-f218157e8e90.png)

A denovo ;-;

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/129484411-0e7fd639-4ba2-4950-be1d-f218157e8e90.png)
> 
> A denovo ;-;
> 

Abra a `case 'video':`, lá possui instruções de como resolver esse bug especifico, de forma geral, remova a `replace(...)` de tudo, isso corrige - assim como pode estragar mais - o comando.

P.S: Isso ocorre por que não foi possivel ler o número do usuario, não é um bug frequente pra todas as pessoas.

**Comment by maradona4** [comment]
não achei replace

			

**case 'video':
if (args.length == 0) return await kill.reply(from, mess.noargs() + 'Títulos do YouTube.', id)
try {
await kill.reply(from, mess.wait(), id)
const vipres = await ytsearch(`${body.slice(7)}`)
await kill.sendYoutubeLink(from, `${vipres.all[0].url}`, '\n' + mess.play(vipres))
await youtubedl(`https://www.youtube.com/watch?v=${vipres.all[0].videoId}`, { noWarnings: true, noCallHome: true, noCheckCertificate: true, preferFreeFormats: true, youtubeSkipDashManifest: true, referer: `https://www.youtube.com/watch?v=${vipres.all[0].videoId}`, getUrl: true, x: true, format: 'mp4', skipDownload: true, matchFilter: `filesize < ${Number(config.Max_Download_Size)}M` }).then(async (video) => { await kill.sendFileFromUrl(from, video, `${vipres.all[0].title}.mp4`, `${vipres.all[0].title}`, id) })
} catch (error) {
await kill.reply(from, mess.verybig(), id)
console.log(color('[VIDEO]', 'crimson'), color(`→ Obtive erros no comando ${prefix}${command} → ${error.message} - Você pode ignorar.`, 'gold'))
}
break**

**Comment by KillovSky** [comment]
> não achei replace
> 
> 			
> 
> ```
> 			case 'video':
> 				if (args.length == 0) return await kill.reply(from, mess.noargs() + 'Títulos do YouTube.', id)
> 				try {
> 					await kill.reply(from, mess.wait(), id)
> 					const vipres = await ytsearch(`${body.slice(7)}`)
> 					await kill.sendYoutubeLink(from, `${vipres.all[0].url}`, '\n' + mess.play(vipres))
> 					await youtubedl(`https://www.youtube.com/watch?v=${vipres.all[0].videoId}`, { noWarnings: true, noCallHome: true, noCheckCertificate: true, preferFreeFormats: true, youtubeSkipDashManifest: true, referer: `https://www.youtube.com/watch?v=${vipres.all[0].videoId}`, getUrl: true, x: true, format: 'mp4', skipDownload: true, matchFilter: `filesize < ${Number(config.Max_Download_Size)}M` }).then(async (video) => { await kill.sendFileFromUrl(from, video, `${vipres.all[0].title}.mp4`, `${vipres.all[0].title}`, id) })
> 				} catch (error) {
> 					await kill.reply(from, mess.verybig(), id)
> 					console.log(color('[VIDEO]', 'crimson'), color(`→ Obtive erros no comando ${prefix}${command} → ${error.message} - Você pode ignorar.`, 'gold'))
> 				}
> 				break
> ```

Entendi, então basicamente foi so um erro de não ter encontrado resultados.

**Comment by maradona4** [comment]
Serio,  aparece ele[a] continuar "você pode ignorar" replace of null

**Comment by KillovSky** [comment]
> Serio,  aparece ele[a] continuar "você pode ignorar" replace of null
> 

Nao tenho uma ideia geral de como corrigir pois o bug e na youtube-dl-exec, enfim, tehte reinstalar esse módulo.

**Comment by maradona4** [comment]
Ok, vou usar "npm update"
