### ISSUE TITLE
cmd /botfoto

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#127]
![image](https://user-images.githubusercontent.com/44541791/129485739-ebdc5534-824b-4367-a428-1d4122608c20.png)

code
![image](https://user-images.githubusercontent.com/44541791/129485751-18bfedff-3d7e-4f28-a07a-32cb195998b6.png)

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/129485739-ebdc5534-824b-4367-a428-1d4122608c20.png)
> 
> code
> ![image](https://user-images.githubusercontent.com/44541791/129485751-18bfedff-3d7e-4f28-a07a-32cb195998b6.png)
> 

Mesmo esquema da #112, você inseriu `400`, deveria ser `401`.
