### ISSUE TITLE
como mandar videos

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#128]
eu to querendo saber como manda foto/video com legenta pq n to conseguindo eu tentei `kill.sendFile(from, './video.mp4', id)` mas ele manda a legenta com o id do chat e se eu tentar `kill.sendFile(from, './video.mp4', 'teste')` ele n manda a palavra "teste"

**Comment by PedroBatistop** [comment]
Olhe na documentação do Wa-automate: https://docs.openwa.dev/classes/api_Client.Client.html#sendFile

Basicamente, sendFile(ChatId, arquivo, 'nome do arquivo.mp4', 'legenda', id)
