### ISSUE TITLE
Console Spam ANTI-FAKE

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#129]
![image](https://user-images.githubusercontent.com/44541791/129572243-7a39a89d-4fe6-41be-a8cb-09854dcfd35a.png)

tanto esse flood console

**Comment by maradona4** [comment]
Vlz, sem spam aqui agr funcionar

**Comment by marru453** [comment]
> Vlz, sem spam aqui agr funcionar

como lo solucionaste, pasa capturas en donde tengo que eliminar
