### ISSUE TITLE
erro /gtav

### ISSUE THREAD

**Issue by EmanuelPeixoto** [KillovSky/iris#131]
apenas retorna "O servidor negou o upload da foto, tente novamente dentro de uns minutos"

**Comment by KillovSky** [comment]
Voce ja abriu a mesma issue a algum tempo, não fez o tutorial dela?

#122

**Comment by EmanuelPeixoto** [comment]
aquele resolveu o do /wasted

**Comment by KillovSky** [comment]
> aquele resolveu o do /wasted

Siga o mesmo procedimento do #112 na `case 'gtav':`, basta adicionar aquilo.

**Comment by EmanuelPeixoto** [comment]
case 'gtav':
				if (isImage || isQuotedImage && pic == 'ERROR: 401') {
					await kill.reply(from, mess.wait(), id)
					const gtavmd = isQuotedImage ? quotedMsg : message
					const gtaddt = await decryptMedia(gtavmd, uaOverride)
					const gtaUpl = await upload(gtaddt, false)
					await kill.sendFileFromUrl(from, `https://videfikri.com/api/textmaker/gtavposter/?urlgbr=${gtaUpl}`, 'Gtav.jpg', 'GTA V PS2!', id).catch(async () => { await kill.reply(from, mess.upfail(), id) })
				} else return await kill.reply(from, mess.onlyimg(), id)
				break
				
				
				
				assim?

**Comment by KillovSky** [comment]
> case 'gtav':
> 				if (isImage || isQuotedImage && pic == 'ERROR: 401') {
> 					await kill.reply(from, mess.wait(), id)
> 					const gtavmd = isQuotedImage ? quotedMsg : message
> 					const gtaddt = await decryptMedia(gtavmd, uaOverride)
> 					const gtaUpl = await upload(gtaddt, false)
> 					await kill.sendFileFromUrl(from, `https://videfikri.com/api/textmaker/gtavposter/?urlgbr=${gtaUpl}`, 'Gtav.jpg', 'GTA V PS2!', id).catch(async () => { await kill.reply(from, mess.upfail(), id) })
> 				} else return await kill.reply(from, mess.onlyimg(), id)
> 				break
> 				
> 				
> 				
> 				assim?
> 

Ahhh, ainda está usando o server via API, isso sinaliza que na verdade o problema e o servidor e não a Iris.

**Comment by EmanuelPeixoto** [comment]
O método sem API seria como? E é melhor?

**Comment by KillovSky** [comment]
> O método sem API seria como? E é melhor?

Ele não existe - ainda -.
