### ISSUE TITLE
Erro ocorre do nada, sem ninguem escrever comando

### ISSUE THREAD

**Issue by EmanuelPeixoto** [KillovSky/iris#132]
Olá, caro dono(a)!
Obtive erros ao executar o comando...

/

Peço que corrija por gentileza para podermos usar sem preocupações.
Agradecida, Íris.

Qual erro?

TypeError: Cannot destructure property 'pushname' of 'sender' as it is null.

**Comment by KillovSky** [comment]
> Olá, caro dono(a)!
> Obtive erros ao executar o comando...
> 
> /
> 
> Peço que corrija por gentileza para podermos usar sem preocupações.
> Agradecida, Íris.
> 
> Qual erro?
> 
> TypeError: Cannot destructure property 'pushname' of 'sender' as it is null.

Atualize a wa-automate com `npm i @open-wa/wa-automate@latest` ou `npm update`, esse erro diz que o usuario não existe, se fez alguma modificação, desfaça e teste-a após atualizar.
Basicamente, não é algo que posso "corrigir" eu mesmo pois envolve a wa-automate.
