### ISSUE TITLE
Ideias para games novos [Pedido]

### ISSUE THREAD

**Issue by BruZim03** [KillovSky/iris#136]
Não sei se pode mandar aqui ou se tá aceitando idéias

Trás uns jogos de adivinhação, tipo o bot manda uma imagem de alguma coisa e o pessoal tenta acertar, o primeiro que acertar ganha 

Um Quiz, bot manda uma pergunta, a galera tentar acertar, o primeiro que acertar ganha

Um jogo tipo forca (não sei conhece assim) 

Acerte a bandeira, um jogo onde o bot manda um emoji de alguma bandeira, e quem acertar primeiro ganha 

Jogo da velha apostando xp (opcional)

**Comment by KillovSky** [comment]
Pode deixar comigo, vou tentar, mas apenas quando tiver tempo 😎🤝

**Comment by BruZim03** [comment]
opa, esqueci de falar que quem ganha, recebe uma quantidade de xp, tmj
