### ISSUE TITLE
Tipo é possivel aumentar a velocidade de resposta da bot?

### ISSUE THREAD

**Issue by akami-is-back** [KillovSky/iris#138]
Eu tenho um amigo tbm usuário da íris q ele conseguiu aumentar a velocidade da íris dele tá igual a bot de termux aí eu queria saber se isso é possível

**Comment by PedroBatistop** [comment]
Caso deseje mexer nos parâmetros de inicialização da Wa-Automate, veja isso > https://docs.openwa.dev/interfaces/api_model_config.configobject.html
Aqui segue uma lista dos parâmetros que podem ser usados/apagados da chromiumArgs > https://peter.sh/experiments/chromium-command-line-switches
Mexer nos parâmetros de inicialização do chromium pode gerar muito mais performance, desde que você não use incorretamente.

Claro que a performance vai depender de muitas outras coisas como se seu computador está devidamente otimizado, da capacidade de processamento do seu computador (RAM, CPU, etc)...
Recomendo sempre realizar a limpeza de disco, manter sempre seu sistema operacional atualizado, desfragmentação de disco...

**Comment by akami-is-back** [comment]
Vlw
