### ISSUE TITLE
descriptografar

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#139]
eu tenho o sistema q mostra as mensagens apagadas e queria um comando para descriptografar as imgens manual mesmo tipo /descript /9j/... e ele iria mandar a foto

**Comment by PedroBatistop** [comment]
const mediaData = await decryptMedia(quotedMsg, uaOverride)

e por aí vai...

**Comment by dodouuglas** [comment]
conseguir fazer n ele ta falando q tem q baixar mas eu n sei
