### ISSUE TITLE
Erros reload

### ISSUE THREAD

**Issue by MatheusSan03** [KillovSky/iris#140]
![image](https://user-images.githubusercontent.com/78276706/129928841-6a63af51-3be4-434d-a0fa-bf561bb96141.png)
 
queria saber se tinha como resolver isso, toda hora fica com esse reload aparecendo, de ontem pra hoje que começou isso

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/78276706/129928841-6a63af51-3be4-434d-a0fa-bf561bb96141.png)
>  
> queria saber se tinha como resolver isso, toda hora fica com esse reload aparecendo, de ontem pra hoje que começou isso

Isso acontece bastante com os comandos de block, mas sem saber qual comando tu usou é dificil achar a causa, detalhe mais seu problema.

**Comment by MatheusSan03** [comment]
Ja foi resolvido, ele ficava assim sem usar nenhum comando, era do nada mesmo, mas troquei o numero do bot de whatsapp e voltou ao normal
