### ISSUE TITLE
Erro com código 1 elifecycle ao iniciar a iris 

### ISSUE THREAD

**Issue by eclipesi** [KillovSky/iris#141]
![IMG-20210818-WA0039](https://user-images.githubusercontent.com/20760654/129936424-d18ea370-e179-432b-bb09-4df55638447a.jpeg)
![IMG-20210818-WA0038](https://user-images.githubusercontent.com/20760654/129936442-2d1df4d7-e4a8-49aa-bfe8-72f4eac1cc11.jpeg)
Já reinstalei o BOt e o nodejs

**Comment by wesley0209** [comment]
leia #78
