### ISSUE TITLE
ERRO Blocklist (FALHA)

### ISSUE THREAD

**Issue by PANINOBR** [KillovSky/iris#142]
Olá sempre que uso o comando !blocklist ele dá uma falha no whatsapp e (console log) prints abaixo
 
 Console log (PRINT)
![image](https://user-images.githubusercontent.com/48421679/129983860-e111ae28-933d-4649-a4cc-d59a780bfc6f.png)

Config.Js (print)
![image](https://user-images.githubusercontent.com/48421679/129983901-0ee92da6-bd18-492d-ac5a-bbd0600cce06.png)

**Comment by KillovSky** [comment]
> Olá sempre que uso o comando !blocklist ele dá uma falha no whatsapp e (console log) prints abaixo
>  
>  Console log (PRINT)
> ![image](https://user-images.githubusercontent.com/48421679/129983860-e111ae28-933d-4649-a4cc-d59a780bfc6f.png)
> 
> 
> Config.Js (print)
> ![image](https://user-images.githubusercontent.com/48421679/129983901-0ee92da6-bd18-492d-ac5a-bbd0600cce06.png)
> 

Erro meu por falta de um `try-catch`, quer dizer que possui 0 bloqueados, mas é estranho, deveria enviar, de toda forma, o `filter` ali é referente a problema na wa-automate, deve ser fixado por eles.
