### ISSUE TITLE
Doar XP - Agiotar bug

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#143]
![image](https://user-images.githubusercontent.com/44541791/130116994-58a4028a-681d-4a5c-95d4-3487587174bc.png)
No caso /agiotar deu 38k XP

/doar 
![image](https://user-images.githubusercontent.com/44541791/130117098-deaaed4a-c5e0-4614-bea4-4383e552173a.png)

auto min Bot agiotar
![image](https://user-images.githubusercontent.com/44541791/130117336-6455e249-e66f-4709-8c21-52de3d6d9df9.png)

mas acho bug?
eu quero Ex: /agiotar voce deu XP
/doar "Você não pode /doar, esperar, você usou /agiotar detectar a espera de tempo de termine"

Cara acho era golpe infinito /ranking 1° lugar ;-;

**Comment by BrJesus** [comment]
@maradona4 esse comando é preocupante kkk eu tava vendo ele mas não sei se é um Bug ao certo meu amigo conseguia dar muito xp através dele agiotando e ele conseguia transferir, por isso deixei desativado.
Pra desativar vai na case "Agiotar" e do lado coloca //
Ficará assim //Case; 'Agiotar':
Até o cara aí resolver esse Bug.

**Comment by maradona4** [comment]
> @maradona4 esse comando é preocupante kkk eu tava vendo ele mas não sei se é um Bug ao certo meu amigo conseguia dar muito xp através dele agiotando e ele conseguia transferir, por isso deixei desativado.
> Pra desativar vai na case "Agiotar" e do lado coloca //
> Ficará assim //Case; 'Agiotar':
> Até o cara aí resolver esse Bug.

Entendi agora ja desativado 
![image](https://user-images.githubusercontent.com/44541791/130124752-7248b17b-145b-4590-aad6-247f35165aa3.png)

**Comment by KillovSky** [comment]
> @maradona4 esse comando é preocupante kkk eu tava vendo ele mas não sei se é um Bug ao certo meu amigo conseguia dar muito xp através dele agiotando e ele conseguia transferir, por isso deixei desativado.
> Pra desativar vai na case "Agiotar" e do lado coloca //
> Ficará assim //Case; 'Agiotar':
> Até o cara aí resolver esse Bug.

Considere isso um "glitch" de dinheiro igual aos de GTA V.
Já foi corrigido na versão que estou fazendo, quando possivel, o que deve demorar MUITO - (pois mal consigo dormir direito, imagine programar a Íris) - a versão vai ar.
