### ISSUE TITLE
antiflood

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#147]
tem como fazer um sistema antiflood no pv? caso alguem floodar ele manda uma mensagem e da block

**Comment by KillovSky** [comment]
> tem como fazer um sistema antiflood no pv? caso alguem floodar ele manda uma mensagem e da block

Ela já possui antiflood no privado, para um auto block insira no código `if` do anti-flood isso abaixo.

```javascript
await kill.contactBlock(user)
```

Tenha em mente que isso vai causar sobrecarga.
