### ISSUE TITLE
cmd: lgbt erro json

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#150]
![image](https://user-images.githubusercontent.com/44541791/130328108-01895a89-4b3f-49da-aa87-bd9f4ae9d761.png)

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/130328108-01895a89-4b3f-49da-aa87-bd9f4ae9d761.png)
> 

Bug de upload de foto no servidor, não é algo que posso fixar, possivelmente causado por um flood enorme, se caso você ou alguém esteja usando muitos comandos de imagem sem parar, esta é a causa, precisaria controlar os membros para que o servidor não seja inundado de requests post e te dê um bloqueio de IP.

Resumidamente, o erro está no servidor e uma **POSSIVEL** causa é um flood gigante de comandos de imagem.
