### ISSUE TITLE
Bugs roleta

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#151]
![image](https://user-images.githubusercontent.com/44541791/130329169-c27383f0-2d7e-49f9-ac9e-038e2846130e.png)

Vejam tem cmd: /roleta
problema, abuso, flood de bugs do XP

![image](https://user-images.githubusercontent.com/44541791/130329204-0273db4d-ad4a-4a89-adf5-e586b45a3300.png)
quero proteção anti flood XP

**Comment by KillovSky** [comment]
Não vejo problema algum e os comandos possuem anti-flood a menos que você tenha usado o `/nolimit`, de toda forma, não vejo nenhum problema aqui.

**Comment by maradona4** [comment]
Entendi, o meu ficar desativado /nolimit

nao esta on 
aparece /roleta 
Sate, sate, sate ........

**Comment by KillovSky** [comment]
> Entendi, o meu ficar desativado /nolimit
> 
> nao esta on 
> aparece /roleta 
> Sate, sate, sate ........

Detalhe mais por gentileza, pois até agora não vi problema nenhum no comando pois ele está limitando os jogos ou seja, funcionando, ao menos nos meus testes ele não apresentou erro nenhum.
