### ISSUE TITLE
ideia de algo novo [Pedido]

### ISSUE THREAD

**Issue by ddd33333f** [KillovSky/iris#152]
Eu tenho uma ideia e é anti-spam quando alguém envia 7 mensagens e há ordens para bloqueá-lo e obrigado pelo que você fornece

**Comment by KillovSky** [comment]
> Eu tenho uma ideia e é anti-spam quando alguém envia 7 mensagens e há ordens para bloqueá-lo e obrigado pelo que você fornece

Estou fazendo um sistema universal de bloqueio já, stickers, documentos, fotos e outros, obrigado, em breve - ou **deve demorar MUITO, MUITO MESMO** - vai estar pronto.
