### ISSUE TITLE
Agiotagem e aposta

### ISSUE THREAD

**Issue by wesley0209** [KillovSky/iris#153]
Nao e possivel agiotar um valor acima que 2bilhoes, o mesmo vale para aposta, se voce tem 6 bilhoes de xp, o maximo que voce consegue apostar e 2bilhoes, flip, roleta, cassino

**Comment by KillovSky** [comment]
Os jogos tem um limitador que impede apostas que possam perder mais da metade do XP atual, o que pode deixar negativo.
Verifique se você está usando corretamente, não use traços, pontos e nada, somente números.
E tenha em mente que o give tem um risco de corrupção de arquivo.
Também detalhe os problemas, mostre fotos do terminal, edições feitas no sistema, prints de usando comandos e qualquer informação util, afinal, como posso resolver um problema se você não mostrar informações? Existem "milhões" de causas possiveis para os erros, sempre detalhe o maximo possivel :)

**Comment by wesley0209** [comment]
> Os jogos tem um limitador que impede apostas que possam perder mais da metade do XP atual, o que pode deixar negativo.
> Verifique se você está usando corretamente, não use traços, pontos e nada, somente números.
> E tenha em mente que o give tem um risco de corrupção de arquivo.
> Também detalhe os problemas, mostre fotos do terminal, edições feitas no sistema, prints de usando comandos e qualquer informação util, afinal, como posso resolver um problema se você não mostrar informações? Existem "milhões" de causas possiveis para os erros, sempre detalhe o maximo possivel :)

case 'rolette':;case 'roleta':
				if (!isxp) return await kill.reply(from, mess.needxpon(), id)
				const limitrl = await gaming.getLimit(user, daily);if (gaming.isLimit(limitrl) == 1) return await kill.reply(from, mess.limitgame(), id)
				const checkxpr = await gaming.getValue(user, nivel, 'xp');const xpMenorT = parseInt(checkxpr / 2, 10)
				if (isNaN(args[0]) || !isInt(args[0]) || Number(args[0]) >= xpMenorT || Number(args[0]) < 250) return await kill.reply(from, mess.gaming(checkxpr, xpMenorT), id)
				var nrolxp = Math.floor(Math.random() * -milSort) - Number(args[0]);var prolxp = Math.floor(Math.random() * milSort) + Number(args[0])
				side == 1 ? await kill.sendFileFromUrl(from, 'https://i.ibb.co/vQj6nq4/roleta1.png', 'rol1.png', mess.loseshot(nrolxp), id) : await kill.sendFileFromUrl(from, 'https://i.ibb.co/PwKR2nR/roleta.jpg', 'rol.jpg', mess.winshot(prolxp), id)
				side == 1 ? await gaming.addValue(user, Number(nrolxp), nivel, 'xp') : await gaming.addValue(user, Number(prolxp), nivel, 'xp')
				if (noLimits == 0) await gaming.addLimit(user, daily, './lib/config/Gerais/diario.json')
				break

case 'flip':
				if (!isxp) return await kill.reply(from, mess.needxpon(), id)
				const limitfp = await gaming.getLimit(user, daily);if (gaming.isLimit(limitfp) == 1) return await kill.reply(from, mess.limitgame(), id)
				const checkxp = await gaming.getValue(user, nivel, 'xp');const xpMenorc = parseInt(checkxp / 2, 10)
				if (isNaN(args[1]) || !isInt(args[1]) || Number(args[1]) >= xpMenorc || Number(args[1]) < 250) return await kill.reply(from, mess.gaming(checkxp, xpMenorc), id)
				var nflipxp = Math.floor(Math.random() * -milSort) - Number(args[1]);var pflipxp = Math.floor(Math.random() * milSort) + Number(args[1])
				if (args[0].toLowerCase() == 'cara' || args[0].toLowerCase() == 'coroa') {
					if (side == 1) { await kill.sendStickerfromUrl(from, 'https://i.ibb.co/LJjkVK5/heads.png', { method: 'get' }, { author: config.Sticker_Author, pack: config.Sticker_Pack, keepScale: true }) } else { await kill.sendStickerfromUrl(from, 'https://i.ibb.co/wNnZ4QD/tails.png', { method: 'get' }, { author: config.Sticker_Author, pack: config.Sticker_Pack, keepScale: true }) }
					if (args[0].toLowerCase() == 'cara' && side == 1) {
						await kill.reply(from, mess.flipwin(pflipxp) + ' "cara".', id)
						await gaming.addValue(user, Number(pflipxp), nivel, 'xp')
					} else if (args[0].toLowerCase() == 'coroa' && side == 2) {
						await kill.reply(from, mess.flipwin(pflipxp) + ' "coroa".', id)
						await gaming.addValue(user, Number(pflipxp), nivel, 'xp')
					} else { await kill.reply(from, mess.fliplose(nflipxp) + ` "${args[0].toLowerCase()}".`, id);await gaming.addValue(user, Number(nflipxp), nivel, 'xp') }
				} else return await kill.reply(from, mess.fliphow(), id)
				if (noLimits == 0) await gaming.addLimit(user, daily, './lib/config/Gerais/diario.json')
				break
				
			case 'cassino':
				if (!isxp) return await kill.reply(from, mess.needxpon(), id)
				const limitcs = await gaming.getLimit(user, daily)
				if (gaming.isLimit(limitcs) == 1) return await kill.reply(from, mess.limitgame(), id)
				var checkxpc = await gaming.getValue(user, nivel, 'xp')
				const xpMenor = parseInt(checkxpc / 2, 10)
				if (isNaN(args[0]) || !isInt(args[0]) || Number(args[0]) >= xpMenor || Number(args[0]) < 250) return await kill.reply(from, mess.gaming(checkxpc, xpMenor), id)
				var pcasxp = Math.floor(Math.random() * milSort) + Number(args[0])
				var cassin = ['- 🍒 ', '- 🎃 ', '- 🍐 ']
				var cassinend = valueRand(cassin) + valueRand(cassin) + valueRand(cassin) + '-'
				if (cassinend == '- 🍒 - 🍒 - 🍒 -' || cassinend == '- 🍐 - 🍐 - 🍐 -' || cassinend == '- 🎃 - 🎃 - 🎃 -') { await gaming.addValue(user, Number(pcasxp), nivel, 'xp');await kill.reply(from, mess.caswin(cassinend, Number(pcasxp)), id) } else { await gaming.addValue(user, Number(-pcasxp), nivel, 'xp');await kill.reply(from, mess.caslose(cassinend, Number(-pcasxp)), id) }
				if (noLimits == 0) await gaming.addLimit(user, daily, './lib/config/Gerais/diario.json')
				break

case 'agiotar':
				if (!isxp) return await kill.reply(from, mess.needxpon(), id)
				if (args.length <= 1) return await kill.reply(from, mess.semmarcar() + `\n\nEx: ${prefix}Agiotar @user <value/valor>`, id)
				const checkAgiota = await gaming.getValue(user, nivel, 'xp')
				var theAgiota = quotedMsg ? parseInt(args[0], 10) : (mentionedJidList.length !== 0 ? parseInt(args[1], 10) : parseInt(args[1], 10))
				var timeAgiota = quotedMsg ? args[1] : (mentionedJidList.length !== 0 ? args[2] : args[2])
				if (isNaN(theAgiota) || !isInt(theAgiota) || Number(theAgiota) > checkAgiota || theAgiota < 100 || isNaN(timeAgiota) || timeAgiota < 5) return await kill.reply(from, mess.maxAgiota(checkAgiota), id)
				var alvoAgiota = quotedMsg ? quotedMsgObj.sender.id : (mentionedJidList.length !== 0 ? mentionedJidList[0] : null)
				if (alvoAgiota == null) return await kill.reply(from, mess.cmdfailed(), id)
				await gaming.addValue(user, Number(-theAgiota), nivel, 'xp');await gaming.addValue(alvoAgiota, Number(theAgiota), nivel, 'xp')
				await kill.sendTextWithMentions(from, mess.moneyagi(theAgiota, alvoAgiota, timeAgiota))
				await sleep(Number(timeAgiota * 60000));await kill.sendTextWithMentions(from, mess.backmoney(theAgiota, user, alvoAgiota))
				await gaming.addValue(alvoAgiota, Number(-theAgiota), nivel, 'xp');await gaming.addValue(user, Number(theAgiota), nivel, 'xp')
				break

**Comment by wesley0209** [comment]
eu uso o codigo original, memo tendo 10bilhoes de xp, o maximo que consigo apostar e 2bilhoes

**Comment by KillovSky** [comment]
Não é necessario publicar o código todo, meio que eu fiz ele então se disser que está padrão saberei como está, de toda forma, não vejo problemas com os limitadores, pra mim está tudo funcional, seus "milhoes" tem virgulas no meio?
Por exemplo, se voce usou give com 10,000, voce não ganharia 10 mil e sim 10 XP e ainda por cima corrompe o sistema de brinde.
Tente restaurar um backup e ver no que dá.
Se quiser tirar o limitador **por sua conta e risco**, basta trocar o `xpMenor` da `if` para um valor muito alto, faça o mesmo nas outras cases, veja qual a variavel de limite (geralmente debaixo da `getValue`) e mude-a.
Em forma geral, não é um bug e na minha opinião, é azar de punição merecida por roubar no jogo :)
Brincadeira, de fato não sei o motivo, mas não possui um problema em si pra resolver, basta desfazer o XP sujo e jogar limpo ou tentar remover o limitador e correr risco de corrupção de arquivos, afinal, ele reflete no nivel e nas mensagens.

**Comment by wesley0209** [comment]
![WhatsApp Image 2021-08-22 at 15 54 28](https://user-images.githubusercontent.com/83685462/130361657-d535dc47-3b3a-4c61-b3d3-511dd2c812bb.jpeg)
![WhatsApp Image 2021-08-22 at 15 54 38](https://user-images.githubusercontent.com/83685462/130361664-1b43c863-f20a-4bc9-890a-af9f1c7172c6.jpeg)

**Comment by wesley0209** [comment]
> Não é necessario publicar o código todo, meio que eu fiz ele então se disser que está padrão saberei como está, de toda forma, não vejo problemas com os limitadores, pra mim está tudo funcional, seus "milhoes" tem virgulas no meio?
> Por exemplo, se voce usou give com 10,000, voce não ganharia 10 mil e sim 10 XP e ainda por cima corrompe o sistema de brinde.
> Tente restaurar um backup e ver no que dá.
> Se quiser tirar o limitador **por sua conta e risco**, basta trocar o `xpMenor` da `if` para um valor muito alto, faça o mesmo nas outras cases, veja qual a variavel de limite (geralmente debaixo da `getValue`) e mude-a.
> Em forma geral, não é um bug e na minha opinião, é azar de punição merecida por roubar no jogo :)
> Brincadeira, de fato não sei o motivo, mas não possui um problema em si pra resolver, basta desfazer o XP sujo e jogar limpo ou tentar remover o limitador e correr risco de corrupção de arquivos, afinal, ele reflete no nivel e nas mensagens.

![WhatsApp Image 2021-08-22 at 15 54 28](https://user-images.githubusercontent.com/83685462/130361698-07a48626-55ab-4a23-a6e7-09b561232947.jpeg)
![WhatsApp Image 2021-08-22 at 15 54 38](https://user-images.githubusercontent.com/83685462/130361700-31858ae8-abc1-4c31-8740-038f20d8cbdd.jpeg)

**Comment by wesley0209** [comment]
farei o que voce me disse, obg
