### ISSUE TITLE
help

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#154]
to fazendo isso aq e n sei oq colocar aq 
![image](https://user-images.githubusercontent.com/79427063/130369732-e5bab85f-c7f3-402b-a87d-fe1fc964a89d.png)

**Comment by KillovSky** [comment]
> to fazendo isso aq e n sei oq colocar aq 
> ![image](https://user-images.githubusercontent.com/79427063/130369732-e5bab85f-c7f3-402b-a87d-fe1fc964a89d.png)


A `quotedMsg` não é definida na index, abra a config.js e pegue a `const` referente a ela.

Sobre a estrutura do `decrypt`, já esta correto, se você quer descriptografar imagens, é exatamente isso ai.

**Comment by dodouuglas** [comment]
mas n e uma mensagem respondida para ser quotedMsg

**Comment by dodouuglas** [comment]
![image](https://user-images.githubusercontent.com/79427063/130373584-e03390b9-7e06-411e-92c4-5465a5bf8ac1.png)

**Comment by dodouuglas** [comment]
![image](https://user-images.githubusercontent.com/79427063/130373715-bbc34dae-adb7-489f-877d-07bbb5ba52cb.png)
to defenindo e dando error

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/79427063/130373715-bbc34dae-adb7-489f-877d-07bbb5ba52cb.png)
> to defenindo e dando error
> agora deu o error `(node:18936) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'clientUrl' of undefined
>     at D:\iris-main\node_modules\@open-wa\wa-decrypt\dist\decrypt.js:83:45`

Ta completamente incorreto agora, mas em todo caso, respondendo a pergunta anterior, o que você procura não é o parametro `message`?
Não posso fornecer maiores detalhes e nem dar o sistema pronto, ando muito ocupado - inclusive agora -, mas tente message, se não funcionar algo no seu código está digitado errado.
