### ISSUE TITLE
Error reload

### ISSUE THREAD

**Issue by YuriTotoso** [KillovSky/iris#155]
coloquei o comando /reload o bot n reiniciou, e agora não responde mais meus comandos, chega no cmd que a pessoa digitou o comando, mas o bot n responde, oque eu faço?

**Comment by KillovSky** [comment]
Bem, a resposta é simples, desligar e ligar de novo resolverá.
Em caso de falha leia a #144.

**Comment by YuriTotoso** [comment]
Não Resolveu, já Reinstalei o bot 15 vezes e n funcionou...

**Comment by KillovSky** [comment]
> Não Resolveu, já Reinstalei o bot 15 vezes e n funcionou...

Tente outro WhatsApp, também tenha completa certeza que tirou e adicionou a Íris dos grupos com ela online - e zerada - além de também não ter editado nada.
