### ISSUE TITLE
goorm host

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#156]
![image](https://user-images.githubusercontent.com/44541791/130617503-e980632c-f230-407a-bed4-246de29c1ee2.png)

Failed Start?

ja Teste 
Abrir iris/lib/function.json
//useChrome: false,

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/130617503-e980632c-f230-407a-bed4-246de29c1ee2.png)
> 
> Failed Start?
> 
> ja Teste
> Abrir iris/lib/function.json
> //useChrome: false,

Você já abriu a mesma issue a 19 dias atrás.
#94

**Comment by maradona4** [comment]
vdd, eu leia 

talvez conta suspensa esse sites GOORM
