### ISSUE TITLE
Como ter mais de 1 bot ao mesmo tempo

### ISSUE THREAD

**Issue by Elias038** [KillovSky/iris#157]
Como faço pra ter várias íris ao mesmo tempo? até pouco tempo atrás eu usava 3 números diferentes e uma pasta Íris pra cada um, e funcionava perfeitamente. Porém de um tempo pra cá apenas um deles liga. Já conferi o wa automate, já reinstalei todos os programas e arquivos
![Uploading IMG_20210824_140717.jpg…]()

**Comment by PedroBatistop** [comment]
#115
