### ISSUE TITLE
cmd: /nobg

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#159]
![image](https://user-images.githubusercontent.com/44541791/130709417-8948bcfe-6f8f-4829-81dd-62299a4565a9.png)

**Comment by KillovSky** [comment]
O erro está escrito ali.
**Insufficient Credits** ou seja, sua API bateu o limite e somente após o final do mês ela reseta, isso é explicado no exato momento que se usa, enfim, crie outra API que deve funcionar também.

**Comment by maradona4** [comment]
entendi, valeu
