### ISSUE TITLE
Criação de comando;

### ISSUE THREAD

**Issue by Gabrielxx27** [KillovSky/iris#165]
Olá, tudo bem? 
Pode me ajudar com uma seguinte questão?
Todas as vezes que tento criar um comando e utilizo no bot, ele não funciona... até utilizei a base que você deixou para usar.

`case 'Investimento':
				await kill.reply(from, 'Sua mensagem', id)
				break`

Sempre aparece isso no WPP: "O comando /Investimento não existe, reveja nossa listam em /menu para continuar.

Já tente também usar a pasta pt.js para inserir:

`export.invest = () => { return ' Minha mensagem '}`

E na pasta config.js deixei: 

`case 'Investimento':
				await kill.reply(from, mess.invest(), id)
				break`

e mesmo assim deu a mesma mensagem no WPP

**Comment by marru453** [comment]
> vlw

Como lo arreglaste?
