### ISSUE TITLE
cmd /demote

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#169]
![image](https://user-images.githubusercontent.com/44541791/131190927-147b3ca3-60f7-41eb-a380-520aaa719eb0.png)

Saiba  /rebaixar > no caso bot mandar "Falhar iniciado" pq eu acho ele dono criador deste grupos!

![image](https://user-images.githubusercontent.com/44541791/131190992-f98d4674-1dfd-4356-ae7e-03ad1ebe3ddd.png)

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/131190927-147b3ca3-60f7-41eb-a380-520aaa719eb0.png)
> 
> Saiba  /rebaixar > no caso bot mandar "Falhar iniciado" pq eu acho ele dono criador deste grupos!
> 
> ![image](https://user-images.githubusercontent.com/44541791/131190992-f98d4674-1dfd-4356-ae7e-03ad1ebe3ddd.png)
> 

Erro de relação a uma evaluação de valores no puppeteer, o que isso significa?
Que o valor (a função) se tornou invalido para ser executado, é algo mais raro de se obter e não deve ocorrer sempre a menos que seja uma mudança brusca no servidor, nesse caso, é de responsabilidade da wa-automate corrigir o problema.
