### ISSUE TITLE
Erro na inicialização

### ISSUE THREAD

**Issue by herberthsfc** [KillovSky/iris#170]
![1630102558377](https://user-images.githubusercontent.com/76819767/131193936-67cf7f13-b304-490c-9da4-e5311c02dc70.jpg)

Ao dar npm start, escaneio o qrcode e depois aparece isso "shutting down", que significa desligando e não conecta o bot.

**Comment by marru453** [comment]
Usa este comando 

npm i -y
Antes descargar comprueba que tienes el node.js v14.16 o superior

**Comment by NaldoMota1** [comment]
Não resolveu pra mim

**Comment by KillovSky** [comment]
> ![1630102558377](https://user-images.githubusercontent.com/76819767/131193936-67cf7f13-b304-490c-9da4-e5311c02dc70.jpg)
> 
> Ao dar npm start, escaneio o qrcode e depois aparece isso "shutting down", que significa desligando e não conecta o bot.

Erro estranho, pode ser em relação tanto a wa-automate quanto ao servidor do WhatsApp, você instalou tudo certinho? Se sim, experimente instalar novamente baixando do zero e dessa vez rodando com `npm i --force` e também abrir a BOT com o `headless` em `true`, para inserir em `true` abra a `functions.js`.

**Comment by NaldoMota1** [comment]
Eu atualizei a wa-automate e resolveu o problema.

**Comment by KillovSky** [comment]
> Eu atualizei a wa-automate e resolveu o problema.

Entendi, obrigado pela informação, então aparentemente foi um erro de atualização deles novamente e as issues fechadas quase agora tem referência sobre isso, bom, lhe agradeço novamente por informar.

**Comment by herberthsfc** [comment]
> Eu atualizei a wa-automate e resolveu o problema.

para atualizar a wa-automate, eu uso oq?

npm i @open-wa/wa-automate@4.8.2

isso?☝️

**Comment by KillovSky** [comment]
> > Eu atualizei a wa-automate e resolveu o problema.
> 
> para atualizar a wa-automate, eu uso oq?
> 
> npm i @open-wa/wa-automate@4.8.2
> 
> isso?☝️

Quase, é `npm i @open-wa/wa-automate@latest`.

Se você quiser pode inserir uma versão manualmente trocando latest por ela.
