### ISSUE TITLE
error para mandar mensagem quando entra no grupo

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#171]
quando o bot entra no grupo e ja ta no limite que eu coloquei as maiorias das vezes ele sai do grupo e dps manda a mensagem ao inves de mandar a mensagem falando q ele ja ta no maximo e sair

**Comment by marru453** [comment]
Tienes que cambiar el límite de mensajes, si el grupo no tiene  más de un miembro el bot se va

**Comment by KillovSky** [comment]
> quando o bot entra no grupo e ja ta no limite que eu coloquei as maiorias das vezes ele sai do grupo e dps manda a mensagem ao inves de mandar a mensagem falando q ele ja ta no maximo e sair

Isso é por conta da função não aguardar a execução total para prosseguir mesmo sendo assincrono, de qualquer forma, tente transformar em um `.then` ou inserir um `await sleep(tempo)`.

Exemplo:

```javascript
await kill.sendText(....).then(() => {
     Insira outra função "await kill" aqui
}
```

Ou,

```javascript
await sleep(2000)
await kill.sendText(...)
await sleep(1000)
Outra função aqui
```

Os valores da sleep são em `milissegundos`.

**Comment by KillovSky** [comment]
> quando o bot entra no grupo e ja ta no limite que eu coloquei as maiorias das vezes ele sai do grupo e dps manda a mensagem ao inves de mandar a mensagem falando q ele ja ta no maximo e sair

Isso é por conta da função não aguardar a execução total para prosseguir mesmo sendo assincrono, de qualquer forma, tente transformar em um `.then` ou inserir um `await sleep(tempo)`.

Exemplo:

```javascript
await kill.sendText(....).then(async () => {
     Insira outra função "await kill" aqui
})
```

Ou,

```javascript
await sleep(2000)
await kill.sendText(...)
await sleep(1000)
Outra função aqui
```

Os valores da sleep são em `milissegundos`, tenha em mente que quanto mais você usar o `.then`, mais `promises` serão abertas e isso significa mais consumo de CPU/RAM.
