### ISSUE TITLE
Duvida

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#172]
Mas funcionar LINUX PC ?  Suporta node_modules .so

**Comment by KillovSky** [comment]
> Mas funcionar LINUX PC ?  Suporta node_modules .so

Íris funciona tranquilamente em Linux, mas o sistema de arquivos do Windows e Linux são diferentes.
Windows utiliza o sistema de armazenamento `NTFS` enquanto o Linux usa a `EXT 2/3/4`, portanto, a padta módulos do Windows **NÃO PODE SER USADA** no Linux, sendo necessario uma instalação do zero.
