### ISSUE TITLE
crear comando nuevo

### ISSUE THREAD

**Issue by marru453** [KillovSky/iris#173]
![Captura de pantalla 2021-08-28 161052](https://user-images.githubusercontent.com/89472552/131221240-4000788e-470b-47df-8542-b6d88e6cfb06.jpg)
me salta un error en terminal, no se cual comando tengo mal
cuando ejecuto detector me tiene que saltar el menu y en donde el usa este comando para que le envie el medidor 
`case 'plana':
			  if (!isGroupMsg) return await kill.reply(from, mess.detector(), id)
				await kill.reply(from, mess.wait(), id)
				await kill.sendTextWithMentions(from, mess.plana(randomMember))
				break`

**Comment by KillovSky** [comment]
> ![Captura de pantalla 2021-08-28 161052](https://user-images.githubusercontent.com/89472552/131221240-4000788e-470b-47df-8542-b6d88e6cfb06.jpg)
> me salta un error en terminal, no se cual comando tengo mal
> cuando ejecuto detector me tiene que saltar el menu y en donde el usa este comando para que le envie el medidor 
> `case 'plana':
> 			  if (!isGroupMsg) return await kill.reply(from, mess.detector(), id)
> 				await kill.reply(from, mess.wait(), id)
> 				await kill.sendTextWithMentions(from, mess.plana(randomMember))
> 				break`

Falta insertar el `:`.

```javascript
case 'comando':
     função
     break
```

**Comment by marru453** [comment]
eso en donde lo pongo

**Comment by KillovSky** [comment]
> eso en donde lo pongo

En tu código? Nunca olvide ingresar `;` y se recomienda no hacer este esquema de varias funciones en una línea, generará serios errores si se escribe incorrectamente.
La forma correcta de hacer función en una línea es:

```
Función 1; Función 2 ...
```

**SIEMPRE** ingrese `;` para separar funciones.
También siga los consejos que le di en la nueva edición, estudie un poco de JavaScript y luego edite Iris, porque cualquier error compromete la ejecución de Iris.
