### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by marru453** [KillovSky/iris#174]
![Captura de pantalla 2021-08-28 173344](https://user-images.githubusercontent.com/89472552/131223091-0de2dd14-bb29-49e3-98cd-c42fb31c49d7.jpg)

**Comment by KillovSky** [comment]
> ![Captura de pantalla 2021-08-28 173344](https://user-images.githubusercontent.com/89472552/131223091-0de2dd14-bb29-49e3-98cd-c42fb31c49d7.jpg)
> 

Você fez uma edição incorreta, você inseriu um "s" atrás da const na primeira linha do código, desfaça isso e funcionará, tenha em mente que os erros são escritos no terminal e traduzir - ou aprender inglês - pode ajudar a obter a solucão no mesmo segundo, se você não sabe usar JavaScript, é recomendado estudar um pouco antes de tentar editar a Íris, pois até mesmo um simples ponto pode comprometer toda a execução do código.
