### ISSUE TITLE
man me baniram da recepcao porem eu tinha saido da principal 

### ISSUE THREAD

**Issue by pablorere** [KillovSky/iris#175]
https://wa.me/+34642695105 add eu dnv pls <3
@KillovSky

**Comment by KillovSky** [comment]
> https://wa.me/+34642695105 add eu dnv pls <3
> @KillovSky 

Essa pagina é reservada a erros da Íris e não ao grupo Legião Z, por que não chamou os administradores após entrar e veio aqui?
Isso é muito estranho, especialmente por que a recepção do Legião costuma sofrer ataques, de toda forma, você parece ser brasileiro por usar girias do Brasil, então venha ao grupo com um número oficial do Brasil, pois não permitimos números falsos entrando lá.

**Comment by pablorere** [comment]
eu moro na espanha n tenho numero br mn eu vivia na bahia por isso as girias
