### ISSUE TITLE
mandar banner

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#178]
queria saber como fuciona isso aq
https://docs.openwa.dev/classes/api_Client.Client.html#sendBanner
para mandar banner e butao

**Comment by KillovSky** [comment]
> queria saber como fuciona isso aq
> https://docs.openwa.dev/classes/api_Client.Client.html#sendBanner
> para mandar banner e butao

Opa! Parece que finalmente eles lançaram o sistema de API Business!
É algo novo, preciso estudar a estrutura primeiro pra entender, mas tente seguir o formato que eles passaram lá.

```javascript
await kill.sendButtons(from, 'Texto acima dos botões', ['Botao1', 'Botao2', 'Botao3'], 'Titulo')
```

Dê uma olhada se funciona, nunca usei então pode ser que algo falhe.
