### ISSUE TITLE
Error en el comando !add

### ISSUE THREAD

**Issue by marru453** [KillovSky/iris#179]
![IMG-20210829-WA0647](https://user-images.githubusercontent.com/89472552/131248553-baaa2d30-4d89-4c7b-9b63-1a284aca822e.jpg)

Error en el cmd: 
(Adicionar) obtive erros no comando !add NOT_A_CONTACT vocë pode ignorar.

**Comment by KillovSky** [comment]
> 
> ![IMG-20210829-WA0647](https://user-images.githubusercontent.com/89472552/131248553-baaa2d30-4d89-4c7b-9b63-1a284aca822e.jpg)
> 
> Error en el cmd: 
> (Adicionar) obtive erros no comando !add NOT_A_CONTACT vocë pode ignorar.
> 

Es lo que está escrito allí, wa-automate no puede agregar personas que nunca han estado en el privado de Iris o que no forman parte de los contactos del teléfono.

**Comment by marru453** [comment]
@PedroBatistop  mi amigo me abrió un privi en mi WhatsApp del bot y le contesté con el mensaje, pero al parecer cuando quiero meterlo, el bot me salta diciendo que no está en la lista, el Antilink y Demote igual tienen un bug

**Comment by KillovSky** [comment]
> @PedroBatistop  mi amigo me abrió un privi en mi WhatsApp del bot y le contesté con el mensaje, pero al parecer cuando quiero meterlo, el bot me salta diciendo que no está en la lista, el Antilink y Demote igual tienen un bug


Intente agregar a los contactos y puedes abrir una nueva issue del antilink e demote? Gracias!
Pido que envie la mayor cantidad de información posible.

**Comment by marru453** [comment]
@KillovSky  mañana haré un reconocimiento de los bug de add y Antilinks y demote
