### ISSUE TITLE
Faltou Função

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#180]
![image](https://user-images.githubusercontent.com/44541791/131262111-5c2d8168-f381-4064-84ed-8350b8dc96e7.png)

Faltou esse "time"  cor fico escuro
![image](https://user-images.githubusercontent.com/44541791/131262125-26289a8b-2ae5-42d4-888c-7f4b61bbc559.png)

iris/lib/config/gerais/functions.json

**Comment by KillovSky** [comment]
Não vejo nenhum bug, as cores não representam erros, qual erro você obtém com a Íris por conta da `isLimit`?

**Comment by maradona4** [comment]
entendi, sem erro aqui
