### ISSUE TITLE
Falhar Erro GHOST

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#181]
![image](https://user-images.githubusercontent.com/44541791/131267247-9c36fc21-4d41-422a-b61b-66fd061befdf.png)
nao conseguir remover GHOST?

CODE: 
![image](https://user-images.githubusercontent.com/44541791/131267269-4125ba7e-5779-4e22-8aa7-272903486350.png)

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/131267247-9c36fc21-4d41-422a-b61b-66fd061befdf.png)
> nao conseguir remover GHOST?
> 
> CODE: 
> ![image](https://user-images.githubusercontent.com/44541791/131267269-4125ba7e-5779-4e22-8aa7-272903486350.png)
> 

Ele já será fixado assim que possivel.
#69
