### ISSUE TITLE
Gerar novo código QR

### ISSUE THREAD

**Issue by KingBot422** [KillovSky/iris#182]
Olá! O bot iris que instalei, levou hoje um ban do número do WhatsApp... Gostaria de saber como faço para criar um novo QR code para escanear... Ao dar o NPM START não vai...
![IMG-20210830-WA1266](https://user-images.githubusercontent.com/88904502/131376018-717737ea-4eff-4250-80ff-c09d972d2b39.jpg)
Desculpa a qualidade da imagem mas dá para ter noção de onde para o cmd.... Ele fica estacionado nessa parte, aguardo uma resposta, obrigado!

**Comment by dodouuglas** [comment]
e so apagar o arquivo `Iris.data.json` e iniciar dnv

**Comment by KingBot422** [comment]
> e so apagar o arquivo `Iris.data.json` e iniciar dnv

Amigo, esse arquivo que você citou, onde posso está encontrando ele? Pois dei uma pesquisada no Visual Studio Code e não achei.... E nem no gerenciador de arquivo... Será este mesmo o nome? Caso não pode me informar onde posso encontrá-lo por favor ...

**Comment by marru453** [comment]
Actualiza `npm update`  siempre que quieras modificar algo hazlo en una copia aparte, y deja una copia de seguridad

**Comment by KingBot422** [comment]
> Actualiza npm update siempre que quieras modificar algo hazlo en una copia aparte, y deja una copia de seguridad

Si me puede mostrar un ejemplo, le agradecería, ya que todavía soy un laico en el campo. 
O el tutorial detallado, disculpe las molestias.

**Comment by marru453** [comment]
https://github.com/KillovSky/iris/discussions/28

**Comment by KillovSky** [comment]
> > e so apagar o arquivo `Iris.data.json` e iniciar dnv
> 
> Amigo, esse arquivo que você citou, onde posso está encontrando ele? Pois dei uma pesquisada no Visual Studio Code e não achei.... E nem no gerenciador de arquivo... Será este mesmo o nome? Caso não pode me informar onde posso encontrá-lo por favor ...

Pasta raiz da Íris, onde fica a `config.js`, `index.js` e o `package.json`.

Lá estará o arquivo.
