### ISSUE TITLE
Erro Iniciar

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#183]
Lembra, meu pc estava TOMADA pc desligo  force

![image](https://user-images.githubusercontent.com/44541791/131389887-0398d33e-3454-4cc8-a00c-ced114b05171.png)

Perdi bot ligado, dps deu erro iniciado

**Comment by marru453** [comment]
npm start index.js o node index.js

**Comment by maradona4** [comment]
Agora conseguir, mas a vdd estrago 
![image](https://user-images.githubusercontent.com/44541791/131400903-da72dad4-cf52-4b97-95f9-437d9924f63e.png)

deu tudo  aparece "?"
fui tomada ;( perdi todos contato level

**Comment by maradona4** [comment]
![image](https://user-images.githubusercontent.com/44541791/131402967-fe116e7a-9276-4d36-b742-e7cb100c2792.png)

Agora ja deu funcionar ;-; 
problema level.json 
eu acho backup ja recuperacao ;)
