### ISSUE TITLE
novo sistema

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#184]
eu tava querendo fazer um sistema de anti arquivar e queria saber se tem como fazer tipo e a pessoa banir 3 pessoa em 1 mininuto o bot da ban na pessoa

**Comment by KillovSky** [comment]
> eu tava querendo fazer um sistema de anti arquivar e queria saber se tem como fazer tipo e a pessoa banir 3 pessoa em 1 mininuto o bot da ban na pessoa

Ban cronometrado?

```javascript
for (let i = 0; i < mentionedJidList.length; i++) {
     await sleep(Number(args[0]))
     await kill.removeParticipant(mentionedJidList[i])
}
```

Crie sua case isso e use assim:

`/Comando 5000 @User1 @User2...`

5000 se refere a 5 mil milissegundos.

Confira o código antes de usar, fiz ele correndo, pode ter algum erro, de toda forma, use ele para se **BASEAR** e fazer seu código único.

**Comment by dodouuglas** [comment]
é tipo se a pessoa tirar 3 pessoas em 1 minuto o bot detecta arquivamento e da ban na pessoa que tirou as pessoas

**Comment by KillovSky** [comment]
> é tipo se a pessoa tirar 3 pessoas em 1 minuto o bot detecta arquivamento e da ban na pessoa que tirou as pessoas

Vi aqui na wa automate sobre os parametros e todos que são retirados do grupo ou que **saem** caem nela como `remove` no sistema de welcome, que é onde seria necessario mexer para criar seu sistema.
Não tenho certeza se é possivel criar por hora seu sistema de anti-arquivar grupos, mas deixarei como futura ideia.

**Comment by PedroBatistop** [comment]
Fiz um código aqui correndo, não sei se está funcionando

`let lastOneMinRemoved = []` isso lá junto com os require da index.js

coloque tudo isso abaixo dentro do kill.onGlobalParticipantsChanged da index.js
```
if (event.action == 'remove') {
  lastOneMinRemoved.push(event.by)
  for (let i = 0; i < lastOneMinRemoved.length; i++) {
    if (lastOneMinRemoved.split(lastOneMinRemoved[i]).length - 1 > 2) {
      await kill.removeParticipant(event.chat, event.who)
    }
  }
  await sleep(60000)// um minuto em milissegundos
  lastOneMinRemoved.splice(event.by, 1)
}
```
