### ISSUE TITLE
Bug !add !Antilinks no funcionan

### ISSUE THREAD

**Issue by marru453** [KillovSky/iris#187]
![Screenshot_2021-08-31-01-23-22-117_com gbwhatsapp](https://user-images.githubusercontent.com/89472552/131418179-930f7e50-59d4-4f00-a94b-f592c07f2c64.jpg)
![Screenshot_2021-08-31-01-24-24-573_com yowhatsapp](https://user-images.githubusercontent.com/89472552/131418248-642afb2a-1923-491e-b38f-8fc8383d7e8e.jpg)

**Comment by KillovSky** [comment]
Puedes insertar una screenshot de console?

**Comment by marru453** [comment]
@KillovSky el de Antilinks si funciona el usuario no tiene que ser admins, pero el add no va creo que necesita alguna modificación, no puedo tengo el bot el pc y el pc está en la habitación de mi hermana, si quieres mañana lo pongo

**Comment by marru453** [comment]
O también si quieres lo podemos probar, pásame el número de tu bot, y te mando el mensaje ahí y así tú usas el comando de add en mi, así sabrás el fallo

**Comment by KillovSky** [comment]
> @KillovSky el de Antilinks si funciona el usuario no tiene que ser admins, pero el add no va creo que necesita alguna modificación, no puedo tengo el bot el pc y el pc está en la habitación de mi hermana, si quieres mañana lo pongo 

No hay problema, sobre lo antilink, sí, solo se puede kick a los usuarios comunes, no prohíbe ni a los owners ni a los administradores, sobre el add, necesita ser parte de los contactos del teléfono.

**Comment by marru453** [comment]
Es parte de mis contactos y también tengo en el otro WhatsApp la parte de permisos de contactos y no va

**Comment by KillovSky** [comment]
> Es parte de mis contactos y también tengo en el otro WhatsApp la parte de permisos de contactos y no va 

Entiendo, entonces necesito ver su terminal.

**Comment by marru453** [comment]
@KillovSky aquí tienes mi terminal

![Captura de pantalla 2021-08-31 140218](https://user-images.githubusercontent.com/89472552/131499269-6bfc5b72-cdcc-427a-99e8-03ce603ddf94.jpg)

**Comment by KillovSky** [comment]
> @KillovSky aquí tienes mi terminal
> 
> ![Captura de pantalla 2021-08-31 140218](https://user-images.githubusercontent.com/89472552/131499269-6bfc5b72-cdcc-427a-99e8-03ce603ddf94.jpg)
> 

Mala suerte, dice exactamente lo que ya dijo, que no es un contacto...Su WhatsApp tiene permiso para acceder a los contactos?

**Comment by marru453** [comment]
@KillovSky  si tiene
