### ISSUE TITLE
Sistema de VIPs

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#188]
![image](https://user-images.githubusercontent.com/44541791/131480349-2dc96a58-5fd6-461d-90b8-98e0a40a8089.png)

Como ele Permissao /mymsg 
pq "voce nao e vip"?

code:
1 - 
![image](https://user-images.githubusercontent.com/44541791/131480626-d3d25fc1-44bb-47ab-9211-f7d3af1571bb.png)

2-
![image](https://user-images.githubusercontent.com/44541791/131480554-792c29f6-a7f8-4874-9d69-0760cd067f1b.png)

3-
Tem problema duas ?
![image](https://user-images.githubusercontent.com/44541791/131480706-72153450-da93-4286-b61b-623fdbffd9dd.png)

4-
![image](https://user-images.githubusercontent.com/44541791/131480869-8c313155-dae9-45b2-b7ed-536cad8420fa.png)

5- 
![image](https://user-images.githubusercontent.com/44541791/131481129-c574b276-7a6a-4f8d-a76c-7e5b8f09838c.png)

quero arrumar isso?

**Comment by KillovSky** [comment]
Não poderei te passar um código assim já pronto pois estou a ir ao trabalho mas posso te dar uma base, para criar, monte uma case com `fs` e `json` usando a `case 'mutepv':` de base.

```javascript
// Primeiro declare uma var de array
var vips = []

 // Para adicionar um VIP
vips.push(mentionedJidList[0])

// Para remover
vips.splice(mentionedJidList[0], 1)

// Para tornar um comando VIP adicione isso após a case
if (!vips.includes(user)) return await kill.reply(from, 'Você não é um VIP para usar esse comando.', id)

// Modo de usar após você fazer a case = "/Vip on @User", tenha em mente que o [0] pega apenas o primeiro marcado e não todos.
```

E é isso apenas, monte uma case usando o `mutepv` de exemplo e terá um sistema de vips, ou aguarde a proxima atualização pois vai chegar com isso.

**Comment by maradona4** [comment]
Valeu

**Comment by KillovSky** [comment]
Desculpe não ter visto ali, meio corrido, mas aproveitar que o onibus atrasou e dar um exclarecimento.
Não se deve ter duas arrays em um json de jeito nenhum!
O formato certo seria `['numero1', 'numero2'...]` e assim vai.
A sua `isUserV` deve ser inserida dentro dentro da `try`, para assim ser atualizada a cada mensagem.
O seu código lá de push, está adicionando de forma geral o `mentionedJidList`, pois você esqueceu de inserir o `[0]` nela.

**Comment by marru453** [comment]
@maradona4  al final como lo hiciste?
