### ISSUE TITLE
descriptografar dnv

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#190]
eu nao estou conseguindo defenir os bagui para descriptografar as imagens apagadas para fazer isso fucionar 
![image](https://user-images.githubusercontent.com/79427063/131431298-c742b4f2-db6c-4fa4-8fb7-43073a8ff0f8.png)

**Comment by dodouuglas** [comment]
eu conseguir fazer e ficou assim 
![image](https://user-images.githubusercontent.com/79427063/131432805-83935ead-ff51-4b5a-acce-cba2d13403f6.png)
ai eu queria colocar para ele mandar .mp4 ou .png para se for imagem ou video e mandar o arquivo certo pq ele mandou um arquivo nd a ver kk

**Comment by KillovSky** [comment]
> eu conseguir fazer e ficou assim 
> ![image](https://user-images.githubusercontent.com/79427063/131432805-83935ead-ff51-4b5a-acce-cba2d13403f6.png)
> ai eu queria colocar para ele mandar .mp4 ou .png para se for imagem ou video e mandar o arquivo certo pq ele mandou um arquivo nd a ver kk

Mostre-me como o arquivo foi enviado, pois seu código acima me é um pouco confuso, desculpe, então preciso de toda informação possivel.

**Comment by dodouuglas** [comment]
![image](https://user-images.githubusercontent.com/79427063/131572097-449666bc-be1e-4d9b-ba2b-864007ae4ae7.png)
ele ta mandando assim

**Comment by dodouuglas** [comment]
`	kill.onMessageDeleted(async (msg) => {
		if (msg.body.startsWith("/9j")){
			const mediaData = await decryptMedia(msg, uaOverride)
			kill.sendFile("559391546825-1519748070@g.us", `data:${msg.body.mimetype};base64,${mediaData.toString('base64')}`, '', '')
		} else {
			await kill.sendText("559391546825-1519748070@g.us", `Nova mensagem apagada:\n\nDe: wa.me/+${msg.from.replace('@c.us', '')}\nPara: wa.me/+${msg.to}\nQuando: ${msg.t}\nMensagem: ${msg.body}`)
		}
	})`
	e o script ta assim (eu mandei assim pq eu n sei mandar de outra forma kkkk)

**Comment by PedroBatistop** [comment]
Tente isso, não testei
```
kill.onMessageDeleted(async (msg) => {
  const tipoArquivo = msg.body.mimetype.includes('image') ? '.jpg' : msg.body.mimetype.includes('video') ? '.mp4' : ''
  if (msg.body.startsWith("/9j")) {
    const mediaData = await decryptMedia(msg, uaOverride) 
    await kill.sendFile("559391546825-1519748070@g.us", `data:${msg.body.mimetype};base64,${mediaData.toString('base64')}`, `Deletado${tipoArquivo}`, '')
  } else {
    await kill.sendText("559391546825-1519748070@g.us", `Nova mensagem apagada:\n\nDe: wa.me/+${msg.from.replace('@c.us', '')}\nPara: wa.me/+${msg.to}\nQuando: ${msg.t}\nMensagem: ${msg.body}`) 
  }
})
```

**Comment by dodouuglas** [comment]
deu error `TypeError: Cannot read property 'split' of undefined`

**Comment by dodouuglas** [comment]
tava tentando usar replace mas deu a mesma coisa

**Comment by PedroBatistop** [comment]
Tenta agora, código atualizado.

**Comment by dodouuglas** [comment]
deu a mesma coisa

**Comment by KillovSky** [comment]
> deu a mesma coisa 

Tente por `Deletado.${tipoArquivo}`.
Se a resposta de mimetype for **"image/png"** por exemplo, faltaria inserir um `.` para que realmente fosse enviado no formato de **"png"**.

**Comment by dodouuglas** [comment]
deu a mesma coisa

**Comment by PedroBatistop** [comment]
Código atualizado. Tenha certeza que o código que você está utilizando é o certo, apague o antigo e coloque o novo no lugar. Se não der certo, por favor, envie o comando e a resposta dada pelo bot no whatsapp e o erro no console.

**Comment by dodouuglas** [comment]
eu mandei uma imagem e apaguei para todos e deu a mesma coisa 
![image](https://user-images.githubusercontent.com/79427063/131924894-fc8143cf-c6a6-4edc-83b4-3a4ebff825fe.png)

**Comment by PedroBatistop** [comment]
Que coisa? Posso ver o print da conversa do whatsapp com o comando e a mensagem de erro? Me manda o erro que aparece no console.

**Comment by PedroBatistop** [comment]
Me manda print do seu código

**Comment by dodouuglas** [comment]
so tem o error ele n manda nd n. esse script ai e para quando alguem mandar uma ft/video e apagar o bot ira mandar nesse grupo

**Comment by PedroBatistop** [comment]
Então, me manda o código

**Comment by dodouuglas** [comment]
e esse q vc me mandou ta do mesmo jeito

**Comment by marru453** [comment]
A mi también me daba error, use corchetes y símbolos, ; para cerrar códigos y separar funciones. Espero que esto te sirva

**Comment by PedroBatistop** [comment]
Perdão pelo erro bobo, código corrigido, dessa vez vai! Eu estava levando em conta o sue código base, onde lê-se `msg.body.mimetype`, o que está errado. O certo seria `msg.mimetype`.

**Comment by dodouuglas** [comment]
nss vdd kkkkk

**Comment by dodouuglas** [comment]
deu certo

**Comment by dodouuglas** [comment]
agora vou tentar fazer um bagui para desativar e ativar nos grupos

**Comment by KillovSky** [comment]
> e esse q vc me mandou ta do mesmo jeito

Minhas ultimas ideias:

Use alternadores.

```javascript
if (msg.body.mimetype.split('/')[0] == 'image') {
     await kill.sendFile("559391546825-1519748070@g.us", `data:image/jpg;base64,${mediaData.toString('base64')}`, 'foto.jpg', '')
} else if (msg.body.mimetype.split('/')[0] == 'video') {
      await kill.sendFile("559391546825-1519748070@g.us", `data:video/mp4;base64,${mediaData.toString('base64')}`, 'video.mp4', '')
} else {
     await kill.sendFile("559391546825-1519748070@g.us", `data:${msg.body.mimetype};base64,${mediaData.toString('base64')}`, `deletado.${tipoArquivo}`, '')
}
```

Mescle dentro do verificador de midia que você fez, se falhar, teste o sistema de `forwarding` de mensagens da wa-automate para encaminhar a mensagem - não sei faze-lo por nunca ter tentado e nem lido a sua documentação, veja ela [aqui](https://docs.openwa.dev/classes/api_Client.Client.html#forwardMessages), mas creio que seja:

```javascript
await kill.forwardMessages("559391546825-1519748070@g.us", message.id, true)
```

**NÃO USE DIRETO**, analise se está correto pois eu estou **CHUTANDO O USO.**

Se falhar novamente tente salvar ela no HD/SSD.

```javascript
let randNbr = Math.floor(Math.random() * 10000) + 1
let fileName = `${randNbr}.${tipoArquivo}`
await fs.writeFileSync(fileName, `data:${msg.body.mimetype};base64,${mediaData.toString('base64')}`)
await kill.sendFile("559391546825-1519748070@g.us", fileName, '', '')
```

Não testado - pois não posso testar - se nem isso funcionar então não sei te dar uma ideia funcional pois literalmente já deveria funcionar pois testamos ideias literalmente diretas.

**Comment by PedroBatistop** [comment]
```
kill.onMessageDeleted(async (msg) => {
  if (msg.type == 'image' || msg.type == 'video' || msg.type == 'audio' || msg.type == 'document' || msg.type == 'unknown') {
    const tipoArquivo = msg.mimetype.split('/')[1]
    const mediaData = await decryptMedia(msg, uaOverride) 
    await kill.sendFile("559391546825-1519748070@g.us", `data:${msg.mimetype};base64,${mediaData.toString('base64')}`, 'Deletado.'+`${tipoArquivo}`, '')
  } else if (msg.type == 'chat') {
    await kill.sendText("559391546825-1519748070@g.us", `Nova mensagem apagada:\n\nDe: wa.me/+${msg.from.replace('@c.us', '')}\nPara: wa.me/+${msg.to}\nQuando: ${msg.t}\nMensagem: ${msg.body}`)
  } else if (msg.type == 'ptt') {
    const mediaData = await decryptMedia(msg)
    await kill.sendPtt("559391546825-1519748070@g.us", `data:${msg.mimetype};base64,${mediaData.toString('base64')}`)
  } else return 0
})
```

**Comment by KillovSky** [comment]
> ```
> kill.onMessageDeleted(async (msg) => {
>   if (msg.type == 'image' || msg.type == 'video' || msg.type == 'audio' || msg.type == 'document' || msg.type == 'unknown') {
>     const tipoArquivo = msg.mimetype.split('/')[1]
>     const mediaData = await decryptMedia(msg, uaOverride) 
>     await kill.sendFile("559391546825-1519748070@g.us", `data:${msg.mimetype};base64,${mediaData.toString('base64')}`, 'Deletado.'+`${tipoArquivo}`, '')
>   } else if (msg.type == 'chat') {
>     await kill.sendText("559391546825-1519748070@g.us", `Nova mensagem apagada:\n\nDe: wa.me/+${msg.from.replace('@c.us', '')}\nPara: wa.me/+${msg.to}\nQuando: ${msg.t}\nMensagem: ${msg.body}`)
>   } else if (msg.type == 'ptt') {
>     const mediaData = await decryptMedia(msg)
>     await kill.sendPtt("559391546825-1519748070@g.us", `data:${msg.mimetype};base64,${mediaData.toString('base64')}`)
>   } else return 0
> })
> ```

Perfeito.
