### ISSUE TITLE
Arquivo JSON

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#191]
![image](https://user-images.githubusercontent.com/44541791/131530829-bc17fbef-b5b8-4e7d-9db3-c6db23dd9708.png)

Mano eu termine editar VIPs agora funcionar,  MUTEpv
mas porque aquele muito longo?
Anti
Silence
antilinks 
etc....
Como tira isso ? 

Code:
![image](https://user-images.githubusercontent.com/44541791/131532832-16168504-ff8f-469a-89c3-8c38639beb0a.png)

**Comment by maradona4** [comment]
Agora Conseguir vdd, eu achei era "mentionedJidList[0]"

**Comment by maradona4** [comment]
A mano vdd dnv 

como remover contato 
![image](https://user-images.githubusercontent.com/44541791/131538913-11448629-8c27-4cfe-b6eb-369241b3bcd8.png)
Rebaixar VIP

**Comment by patulinomods** [comment]
Eu tava fazendo isso kkkkkk, so que o meu ia sem mais simples
seu chato, to a moh tempo tentando botar meu nome no repo da iris kkk

**Comment by maradona4** [comment]
kkkk

> Eu tava fazendo isso kkkkkk, so que o meu ia sem mais simples
> seu chato, to a moh tempo tentando botar meu nome no repo da iris kkk

kkkkk
