### ISSUE TITLE
Erro HTTP /perfil

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#193]
![image](https://user-images.githubusercontent.com/44541791/131581571-80a203bd-a2a6-439d-8363-bd9710e1d37d.png)

**Comment by PedroBatistop** [comment]
É o que está escrito na descrição do erro. Você fez muitas tentativas e fez com que o servidor bloqueasse seus acessos por excesso de tentativas.

**Comment by maradona4** [comment]
vish , F

**Comment by maradona4** [comment]
![image](https://user-images.githubusercontent.com/44541791/131583395-ec51b330-1ea2-4fdf-b37d-dec18cc0c15a.png)

Acabei de fazer, agr eu entendi
