### ISSUE TITLE
/gerador

### ISSUE THREAD

**Issue by patulinomods** [KillovSky/iris#197]
![image](https://user-images.githubusercontent.com/73912095/131767902-c898b3e4-62b1-45fa-88f3-8abb905301b0.png)
Entao, o comando /gerador nao estava pegando eett eu ativei a funçao _"Windows Subsistema para Linux opção (Beta)'_ Mesmo depois de reiniciar continuou isso, ja tentei apenas digitar _bash_ no terminal , mais deu o mesmo erro

**Comment by KillovSky** [comment]
> ler #125 

Obrigado!
Também experimente instalar o **"GIT BASH"** e se ainda ocorrer erro, adicione o local do arquivo `bash.exe` nas **variaveis do sistema** no seu windows.

**Comment by maradona4** [comment]
> > ler #125
> 
> Obrigado!
> Também experimente instalar o **"GIT BASH"** e se ainda ocorrer erro, adicione o local do arquivo `bash.exe` nas **variaveis do sistema** no seu windows.

Denada =)
