### ISSUE TITLE
Falhar /greet on

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#198]
![image](https://user-images.githubusercontent.com/44541791/131776550-1a1f78b1-0880-441f-a41f-3422b99d6368.png)

funcao ativada

Deu erro
![image](https://user-images.githubusercontent.com/44541791/131776591-f09e756e-ff52-40f8-93b9-b08a7c5f87b2.png)

Code
![image](https://user-images.githubusercontent.com/44541791/131776674-6cb3c5d7-6152-4c84-91d1-7eb4a2b5a0f9.png)

**Comment by PedroBatistop** [comment]
tente atualizar os módulos usando `npm update`.

**Comment by maradona4** [comment]
ok

**Comment by maradona4** [comment]
![d4164203-a494-4830-8d22-215f7244bd4a](https://user-images.githubusercontent.com/44541791/131877768-913ce13e-c954-4717-b324-5c0927bf9912.jpg)

Valeu funcionar certo, sem erro ;)
