### ISSUE TITLE
Hay alguna manera de quitar este mensaje molesto?

### ISSUE THREAD

**Issue by marru453** [KillovSky/iris#199]
![IMG_20210902_181048](https://user-images.githubusercontent.com/89472552/131879470-b0be6e31-53a3-4271-bfb1-f81993f0543b.jpg)

**Comment by KillovSky** [comment]
> 
> 
> ![IMG_20210902_181048](https://user-images.githubusercontent.com/89472552/131879470-b0be6e31-53a3-4271-bfb1-f81993f0543b.jpg)
> 

Olvidó de insertar el `break` en su `case` - creo.

**Comment by marru453** [comment]
los tengo puestos y nada

**Comment by marru453** [comment]
ya lo arregle, me falto añadir un signo en es.js
