### ISSUE TITLE
O Wa-automate não inicia no goorm ou google shell

### ISSUE THREAD

**Issue by bakapyon** [KillovSky/iris#20]
Não entendi o porquê de não iniciar o Wa-automate nesses sites, ja tentei de tudo mais ele fica congelado.

**Comment by KillovSky** [comment]
Instale o Google Chrome seguindo o tutorial que eu passei na página inicial, isso corrige o problema.

**Comment by bakapyon** [comment]
Eu fiz tudo certinho, mas aparece um erro que não consigo concertar. Segue o erro na imagem em anexo...

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: ***@***.***>
Enviado:sexta-feira, 2 de abril de 2021 14:04
Para: ***@***.***>
***@***.***>; ***@***.***>
Assunto: Re: [KillovSky/iris] O Wa-automate não inicia no goorm ou google shell (#20)


Instale o Google Chrome seguindo o tutorial que eu passei na página inicial, isso corrige o problema.

**Comment by KillovSky** [comment]
Opa, aparentemente a imagem não carregou no envio, tente falar no meu WhatsApp, lá garanto suporte em tempo real.
wa.me/+5518998044132
