### ISSUE TITLE
Duvida sobre alocar a iris em outro HD!

### ISSUE THREAD

**Issue by n2005s** [KillovSky/iris#200]
**Ou killovysky** queria saber se tem como por exemplo eu colocar a Iris em outro HD sem ser o disco local C e dar "npm i" e dps "npm start" em outro HD, é possivel isso?

**Comment by marru453** [comment]
Claro que lo puedes hacer, y si tienes un disco SSD mejor así trabajará más rápido, no importa la unidad, da igual que lo tengas en disco local c o e.ect, la diferencia de un disco HD y ssd, que el HD es muy lento y el ssd trabaja más rápido y así las aplicaciones puede acceder a los archivos más rápido.

**Comment by PedroBatistop** [comment]
Delete a pasta `node_modules` e depois mova todos os arquivos para onde você quer mover. No prompt de comando dê `npm i` e pronto.

**Comment by KillovSky** [comment]
Você pode, mas desde que o sistema de arquivos seja do mesmo tipo do sistema operacional.

Instalar a Íris em um HD/SSD NTFS usando o Linux iria falhar, assim como tentar instalar a Íris em uma partição EXT usando o Windows, afinal, as instalações mudam de arquitetura dependendo do seu sistema operacional.

Windows = NTFS
Linux = EXT
Portateis (Pendrives, cartões SD's...) = FAT

Mantenha o sistema de arquivos do HD/SSD da Íris na mesma formatacão de partição e tudo estará bem.
