### ISSUE TITLE
Hay alguna manera de acelerar el bot? 

### ISSUE THREAD

**Issue by marru453** [KillovSky/iris#201]
Para que responda los comandos más rápido, visto en otros bot que responden rápido pero este suele tardar entre 30 y 40 segundos en responder. Alguna manera sin usar discos duros SSD ni RAM, ni CPU

**Comment by KillovSky** [comment]
Mantén tu PC y WhatsApp limpios, puedes usar al ccleaner, optimiza los servicos de windows tambien (vea google sobre la desactivación de servicios de Windows), reinicia Iris de vez en cuando y también descarga algunos optimizadores (Reducer Memory, recomiendo).

**Comment by marru453** [comment]
De acuerdo.
