### ISSUE TITLE
cmd : /admins 

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#202]
![image](https://user-images.githubusercontent.com/44541791/131924444-90126928-fb31-47ea-a5fb-9014a5e253c7.png)

Code: 
![image](https://user-images.githubusercontent.com/44541791/131924474-6c779ec3-4d82-4b4b-9313-ae36b37c836d.png)

bot não mandar msg
![image](https://user-images.githubusercontent.com/44541791/131924536-6baf55b1-219f-4ce8-abe5-3266e9ab6f5f.png)

**Comment by marru453** [comment]
Elimina app.data y inicia de nuevo, ya que el servidor está lleno de gente por eso va lento

**Comment by KillovSky** [comment]
#179 e #42, basicamente, não se pode mandar mensagens para quem não faz parte dos seus contatos.
@marru453 obrigado por tentar ajudar! sz
