### ISSUE TITLE
Zerar o sistema de xp

### ISSUE THREAD

**Issue by KingBot422** [KillovSky/iris#204]
Há um participante do grupo que cada mensagem que ele manda ele ganha 1k de XP.... Msm configurando para dar de 1 a 5 de XP por msg. Gostaria de saber se resetando o sistema de XP iris resolver o caso, e também como reseto ele... O arquivo...

**Comment by KillovSky** [comment]
> Há um participante do grupo que cada mensagem que ele manda ele ganha 1k de XP.... Msm configurando para dar de 1 a 5 de XP por msg. Gostaria de saber se resetando o sistema de XP iris resolver o caso, e também como reseto ele... O arquivo...

Verifique se fez a edição corretamente e para resetar o XP, vá no arquivo `level.json` e delete tudo, deixe apenas o `[]`.
