### ISSUE TITLE
n consigo instalar

### ISSUE THREAD

**Issue by pablorere** [KillovSky/iris#205]
![image](https://user-images.githubusercontent.com/65947059/132042680-50b9a51e-9321-445b-b1be-2ac15e6693aa.png)

**Comment by marru453** [comment]
` npm i -y `
`npm update @open.wa/wa.automate`

**Comment by marru453** [comment]
https://github.com/KillovSky/iris/discussions/28

**Comment by pablorere** [comment]
> `npm i -y`
> `npm update @open.wa/wa.automate`

continuo sem conseguir

**Comment by KillovSky** [comment]
> > `npm i -y`
> > `npm update @open.wa/wa.automate`
> 
> continuo sem conseguir

Facã a instalacão pela sua area de trabalho e não direto na raiz do sistema.
Ou tente executar isso como administrador.

`npm i --force`

**Comment by pablorere** [comment]
> > > `npm i -y`
> > > `npm update @open.wa/wa.automate`
> > 
> > 
> > continuo sem conseguir
> 
> Faça a instalacão pela sua area de trabalho e não direto na raiz do sistema.
> Ou tente executar isso como administrador.
> 
> `npm i --force`
> 
> Se não funcione verifique as permissões do seu sistema, versão do nodeJS e também tente instalar a wa automate manual.
> 
> `npm i @open-wa/wa-automate@latest --force`

funcionou mais ou meno 
![image](https://user-images.githubusercontent.com/65947059/132053802-0058aa04-e917-440b-a187-11947e05e529.png)
 agr fica dando isso

**Comment by KillovSky** [comment]
> > > > `npm i -y`
> > > > `npm update @open.wa/wa.automate`
> > > 
> > > 
> > > continuo sem conseguir
> > 
> > Faça a instalacão pela sua area de trabalho e não direto na raiz do sistema.
> > Ou tente executar isso como administrador.
> > 
> > `npm i --force`
> > 
> > Se não funcione verifique as permissões do seu sistema, versão do nodeJS e também tente instalar a wa automate manual.
> > 
> > `npm i @open-wa/wa-automate@latest --force`
> 
> funcionou mais ou meno 
> ![image](https://user-images.githubusercontent.com/65947059/132053802-0058aa04-e917-440b-a187-11947e05e529.png)
>  agr fica dando isso
> 

Por acaso você ta usando a node_modules de outro PC? Ai o erro diz bem claro que sua pasta canvas não foi moldada no seu sistema operacional atual, faça instalação do zero.

**Comment by marru453** [comment]
Amigo siga los pasos de los tutoriales, y si estás con el portátil te recomiendo que pases a pc sobremesa, y instala todos los archivos necesarios y comproba que tu sistema tenga las aplicaciones de Microsoft visual, y luego escriba npm i -y este comando te descarga todos los módulos, luego comproba que tu open.wa está en la última versión
