### ISSUE TITLE
Ola, novo comando!

### ISSUE THREAD

**Issue by patulinomods** [KillovSky/iris#207]
Ola caro **Lucas R**, hoje dia 03/09/2021 estou tentando criar um novo comando, que no caso eh o /qrpix, mas eu nao estou consegundo terminar ele, o codigo esta da seguinte maneira:

_case 'qrpix':
					if (args[0].toLowerCase() == '-telefone') {
					if(args.length == 0) {
						kill.reply(from, `Informe sua chave pix numero de telefone!`, id)
					} else
					if(args.length >> 11) {
						kill.reply(from, `USE APENAS CHAVE PIX NUMERO DE TELEFONE`, id)
					} else
					await kill.sendFileFromUrl(from, `https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=00020126360014BR.GOV.BCB.PIX0114+${args[1]}5204000053039865802BR5925QR%20PIX%20%ALEXA%20BOT6009Sao%20Paulo62130509844528555630455B3`, id)
				} else if (args[0].toLowerCase() == '-cpf') {
					if(args.length == 0) {
						kill.reply(from, `Informe sua chave pix cpf!`, id)
					} else
					if(args.length >> 11) {
						kill.reply(from, `USE APENAS CHAVE PIX CPF`, id)
					} else
					await kill.sendFileFromUrl(from, `https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=00020126360014BR.GOV.BCB.PIX0114${args[1]}5204000053039865802BR5925QR%20PIX%20%ALEXA%20BOT6009Sao%20Paulo62130509844528555630455B3`, id)
				}  else if (args[0].toLowerCase() == '-chavealeatoria') {
					if(args.length == 0) {
						kill.reply(from, `Informe sua chave pix chave aleatoria de telefone!`, id)
					} else
					if(args.length >> 36) {
						kill.reply(from, `USE APENAS CHAVE PIX CHAVE ALEATORIA`, id)
					} else
					await kill.sendFileFromUrl(from, `https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=00020126360014BR.GOV.BCB.PIX0114${args[1]}5204000053039865802BR5925QR%20PIX%20%ALEXA%20BOT6009Sao%20Paulo62130509844528555630455B3`, id)
				} else if (args[0].toLowerCase() == '-help') {
					kill.reply(from, `COMO USAR O GERADOR DE QR PIX:\n\n/qrpix -cpf\n/qrpix -telefone\n/qrpix -chavealeatoria`)
				}
				else kill.reply(from, `Use /qrpix -help`)
				break_

**Print Do codigo:**

![image](https://user-images.githubusercontent.com/73912095/132075589-bbbaf143-e392-47c5-8bad-3934c878ea0a.png)

Gostaria que voce pudesse me ajudar a criar esse comando, pois alem do whatsapp ja ter o proprio sistema de pagamento, eu gostaria de fazer um bot onde ele estara gerando chave pix por QR code, como base do pix copia e cola, eu peguei do site **[gerarpix](https://www.gerarpix.com.br/)**
Onde ele gera pix qr code pensonalizado!

**Comment by KillovSky** [comment]
Acredito eu que isso pode acabar sendo bloqueado e dar prejuizos.
Dê uma lida nisso [Manual BR Code](https://www.bcb.gov.br/content/estabilidadefinanceira/spb_docs/ManualBRCode.pdf), você verá sobre a construção da estrutura de um QR Code para Pix.

De forma geral, seu `args.length` tem dois `>`, seu `kill.sendFileFromUrl` está faltando o "nome.png" e a descrição da imagem antes do `id` e você deve utilizar `await kill` e não apenas `kill`, a diferença e que se usar await ele espera alguém terminar de usar antes de usar de novo, assim evitando sobrecarga.

**Comment by patulinomods** [comment]
Muito obg, eu tinha mts duvidas sobre o _await_

**Comment by dodouuglas** [comment]
@patulinomods eu consertei o comando e o link q tava errado
[comando qrpix.txt](https://github.com/KillovSky/iris/files/7192758/comando.qrpix.txt)

**Comment by 4devs-net-br** [comment]
https://4devs.net.br/gerador-cpf
