### ISSUE TITLE
Imagem API

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#208]
Sites Naruto: https://api.zeks.me/api/naruto?apikey=(MINHA_API_KEY)&text=TEXT%20BANG

Code:
![image](https://user-images.githubusercontent.com/44541791/132081317-5f3c1b3e-d163-4fde-8892-834f0d7bbb26.png)

![image](https://user-images.githubusercontent.com/44541791/132081322-da77b8ba-9548-413b-a9eb-7d1e9b71c519.png)
Deu Falhar

**Comment by KillovSky** [comment]
> Sites Naruto: https://api.zeks.me/api/naruto?apikey=iO8palFa86diKK9PoycIWrHipUR&text=TEXT%20BANG
> 
> Code:
> ![image](https://user-images.githubusercontent.com/44541791/132081317-5f3c1b3e-d163-4fde-8892-834f0d7bbb26.png)
> 
> ![image](https://user-images.githubusercontent.com/44541791/132081322-da77b8ba-9548-413b-a9eb-7d1e9b71c519.png)
> Deu Falhar
> 

Timeout de 30000ms significa que o site demorou mais de 30 segundos para conseguir processar seu comando.
Adicione uns `await sleep(10000)` no meio das suas funções para dar tempo da pagina carregar, mude o 10000 para um valor que desejar em MILISSEGUNDOS.

E não exponha sua KEY, você pode ser bloqueado e perder acesso a ela se expor sua KEY privada visualmente.

**Comment by maradona4** [comment]
entendi
