### ISSUE TITLE
Empréstimos de XP com a BOT (Auto-Agiotagem)

### ISSUE THREAD

**Issue by wesley0209** [KillovSky/iris#210]
Queria um código pros negativados conseguirem fazer um empréstimo diretamente com o sistema, sem depender de outra pessoa, porém apenas quem estiver abaixo de 0 irá conseguir o empréstimo, um valor apenas pra ele sair do 0,  daí ele tem de devolver tendo ou não em 5 minutos.

Eu quebrei a minha cabeça tentando desenvolver um mas não conseguir, quem puder me ajudar por favor.

**Comment by KillovSky** [comment]
```javascript
case 'emprestar':
    let checkNeg = await gaming.getValue(user, nivel, 'xp')
if (Number(checkNeg) < 0 && !isNaN(args[0])) {
     await kill.reply(from, 'Seu emprestimo foo aprovado', id)
     await gaming.addValue(user, Number(args[0])), nivel, 'xp')
     await kill.reply(from, 'Seu emprestimo foi concluido, você tem até 30 minutos para devolver tudo.', id)
     await sleep(1800000) // 30 minutos em milissegundos
     await gaming.addValue(user, Number(-args[0])), nivel, 'xp')
     await kill.reply(from, 'O valor do emprestimo foi retirado de você.', id)
} else return await kill.reply(from, `Você não tem os requisitos para um emprestimo, para ter, precisará estar negativo e usar da seguinte forma: ${prefix}Emprestar Valor.`, id)
break
```

Melhore o código por si mesmo e deixe-o lindo, boa sorte.

**Comment by KillovSky** [comment]
> Queria um código pros negativados conseguirem fazer um empréstimo diretamente com o sistema, sem depender de outra pessoa, porém apenas quem estiver abaixo de 0 irá conseguir o empréstimo, um valor apenas pra ele sair do 0,  daí ele tem de devolver tendo ou não em 5 minutos.
> 
> Eu quebrei a minha cabeça tentando desenvolver um mas não conseguir, quem puder me ajudar por favor. 

```javascript
case 'emprestar':
    let checkNeg = await gaming.getValue(user, nivel, 'xp')
    if (Number(checkNeg) < 0 && !isNaN(args[0])) {
         await kill.reply(from, 'Seu emprestimo foo aprovado', id)
         await gaming.addValue(user, Number(args[0])), nivel, 'xp')
         await kill.reply(from, 'Seu emprestimo foi concluido, você tem até 30 minutos para devolver tudo.', id)
         await sleep(1800000) // 30 minutos em milissegundos
         await gaming.addValue(user, Number(-args[0])), nivel, 'xp')
        await kill.reply(from, 'O valor do emprestimo foi retirado de você.', id)
     } else return await kill.reply(from, `Você não tem os requisitos para um emprestimo, para ter, precisará estar negativo e usar da seguinte forma: ${prefix}Emprestar Valor.`, id)
     break
```

É uma base, ela precisa de melhorias para ficar linda e sem glitches de dinheiro, entãooo, essa parte eu deixo contigo, afinal, meu intuito na Íris e dar uma base para construirem por si mesmos ;)

**Comment by wesley0209** [comment]
> > Queria um código pros negativados conseguirem fazer um empréstimo diretamente com o sistema, sem depender de outra pessoa, porém apenas quem estiver abaixo de 0 irá conseguir o empréstimo, um valor apenas pra ele sair do 0,  daí ele tem de devolver tendo ou não em 5 minutos.
> > Eu quebrei a minha cabeça tentando desenvolver um mas não conseguir, quem puder me ajudar por favor.
> 
> ```js
> case 'emprestar':
>     let checkNeg = await gaming.getValue(user, nivel, 'xp')
>     if (Number(checkNeg) < 0 && !isNaN(args[0])) {
>          await kill.reply(from, 'Seu emprestimo foo aprovado', id)
>          await gaming.addValue(user, Number(args[0])), nivel, 'xp')
>          await kill.reply(from, 'Seu emprestimo foi concluido, você tem até 30 minutos para devolver tudo.', id)
>          await sleep(1800000) // 30 minutos em milissegundos
>          await gaming.addValue(user, Number(-args[0])), nivel, 'xp')
>         await kill.reply(from, 'O valor do emprestimo foi retirado de você.', id)
>      } else return await kill.reply(from, `Você não tem os requisitos para um emprestimo, para ter, precisará estar negativo e usar da seguinte forma: ${prefix}Emprestar Valor.`, id)
>      break
> ```
> 
> É uma base, ela precisa de melhorias para ficar linda e sem glitches de dinheiro, entãooo, essa parte eu deixo contigo, afinal, meu intuito na Íris e dar uma base para construirem por si mesmos ;)

Muito obrigado. Salvou a pátria
