### ISSUE TITLE
Comprar VIP time

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#212]
![image](https://user-images.githubusercontent.com/44541791/132152021-b105c050-32ee-4a9b-a0cf-7309ab96a1fa.png)
esse certo? 1 horas 
await sleep(1000000)
🤔

eu nao sei esse resultado
![image](https://user-images.githubusercontent.com/44541791/132152104-664f7dd5-956e-4ef8-8ba1-db719d0d86fa.png)

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/132152021-b105c050-32ee-4a9b-a0cf-7309ab96a1fa.png)
> esse certo? 1 horas 
> await sleep(1000000)
> 🤔
> 
> eu nao sei esse resultado
> ![image](https://user-images.githubusercontent.com/44541791/132152104-664f7dd5-956e-4ef8-8ba1-db719d0d86fa.png)
> 
> 

1 hora é 3600000 milissegundos sim, mas não entendi qual o problema que você está tendo, peço que dê detalhes.

**Comment by maradona4** [comment]
![image](https://user-images.githubusercontent.com/44541791/132207095-8a7550b3-de6c-40f4-ac4c-3ab4dedf88c2.png)
Eu sou conseguir !

eu acho era "setTimeout"
