### ISSUE TITLE
Console cairo

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#214]
![image](https://user-images.githubusercontent.com/44541791/132264199-1523f85b-6f60-4bee-9955-6498ac920e53.png)

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/132264199-1523f85b-6f60-4bee-9955-6498ac920e53.png)
> 

Isso é realmente um bug na Íris?
Tenha em mente que essa pagina **É PARA SUPORTE DE PROBLEMAS NA PROGRAMAÇÃO DA ÍRIS**, cairo é um sistema - que acredito ser - utilizado no **canvas** mas relacionado a alguma coisa do sistema do seu windows, sua print não exibe um erro, ele apenas diz "Operação foi concluida com exito." ou seja, não ocorreu erros na execução "X", apenas foi executado alguma coisa no "cairo", mas em uma busca pelo Google não encontrei o que seria isso em especifico, exceto que possui relação com a `GNU Compiler Collection` (GCC), que tem algumas referencias com a interface do Windows, Visual-Code e o terminal do Git-Bash, me baseando no nome do erro ali, está font, talvez seja uma simples instalação de fonte no windows, logo não é um bug, reinicie seu PC e teste, se der no mesmo, reinstale o canvas com `npm i canvas --force` ou reinstale a Íris do zero junto com todos os requisitos dela (Git Bash, Visual C+ Redist, Python, FFmpeg...), se ainda assim falhar, dê uma olhada na pagina oficial do ["cairo"](https://cairographics.org).

**Comment by maradona4** [comment]
Entendi
