### ISSUE TITLE
Erro Iniciar "New Windows 11"

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#215]
eu acho era canvas?
'node-pre-gyp' não é reconhecido como um comando interno
![image](https://user-images.githubusercontent.com/44541791/132303505-59e8f1eb-d8cf-49a6-bcb4-eba9072f6f0c.png)

Meu PC acabo atualizador win10 para win11

![image](https://user-images.githubusercontent.com/44541791/132303613-d22efc57-0cfe-4e2e-870e-6d4ba0d54971.png)

**Comment by maradona4** [comment]
![image](https://user-images.githubusercontent.com/44541791/132312360-cb7124c4-5b77-432d-837a-b35f0ae93809.png)

Agr conseguir! achei comandos
npm install canvas -g
e
npm install --verbose sharp
duas mesmo comandos

**Comment by marru453** [comment]
windows 11 va bien?

**Comment by maradona4** [comment]
yes

**Comment by marru453** [comment]
pero el windows 11 es una beta

**Comment by maradona4** [comment]
![image](https://user-images.githubusercontent.com/44541791/132440499-bac17ed8-5458-4505-b006-a2e1773ac408.png)
