### ISSUE TITLE
error al actualizar npm update 

### ISSUE THREAD

**Issue by marru453** [KillovSky/iris#217]
![Captura de pantalla 2021-09-07 220557](https://user-images.githubusercontent.com/89472552/132404672-16623784-6a2b-49f1-b9be-75e11e8298d7.jpg)

no me instala todas los modulos

**Comment by KillovSky** [comment]
> ![Captura de pantalla 2021-09-07 220557](https://user-images.githubusercontent.com/89472552/132404672-16623784-6a2b-49f1-b9be-75e11e8298d7.jpg)
> 
> no me instala todas los modulos

Errores? No hay errores, esto es una advertencia de que algunos módulos están desactualizados y por lo tanto son más vulnerables, pero no se trata de Iris en sí, ya que usamos las últimas versiones, simplemente ignórelo.

**Comment by marru453** [comment]
muchimas gracias
