### ISSUE TITLE
Botao

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#218]
![image](https://user-images.githubusercontent.com/44541791/132448344-073debd7-1d6e-4cff-bae7-c6ee8a346db6.png)

Por que aparece [MENSAGEM]
![image](https://user-images.githubusercontent.com/44541791/132448106-cd7ebfc0-09b6-4853-bcc2-d5d7f7673a9e.png)
Nao achar [CMD-GRUPOS] "/menu" 

code:
![image](https://user-images.githubusercontent.com/44541791/132448364-86b300c9-88c6-4211-8397-c124ebbdf481.png)

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/132448344-073debd7-1d6e-4cff-bae7-c6ee8a346db6.png)
> 
> Por que aparece [MENSAGEM]
> ![image](https://user-images.githubusercontent.com/44541791/132448106-cd7ebfc0-09b6-4853-bcc2-d5d7f7673a9e.png)
> Nao achar [CMD-GRUPOS] "/menu" 
> 
> code:
> ![image](https://user-images.githubusercontent.com/44541791/132448364-86b300c9-88c6-4211-8397-c124ebbdf481.png)

Não compreendo o erro mas minha tese é que isso afeta a estrutura base, não faço ideia de como corrigir mas coloque um `console.log` na `kill.onMessage` e veja o que o parametro `body` contém, se for uma mudança drastica de arquitetura (por exemplo, aparecer que é resposta de botão e não mensagem) você precisará refazer a base da Íris.
Basta moldar o sistema para o `body` de resposta após o botão.

**Comment by maradona4** [comment]
Entendi, eu sou nao funcionar, mas dificil

**Comment by dodouuglas** [comment]
> Entendi, eu sou nao funcionar, mas dificil

tem como me mandar uma base de como fuciona esses butoes?

**Comment by dodouuglas** [comment]
acho q tem um evento para fucionar

**Comment by dodouuglas** [comment]
https://docs.openwa.dev/classes/api_Client.Client.html#onButton

**Comment by dodouuglas** [comment]
isso vc coloca la na index
```	kill.onButton(async (msg) => {
		if(msg.body == '!menu' && msg.type == 'buttons_response')
		const theMsg = await gaming.getValue(user, nivel, 'msg')
		const uzrXp = await gaming.getValue(user, nivel, 'xp')
		const uzrlvl = await gaming.getValue(user, nivel, 'level')
		const mping = processTime(t, moment())
		await kill.reply(from, mess.menu(pushname, time, theMsg, uzrXp, getReqXP(uzrlvl), uzrlvl, mping, patente), id)
	})
```

**Comment by dodouuglas** [comment]
e isso la em cima nas `const`
```const { gaming } = require('./lib/functions')
const nivel = JSON.parse(fs.readFileSync('./lib/config/Gerais/level.json'))
const moment = require('moment-timezone')
var region = config.Language
var mess = mylang(region);moment.tz.setDefault('America/Sao_Paulo').locale('pt_BR')
const math = require('mathjs')`
```

**Comment by maradona4** [comment]
![image](https://user-images.githubusercontent.com/44541791/132779897-f83445f3-39e4-444d-965a-9b9244727d3b.png)

ReferenceError: msg is not defined

**Comment by dodouuglas** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/132779897-f83445f3-39e4-444d-965a-9b9244727d3b.png)
> 
> ReferenceError: msg is not defined

ja consertou? me mostra qual e a linha

**Comment by dodouuglas** [comment]
e pq n tava aparecendo tudo 
[butao.txt](https://github.com/KillovSky/iris/files/7140755/butao.txt)

**Comment by maradona4** [comment]
Ja teste, mas funfa

**Comment by KillovSky** [comment]
> Ja teste, mas nao funfa

```javascript
       // Index.js, acima da "kill.onMessage"
	kill.onButton(async (message) => {
		return await kconfig(kill, message)
	})
	
	// Config.js, substitua a linha abaixo
	const { type, id, from, t, sender, author, isGroupMsg, chat, chatId, caption, isMedia, mimetype, quotedMsg, quotedMsgObj, mentionedJidList } = message
	
	// Por essa, ou seja, apague o "id" dela
	const { type, from, t, sender, author, isGroupMsg, chat, chatId, caption, isMedia, mimetype, quotedMsg, quotedMsgObj, mentionedJidList } = message
	
	// Abaixo dela insira isso
	id = message.type == "buttons_response" ? message.quotedMsgObj.footer : message.id
	
	// Modo de uso
	await client.sendButtons(from, 'Mensagem de baixo', [
		{
		        "id": "1",
			"text": "Comando aqui"
		}
	], 'Mensagem de cima')
```
Dei uma voltazinha "rápida" na programação, por sorte, consegui aprender a utilizar rápido o sistema de botões sem adicionar mais de 10 linhas, espero que lhe seja util.

**Comment by KillovSky** [comment]
Leiam a #257
