### ISSUE TITLE
Bot Group issue 

### ISSUE THREAD

**Issue by HAMODE3389** [KillovSky/iris#219]
![image](https://user-images.githubusercontent.com/46901427/132518233-be7569ec-4041-40df-aac0-3374600c3295.png)

The Bot reply to every messages with Ops, For some reason i got errors with this command... in group only.

![1](https://user-images.githubusercontent.com/46901427/132518961-568a535c-f562-474b-8e7c-b0ba4d027ab7.png)

In DM works fine.

**Comment by KillovSky** [comment]
Line 122 is for `NSFW`, this error appears to a corrupted file or object, go to `functions.json` and take a look on NSFW parameter inside.
If there any problem jn NSFW parameter, you can reset her by changing `"nsfw":[Your ID's...]` to `"nsfw":[]`, this will reset the NSFW system.
If the file is corrupted, copy and paste this inside and save.

```json
[{"anti":[],"silence":[],"antilinks":[],"antiporn":[],"antitrava":[],"blacklist":[],"fake":[],"pt":[],"es":[],"en":[],"nsfw":[],"sticker":[],"welcome":[],"xp":[],"thieves":[],"companions":[]}]
```

**Comment by HAMODE3389** [comment]
> Line 122 is for `NSFW`, this error appears to a corrupted file or object, go to `functions.json` and take a look on NSFW parameter inside.
> If there any problem jn NSFW parameter, you can reset her by changing `"nsfw":[Your ID's...]` to `"nsfw":[]`, this will reset the NSFW system.
> If the file is corrupted, copy and paste this inside and save.
> 
> ```json
> [{"anti":[],"silence":[],"antilinks":[],"antiporn":[],"antitrava":[],"blacklist":[],"fake":[],"pt":[],"es":[],"en":[],"nsfw":[],"sticker":[],"welcome":[],"xp":[],"thieves":[],"companions":[]}]
> ```

Thanks, It works now, Actually it was my fault, I removed it from functions.json.
