### ISSUE TITLE
crear comando topparejas

### ISSUE THREAD

**Issue by marru453** [KillovSky/iris#222]
quiero crear un comando de topparejas, cuando algún admin usa el comando !topparejas @usuario1 @usuario2 automaticamente lo agrega en un archivo json con el nombre de topparejas.
config.js 
> `case "topParejas" { 
        if (!isGroupMsg) return await kill.reply(from, mess.sogrupo(), id)
        if (!isBotGroupAdmins) return await kill.reply(from, mess.botademira(), id)	
           const ratings = args.join(' ')
           const personanovia =  `@${mentionedJidList[0].replace('@c.us', '')}`
           const personanovio =  `@${mentionedJidList[1].replace('@c.us', '')}`
           if (!ratings) kill.reply(from, '')
           await kill.sendTextWithMentions(from, fs.writeFileSync('./lib/config/Gerais/TopParejas.json'))};
        break`

![Captura de pantalla 2021-09-08 162205](https://user-images.githubusercontent.com/89472552/132527304-0fddc713-85b0-4969-bd7b-22f1a735b85b.jpg)

**Comment by KillovSky** [comment]
> quiero crear un comando de topparejas, cuando algún admin usa el comando !topparejas @usuario1 @usuario2 automaticamente lo agrega en un archivo json con el nombre de topparejas.
> config.js 
> > `case "topParejas" { 
>         if (!isGroupMsg) return await kill.reply(from, mess.sogrupo(), id)
>         if (!isBotGroupAdmins) return await kill.reply(from, mess.botademira(), id)	
>            const ratings = args.join(' ')
>            const personanovia =  `@${mentionedJidList[0].replace('@c.us', '')}`
>            const personanovio =  `@${mentionedJidList[1].replace('@c.us', '')}`
>            if (!ratings) kill.reply(from, '')
>            await kill.sendTextWithMentions(from, fs.writeFileSync('./lib/config/Gerais/TopParejas.json'))};
>         break`
> 
> ![Captura de pantalla 2021-09-08 162205](https://user-images.githubusercontent.com/89472552/132527304-0fddc713-85b0-4969-bd7b-22f1a735b85b.jpg)
> 

No entiendo nada de lo que planea hacer, pero si desea hacer pares que siempre sigan siendo el mismo resultado, debe crear un objeto con lo par1 y luego insertar lo par2 de valor para ese objeto, luego escribirlo en json con fs y stringify, es un sistema difícil de hacer, como dejé de programar por un tiempo y no tengo mas tiempo libre, hacer y entregar esto es algo que no puedo, pero en general, intente crear de acuerdo con los pasos anteriores.

**Comment by marru453** [comment]
@KillovSky  El sistema es simple, cuando un admin escribe el comando de !topparejas menciona a la pareja, el bot automáticamente la añada a la aplicacion de topparejas.json, es como el comando de blocklist pero un poco mas complejo, aunque quería algo mas avanzado en plan el comando de !emparejar y !topparejas, pero es algo complicado de hacer

**Comment by KillovSky** [comment]
> @KillovSky  El sistema es simple, cuando un admin escribe el comando de !topparejas menciona a la pareja, el bot automáticamente la añada a la aplicacion de topparejas.json, es como el comando de blocklist pero un poco mas complejo, aunque quería algo mas avanzado en plan el comando de !emparejar y !topparejas, pero es algo complicado de hacer

const toppa = JSON.parse(fs.readFileSync('./lib/config/Gerais/TopParejas.json'))

for (let i in mentionedJidList.length) {
     toppa.push(mentionedJidList[i])
}

await fs.writeFileSync('./lib/config/Gerais/TopParejas.json', JSON.stringify(toppa))

**Comment by marru453** [comment]
eso en donde lo añado?
