### ISSUE TITLE
butoes

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#224]
ja sabe como usa os butoes? kkk

**Comment by KillovSky** [comment]
#218 tem um exemplo de código do @maradona4 e na #178 tem um código meu de exemplo, não sei se o meu vai funcionar pois ainda não usei os botões.

**Comment by dodouuglas** [comment]
maradona4

**Comment by markoswythor** [comment]
> ja sabe como usa os butoes? kkk`


**eu adiciono os 3 botões assim:**

```
		case 'teste2':
			await kill.sendButtons(from, 'msg de baixo',  [
                {
                    "id":"id1",
                    "text": "msg1"
                },
                {
                    "id":"id2",
                    "text": "msg2"
                },
                {
                    "id":"id3",
                    "text": "msg3"
                }
            ],"msg principal")
			break
```
porém quando clico não n faz nem uma função mas se vc pegar os exemplos dos outros códigos talvez pegue

**também esse código pega:** (resumido)


```
		case 'testesla':
				await kill.sendButtons(from, "txt de baixo", [{ id: "0", "text": 'botão1'}], 'texto de cima')
				break
```

**Comment by KillovSky** [comment]
> > ja sabe como usa os butoes? kkk`
> 
> 
> **eu adiciono os 3 botões assim:**
> 
> ```
> 		case 'teste2':
> 			await kill.sendButtons(from, 'msg de baixo',  [
>                 {
>                     "id":"id1",
>                     "text": "msg1"
>                 },
>                 {
>                     "id":"id2",
>                     "text": "msg2"
>                 },
>                 {
>                     "id":"id3",
>                     "text": "msg3"
>                 }
>             ],"msg principal")
> 			break
> ```
> porém quando clico não n faz nem uma função mas se vc pegar os exemplos dos outros códigos talvez pegue
> 
> **também esse código pega:** (resumido)
> 
> 
> ```
> 		case 'testesla':
> 				await kill.sendButtons(from, "txt de baixo", [{ id: "0", "text": 'botão1'}], 'texto de cima')
> 				break
> ```

É necessario criar outro sistema de comandos, da qual se trata da `kill.onButton`.
É uma tarefa um pouco dificil pois é preciso refazer a base da Íris, mas se quiser fazer um teste, duplique as linhas da `kill.onMessage` e mude-a para `kill.onButton`, deve dar um pontapé inicial para descobrir.

P.S: Eu também não sei usar mas pretendo programar isso quando eu voltar a trabalhar no update.

**Comment by KillovSky** [comment]
Ref: #257
