### ISSUE TITLE
MentionAll Feature 

### ISSUE THREAD

**Issue by HAMODE3389** [KillovSky/iris#230]
I found this code around here to mention all members in the group,

        case 'mentionall':
            if (!isGroupMsg) return client.reply(from, 'Only For Groups', id)
            if (!isGroupAdmins) return client.reply(from, 'Only For Admin's Group', id)
            const groupMem = await client.getGroupMembers(groupId)
            let hehe = '╔══ 〘 Mention All 〙 ══\n'
            for (let i = 0; i < groupMem.length; i++) {
                hehe += '╠➥'
                hehe += ` @${groupMem[i].id.replace(/@c.us/g, '')}\n`
            }
            hehe += '╚═〘 - Helllo World - 〙'
            await client.sendTextWithMentions(from, hehe)
            break

How I can make it works on Iris bot ?

**Comment by marru453** [comment]
el bot iris ya lo tiene

**Comment by HAMODE3389** [comment]
> el bot iris ya lo tiene

Really ? , Iris have a lot of features , its hard to find exact one xD

So , What is the command ?

**Comment by KillovSky** [comment]
> I found this code around here to mention all members in the group,
> 
>         case 'mentionall':
>             if (!isGroupMsg) return client.reply(from, 'Only For Groups', id)
>             if (!isGroupAdmins) return client.reply(from, 'Only For Admin's Group', id)
>             const groupMem = await client.getGroupMembers(groupId)
>             let hehe = '╔══ 〘 Mention All 〙 ══\n'
>             for (let i = 0; i < groupMem.length; i++) {
>                 hehe += '╠➥'
>                 hehe += ` @${groupMem[i].id.replace(/@c.us/g, '')}\n`
>             }
>             hehe += '╚═〘 - Helllo World - 〙'
>             await client.sendTextWithMentions(from, hehe)
>             break
> 
> How I can make it works on Iris bot ?

Iris don't need because she just have a similar command.
`/everyone`.

Please, ever read the command list.
