### ISSUE TITLE
bug gerador y news

### ISSUE THREAD

**Issue by marru453** [KillovSky/iris#231]
> COMANDO "[!GERADOR]" AS 09/09/21 16:08:31 DE "🍋 ⃢⃞⃝꧁ℒ𝒾𝓂ℴ𝓃𝒸𝒾𝓁𝓁ℴ🍋 ⃢⃞⃝꧂ - []"
Error: Command failed: lib
"lib" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

    at ChildProcess.exithandler (child_process.js:390:12)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:470:12)
    at maybeClose (internal/child_process.js:1055:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:470:12)
    at Pipe.<anonymous> (net.js:675:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'lib'
} "lib" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

> COMANDO "[!NEWS]" AS 09/09/21 16:10:11 DE "🍋 ⃢⃞⃝꧁ℒ𝒾𝓂ℴ𝓃𝒸𝒾𝓁𝓁ℴ🍋 ⃢⃞⃝꧂ - []"
[FALHA GERAL] TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (fs.js:1517:5)
    at kconfig (C:\Users\Born4Kill\Desktop\BT-LIMONCIO\config.js:4736:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async C:\Users\Born4Kill\Desktop\BT-LIMONCIO\index.js:46:3 {
  code: 'ERR_INVALID_ARG_TYPE'

**Comment by maradona4** [comment]
#125

**Comment by marru453** [comment]
lo tengo cambiado y nada

**Comment by marru453** [comment]
> `case 'gerador':
				await exec(`lib`, async (error, stdout, stderr) => {
					if (error || stderr || stdout == null || stdout == '') {
						await kill.reply(from, mess.fail(), id);console.log(error, stderr)
					} else return await kill.sendFileFromUrl(from, 'https://thispersondoesnotexist.com/image', 'image.jpg', stdout, id)
				})
				break`

> `case 'news':
				if (args.length == 0) return await kill.reply(from, mess.noargs() + 'Theme/Tema.', id)
				const theNews = await axios.get(`https://news.google.com/rss/search?q=${body.slice(6)}&hl=${region}`)
				await fs.writeFileSync(theNews.data)
				await exec(`lib`, async (error, stdout, stderr) => {
					if (error || stderr || stdout == null || stdout == '') {
						await kill.reply(from, mess.fail(), id);console.log(error, stderr)
					} else return await kill.reply(from, `${stdout}`, id)
				})
				break`

**Comment by KillovSky** [comment]
> > `case 'gerador':
> 				await exec(`lib`, async (error, stdout, stderr) => {
> 					if (error || stderr || stdout == null || stdout == '') {
> 						await kill.reply(from, mess.fail(), id);console.log(error, stderr)
> 					} else return await kill.sendFileFromUrl(from, 'https://thispersondoesnotexist.com/image', 'image.jpg', stdout, id)
> 				})
> 				break`
> 
> > `case 'news':
> 				if (args.length == 0) return await kill.reply(from, mess.noargs() + 'Theme/Tema.', id)
> 				const theNews = await axios.get(`https://news.google.com/rss/search?q=${body.slice(6)}&hl=${region}`)
> 				await fs.writeFileSync(`lib`,theNews.data)
> 				await exec(`lib`, async (error, stdout, stderr) => {
> 					if (error || stderr || stdout == null || stdout == '') {
> 						await kill.reply(from, mess.fail(), id);console.log(error, stderr)
> 					} else return await kill.reply(from, `${stdout}`, id)
> 				})
> 				break`

Editaste el código? este no es el código que escribí, deshaga las ediciones que haya realizado, cada letra de código que usa shell es importante, cualquier edición incorrecta danara el sistema ya que es una mezcla de Shell y JavaScript.

**Comment by marru453** [comment]
Deshace el código y nada sigue dando error, en gerador me lo pone como null y el news me dice que lib no existe la función

**Comment by marru453** [comment]
@KillovSky  cuando puedas me puedes dar una solución para esto, y si vas a sacar la actualización este mes, espero a la actualización

**Comment by KillovSky** [comment]
> Deshace el código y nada sigue dando error, en gerador me lo pone como null y el news me dice que lib no existe la función 

Revisé el código que escribiste y lo editaste incorrectamente, solo insertaste la carpeta y no el archivo, debería ser exactamente así `./lib/news.xml`, en el tuyo es solo lib.
sobre el generador, instala **GIT BASH**, el único error que puede ocurrir al no abrir el generador es que el bash no pueda ejecutarse, en el peor de los casos, agregue la ubicación de `bash.exe` a las variables de path del sistema, aquí sigue un [tutorial](https://medium.com/@01luisrene/como-agregar-variables-de-entorno-s-o-windows-10-e7f38851f11f).
Usa la ubicacion de `bash.exe`.
