### ISSUE TITLE
banner

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#232]
eu testei o banner e deu error `[FALHA GERAL] Error: Evaluation failed: DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.`

**Comment by KillovSky** [comment]
> eu testei o banner e deu error `[FALHA GERAL] Error: Evaluation failed: DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.`

Basta inserir as respostas em um tradutor e você terá instantaneamente o problema e a solução em mãos.

Embora eu não saiba resolver pois não estou programando, ai diz que o problema é que a string não foi codificada corretamente, ou seja, aparentemente você precisa codificar o sistema para alguma coisa, pode ser que seja base64 por exemplo ou talvez uma object ou algo do tipo.

**Comment by dodouuglas** [comment]
isso eu sei so n sei resolver kkk por isso eu mandei aq

**Comment by KillovSky** [comment]
Tente isso, não testei, estou chutando a forma de uso.

```javascript
let Banner = await decryptMedia(message, uaOverride)
await kill.sendBanner(from, `data:${mimetype};base64,${Banner.toString('base64')}`)
```

Termine de montar a sua case e deve funcionar - eu acho.

Modo de uso: Envie uma imagem com o comando.

**Comment by dodouuglas** [comment]
ata, mas e ser eu quiser colocar uma imagem q ta no pc tipo usando ./

**Comment by dodouuglas** [comment]
> ```js
> let Banner = await decryptMedia(message, uaOverride)
> await kill.sendBanner(from, `data:${mimetype};base64,${Banner.toString('base64')}`)
> ```

como q faz pra mandar com uma imagem que ta no pc?

**Comment by KillovSky** [comment]
Troque a `Base64` por o local, exemplo, `./imagem.jpg`.

**Comment by dodouuglas** [comment]
> Troque a `Base64` por o local, exemplo, `./imagem.jpg`.

![image](https://user-images.githubusercontent.com/79427063/155253536-f540b839-cc0e-4d80-98f7-6f6fb5194999.png)

**Comment by KillovSky** [comment]
Desculpe, precisa ser em `Base64`, para isso, use o `fs` para ler a imagem e utilizar.

Na próxima, leia a página de informações da [Wa-Automate](https://docs.openwa.dev/classes/api_Client.Client.html#sendBanner), pois, essa página se destina a ajudar nos erros e não construir códigos <- #316

```javascript
	const myBannerImage = fs.readFileSync('./Local_Da_Imagem/imagem.jpg', {
		encoding: 'base64'
	})
	await kill.sendBanner(from, tools('others').dataURI(myBannerImage))
```

Creio que seja isso o que você deseja, caso falhe, tente trocar `"tools('others').dataURI(myBannerImage)"` para apenas `"myBannerImage"`, sem as aspas.
