### ISSUE TITLE
Anti Racismo

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#233]
![image](https://user-images.githubusercontent.com/44541791/132923434-c5914d83-4e4d-431d-93a4-99907e75a4b6.png)

Deu logs
Falhar ao iniciado
"includes"

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/132923434-c5914d83-4e4d-431d-93a4-99907e75a4b6.png)
> 
> Deu logs
> Falhar ao iniciado
> "includes"

Sem mostrar o terminal fica dificil saber qual erro tem no parametro `includes`.

**Comment by maradona4** [comment]
Deu certo, agr funcionar

code: message.body ==
assim funcionar
