### ISSUE TITLE
olá, uma duvida aparentemente simples

### ISSUE THREAD

**Issue by llbranco** [KillovSky/iris#235]
parabéns pelo projeto, o bot é maravilhoso, mas infelizmente tem MUITOS comandos pra minha necessidade principal

como devo proceder para permitir que o bot responda sómente aos ADMINS e ninguém mais?
(ahhh sem comprometer a mensagem de boas vindas)

no grupo que pretendo rodar não posso deixar se quer a resposta a um simples "oi" ativada, além disso planejo roda-lo em uma raspberry pi que já esta com muitos outros serviços rodando, então quanto mais enxuto o bot ficar melhor pro meu cenário.
gostaria muito de poder usa-lo como ele é, seria maravilhoso, mas conheço os usuários do meu grupo, ter o bot aberto é pior do que não te-lo e estou desesperado precisando de anti-spam, anti-trava, mensagem de boas vindas e TALVEZ enviar "F" toda vez que alguém for expulso do grupo, no MAXIMO isso.

grato pela compreenção
e agradeço pelo excelente trabalho com esse bot incrível

**Comment by KillovSky** [comment]
Sobre responder somente aos administradores, isso aqui deve funcionar

```javascript
if (isGroupMsg && !isGroupAdmins && !isOwner) return
```

Insira isso junto aos ifs lá em cima, ou seja, os ifs de anti-trava, anti pornografia e outros.

Sobre limitar comandos, vá na `case` que deseja limitar e insira '/*' atras da case, ficando `/*case`.
Vá no `break` e insira '*/' depois dele, ficando `break*/`.

Isso deve impedir o comando de executar.

Se deseja criar mensagens customizadas, tem um código já pronto na linha [#331](https://github.com/KillovSky/iris/blob/main/config.js#L331) para criar.

Limitar o welcome basta adicionar a if para que ele não seja ativado por administradores.

```javascript
if (!isOwner) return await kill.reply(from, mess.sodono(), id)
```

E por fim, se quer editar o welcome, basta desativar as linhas que deseja com //
Por exemplo, para desativar a mensagem de audio insira // ao `await kill.sendPtt(...)`

`// await kill.sendPtt(....)`

As linhas que tem escrito `mess` e `mylanguage`, são as linhas de dialogo, pra mudar eles só ir nos arquivos de linguagem em `lib/lang`.

Creio ser isso.
