### ISSUE TITLE
Whatsapp Próprio

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#236]
![image](https://user-images.githubusercontent.com/44541791/132955494-2a6bc6d7-ab18-4bf1-a56a-6fc5b271698e.png)

o que isso, esse meu numero, acho e bot

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/132955494-2a6bc6d7-ab18-4bf1-a56a-6fc5b271698e.png)
> 
> o que isso, esse meu numero, acho e bot

Esse é seu proprio WhatsApp, você pode rodar comandos ai dentro se ativar o sistema de comandos na `index.js`.

A mensagem é um sistema de segurança da wa-automate, serve para informar o usuario de que tem bots no controle da conta, para assim ele saber se está sendo clonado ou não.

**Comment by maradona4** [comment]
Entendi
