### ISSUE TITLE
no me funciona bien el news y gerador

### ISSUE THREAD

**Issue by marru453** [KillovSky/iris#237]
> COMANDO "[!NEWS]" AS 11/09/21 15:48:04 DE "🍋 ⃢⃞⃝꧁ℒ𝒾𝓂ℴ𝓃𝒸𝒾𝓁𝓁ℴ🍋 ⃢⃞⃝꧂ - [34631110323]"
null

> COMANDO "[!GERADOR]" AS 11/09/21 15:47:33 DE "🍋 ⃢⃞⃝꧁ℒ𝒾𝓂ℴ𝓃𝒸𝒾𝓁𝓁ℴ🍋 ⃢⃞⃝꧂ - [34631110323]"
null

**Comment by maradona4** [comment]
mi trabajo
![image](https://user-images.githubusercontent.com/44541791/132976657-fe65491b-3a6a-42c9-a887-ca8037eb150d.png)

**Comment by KillovSky** [comment]
> mi trabajo
> ![image](https://user-images.githubusercontent.com/44541791/132976657-fe65491b-3a6a-42c9-a887-ca8037eb150d.png)
> 

Editado incorretamente, você deletoi da linha até mesmo o bash config.sh que é **ESSENCIAL**.
Desfaça suas modificações e apague apenas o `/scripts`.

**Comment by marru453** [comment]
@KillovSky hice lo que me dijiste y solo me funcionó el de gerador, el de news sigue dando error

**Comment by KillovSky** [comment]
> @KillovSky hice lo que me dijiste y solo me funcionó el de gerador, el de news sigue dando error 

Screenshot del console?

**Comment by marru453** [comment]
case 'news':
				if (args.length == 0) return await kill.reply(from, mess.noargs() + 'Theme/Tema.', id)
				const theNews = await axios.get(`https://news.google.com/rss/search?q=${body.slice(6)}&hl=${region}`)
				await fs.writeFileSync('./lib/news.xml', theNews.data)
				await exec(`cd lib`, async (error, stdout, stderr) => {
					if (error || stderr || stdout == null || stdout == 'config.sh') {
						await kill.reply(from, mess.fail(), id);console.log(error, stderr)
					} else return await kill.reply(from, `${stdout}`, id)
				})
				break
cuando usas el comando de news el bot envía la noticia de lo que le has dicho

**Comment by KillovSky** [comment]
> @KillovSky  ahí tienes el código 
> 
> 
> case 'news':
> 				if (args.length == 0) return await kill.reply(from, mess.noargs() + 'Theme/Tema.', id)
> 				const theNews = await axios.get(`https://news.google.com/rss/search?q=${body.slice(6)}&hl=${region}`)
> 				await fs.writeFileSync('./lib/news.xml', theNews.data)
> 				await exec(`cd lib`, async (error, stdout, stderr) => {
> 					if (error || stderr || stdout == null || stdout == 'config.sh') {
> 						await kill.reply(from, mess.fail(), id);console.log(error, stderr)
> 					} else return await kill.reply(from, `${stdout}`, id)
> 				})
> 				break
> cuando usas el comando de news el bot envía la noticia de lo que le has dicho

`cd lib`???

Nuevamente, usted has hecho una edición totalmente incorrecta, no es solo `cd lib`, comience de nuevo y haga las ediciones correctas nuevamente desde cero y **preste mucha atención** ya que un error comprometerá el código.
