### ISSUE TITLE
Adicionar do bot?

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#238]
![image](https://user-images.githubusercontent.com/44541791/132967170-b3db27bd-ade0-464e-9c57-2d524d5db08c.png)
Adicionar do bot?

Console
![image](https://user-images.githubusercontent.com/44541791/132967165-fa412159-066c-486e-b0a1-ccdbea2137a6.png)

bot config:
Resquito: acima 60+ membros
Grupos Limite: 20

Atual Grupos
17/20

**Comment by dodouuglas** [comment]
o butao n fucionou? manda o script para eu ver se consigo ajudar

**Comment by maradona4** [comment]
> o butao n fucionou? manda o script para eu ver se consigo ajudar

outro grupos do bot! Olha, ele(a) funcionar tentar botão  lista de menu
![image](https://user-images.githubusercontent.com/44541791/132971018-467ec25a-b0f7-40c4-b056-adc2db769834.png)
e
![image](https://user-images.githubusercontent.com/44541791/132971027-803ef74a-816f-4af6-a767-108d32a47c38.png)


Eu Tire, mas não funcionar, ele(a) sem respondeu!, talvez deixe o iris bot melhor!

**Comment by dodouuglas** [comment]
> > o butao n fucionou? manda o script para eu ver se consigo ajudar
> 
> Eu Tire, mas não funcionar, ele(a) sem respondeu!, talvez deixe o iris bot melhor!
> 
> outro grupos do bot! Olha, ele(a) funcionar tentar botão lista de menu
> ![image](https://user-images.githubusercontent.com/44541791/132971018-467ec25a-b0f7-40c4-b056-adc2db769834.png)
> e
> ![image](https://user-images.githubusercontent.com/44541791/132971027-803ef74a-816f-4af6-a767-108d32a47c38.png)

eu n entendi nd

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/132967170-b3db27bd-ade0-464e-9c57-2d524d5db08c.png)
> Adicionar do bot?
> 
> Console
> ![image](https://user-images.githubusercontent.com/44541791/132967165-fa412159-066c-486e-b0a1-ccdbea2137a6.png)
> 
> bot config:
> Resquito: acima 60+ membros
> Grupos Limite: 20
> 
> Atual Grupos
> 17/20
> 

Erro relacionado a wa-automate, tente atualizar.

**Comment by maradona4** [comment]
Oki
