### ISSUE TITLE
cmd Pugb

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#239]
como separar comandos ex: /pugb Rei | Mateus

![image](https://user-images.githubusercontent.com/44541791/132974081-223ed1ab-b71e-449d-bacb-f4174170ee9e.png)

code here: ${body.slice(6)}

outro comandos naruto, o meu funcionar mandar imagem naruto Nome "mateus"

**Comment by marru453** [comment]
con corchetes {}

**Comment by KillovSky** [comment]
> como separar comandos ex: /pugb Rei | Mateus
> 
> ![image](https://user-images.githubusercontent.com/44541791/132974081-223ed1ab-b71e-449d-bacb-f4174170ee9e.png)
> 
> code here: ${body.slice(6)}
> 
> outro comandos naruto, o meu funcionar mandar imagem naruto Nome "mateus"

`let value = arg.split('|')`

`text=${value[0]}`

`text2=${value[1]}`

Isso separa dois argumentos pelo `|`.

`/comando Texto 1 | Texto 2`

**Comment by maradona4** [comment]
![image](https://user-images.githubusercontent.com/44541791/133082735-0f7fecb4-a297-4c8e-b03e-b14cb05236d3.png)

Muito obrigado, agr deu funcionar
