### ISSUE TITLE
wpp fechando

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#240]
quando eu ligo o bot o wpp fica fechando

**Comment by KillovSky** [comment]
> quando eu ligo o bot o wpp fica fechando
> 

O do seu telefone? Você esta utilizando WhatsApp de terceiros? Se sim, use o WhatsApp normal, pois os de terceiros podem comprometer seriamente o funcionamento da Íris assim como podem ser um risco enorme a segurança.

**Comment by dodouuglas** [comment]
> > quando eu ligo o bot o wpp fica fechando
> 
> O do seu telefone? Você esta utilizando WhatsApp de terceiros? Se sim, use o WhatsApp normal, pois os de terceiros podem comprometer seriamente o funcionamento da Íris assim como podem ser um risco enorme a segurança, portanto, não é culpa da Íris.
> 
> Se for o navegador do computador, se certifique de limpar a Íris, apague a pasta logs e use ccleaner.
> 
> E na proxima issue, poste uma foto ou algo assim, insira muita informação sobre o erro, afinal, ninguem aqui tem uma dedução absurda pra ajudar sem ter ideia de qual o problema inicial que obteve certo?

estou usando o wpp normal duplicado

**Comment by KillovSky** [comment]
> > > quando eu ligo o bot o wpp fica fechando
> > 
> > O do seu telefone? Você esta utilizando WhatsApp de terceiros? Se sim, use o WhatsApp normal, pois os de terceiros podem comprometer seriamente o funcionamento da Íris assim como podem ser um risco enorme a segurança, portanto, não é culpa da Íris.
> > 
> > Se for o navegador do computador, se certifique de limpar a Íris, apague a pasta logs e use ccleaner.
> > 
> > E na proxima issue, poste uma foto ou algo assim, insira muita informação sobre o erro, afinal, ninguem aqui tem uma dedução absurda pra ajudar sem ter ideia de qual o problema inicial que obteve certo?
> 
> estou usando o wpp normal duplicado

Então mostre a sua tela do computador, como eu disse acima, preciso de detalhes para entender os erros.
