### ISSUE TITLE
butao dnv kkkkk

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#243]
eu quero fazer um script q use o | mas n to consegindo, no caso o meu iria ficar assim ``!butao id do grupo | mensagem`` ai ele manda um butao com a mensagem no grupo meu script ta assim 
```
case 'butao':
await kill.sendButtons(`${encodeURIComponent(body.split('|')[0])}`, `${encodeURIComponent(body.split('|')[1])}`, [{id: "0", "text": 'sim'}, {id: "1", "text": 'não'}], '')		
break
```

**Comment by KillovSky** [comment]
> eu quero fazer um script q use o | mas n to consegindo, no caso o meu iria ficar assim ``!butao id do grupo | mensagem`` ai ele manda um butao com a mensagem no grupo meu script ta assim 
> ```
> case 'butao':
> await kill.sendButtons(`${encodeURIComponent(body.split('|')[0])}`, `${encodeURIComponent(body.split('|')[1])}`, [{id: "0", "text": 'sim'}, {id: "1", "text": 'não'}], '')		
> break
> ```

Falta o `@g.us` no final ali de onde ficava o `from`, deveria ser `${body.split('|')[0]}@g.us` e o encodeUri não é util aqui, pode causar problemas eventualmente, por isso eu so uso em links.

**Comment by dodouuglas** [comment]
> > eu quero fazer um script q use o | mas n to consegindo, no caso o meu iria ficar assim `!butao id do grupo | mensagem` ai ele manda um butao com a mensagem no grupo meu script ta assim
> > ```
> > case 'butao':
> > await kill.sendButtons(`${encodeURIComponent(body.split('|')[0])}`, `${encodeURIComponent(body.split('|')[1])}`, [{id: "0", "text": 'sim'}, {id: "1", "text": 'não'}], '')		
> > break
> > ```
> 
> Falta o `@g.us` no final ali de onde ficava o `from`, deveria ser `${body.split('|')[0]}@g.us` e o encodeUri não é util aqui, pode causar problemas eventualmente, por isso eu so uso em links.

e eu coloco oq no lugar do encodeUri

**Comment by KillovSky** [comment]
> > > eu quero fazer um script q use o | mas n to consegindo, no caso o meu iria ficar assim `!butao id do grupo | mensagem` ai ele manda um butao com a mensagem no grupo meu script ta assim
> > > ```
> > > case 'butao':
> > > await kill.sendButtons(`${encodeURIComponent(body.split('|')[0])}`, `${encodeURIComponent(body.split('|')[1])}`, [{id: "0", "text": 'sim'}, {id: "1", "text": 'não'}], '')		
> > > break
> > > ```
> > 
> > Falta o `@g.us` no final ali de onde ficava o `from`, deveria ser `${body.split('|')[0]}@g.us` e o encodeUri não é util aqui, pode causar problemas eventualmente, por isso eu so uso em links.
> 
> e eu coloco oq no lugar do encodeUri

Ja esta na resposta que dei, **deveria ser...**

**Comment by KillovSky** [comment]
Ref: #257
