### ISSUE TITLE
bot responder tds as mensagens

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#244]
quero saber como q faz para o bot responder tds as mensagens que mande cm a api do "/iris" ai dps eu mudo para ativar e desativar sla

**Comment by KillovSky** [comment]
> quero saber como q faz para o bot responder tds as mensagens que mande cm a api do "/iris" ai dps eu mudo para ativar e desativar sla

Procure pelos comandos sem prefix na config.js, eles estão na parte de cima do código, insira isso abaixo deles.

```javascript
await kill.reply(from, chatBotR, id)
```

Tenha em mente que se houver flood ou muitas mensagens a bot pode ser banida e enviar **MUITAS MENSAGENS** assim floodando o grupo, por isso eu não fiz ela responder todas as mensagens.

Dica: Quando for pensar em criar um sistema, pense primeiro nas consequencias que virão dele, para então agir, senão o dano **pode ser grave**.

**Comment by dodouuglas** [comment]
> > quero saber como q faz para o bot responder tds as mensagens que mande cm a api do "/iris" ai dps eu mudo para ativar e desativar sla
> 
> Procure pelos comandos sem prefix na config.js, eles estão na parte de cima do código, insira isso abaixo deles.
> 
> ```js
> await kill.reply(from, chatBotR, id)
> ```
> 
> Tenha em mente que se houver flood ou muitas mensagens a bot pode ser banida e enviar **MUITAS MENSAGENS** assim floodando o grupo, por isso eu não fiz ela responder todas as mensagens.
> 
> Dica: Quando for pensar em criar um sistema, pense primeiro nas consequencias que virão dele, para então agir, senão o dano **pode ser grave**.

n conseguir fazer n e eu quero fazer cm a api "http://simsumi.herokuapp.com/api" eu vou colocar isso em alguns grupos so ai ou pago mas n sei se eu posso deixar pago. mas vai ficar so em alguns grupos mesmos ai essa parte eu consigo fazer

**Comment by dodouuglas** [comment]
conseguir fazer kkkk
