### ISSUE TITLE
Iris reiniciando, não chegar inicializa

### ISSUE THREAD

**Issue by DeyvissonSnuffs** [KillovSky/iris#247]
![Screenshot_2021-09-15-12-47-52-448_com teamviewer teamviewer market mobile](https://user-images.githubusercontent.com/85204721/133466276-028584db-4040-4b19-b173-a92a72cefd3d.jpg)

**Comment by EndervorHero** [comment]
Same here!
I think it is a wa-automate problem, try to update it or downgrade it to another version,  and looks if it works, if not, the only thing we can do is wait for an update

**Comment by KillovSky** [comment]
#245
