### ISSUE TITLE
Não consigo dar "npm start"

### ISSUE THREAD

**Issue by Wi-Fallen** [KillovSky/iris#248]
![IMG-20210915-WA0062](https://user-images.githubusercontent.com/90735036/133503647-4bf92b90-3637-4836-bbef-3282a8581645.jpeg)

**Comment by KillovSky** [comment]
Erro referente a uma porta, pode ser a do bomb, siga os procedimentos ds pagina inicial da Íris e diga se funcionar.
Procedimentos para referencia mais facil:

```
Desativar a auto-abertura de navegador do bomb

Para fazer com que o navegador pare de abrir toda vez que iniciar a Íris, abra a pasta node_modules e vá em bomber-api, abra o arquivo index.js e remova as linhas "open(`http://localhost:3000/`)" e "open(`http://localhost:${arguments.port}/`)", se você obteve problemas com a porta 3000, você pode editar a "app.listen(3000" para uma porta aleatória que não esteja em uso.
```

**Comment by KillovSky** [comment]
> ![IMG-20210915-WA0062](https://user-images.githubusercontent.com/90735036/133503647-4bf92b90-3637-4836-bbef-3282a8581645.jpeg)
> 

Erro referente a uma porta, pode ser a do bomb, siga os procedimentos ds pagina inicial da Íris e diga se funcionar.
Procedimentos para referencia mais facil:

----------

Desativar a auto-abertura de navegador do bomb

Para fazer com que o navegador pare de abrir toda vez que iniciar a Íris, abra a pasta node_modules e vá em bomber-api, abra o arquivo index.js e remova as linhas "open(`http://localhost:3000/`)" e "open(`http://localhost:${arguments.port}/`)", se você obteve problemas com a porta 3000, você pode editar a "app.listen(3000" para uma porta aleatória que não esteja em uso.
