### ISSUE TITLE
NOVO COMANDO PRA ENVIAR VIDEOS DO PC  ERROInvalidMediaFileType

### ISSUE THREAD

**Issue by DeyvissonSnuffs** [KillovSky/iris#249]
criei um comando pra poder enviar video de uma pasta do pc
assim o usuário pode usa comando ex ''/hentai"
e a íris enviar vídeos aleatório da pasta

ta funcionando apenas para imagens, quando ela pega o video pra enviar da esse erro

`						case 'hentai':
							if (isGroupMsg && !isNsfw) return await kill.reply(from, mess.gpadulto(), id)
							await kill.reply(from, mess.wait(), id)
							let arquivosHentai = await fs.readdir('./lib/media/hentai/') // depois se quiser mudar o path
							var numeroHentai = Math.floor(math.random()*arquivosHentai.length)
							if(numeroHentai==arquivosHentai.length){
								numeroHentai--;
							}//se mudar o path mude no sendFile tb
							await kill.sendFile(from, './lib/media/hentai/'+arquivosHentai[numeroHentai], 'hentai'+arquivosHentai[numeroHentai], '', id)
							break`

`[FALHA GERAL] Error: Evaluation failed: Error: InvalidMediaFileType
0|index  |     at Object.sendToChat (https://web.whatsapp.com/bootstrap_qr.6413cd4b0bfc5863366e.js:55:201826)
0|index  |     at __puppeteer_evaluation_script__:1:106169
0|index  |     at async Object.window.<computed>.<computed> [as sendImage] (__puppeteer_evaluation_script__:1:102881)
0|index  |     at ExecutionContext._evaluateInternal (C:\Users\dey_v\Kaotic\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
0|index  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
0|index  |     at async ExecutionContext.evaluate (C:\Users\dey_v\Kaotic\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)`

**Comment by KillovSky** [comment]
> criei um comando pra poder enviar video de uma pasta do pc
> assim o usuário pode usa comando ex ''/hentai"
> e a íris enviar vídeos aleatório da pasta
> 
> ta funcionando apenas para imagens, quando ela pega o video pra enviar da esse erro
> 
> `						case 'hentai':
> 							if (isGroupMsg && !isNsfw) return await kill.reply(from, mess.gpadulto(), id)
> 							await kill.reply(from, mess.wait(), id)
> 							let arquivosHentai = await fs.readdir('./lib/media/hentai/') // depois se quiser mudar o path
> 							var numeroHentai = Math.floor(math.random()*arquivosHentai.length)
> 							if(numeroHentai==arquivosHentai.length){
> 								numeroHentai--;
> 							}//se mudar o path mude no sendFile tb
> 							await kill.sendFile(from, './lib/media/hentai/'+arquivosHentai[numeroHentai], 'hentai'+arquivosHentai[numeroHentai], '', id)
> 							break`
> 
> `[FALHA GERAL] Error: Evaluation failed: Error: InvalidMediaFileType
> 0|index  |     at Object.sendToChat (https://web.whatsapp.com/bootstrap_qr.6413cd4b0bfc5863366e.js:55:201826)
> 0|index  |     at __puppeteer_evaluation_script__:1:106169
> 0|index  |     at async Object.window.<computed>.<computed> [as sendImage] (__puppeteer_evaluation_script__:1:102881)
> 0|index  |     at ExecutionContext._evaluateInternal (C:\Users\dey_v\Kaotic\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
> 0|index  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> 0|index  |     at async ExecutionContext.evaluate (C:\Users\dey_v\Kaotic\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)`

Falta definir `.mp4` após o `[numeroHentai]`, também tenha certeza de estar a usar o chrome atualizado.

**Comment by DeyvissonSnuffs** [comment]
`0|index  | [FALHA GERAL] FILE_NOT_FOUND: Cannot find file. Make sure the file reference is relative, a valid URL or a valid DataURL: ./lib/media/hentai/undefine
0|index  |     at Client.<anonymous> (C:\Users\dey_v\iris\node_modules\@open-wa\wa-automate\dist\api\Client.js:1293:27)
0|index  |     at Generator.next (<anonymous>)
0|index  |     at C:\Users\dey_v\iris\node_modules\@open-wa\wa-automate\dist\api\Client.js:27:71
0|index  |     at new Promise (<anonymous>)
0|index  |     at __awaiter (C:\Users\dey_v\iris\node_modules\@open-wa\wa-automate\dist\api\Client.js:23:12)
0|index  |     at Client.sendImage (C:\Users\dey_v\iris\node_modules\@open-wa\wa-automate\dist\api\Client.js:1281:16)
0|index  |     at Client.<anonymous> (C:\Users\dey_v\iris\node_modules\@open-wa\wa-automate\dist\api\Client.js:1388:25)
0|index  |     at Generator.next (<anonymous>)
0|index  |     at C:\Users\dey_v\iris\node_modules\@open-wa\wa-automate\dist\api\Client.js:27:71
0|index  |     at new Promise (<anonymous>)`

**Comment by DeyvissonSnuffs** [comment]
usando comando `\exec` no chat pra puxa o arquivo da o msm erro

**Comment by KillovSky** [comment]
> usando comando `\exec` no chat pra puxa o arquivo da o msm erro

Esse erro é diferente, ele diz que não achou o arquivo pois você programou uma variavel incorreta no nome.

**Comment by KillovSky** [comment]
Fui avisado pelo dono que isso foi fixado instalando o Google Chrome recente, fechando issue.
