### ISSUE TITLE
Não consigo inicializar 

### ISSUE THREAD

**Issue by gitrb12** [KillovSky/iris#250]
![image](https://user-images.githubusercontent.com/90810216/133534878-c19b181f-346f-4799-9018-9bcf21316c00.png)

Fica aparecendo este erro

**Comment by KillovSky** [comment]
> 
> ![image](https://user-images.githubusercontent.com/90810216/133534878-c19b181f-346f-4799-9018-9bcf21316c00.png)
> 
> 
> 
> Fica aparecendo este erro

Atualize a `wa-automate`, rode `npm update`.
O erro é referente a um lentidão na sua internet que fez o navegador esperar 30 segundos ou mais, mas não conseguir carregar o WhatsApp, mas também pode ser causado por módulos desatualizados, experimente também deixar o `headless` em `false` na `functions.js`
