### ISSUE TITLE
Erro na inicialização

### ISSUE THREAD

**Issue by KingBot422** [KillovSky/iris#251]
Ao dar o npm start aparece o seguinte erro... Já tentei apagar a iris.data para a criação de um novo QR code... Mas sem sucesso também. Gostaria de saber como posso resolver.
![20210916_081813.jpg](https://user-images.githubusercontent.com/88904502/133603086-0264ac9e-850b-4efb-85e8-0c532f06c975.jpg)

Edit: já apaguei a pasta node modules e instalei novamente... Mas ainda permanece com o mesmo erro. Também o npm update foi realizado.. mas permanece o erro

**Comment by wesley0209** [comment]
Le a #78 mano

**Comment by KingBot422** [comment]
> Le a #78 mano

Obrigado amigo, assim q testar irei sinalizar se deu certo, thanks
