### ISSUE TITLE
Enviar as primeiras mensagens do PV dos usuários ao PV dono [Pedido]

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#254]
tem como identificar se e a primeira mensagem da pessoa tipo assim q a pessoa falar algo na 1 vez no pv do bot ele manda o menu

**Comment by KillovSky** [comment]
> tem como identificar se e a primeira mensagem da pessoa tipo assim q a pessoa falar algo na 1 vez no pv do bot ele manda o menu 

Sobre a primeira mensagem, você precisa fazer um JSON - voce - ou criar uma var com object.

```javascript
var isMsg = {}
// Insira a var acima da module exports

// Depois crie um um if no local do anti-porn e anti-travas

if (!isGroupMsg && !isMedia) {
     isMsg[user] == null ? isMsg[user] = 1 : isMsg[user] += 1
     if (isMsg[user] < 2) {
         await kill.sendText('seuNumero@c.us', user + '\n\n' + message.body)
     }
}
```

Creio eu que funcionará, vai mandar o número junto a mensagem, ignorando imagens, mas se mandarem travas você se dará bem feio, enfim, evite violar a privacidade dos seus usuarios.

**Comment by dodouuglas** [comment]
isso ai ele manda a mensagem da pessoa para o meu pv eu quero q ele mande o menu mas eu sei fazer isso e so colocar as consts from ali no começo...
