### ISSUE TITLE
Comandos sem prefix, esse responde se marcar a BOT

### ISSUE THREAD

**Issue by DeyvissonSnuffs** [KillovSky/iris#255]
na linha 327 da confi.js
`		if (!isFiltered(from) && !isCmd) { try { if (chats.toLowerCase() == 'oi') await kill.reply(from, 'oi2', id) } catch (error) { return } }
`

o comando nao quer executar sem o prefix

**Comment by KillovSky** [comment]
> na linha 327 da confi.js
> `		if (!isFiltered(from) && !isCmd) { try { if (chats.toLowerCase() == 'oi') await kill.reply(from, 'oi2', id) } catch (error) { return } }
> `
> 
> o comando nao quer executar sem o prefix

Experimente `body.message.toLowerCase()` em vez de `chats...`.

**Comment by DeyvissonSnuffs** [comment]
`		if (!isFiltered(from) && !isCmd) { try { if (body.toLowerCase() == 'teste') await kill.reply(from, 'MSG ENVIADA', id) } catch (error) { return } }
`

tmb nao foi

**Comment by KillovSky** [comment]
> `		if (!isFiltered(from) && !isCmd) { try { if (body.toLowerCase() == 'teste') await kill.reply(from, 'MSG ENVIADA', id) } catch (error) { return } }
> `
> ou
> 
> ``		if (!isFiltered(from) && !isCmd) { try { if (body.message.toLowerCase() == 'teste') await kill.reply(from, 'MSG ENVIADA', id) } catch (error) { return } }
> ``
> 
> 
> tmb nao foi

Alguma coisa se você utilizar `includes`?

```javascript
try {
     if (chats.toLowerCase().includes('oi')) {
         await kill.reply(from, 'oi', id)
     } else {
         console.log('A mensagem é: ' + chats)
     }
} catch (error) {
     console.log(error)
}
```

Teste e poste os resultados da tela do terminal.

**Comment by DeyvissonSnuffs** [comment]
> > `		if (!isFiltered(from) && !isCmd) { try { if (body.toLowerCase() == 'teste') await kill.reply(from, 'MSG ENVIADA', id) } catch (error) { return } } `
> > ou
> > `		if (!isFiltered(from) && !isCmd) { try { if (body.message.toLowerCase() == 'teste') await kill.reply(from, 'MSG ENVIADA', id) } catch (error) { return } } `
> > tmb nao foi
> 
> Alguma coisa se você utilizar `includes`?
> 
> ```js
> try {
>      if (chats.toLowerCase().includes('oi')) {
>          await kill.reply(from, 'oi', id)
>      } else {
>          console.log('A mensagem é: ' + chats)
>      }
> } catch (error) {
>      console.log(error)
> }
> ```
> 
> Teste e poste os resultados da tela do terminal.

Deu certo, obrigado

**Comment by DeyvissonSnuffs** [comment]
com esse comando agora posso criar um sistema que filtra racismos pra poder bannir pessoas de grupo
