### ISSUE TITLE
antilink

### ISSUE THREAD

**Issue by MatheusOFC** [KillovSky/iris#256]
Preciso deixar o antilink mais "eficiente " retirei tudo o que podia mensagem no console , os mess, etc...
Mas mesmo assim continua lento, sei que existem vários problemas que possam interferir como a Ram, processador ou internet.
Mas não acredito q sejam esses problemas e sim o Flood fiz vários teste e quando ocorre o flood sendo só msm de mensagem sem comsndos, o Bot da uma "travada"
O problema que quando vão jogar os links 99℅ das vezes esses c@petas floodam oq faz o Bot não ter a eficácia que poderia ter..
Da uma força ai luskinha nunca te pedi nada..

**Comment by KillovSky** [comment]
> Preciso deixar o antilink mais "eficiente " retirei tudo o que podia mensagem no console , os mess, etc...
> Mas mesmo assim continua lento, sei que existem vários problemas que possam interferir como a Ram, processador ou internet.
> Mas não acredito q sejam esses problemas e sim o Flood fiz vários teste e quando ocorre o flood sendo só msm de mensagem sem comsndos, o Bot da uma "travada"
> O problema que quando vão jogar os links 99℅ das vezes esses c@petas floodam oq faz o Bot não ter a eficácia que poderia ter..
> Da uma força ai luskinha nunca te pedi nada..

Tente inserir na `index.js`.

```javascript
// Esse você edita lá em cima
const { color, sleep, options, isUrl } = require('./lib/functions')

// Esse você insere acima da "await kconfig(kill, message)"
if (message.isGroupMsg && isUrl(message.body)) return await kill.removeParticipant(message.from, message.sender.id)
```
