### ISSUE TITLE
Como utilizar os botões

### ISSUE THREAD

**Issue by KillovSky** [KillovSky/iris#257]
```javascript
	
	// Config.js, substitua a linha abaixo
	const { type, id, from, t, sender, author, isGroupMsg, chat, chatId, caption, isMedia, mimetype, quotedMsg, quotedMsgObj, mentionedJidList } = message
	
	// Por essa, ou seja, apague o "id" dela
	const { type, from, t, sender, author, isGroupMsg, chat, chatId, caption, isMedia, mimetype, quotedMsg, quotedMsgObj, mentionedJidList } = message
	
	// Abaixo dela insira isso
	id = message.type == "buttons_response" ? message.quotedMsgObj.id : message.id
	
	// Modo de uso
	await kill.sendButtons(from, 'Mensagem de baixo', [
		{
		    "id": "1",
			"text": "Comando aqui"
		}
	], 'Mensagem de cima')
```

Isso permite que seja utilizado os botões na Íris sem maiores edições e criação de outras exports.

Teste:
![896312fa-2388-45d9-b4b6-eacf85dc11ad](https://user-images.githubusercontent.com/55511420/133787035-9120cbc3-446e-469a-a855-240a37a9457e.jpg)

**Comment by markoswythor** [comment]
> ```js
> 	
> 	// Config.js, substitua a linha abaixo
> 	const { type, id, from, t, sender, author, isGroupMsg, chat, chatId, caption, isMedia, mimetype, quotedMsg, quotedMsgObj, mentionedJidList } = message
> 	
> 	// Por essa, ou seja, apague o "id" dela
> 	const { type, from, t, sender, author, isGroupMsg, chat, chatId, caption, isMedia, mimetype, quotedMsg, quotedMsgObj, mentionedJidList } = message
> 	
> 	// Abaixo dela insira isso
> 	id = message.type == "buttons_response" ? message.quotedMsgObj.id : message.id
> 	
> 	// Modo de uso
> 	await kill.sendButtons(from, 'Mensagem de baixo', [
> 		{
> 		    "id": "1",
> 			"text": "Comando aqui"
> 		}
> 	], 'Mensagem de cima')
> ```
> 
> Isso permite que seja utilizado os botões na Íris sem maiores edições e criação de outras exports.
> 
> Teste:
> ![896312fa-2388-45d9-b4b6-eacf85dc11ad](https://user-images.githubusercontent.com/55511420/133787035-9120cbc3-446e-469a-a855-240a37a9457e.jpg)

Obrigado amigo <3

**Comment by maradona4** [comment]
![image](https://user-images.githubusercontent.com/44541791/133861692-a9cffac9-dfcd-4ad5-9318-ee07c3f0f71f.png)

![image](https://user-images.githubusercontent.com/44541791/133861702-c2cbd9c0-0cab-4263-8e3f-cfc1a2786e5e.png)
"sendText" ? tao diferente

**Comment by patulinomods** [comment]
Lucas, me tira uma duvida, estou tentando criar os botoes de boa, ate ai tudo bem, mas como eu faço para reconhecer quando a pessoa preciona o botao?

**Comment by KillovSky** [comment]
> Lucas, me tira uma duvida, estou tentando criar os botoes de boa, ate ai tudo bem, mas como eu faço para reconhecer quando a pessoa preciona o botao?

Isso já esta acima.

Mas tem duas formas.

Uma é o `kill.onButton(...)` descrito [aqui](https://docs.openwa.dev/classes/api_Client.Client.html#onButton), deve ser usado na `index.js` onde fica o `kill.onMessage(...)`, portanto, usar o `kill.onButton(...)` é o mesmo que editar a base de funções da Íris, indo no mesmo caminho de criar uma `config.js`.

A outra é simples e facil, basta usar isto, `message.type == "buttons_response"`.

**Comment by markoswythor** [comment]
> ```js
> 	
> 	// Config.js, substitua a linha abaixo
> 	const { type, id, from, t, sender, author, isGroupMsg, chat, chatId, caption, isMedia, mimetype, quotedMsg, quotedMsgObj, mentionedJidList } = message
> 	
> 	// Por essa, ou seja, apague o "id" dela
> 	const { type, from, t, sender, author, isGroupMsg, chat, chatId, caption, isMedia, mimetype, quotedMsg, quotedMsgObj, mentionedJidList } = message
> 	
> 	// Abaixo dela insira isso
> 	id = message.type == "buttons_response" ? message.quotedMsgObj.id : message.id
> 	
> 	// Mude então as linhas abaixo:
> 	const chats = (type === 'chat') ? body : ((type === 'image' || type === 'video')) ? caption : ''
> 
> 	body = (type === 'chat' && body.startsWith(prefix)) ? body : (((type === 'image' || type === 'video') && caption) && caption.startsWith(prefix)) ? caption : ''
> 
>         // Para essas:
> 	const chats = (type === 'chat' || type == "buttons_response") ? body : ((type === 'image' || type === 'video')) ? caption : ''
> 
> 	body = (type == 'chat' && body.startsWith(prefix) || type == "buttons_response") ? body : (((type === 'image' || type === 'video') && caption) && caption.startsWith(prefix)) ? caption : ''
> 	
> 	// Feito isso basta construir os comandos com botões
> 	// Modo de uso
> 	await kill.sendButtons(from, 'Mensagem de baixo', [
> 		{
> 		    "id": "1",
> 		    "text": "Comando aqui"
> 		}
> 	], 'Mensagem de cima')
> ```
> 
> Isso permite que seja utilizado os botões na Íris sem maiores edições e criação de outras exports.
> 
> Teste:
> ![896312fa-2388-45d9-b4b6-eacf85dc11ad](https://user-images.githubusercontent.com/55511420/133787035-9120cbc3-446e-469a-a855-240a37a9457e.jpg)
> 
> > Se eu achar algumas falhas ou puder melhorar o código acima, irei ir editando e postando nesta issue.

depois de eu ter feito todos os processos, a iris começou a responder marcando outras mensagens e caso alguém dê o comando ao msm tempo ela bagunça as mensagens e responde pessoas aleatórias 

![image](https://user-images.githubusercontent.com/76796419/134083133-efa4af87-a851-4d01-89a1-81e5ddc54ab0.png)

**Comment by KillovSky** [comment]
> > ```js
> > 	
> > 	// Config.js, substitua a linha abaixo
> > 	const { type, id, from, t, sender, author, isGroupMsg, chat, chatId, caption, isMedia, mimetype, quotedMsg, quotedMsgObj, mentionedJidList } = message
> > 	
> > 	// Por essa, ou seja, apague o "id" dela
> > 	const { type, from, t, sender, author, isGroupMsg, chat, chatId, caption, isMedia, mimetype, quotedMsg, quotedMsgObj, mentionedJidList } = message
> > 	
> > 	// Abaixo dela insira isso
> > 	id = message.type == "buttons_response" ? message.quotedMsgObj.id : message.id
> > 	
> > 	// Mude então as linhas abaixo:
> > 	const chats = (type === 'chat') ? body : ((type === 'image' || type === 'video')) ? caption : ''
> > 
> > 	body = (type === 'chat' && body.startsWith(prefix)) ? body : (((type === 'image' || type === 'video') && caption) && caption.startsWith(prefix)) ? caption : ''
> > 
> >         // Para essas:
> > 	const chats = (type === 'chat' || type == "buttons_response") ? body : ((type === 'image' || type === 'video')) ? caption : ''
> > 
> > 	body = (type == 'chat' && body.startsWith(prefix) || type == "buttons_response") ? body : (((type === 'image' || type === 'video') && caption) && caption.startsWith(prefix)) ? caption : ''
> > 	
> > 	// Feito isso basta construir os comandos com botões
> > 	// Modo de uso
> > 	await kill.sendButtons(from, 'Mensagem de baixo', [
> > 		{
> > 		    "id": "1",
> > 		    "text": "Comando aqui"
> > 		}
> > 	], 'Mensagem de cima')
> > ```
> > 
> > Isso permite que seja utilizado os botões na Íris sem maiores edições e criação de outras exports.
> > 
> > Teste:
> > ![896312fa-2388-45d9-b4b6-eacf85dc11ad](https://user-images.githubusercontent.com/55511420/133787035-9120cbc3-446e-469a-a855-240a37a9457e.jpg)
> > 
> > > Se eu achar algumas falhas ou puder melhorar o código acima, irei ir editando e postando nesta issue.
> 
> depois de eu ter feito todos os processos, a iris começou a responder marcando outras mensagens e caso alguém dê o comando ao msm tempo ela bagunça as mensagens e responde pessoas aleatórias 
> 
> ![image](https://user-images.githubusercontent.com/76796419/134083133-efa4af87-a851-4d01-89a1-81e5ddc54ab0.png)
> 

Acontece com mensagens muito rapidas, basta inserir `const` antes do `id`.
Código corrigido.

**Comment by MatheusOFC** [comment]
meuu deus n entendi nada, cade a primeira issue sobre o assunto kskss

**Comment by MatheusOFC** [comment]
Man coloquei os botão, porém deu ban no meu número assim que a ultilizo skskksskks

**Comment by dodouuglas** [comment]
> 

n tem que usar evento pra ele responder quando clica no botao

**Comment by KillovSky** [comment]
> > 
> 
> n tem que usar evento pra ele responder quando clica no botao

Ja estou fazendo isso de forma diferente, mas não, não é necessario um evento para que ele seja lido.

**Comment by dodouuglas** [comment]
> > > 
> > 
> > 
> > n tem que usar evento pra ele responder quando clica no botao
> 
> Ja estou fazendo isso de forma diferente, mas não, não é necessario um evento para que ele seja lido.

como?

**Comment by KillovSky** [comment]
Este tutorial que enviei nesta página já o faz pois independente de ser um botão, ele não deixa de ser uma mensagem que a Íris lê.
Use a versão DEV, ela já possui isso implementado -> [ÍRIS DEV](https://github.com/KillovSky/iris/tree/dev)
