### ISSUE TITLE
cmd

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#258]
as vezes da no console opering etc tipo q foi desconectado ou da timeout ou n da nd so para do nada.
resumindo ele as vezes para de responder do nada e ta tudo de boa

**Comment by KillovSky** [comment]
> as vezes da no console opering etc tipo q foi desconectado ou da timeout ou n da nd so para do nada.
> resumindo ele as vezes para de responder do nada e ta tudo de boa

Pode ser algum problema de congelamento no telefone, se certifique de desativar a melhoria de bateria do WhatsApp no seu telefone indo nas configurações/bateria.
Também ative a limpeza de cache na `index.js` e instale um optimizador, recomendo para a RAM o `Reduce Memory`.
