### ISSUE TITLE
Media Missing?

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#259]
![image](https://user-images.githubusercontent.com/44541791/133858851-6da14664-b2be-4c6d-b8f6-a99c3302c7b6.png)

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/133858851-6da14664-b2be-4c6d-b8f6-a99c3302c7b6.png)
> 

Qual o comando e forma de uso utilizada?

**Comment by maradona4** [comment]
Vish, não lembro, eu tava fechar console propt comandos, dps eu avisou

**Comment by KillovSky** [comment]
> Vish, não lembro, eu tava fechar console propt comandos, dps eu avisou

Fechando por estar 3 dias sem uma resposta, caso o erro persista **reabra esta issue**.
