### ISSUE TITLE
Problema ao inicializar

### ISSUE THREAD

**Issue by akami-is-back** [KillovSky/iris#260]
![16319201678868648648601973270885](https://user-images.githubusercontent.com/87986512/133862528-ded3e0aa-ebb4-4325-bf2f-4aef2e8e1564.jpg)

Ela está com um certo probleminha quando dou NPM START eu já tentei outros comandos como NPM UPDATE ou remover a abertura do bomber-api 

Mais ainda persiste este problema bah

**Comment by DeyvissonSnuffs** [comment]
tenta apaga a pasta ( node_modules )

dps da

npm clear cache
npm i --force

**Comment by akami-is-back** [comment]
mesma coisa ainda :/

**Comment by KillovSky** [comment]
> mesma coisa ainda :/

Notei que está na pasta do One Drive, tente na area de trabalho e tenha certeza de ter um node lts atualizado e testar como administrador.

**Comment by akami-is-back** [comment]
ok

**Comment by akami-is-back** [comment]
Mesma coisa ainda ;-;

**Comment by KillovSky** [comment]
> Ainda n resolveu ;-; , aparece a mesma coisa

Você está usando a versão LTS do NodeJS? **É IMPORTANTE** usar a 14, se sim ou se não, tente reinstalar seu NodeJS.

Apague a pasta `node_modules` e instale do zero pela **area de trabalho** após reinstalar o NodeJS e obviamente, ative a opção para instalar os extras dele nas etapas de instalação do NodeJS, senão ocorre graves erros depois.

**Comment by KillovSky** [comment]
> Ainda n resolveu ;-; , aparece a mesma coisa

Você está usando a versão LTS do NodeJS?
**É IMPORTANTE** usar a 14, se sim ou se não, tente reinstalar seu NodeJS, lembrando, **É OBRIGATORIO** ativar a opção abaixo.

Após a reinstalação, delete a pasta `node_modules` e instale do zero pela **AREA DE TRABALHO**.
![images_2.png](https://user-images.githubusercontent.com/55511420/133933149-00529149-2dd4-40ec-885c-ae7578e95f78.png)
*

**Comment by akami-is-back** [comment]
Agora sim resolvido, obrigadu
