### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#261]
quando essa pessoa tenta usar o bot da esse error e eu nao sei oq e
![image](https://user-images.githubusercontent.com/79427063/133869701-8e92e0da-ec7a-4fc4-9f64-189846872e8e.png)

**Comment by maradona4** [comment]
mesmo kkk

**Comment by KillovSky** [comment]
> quando essa pessoa tenta usar o bot da esse error e eu nao sei oq e
> ![image](https://user-images.githubusercontent.com/79427063/133869701-8e92e0da-ec7a-4fc4-9f64-189846872e8e.png)
> 

É um erro de escrita no programa, da qual undefined está escrito errado, como eu não cometi esse erro com absoluta certeza, deve haver algo em uma atualização da wa-automate que a fez criar esse erro, de toda forma, espere uma atualização deles e rode o `npm update` quando ocorrer.
