### ISSUE TITLE
XP

### ISSUE THREAD

**Issue by anonimo850** [KillovSky/iris#262]
Sistema de xp so ta funcionando comigo, com outros membros n Funfa, tipo o cassino etc Ajuda ae amigo :)

**Comment by KillovSky** [comment]
> Sistema de xp so ta funcionando comigo, com outros membros n Funfa, tipo o cassino etc Ajuda ae amigo :)

Muito estranho, tu ativou o `/Rank on`?
Me exiba sua tela do terminal e também o código se você fez edições e claro, tenha absoluta de que eles estão usando corretamente, de que você não usou o give incorretamente neles e por fim, que o arquivo está seguro e sem corrupção, de qualquer forma.

XP's negativos não podem usar jogos.

Não é possivel apostar menos que 250xp por segurança.

Não é possivel usar numeros não inteiros, por exemplo, `544.99`.

Não pode apostar um valor maior que a metade do seu XP (ajudar a evitar um burnall do XP).

Meu XP = 2000

Exemplos de apostas com sucesso e sem sucesso:

-10XP = Não aposta

500.5 XP = Não aposta

144XP = Não aposta

1200XP = Não aposta

1000 XP = Aposta

500XP = Aposta

251 XP = Aposta

**Comment by anonimo850** [comment]
![Capturar](https://user-images.githubusercontent.com/80079258/133892017-fd70f586-c7b7-4982-9d68-cbc691dc1c19.PNG)
Comigo n acontece esse problema so com os outros, os membros tbm n sobe de level mandando msg

**Comment by KillovSky** [comment]
> ![Capturar](https://user-images.githubusercontent.com/80079258/133892017-fd70f586-c7b7-4982-9d68-cbc691dc1c19.PNG)
> Comigo n acontece esse problema so com os outros, os membros tbm n sobe de level mandando msg

Como dito ali, ele não tem XP pra apostar, especifiquei os limites acima e está na mensagem "minimo de 250xp de aposta", logo 5XP não é apostavel.
Verifique sua `config.json`, la tem os parametros de XP, a XP_Difficulty se colocada muito alto faz com que seja muito dificil subir de nivel.
Também tem os outros parametros de XP, você pode ver o que todos significam e onde acha-los clicando [aqui](https://github.com/KillovSky/iris/blob/main/.readme/pt/config.md), caso você tenha definido algum valor dos de XP como zero ou um número muito baixo, faria sentido que eles não ganhassem XP, mas como ele tem 144 ali, pode ser que você tenha definido um valor gigante para o tempo de ganho a cada mensagem, de qualquer forma, tente fazer a configuração usando o tutorial do link ali.

**Comment by anonimo850** [comment]
> > ![Capturar](https://user-images.githubusercontent.com/80079258/133892017-fd70f586-c7b7-4982-9d68-cbc691dc1c19.PNG)
> > Comigo n acontece esse problema so com os outros, os membros tbm n sobe de level mandando msg
> 
> Como dito ali, ele não tem XP pra apostar, especifiquei os limites acima e está na mensagem "minimo de 250xp de aposta", logo 5XP não é apostavel.
> Verifique sua `config.json`, la tem os parametros de XP, a XP_Difficulty se colocada muito alto faz com que seja muito dificil subir de nivel.
> Também tem os outros parametros de XP, você pode ver o que todos significam e onde acha-los clicando [aqui](https://github.com/KillovSky/iris/blob/main/.readme/pt/config.md), caso você tenha definido algum valor dos de XP como zero ou um número muito baixo, faria sentido que eles não ganhassem XP, mas como ele tem 144 ali, pode ser que você tenha definido um valor gigante para o tempo de ganho a cada mensagem, de qualquer forma, tente fazer a configuração usando o tutorial do link ali.

Aqui ta 5 o XP  difficulty, (Max XP 50) (Min XP 15) qual seria o ideal pros outros membros ganhar XP?

**Comment by KillovSky** [comment]
> > > ![Capturar](https://user-images.githubusercontent.com/80079258/133892017-fd70f586-c7b7-4982-9d68-cbc691dc1c19.PNG)
> > > Comigo n acontece esse problema so com os outros, os membros tbm n sobe de level mandando msg
> > 
> > 
> > Como dito ali, ele não tem XP pra apostar, especifiquei os limites acima e está na mensagem "minimo de 250xp de aposta", logo 5XP não é apostavel.
> > Verifique sua `config.json`, la tem os parametros de XP, a XP_Difficulty se colocada muito alto faz com que seja muito dificil subir de nivel.
> > Também tem os outros parametros de XP, você pode ver o que todos significam e onde acha-los clicando [aqui](https://github.com/KillovSky/iris/blob/main/.readme/pt/config.md), caso você tenha definido algum valor dos de XP como zero ou um número muito baixo, faria sentido que eles não ganhassem XP, mas como ele tem 144 ali, pode ser que você tenha definido um valor gigante para o tempo de ganho a cada mensagem, de qualquer forma, tente fazer a configuração usando o tutorial do link ali.
> 
> Aqui ta 5 o XP difficulty, (Max XP 50) (Min XP 15) qual seria o ideal pros outros membros ganhar XP?

Estranho, isso já esta no valor padrão, tente reinstalar o arquivo `functions.json` e `level.json`, também pode ser o caso dos seus membros estarem floodando ou seja, enviando muitos comandos sem esperar, a cada flood eles perdem 100 XP.
