### ISSUE TITLE
loop infinito na inicialização

### ISSUE THREAD

**Issue by SrWalker7** [KillovSky/iris#263]
Quando inicializo o bot aparece isso.

https://user-images.githubusercontent.com/90977277/133894814-ab0aa9ce-f2ef-4cae-8347-ea94f1d0cd45.mp4

![WhatsApp Image 2021-09-18 at 12 53 56](https://user-images.githubusercontent.com/90977277/133894817-6d4ce1fc-a56e-4295-bd99-720b335fc310.jpeg)

**Comment by EndervorHero** [comment]
você tem que atualizar wa-automatizar com npm i --save @open-wa/wa-automate@latest

**Comment by KillovSky** [comment]
Atualizar a `Wa-Automate`  corrigirá pois você está com uma versão antiga, mas se usar o termo `--save`, ela será instalada no sistema, recomendo apenas rodar um `npm update`, assim todos os módulos são atualizados na pasta da iris, sem instalações no sistema, o `npm update`  é para casos de mais algum módulo não estar nas versões mais recentes.
