### ISSUE TITLE
[Banner logo] Status "patente"

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#264]
Como, Um banner abaixo da mensagem ou emcima junto com o texto /clashtatus

![image](https://user-images.githubusercontent.com/44541791/133910675-5594b572-1097-4d50-89d7-9aba56b0170d.png)

![image](https://user-images.githubusercontent.com/44541791/133910685-012fdd8a-088a-4235-a75c-ead3280feacb.png)

Function
![image](https://user-images.githubusercontent.com/44541791/133910693-a01572e9-c6ba-4ea0-9f22-a8d8160b00aa.png)

Config js
![image](https://user-images.githubusercontent.com/44541791/133910699-5e5fe023-e14c-440f-b64e-50ba4fc308c0.png)

codigo: kill.sendFileFromUrl
🤔

**Comment by KillovSky** [comment]
> Como, Um banner abaixo da mensagem ou emcima junto com o texto /clashtatus
> 
> ![image](https://user-images.githubusercontent.com/44541791/133910675-5594b572-1097-4d50-89d7-9aba56b0170d.png)
> 
> ![image](https://user-images.githubusercontent.com/44541791/133910685-012fdd8a-088a-4235-a75c-ead3280feacb.png)
> 
> Function
> ![image](https://user-images.githubusercontent.com/44541791/133910693-a01572e9-c6ba-4ea0-9f22-a8d8160b00aa.png)
> 
> Config js
> ![image](https://user-images.githubusercontent.com/44541791/133910699-5e5fe023-e14c-440f-b64e-50ba4fc308c0.png)
> 
> codigo: kill.sendFileFromUrl
> 🤔

`await kill.sendFileFromUrl(from, 'link da imagem', 'nome.formato da imagem (ex: foto.jpg)', 'Sua mensagem', id)`

**Comment by maradona4** [comment]
Ok thank
