### ISSUE TITLE
Planos para a "I-Coin"

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#265]
quero saber para q server o í-coin

**Comment by markoswythor** [comment]
> quero saber para q server o í-coin

comentando só pra ver a resposta dele tbm kkkk mas creio eu q ele estava com um projeto de criar uma lojinha na iris com as í-coins tipo 

700 í-coins = 20% de acertos no cassino

**Comment by KillovSky** [comment]
> > quero saber para q server o í-coin
> 
> comentando só pra ver a resposta dele tbm kkkk mas creio eu q ele estava com um projeto de criar uma lojinha na iris com as í-coins tipo 
> 
> 700 í-coins = 20% de acertos no cassino 

Até o momento eu mantinha segredo, mas em vista de estar super atrasado o update por eu ter parado muito tempo, irei revelar os planos mais considerados por mim para as `icoins`.

São um "projeto" com base nisso dito acima, mass, também planejo futuramente trazer jogos via texto, mas como seriam?

Conhecem a `AI-Dugeon`?
Neste estilo de RPG - porém muito mais simples, quem me derá ter um nivel tão alto a ponto de fazer um "AI-Dugeon" -, da qual as `icoins` podem comprar poções, equipamentos e outros, além de poder ser usada pra batalhas entre grupos.

**∆ - P'S: Isso não é uma promessa de futuro jogo incrivel, se eu por acaso não conseguir aprender a fazer o RPG, irei partir para outras ideias mais simples até aprender ou desistir do RPG.**

Mas como eu ainda não tenho um nivel tão grande em programação, apenas criei as `icoins` para **futuramente**, quando eu possuir o conhecimento, conseguir utiliza-las.

Por hora, vou aplicar em ideias mais basicas, e claro, aqueles que já tem um conhecimento excelente em programação, estão a utilizar elas para criar jogos e sistemas otimos, se você possui o conhecimento, o uso dela é feito do mesmo jeito que se usa para adquirir o XP e Nivel.

```javascript
const nome = await gaming.getValue(user, nivel, 'coin')
```

Espero que tenha conseguido entender, resumidamente, planejo fazer jogos melhores com a `Icoin`, quando eu tiver o conhecimento para isso, claro.

**Comment by dodouuglas** [comment]
ja que não tem fucionanidade no momento eu queria fazer um sistema de comandos limitados tipo se a pessoa der o comando ... ele tira 1 coin ai se a pessoa n tiver ele n executa o comando

**Comment by KillovSky** [comment]
> ja que não tem fucionanidade no momento eu queria fazer um sistema de comandos limitados tipo se a pessoa der o comando ... ele tira 1 coin ai se a pessoa n tiver ele n executa o comando

```javascript
// Pega total de icoin
const nome = await gaming.getValue(user, nivel, 'coin')

// Adiciona icoin
await gaming.addValue(user, valor, nivel, 'coin')

// Remove icoin
await gaming.addValue(user, -valor, nivel, 'coin')

// Note que a diferença entre adicionar e remover é simplesmente inserir um -.

// Agora vamos a um código de base

// Junto aos ifs na parte superior do código insira:

if (isCmd) {
    [Insira o código para checar a quantidade de icoin do usuario aqui]
    [Insira o código de remoção da icon aqui]
}

// Deixo a construção você (não que eu esteja ocupado demais pra montar haha), quanto maior a quantidade de erros, maior será seu aprendizado em construi-los, mas, não será apenas inserir os "await gaming", esse é o desafio, a construção do resto
```

Creio que dê para se ter uma ideia de montagem.
