### ISSUE TITLE
Patente Pontos

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#268]
![image](https://user-images.githubusercontent.com/44541791/133945362-d4386f4a-7a09-4405-a951-6579c9648458.png)

pq 3000+ e 3001+ duas?

"a9": "Motanha do Porco", troféu atual: 3000
"a10": "Arena Eletrovale", Troféu atual: 3400

Patente
![image](https://user-images.githubusercontent.com/44541791/133945431-a841afea-cce0-4f39-9d9d-79e3cee1099c.png)

Function
![image](https://user-images.githubusercontent.com/44541791/133945427-e03e101f-fd05-4e4e-a479-ccecb78eb583.png)

**Comment by dodouuglas** [comment]
como assim?

**Comment by maradona4** [comment]
Outro grupos contato: Wdrian
Era troféu: 3000

Patente: Motanha do porco
pq assim subiu troféu: 3001? paente: Arena eletrovale? mas estranho,

Arena eletrovale so isso acima troféu: 3400+
mas bugou 3001?

**Comment by KillovSky** [comment]
> Outro grupos contato: Wdrian
> Era troféu: 3000
> 
> Patente: Motanha do porco
> pq assim subiu troféu: 3001? paente: Arena eletrovale? mas estranho,
> 
> Arena eletrovale so isso acima troféu: 3400+
> mas bugou 3001?

`<` é um simbolo que faz referencia a um valor **menor que**, mesclando ele com `=`, temos um sistema que verifica se o valor é **menor ou igual que x**, 

`<` = `Menor que`
`=` = `O mesmo que`
`>` = `Maior que`
`!=` = `Diferente de`

Basicamente, isso é pura `equação`, se deseja que caia ainda no mesmo valor quando subir `1 XP` a mais apenas, insira outro verificador.

```javascript
// Maior que 3000 mas menor que 4000, exemplo
else if (point > 3000 && point < 4000) {
     [...]
}
```

Bom, basta testar para tentar localizar os valores e sinais que servem a ti.

**Comment by maradona4** [comment]
Obg, deu funcionar
