### ISSUE TITLE
comando de kick

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#269]
queria saber se tem como colocar eventos no config.js pq eu tava querendo fazer uma confirmação para o comando de kick tipo quando vc der o comando o bot vai mandar um butao de sim e nao ai quando vc clicar em sim ele vai mandar a mensagem de ban e vai tirar e se clicar em nao ele vai mandar "açao cancelada com sucesso"

**Comment by KillovSky** [comment]
> queria saber se tem como colocar eventos no config.js pq eu tava querendo fazer uma confirmação para o comando de kick tipo quando vc der o comando o bot vai mandar um butao de sim e nao ai quando vc clicar em sim ele vai mandar a mensagem de ban e vai tirar e se clicar em nao ele vai mandar "açao cancelada com sucesso"

Xi, pedido complicadinho, precisa definir os adms em uma variável, o usuário que levará ban em outra, definir múltiplos grupos pra que não seja banido ou afete de outros locais e impedir que usuários normais tentem usar o sim, tem que refazer o comando de kick para suportar isso e outros detalhes difíceis, portanto, irei considerar isso um pedido e entregar, se construído com sucesso, na próxima atualização.
