### ISSUE TITLE
N sei qual error

### ISSUE THREAD

**Issue by patulinomods** [KillovSky/iris#271]
**Ola pessoa que criou a melhor  bot do zapzap**

e o seguinte , estou tentando hospedar a iris em um servidor vps, mas de vez em quando a esse erro aki : 

![image](https://user-images.githubusercontent.com/73912095/134045116-7fa73303-d3af-40aa-9fe9-7a15d9928d62.png)
 
e esse erro infelismente  faz a iris audo desligar, nao sei oque causa isso , pis as vezes ninguem mandou comando ela simplemente acontece isso

**Comment by dodouuglas** [comment]
ele ta usando muita memoria ram ai desliga

**Comment by KillovSky** [comment]
> **Ola pessoa que criou a melhor  bot do zapzap**
> 
> e o seguinte , estou tentando hospedar a iris em um servidor vps, mas de vez em quando a esse erro aki : 
> 
> ![image](https://user-images.githubusercontent.com/73912095/134045116-7fa73303-d3af-40aa-9fe9-7a15d9928d62.png)
>  
> e esse erro infelismente  faz a iris audo desligar, nao sei oque causa isso , pis as vezes ninguem mandou comando ela simplemente acontece isso

Erro de alocação de memoria, acontece quando tem **MUITO** dado a ser processado, recomendo que voce filtre ou faça algum tipo de separador.
Ref: #177

**Comment by patulinomods** [comment]
ok Lugas, obtigado por tirar minha duvida , mas mesmo assim nao entendi como eu posso arrumar esse erro _-nao ligue, sou lerdo-_

Mas por algum acaso, pode ser por conta de eu ter apenas 4gb de memoria sobrando? pois como estou usando um servidor vps disponibilizado gratuitamente pela a AWS , eu consigo pegar apenas 30gb de armazenamento, : 

![image](https://user-images.githubusercontent.com/73912095/134049339-22b08bf5-548a-4530-9341-773a5017febb.png)

E outra coisa, eu tenho um bot de telegram hospedado na mesma vps, e ele sempre pegou normal, _( isso a vps estava ocupando apenas 11gb de 30gb disponiveis)_ , depois que eu dei um  _git clone_ na iris, a memoria subiu muito rapido

**Comment by KillovSky** [comment]
> ok Lugas, obtigado por tirar minha duvida , mas mesmo assim nao entendi como eu posso arrumar esse erro _-nao ligue, sou lerdo-_
> 
> Mas por algum acaso, pode ser por conta de eu ter apenas 4gb de memoria sobrando? pois como estou usando um servidor vps disponibilizado gratuitamente pela a AWS , eu consigo pegar apenas 30gb de armazenamento, : 
> 
> ![image](https://user-images.githubusercontent.com/73912095/134049339-22b08bf5-548a-4530-9341-773a5017febb.png)
> 
> E outra coisa, eu tenho um bot de telegram hospedado na mesma vps, e ele sempre pegou normal, _( isso a vps estava ocupando apenas 11gb de 30gb disponiveis)_ , depois que eu dei um  _git clone_ na iris, a memoria subiu muito rapido

Sem problema po, isso ali significa que o nodejs usou o maximo de memoria que ele tinha pois o seu comando usou uma quantidade enorme de memoria ou seja, existem MUITO dados, tantos dados que a Íris não consegue processar todos e trava, ou seja 2, variaveis usam memoria e quanto mais dados existem na variavel, maior o consumo dela, se houver uma quantidade ANORMAL de dados dentro de uma variavel, o seu peso pode ser tao grande que faz o nodejs travar.

Tente isso aqui:

https://www.ti-enxame.com/pt/node.js/como-aumentar-memoria-padrao-do-nodejs/823193408/

**Comment by maradona4** [comment]
![image](https://user-images.githubusercontent.com/44541791/134089130-1db5c5a9-35d3-401a-b8fe-ccc16659d29a.png)
 tem grátis  pegar  15gb
 
 google driver > conta
