### ISSUE TITLE
/poll > votação

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#272]
![image](https://user-images.githubusercontent.com/44541791/134053627-1d6c0102-bd7c-4fd9-a993-f6ce29d778ee.png)

**Comment by EndervorHero** [comment]
@maradona4 Eu poderia entrar no seu grupo, gostaria de entrar e conhecer alguém, você poderia me convidar?  :c

**Comment by KillovSky** [comment]
Referencia a falha de escrita do arquivo, crie um arquivo com o nome dentro das aspas ali e dentro dele insira `{}` e faça um teste, se der erro em outro arquivo da mesma pasta poll, faça o mesmo com o arquivo em questão, isso se dá por uma edição ou um delete feito manualmente, ou corrupção de arquivo, na próxima atualização irei construir um sistema de segurança para ele.

**Comment by maradona4** [comment]
> @maradona4 Eu poderia entrar no seu grupo, gostaria de entrar e conhecer alguém, você poderia me convidar? :c

Chamar la (41) 996892637 ou (41) 96892637

**Comment by maradona4** [comment]
> Referencia a falha de escrita do arquivo, crie um arquivo com o nome dentro das aspas ali e dentro dele insira `{}` e faça um teste, se der erro em outro arquivo da mesma pasta poll, faça o mesmo com o arquivo em questão, isso se dá por uma edição ou um delete feito manualmente, ou corrupção de arquivo, na próxima atualização irei construir um sistema de segurança para ele.

Ok

**Comment by maradona4** [comment]
Pronto
