### ISSUE TITLE
mudar a ft do grupo

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#274]
quando eu vo mudar a ft do grupo ele fala q falta um mimeInfo mas n sei oq e

**Comment by KillovSky** [comment]
> quando eu vo mudar a ft do grupo ele fala q falta um mimeInfo mas n sei oq e

Sem informações como prints da tela, arquivos de log e outros, para ter uma analise, é dificilimo te responder, afinal, programação pode ter inumeros erros.
Sempre insira informações **SUFICIENTES** para a identificação do problema.
