### ISSUE TITLE
Apenas meu querido dono pode ter acesso a esses comandos.

### ISSUE THREAD

**Issue by Nhamin** [KillovSky/iris#276]
já botei meu numero mas simplesmente não vai boto direitinho, botei de tudo q é forma mas ele simplesmente da esse erro quando dou /dono

**Comment by Nhamin** [comment]
> já botei meu numero mas simplesmente não vai boto direitinho, botei de tudo q é forma mas ele simplesmente da esse erro quando dou /dono

**Comment by Nhamin** [comment]
.

**Comment by KillovSky** [comment]
> estou precisando saber para customizar em temática para um grupo de lol, dai para quando alguem entrar não falar welcome dql jeito grossão e sim igual quando entra em partida no lolzinho kkkk, se puder me falar os diretórios para mudar isso agradeço

Procure a `kill.sendPtt(...)` na `index.js`, lá você verá um link dentro, remova o link e mude para:

Opção 1: Outro Link

Opção 2: Um arquivo do PC (`./audio.mp3`)

Tenha em mente que o exemplo é ilustrativo.
