### ISSUE TITLE
quiero configurar el comando de welcome y add?

### ISSUE THREAD

**Issue by marru453** [KillovSky/iris#277]
quiero cuando alguien entra en el grupo mediante enlace de invitación o mediante contactos que el bot mencione a la persona que entro al grupo.
archivo es.js

> `😈🍋 ⃢⃞⃝꧁ℒ𝒾𝓂ℴ𝓃𝒸𝒾𝓁𝓁ℴ🍋 ⃢⃞⃝꧂😈

🍋 *!𝚃𝙴 𝙳Á 𝙻𝙰 𝙱𝙸𝙴𝙽𝚅𝙴𝙽𝙸𝙳𝙰 𝙰𝙻 𝙶𝚁𝚄𝙿𝙾¡* 🍋
@⁨nick 

🥵 𝙿𝚞𝚎𝚍𝚎𝚜 𝚎𝚡𝚙𝚛𝚎𝚜𝚊𝚛 𝚝𝚞𝚜 𝚋𝚞𝚎𝚗𝚘𝚜 𝚍𝚎𝚜𝚎𝚘𝚜 𝚌𝚘𝚗 𝚖𝚞𝚌𝚑𝚊𝚜 𝚙𝚊𝚕𝚊𝚋𝚛𝚊𝚜, 𝚙𝚎𝚛𝚘 𝚞𝚗𝚊 𝚍𝚎 𝚕𝚊𝚜 𝚖á𝚜 𝚒𝚖𝚙𝚘𝚛𝚝𝚊𝚗𝚝𝚎𝚜 𝚎𝚜 !𝚋𝚒𝚎𝚗𝚟𝚎𝚗𝚒𝚍𝚘¡ 🥵

• * 𝑬𝒏 𝒆𝒔𝒕𝒆 𝑮𝒓𝒖𝒑𝒐  𝒃𝒖𝒔𝒄𝒂𝒎𝒐𝒔 𝒑𝒆𝒓𝒔𝒐𝒏𝒂𝒔 𝒑𝒂𝒓𝒂 𝒉𝒂𝒄𝒆𝒓 𝒂𝒎𝒊𝒔𝒕𝒂𝒅𝒆𝒔 𝒑𝒂𝒓𝒂 𝒇𝒐𝒓𝒎𝒂𝒓 𝒖𝒏𝒂 𝑮𝒓𝒂𝒏 𝑭𝒂𝒎𝒊𝒍𝒊𝒂 𝒕𝒐𝒅𝒐𝒔 𝒋𝒖𝒏𝒕𝒐𝒔 𝒚 𝒑𝒂𝒔𝒂𝒓𝒍𝒐 𝒈𝒆𝒏𝒊𝒂𝒍 𝒆𝒏𝒕𝒓𝒆 𝒕𝒐𝒅𝒐𝒔 𝒚 𝒅𝒊𝒔𝒇𝒓𝒖𝒕𝒂𝒓 𝒅𝒆 𝒍𝒂𝒔 𝑨𝒄𝒕𝒊𝒗𝒊𝒅𝒂𝒅𝒆𝒔.* ☑️

   ⚫ 𝑶𝑩𝑳𝑰𝑮𝑨𝑻𝑶𝑹𝑰𝑶 ⚫
➳ ℕ𝕠𝕞𝕓𝕣𝕖 𝕪 𝔼𝕕𝕒𝕕.
➳ ℙ𝕒𝕚𝕤 𝕪 𝔽𝕠𝕥𝕠 𝕆𝕡𝕔𝕚𝕠𝕟𝕒𝕝.

🍋🔥 𝑵𝑶𝑹𝑴𝑨𝑻𝑰𝑽𝑨𝑺 🔥🍋

⚠️ ¡𝐒𝐢 𝐢𝐧𝐜𝐥𝐮𝐦𝐩𝐥𝐞𝐬 𝐥𝐚𝐬 𝐧𝐨𝐫𝐦𝐚𝐬, 𝐓𝐞 𝐕𝐚𝐬 𝐅𝐮𝐞𝐫𝐚!
⚠️ ¡𝐒𝐢 𝐩𝐚𝐬𝐚𝐬 𝐜𝐨𝐧𝐭𝐞𝐧𝐢𝐝𝐨 𝐢𝐧𝐚𝐝𝐞𝐜𝐮𝐚𝐝𝐨, 𝐓𝐞 𝐕𝐚𝐬 𝐅𝐮𝐞𝐫𝐚!
⚠️ ¡𝐒𝐢 𝐦𝐨𝐥𝐞𝐬𝐭𝐚𝐬 𝐚 𝐜𝐮𝐚𝐥𝐪𝐮𝐢𝐞𝐫𝐚, 𝐓𝐞 𝐕𝐚𝐬 𝐅𝐮𝐞𝐫𝐚!
⚠️ ¡𝐋𝐚 𝐏𝐫𝐨𝐭𝐞𝐜𝐜𝐢𝐨́𝐧 𝐜𝐨𝐧𝐭𝐫𝐚 𝐄𝐧𝐥𝐚𝐜𝐞𝐬 𝐝𝐞 𝐖𝐡𝐚𝐭𝐬𝐀𝐩𝐩, 𝐞𝐬𝐭𝐚𝐫𝐚́ 𝐬𝐢𝐞𝐦𝐩𝐫𝐞 𝐚𝐜𝐭𝐢𝐯𝐚𝐝𝐚!
⚠️ ¡𝐋𝐚 𝐏𝐫𝐨𝐭𝐞𝐜𝐜𝐢𝐨́𝐧 𝐜𝐨𝐧𝐭𝐫𝐚 𝐄𝐧𝐥𝐚𝐜𝐞𝐬 𝐝𝐞 𝐈𝐧𝐬𝐭𝐚𝐠𝐫𝐚𝐦, 𝐞𝐬𝐭𝐚𝐫𝐚́ 𝐬𝐢𝐞𝐦𝐩𝐫𝐞 𝐚𝐜𝐭𝐢𝐯𝐚𝐝𝐚!

🍋 ¡𝑬𝑺𝑷𝑬𝑹𝑶 𝑸𝑼𝑬 𝑫𝑰𝑺𝑭𝑹𝑼𝑻𝑬𝑺 𝒀 𝑪𝑶𝑵𝑶𝒁𝑪𝑨𝑺 𝑨 𝑮𝑬𝑵𝑻𝑬! 🍋

  🛡️𝑷𝑹𝑶𝑻𝑬𝑪𝑻𝑰𝑶𝑵 𝑩𝒀 𝑳𝑰𝑴𝑶𝑵𝑪𝑰𝑶𝑺🛡️
𝑩𝒚  ⃢⃞⃝꧁ℒ𝒾𝓂ℴ𝓃𝒸𝒾𝓁𝓁ℴ🍋 ⃢⃞⃝꧂
`

**Comment by EndervorHero** [comment]
Para eso es el comando /greet [mensaje] | 1

**Comment by marru453** [comment]
@EndervorHero pero yo quiero poner el mensaje ese en el comando de add y welcome

**Comment by marru453** [comment]
![Screenshot_2021-09-21-17-54-26-401_com gbwhatsapp](https://user-images.githubusercontent.com/89472552/134205040-674dcce4-78c8-4d24-8e64-c7ed7bdbd1f1.jpg)
Responde el mensaje pero no menciona a la persona

**Comment by KillovSky** [comment]
> ![Screenshot_2021-09-21-17-54-26-401_com gbwhatsapp](https://user-images.githubusercontent.com/89472552/134205040-674dcce4-78c8-4d24-8e64-c7ed7bdbd1f1.jpg)
> Responde el mensaje pero no menciona a la persona 

Necesitas cambiar la `index.js` de `kill.sendText` a `kill.sendTextWithMentions`.

**Comment by marru453** [comment]
@KillovSky 
no encuentro lo de kill.sendtext
lo de exportar en donde lo pongo

**Comment by KillovSky** [comment]
> @KillovSky
> no encuentro lo de kill.sendtext
> lo de exportar en donde lo pongo

`await kill.sendText(event.chat, welcmsg[o][i])`

Pero, es mejor que usted mude la linea:

```javascript
await kill.sendFile(event.chat, `data:image/png;base64,${welcomer.toBuffer().toString('base64')}`, 'welcome.png', mylang(config.Language).welcome(pushname, name))
```


> @KillovSky
> no encuentro lo de kill.sendtext
> lo de exportar en donde lo pongo

[Linha 101 Index.js](https://github.com/KillovSky/iris/blob/0e1c29f31f5a64b1149c0c0bb21d86a8ee7fceca/index.js#L101)

**Comment by KillovSky** [comment]
> @KillovSky
> no encuentro lo de kill.sendtext
> lo de exportar en donde lo pongo

[Linha 101 Index.js](https://github.com/KillovSky/iris/blob/0e1c29f31f5a64b1149c0c0bb21d86a8ee7fceca/index.js#L101)

**Comment by marru453** [comment]
@KillovSky 
await kill.sendTextWithMentions(event.chat, mylang(config.Language).entrace()) en la linea 88 index.js
y lo de await kill.file() lo he reemplazado por lo que estaba en la linea 101 index.js

**Comment by marru453** [comment]
@KillovSky 
kill.sendTextWithMentions esto lo cambio por kill.sendtext
https://github.com/KillovSky/iris/blob/0e1c29f31f5a64b1149c0c0bb21d86a8ee7fceca/index.js#L88

@${event.who.replace('@c.us','')} pero esto no se en donde lo pongo
https://github.com/KillovSky/iris/blob/0e1c29f31f5a64b1149c0c0bb21d86a8ee7fceca/index.js#L106

**Comment by KillovSky** [comment]
> @KillovSky 
> kill.sendTextWithMentions esto lo cambio por kill.sendtext
> https://github.com/KillovSky/iris/blob/0e1c29f31f5a64b1149c0c0bb21d86a8ee7fceca/index.js#L88
> 
> @${event.who.replace('@c.us','')} pero esto no se en donde lo pongo
> https://github.com/KillovSky/iris/blob/0e1c29f31f5a64b1149c0c0bb21d86a8ee7fceca/index.js#L106
> es.js
> exports.welcome = (pushname, name) => { return `
> 
>     😈🍋 ⃢⃞⃝꧁ℒ𝒾𝓂ℴ𝓃𝒸𝒾𝓁𝓁ℴ🍋 ⃢⃞⃝꧂😈
> 
> 🍋 !𝚃𝙴 𝙳Á 𝙻𝙰 𝙱𝙸𝙴𝙽𝚅𝙴𝙽𝙸𝙳𝙰 𝙰𝙻 𝙶𝚁𝚄𝙿𝙾¡ 🍋
> "@${event.who.replace('@c.us','')}"
> 
> 🥵 𝙿𝚞𝚎𝚍𝚎𝚜 𝚎𝚡𝚙𝚛𝚎𝚜𝚊𝚛 𝚝𝚞𝚜 𝚋𝚞𝚎𝚗𝚘𝚜 𝚍𝚎𝚜𝚎𝚘𝚜 𝚌𝚘𝚗 𝚖𝚞𝚌𝚑𝚊𝚜 𝚙𝚊𝚕𝚊𝚋𝚛𝚊𝚜, 𝚙𝚎𝚛𝚘 𝚞𝚗𝚊 𝚍𝚎 𝚕𝚊𝚜 𝚖á𝚜 𝚒𝚖𝚙𝚘𝚛𝚝𝚊𝚗𝚝𝚎𝚜 𝚎𝚜 !𝚋𝚒𝚎𝚗𝚟𝚎𝚗𝚒𝚍𝚘¡ 🥵
> 
> • * 𝑬𝒏 𝒆𝒔𝒕𝒆 𝑮𝒓𝒖𝒑𝒐 𝒃𝒖𝒔𝒄𝒂𝒎𝒐𝒔 𝒑𝒆𝒓𝒔𝒐𝒏𝒂𝒔 𝒑𝒂𝒓𝒂 𝒉𝒂𝒄𝒆𝒓 𝒂𝒎𝒊𝒔𝒕𝒂𝒅𝒆𝒔 𝒑𝒂𝒓𝒂 𝒇𝒐𝒓𝒎𝒂𝒓 𝒖𝒏𝒂 𝑮𝒓𝒂𝒏 𝑭𝒂𝒎𝒊𝒍𝒊𝒂 𝒕𝒐𝒅𝒐𝒔 𝒋𝒖𝒏𝒕𝒐𝒔 𝒚 𝒑𝒂𝒔𝒂𝒓𝒍𝒐 𝒈𝒆𝒏𝒊𝒂𝒍 𝒆𝒏𝒕𝒓𝒆 𝒕𝒐𝒅𝒐𝒔 𝒚 𝒅𝒊𝒔𝒇𝒓𝒖𝒕𝒂𝒓 𝒅𝒆 𝒍𝒂𝒔 𝑨𝒄𝒕𝒊𝒗𝒊𝒅𝒂𝒅𝒆𝒔.* ☑️
> 
> ⚫ 𝑶𝑩𝑳𝑰𝑮𝑨𝑻𝑶𝑹𝑰𝑶 ⚫
> ➳ ℕ𝕠𝕞𝕓𝕣𝕖 𝕪 𝔼𝕕𝕒𝕕.
> ➳ ℙ𝕒𝕚𝕤 𝕪 𝔽𝕠𝕥𝕠 𝕆𝕡𝕔𝕚𝕠𝕟𝕒𝕝.
> 
> 🍋🔥 𝑵𝑶𝑹𝑴𝑨𝑻𝑰𝑽𝑨𝑺 🔥🍋
> 
> ⚠️ ¡𝐒𝐢 𝐢𝐧𝐜𝐥𝐮𝐦𝐩𝐥𝐞𝐬 𝐥𝐚𝐬 𝐧𝐨𝐫𝐦𝐚𝐬, 𝐓𝐞 𝐕𝐚𝐬 𝐅𝐮𝐞𝐫𝐚!
> ⚠️ ¡𝐒𝐢 𝐩𝐚𝐬𝐚𝐬 𝐜𝐨𝐧𝐭𝐞𝐧𝐢𝐝𝐨 𝐢𝐧𝐚𝐝𝐞𝐜𝐮𝐚𝐝𝐨, 𝐓𝐞 𝐕𝐚𝐬 𝐅𝐮𝐞𝐫𝐚!
> ⚠️ ¡𝐒𝐢 𝐦𝐨𝐥𝐞𝐬𝐭𝐚𝐬 𝐚 𝐜𝐮𝐚𝐥𝐪𝐮𝐢𝐞𝐫𝐚, 𝐓𝐞 𝐕𝐚𝐬 𝐅𝐮𝐞𝐫𝐚!
> ⚠️ ¡𝐋𝐚 𝐏𝐫𝐨𝐭𝐞𝐜𝐜𝐢𝐨́𝐧 𝐜𝐨𝐧𝐭𝐫𝐚 𝐄𝐧𝐥𝐚𝐜𝐞𝐬 𝐝𝐞 𝐖𝐡𝐚𝐭𝐬𝐀𝐩𝐩, 𝐞𝐬𝐭𝐚𝐫𝐚́ 𝐬𝐢𝐞𝐦𝐩𝐫𝐞 𝐚𝐜𝐭𝐢𝐯𝐚𝐝𝐚!
> ⚠️ ¡𝐋𝐚 𝐏𝐫𝐨𝐭𝐞𝐜𝐜𝐢𝐨́𝐧 𝐜𝐨𝐧𝐭𝐫𝐚 𝐄𝐧𝐥𝐚𝐜𝐞𝐬 𝐝𝐞 𝐈𝐧𝐬𝐭𝐚𝐠𝐫𝐚𝐦, 𝐞𝐬𝐭𝐚𝐫𝐚́ 𝐬𝐢𝐞𝐦𝐩𝐫𝐞 𝐚𝐜𝐭𝐢𝐯𝐚𝐝𝐚!
> 
> 🍋 ¡𝑬𝑺𝑷𝑬𝑹𝑶 𝑸𝑼𝑬 𝑫𝑰𝑺𝑭𝑹𝑼𝑻𝑬𝑺 𝒀 𝑪𝑶𝑵𝑶𝒁𝑪𝑨𝑺 𝑨 𝑮𝑬𝑵𝑻𝑬! 🍋
> 
> 🛡️𝑷𝑹𝑶𝑻𝑬𝑪𝑻𝑰𝑶𝑵 𝑩𝒀 𝑳𝑰𝑴𝑶𝑵𝑪𝑰𝑶𝑺🛡️
> 𝑩𝒚 ⃢⃞⃝꧁ℒ𝒾𝓂ℴ𝓃𝒸𝒾𝓁𝓁ℴ🍋 ⃢⃞⃝꧂` }
> 

Inserta esto abajo del `welcOn = 1`:

```javascript
if (event.chat == 'Tu id de grupo') {
     return await kill.sendTextWithMentions(event.chat, `Su mesaje + @${event.who.replace('@c.us','')}`)
}
```
