### ISSUE TITLE
npm start timeout

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#278]
![image](https://user-images.githubusercontent.com/44541791/134218219-b66d7090-c85c-481f-be1e-1c24e51216e8.png)

2 vezes iniciar, todos hora timeout

**Comment by marru453** [comment]
reencia el bot, borra el archivo de irisdata

**Comment by maradona4** [comment]
Gracias,

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/134218219-b66d7090-c85c-481f-be1e-1c24e51216e8.png)
> 
> 2 vezes iniciar, todos hora timeout

São erros com relação ao cache e velocidade da internet, basta reinciar e apagar a pasta logs, o arquivo `iris.data` não precisa ser deletado.

**Comment by maradona4** [comment]
Entendi
