### ISSUE TITLE
Tem algum jeito fácil de personalizar o bot para um único grupo?

### ISSUE THREAD

**Issue by EmanuelPeixoto** [KillovSky/iris#280]
eu queria personalizar o bot, mas iria afetar todos os grupos, e eu queria modificar em só um

**Comment by KillovSky** [comment]
> eu queria personalizar o bot, mas iria afetar todos os grupos, e eu queria modificar em só um

Precisaria refazer toda a estrutura, mas de toda forma, Íris ja possui comandos de customização unica para cada grupo.
Se você planejar customizar menus e outros, terá que criar outro arquivo de linguagem na pasta lang, edita-lo, adicionar seu valor na index.js da pasta lang e então importa-lo com um valor proprio, igual é feito com os arquivos de idioma.

**Comment by marru453** [comment]
tampoco hace falta crear el archivo desde cerro, eel archivo es.js pt.js en.js se pueden editar solo tienes que  poner el menu dentro de  { return `pones tu menu aqui` }
