### ISSUE TITLE
como mudar os audios do welcome e bye?

### ISSUE THREAD

**Issue by Nhamin** [KillovSky/iris#281]
estou precisando saber para customizar em temática para um grupo de lol, dai para quando alguem entrar não falar welcome dql jeito grossão e sim igual quando entra em partida no lolzinho kkkk, se puder me falar os diretórios para mudar isso agradeço

**Comment by dodouuglas** [comment]
> estou precisando saber para customizar em temática para um grupo de lol, dai para quando alguem entrar não falar welcome dql jeito grossão e sim igual quando entra em partida no lolzinho kkkk, se puder me falar os diretórios para mudar isso agradeço

tem sim e so voce mudar aonde tem `await kill.sendPtt(event.chat, 'https://media1.vocaroo.com/mp3/1aNWZ9vQa2CT')` quando sair e `await kill.sendPtt(event.chat, 'https://www.myinstants.com/media/sounds/welcome-mercador-resident-evil-4.mp3')` quando entrar ai vc pode baixar seu audio e colocar `./lib/media/audio/nome do seu arquivo de audio com a extenção tipo .mp3`

**Comment by KillovSky** [comment]
Ref: #276
Mas a resposta acima esta totalmente correta também.
