### ISSUE TITLE
vps

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#282]
quanto de ram vc indica para colocar a iris na vps?

**Comment by markoswythor** [comment]
> quanto de ram vc indica para colocar a iris na vps?

n sou o kill mas eu era usuário de vps até mês retrasado e usava uma vps br do site minivps 2 de ram e pegava de boa. Porém mês passado estava pedindo mais memória ram pq estava afetando na vps lá ent acho q 4 de ram é o mais recomendado porem o 2 roda (se for poucos pvs), enfim essa duvida depende do site que você quer usar também né pq tem vps que a iris nem roda

**Comment by KillovSky** [comment]
> quanto de ram vc indica para colocar a iris na vps?

Se você nã planeja usar chrome e tem poucos usuarios que raramente usam a Íris, 512mb's já rodam no limite do limite via linux - um linux leve que tenha apenas modo CLI e nada grafico, apenas o Linux em modo texto e sem programas -, a minha recomendação no entanto é que seja utilizado de 1GB pra cima de memoria RAM em sistemas graficos como o Windows e Linux com interface grafica.

**Comment by Nhamin** [comment]
olá há muito tempo atrás tinha falado com o @KillovSky sobre vps, eu usei uma com uma config de 2gb e 10gb de ssd, com navegador em base chromium( usei o vivaldi) https://github.com/KillovSky/iris/issues/35 aqui vc pode ver direitinho como é para mudar seu navegador, ja testei muitos e o vivaldi é o melhor para linux e com estabilidade boa, se tiver travamentos, limite a cpu para 89 que assim a iris fica bem estável e bem rapida...

**Comment by Nhamin** [comment]
faça um script leve para a iris reiniciar em torno de 6/8 horas por dia para o consumo sempre ficar baixo e com eficiencia
