### ISSUE TITLE
Anti Fake Numero PV

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#283]
Como bloquear automatico FAKE NUMERO, ele diz "oi"  

![image](https://user-images.githubusercontent.com/44541791/134405683-3a1e25a0-ecad-4b84-b225-890fa0da9c92.png)

**Comment by KillovSky** [comment]
> Como bloquear automatico FAKE NUMERO, ele diz "oi"  
> 
> ![image](https://user-images.githubusercontent.com/44541791/134405683-3a1e25a0-ecad-4b84-b225-890fa0da9c92.png)
> 
> 
> 

```javascript
if (!isGroupMsg && !user.startsWith(config.DDI)) {
     return kill.contactBlock(user)
}
```

Easy, insira na `config.js`, de preferencia debaixo das `if` de `lang`.

**Comment by maradona4** [comment]
Obg ;)
