### ISSUE TITLE
Problema ao inicializar a IRIS

### ISSUE THREAD

**Issue by Wi-Fallen** [KillovSky/iris#284]
![image](https://user-images.githubusercontent.com/90735036/134418233-dd1a6f17-b787-4658-bb58-3f6384825761.png)

**Comment by maradona4** [comment]
![image](https://user-images.githubusercontent.com/44541791/134491456-907f9cb4-b4c7-4f1f-ba29-d489329a3f29.png)

você tambem

**Comment by maradona4** [comment]
Agr eu conseguir, eu apago "node_modules" dps eu dnv "npm i" e "npm update"

**Comment by KillovSky** [comment]
> 
> ![image](https://user-images.githubusercontent.com/90735036/134418233-dd1a6f17-b787-4658-bb58-3f6384825761.png)
> 
> 

Sua print não mostra erro algum, mas baseado na print do Maradona que mostra todo o terminal, é possivel dizer que o navegador não consegue iniciar o site do WhatsApp, pode ser lentidão, cache ou atualização pedente.

Passe um `CCleaner` no PC.
Apague a pasta `logs`.
Rode `npm update` na Íris.
