### ISSUE TITLE
Imagens && Botões

### ISSUE THREAD

**Issue by markoswythor** [KillovSky/iris#287]
Teria de alguma forma mesclar o código (kill.sendFileFromUrl) de imagens com o kill.sendButtons???
De modo que fique a imagem, o texto e os botões tudo junto

**Comment by dodouuglas** [comment]
> Teria de alguma forma mesclar o código (kill.sendFileFromUrl) de imagens com o kill.sendButtons???
> De modo que fique a imagem, o texto e os botões tudo junto

não

**Comment by markoswythor** [comment]
> > Teria de alguma forma mesclar o código (kill.sendFileFromUrl) de imagens com o kill.sendButtons???
> > De modo que fique a imagem, o texto e os botões tudo junto
> 
> não

Ah sim é que eu ia fazer tipo isso: 

![Screenshot_20210923-072714~2](https://user-images.githubusercontent.com/76796419/134492107-ec0ef003-fe22-4b2c-aa05-2c82df312d87.png)

**Comment by KillovSky** [comment]
> Teria de alguma forma mesclar o código (kill.sendFileFromUrl) de imagens com o kill.sendButtons???
> De modo que fique a imagem, o texto e os botões tudo junto
> 
> 

Infelizmente não existe por hora - ou pode ser que conheça o metodo disso, olhe a pagina da wa-automate [aqui](https://docs.openwa.dev/classes/api_Client.Client.html) sempre que tiver duvidas sobre suas funções -, mas se serve de dica, talvez seja uma boa ideia mandar o texto separadamente pois ele se torna mais facil de copiar e colar do que quando enviado em conjunto com uma imagem, acredite, eu ja perdi diversos comandos por fazer isso e não conseguir copiar depois pelo telefone - não normalmente.
