### ISSUE TITLE
mensagem apagada

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#288]
eu to tentando fazer um sistema de ativar e desativar para quando alguem apagar uma mensagem e apagar o bot vai mandar aonde foi apagada mas n to consegindo 
```	
kill.onMessageDeleted(async (msg) => {
		const numebot = await kill.getHostNumber() + '@c.us'
		const isMyBot = msg.author.includes(numebot)
		const functions = JSON.parse(fs.readFileSync('./lib/config/Gerais/functions.json'))
		const isantimsg = functions[0].antimsg.includes(msg.chat)
		if (msg.type == 'image' || msg.type == 'video' || msg.type == 'audio' || msg.type == 'document' || msg.type == 'unknown' && isantimsg && !isMyBot) {
	  	const tipoArquivo = msg.mimetype.split('/')[1]
	  	const mediaData = await decryptMedia(msg, uaOverride) 
	 	 await kill.sendFile(msg.from, `data:${msg.mimetype};base64,${mediaData.toString('base64')}`, 'Deletado.'+`${tipoArquivo}`, `Novo arquivo apagado:\n\nDe: wa.me/+${msg.from.replace('@c.us', '')}\nPara: wa.me/+${msg.to}\nAuthor: wa.me/+${msg.author.replace('@c.us', '')}\nQuando: ${msg.t}`)
		} else if (msg.type == 'chat') {
	  	await kill.sendText(msg.from, `Nova mensagem apagada:\n\nDe: wa.me/+${msg.from.replace('@c.us', '.')}\nPara: wa.me/+${msg.to}\nAuthor: wa.me/+${msg.author.replace('@c.us', '')}\nQuando: ${msg.t}\nMensagem: ${msg.body}`)
		} else if (msg.type == 'ptt') {
	 	 const mediaData = await decryptMedia(msg)
	 	 await kill.sendPtt(msg.from, `data:${msg.mimetype};base64,${mediaData.toString('base64')}`)
	 	await kill.sendText(msg.from, `Novo audio apagado:\n\nDe: wa.me/+${msg.from.replace('@c.us', '.')}\nPara: wa.me/+${msg.to}\nAuthor: wa.me/+${msg.author.replace('@c.us', '')}\nQuando: ${msg.t}`) 
		} else return;
	})
```
ja coloquei o antimsg la nas functions

**Comment by KillovSky** [comment]
> eu to tentando fazer um sistema de ativar e desativar para quando alguem apagar uma mensagem e apagar o bot vai mandar aonde foi apagada mas n to consegindo 
> ```	
> kill.onMessageDeleted(async (msg) => {
> 		const numebot = await kill.getHostNumber() + '@c.us'
> 		const isMyBot = msg.author.includes(numebot)
> 		const functions = JSON.parse(fs.readFileSync('./lib/config/Gerais/functions.json'))
> 		const isantimsg = functions[0].antimsg.includes(msg.chat)
> 		if (msg.type == 'image' || msg.type == 'video' || msg.type == 'audio' || msg.type == 'document' || msg.type == 'unknown' && isantimsg && !isMyBot) {
> 	  	const tipoArquivo = msg.mimetype.split('/')[1]
> 	  	const mediaData = await decryptMedia(msg, uaOverride) 
> 	 	 await kill.sendFile(msg.from, `data:${msg.mimetype};base64,${mediaData.toString('base64')}`, 'Deletado.'+`${tipoArquivo}`, `Novo arquivo apagado:\n\nDe: wa.me/+${msg.from.replace('@c.us', '')}\nPara: wa.me/+${msg.to}\nAuthor: wa.me/+${msg.author.replace('@c.us', '')}\nQuando: ${msg.t}`)
> 		} else if (msg.type == 'chat') {
> 	  	await kill.sendText(msg.from, `Nova mensagem apagada:\n\nDe: wa.me/+${msg.from.replace('@c.us', '.')}\nPara: wa.me/+${msg.to}\nAuthor: wa.me/+${msg.author.replace('@c.us', '')}\nQuando: ${msg.t}\nMensagem: ${msg.body}`)
> 		} else if (msg.type == 'ptt') {
> 	 	 const mediaData = await decryptMedia(msg)
> 	 	 await kill.sendPtt(msg.from, `data:${msg.mimetype};base64,${mediaData.toString('base64')}`)
> 	 	await kill.sendText(msg.from, `Novo audio apagado:\n\nDe: wa.me/+${msg.from.replace('@c.us', '.')}\nPara: wa.me/+${msg.to}\nAuthor: wa.me/+${msg.author.replace('@c.us', '')}\nQuando: ${msg.t}`) 
> 		} else return;
> 	})
> ```
> ja coloquei o antimsg la nas functions 

Sinceramente, não encontrei um erro no código ao fazer uma revisão, exceto na parte da functions, pois você não exibiu o funcionamento todo dele.

Tente criar outro arquivo json pra utilizar ou exiba ao menos o modo que você faz o `fs.writeFile...` na `case` dele.

Acredito que o erro esteja entre a linha `if` que possui o `isantimsg` e o arquivo `functions.json`.

**Comment by dodouuglas** [comment]
> > eu to tentando fazer um sistema de ativar e desativar para quando alguem apagar uma mensagem e apagar o bot vai mandar aonde foi apagada mas n to consegindo
> > ```
> > kill.onMessageDeleted(async (msg) => {
> > 		const numebot = await kill.getHostNumber() + '@c.us'
> > 		const isMyBot = msg.author.includes(numebot)
> > 		const functions = JSON.parse(fs.readFileSync('./lib/config/Gerais/functions.json'))
> > 		const isantimsg = functions[0].antimsg.includes(msg.chat)
> > 		if (msg.type == 'image' || msg.type == 'video' || msg.type == 'audio' || msg.type == 'document' || msg.type == 'unknown' && isantimsg && !isMyBot) {
> > 	  	const tipoArquivo = msg.mimetype.split('/')[1]
> > 	  	const mediaData = await decryptMedia(msg, uaOverride) 
> > 	 	 await kill.sendFile(msg.from, `data:${msg.mimetype};base64,${mediaData.toString('base64')}`, 'Deletado.'+`${tipoArquivo}`, `Novo arquivo apagado:\n\nDe: wa.me/+${msg.from.replace('@c.us', '')}\nPara: wa.me/+${msg.to}\nAuthor: wa.me/+${msg.author.replace('@c.us', '')}\nQuando: ${msg.t}`)
> > 		} else if (msg.type == 'chat') {
> > 	  	await kill.sendText(msg.from, `Nova mensagem apagada:\n\nDe: wa.me/+${msg.from.replace('@c.us', '.')}\nPara: wa.me/+${msg.to}\nAuthor: wa.me/+${msg.author.replace('@c.us', '')}\nQuando: ${msg.t}\nMensagem: ${msg.body}`)
> > 		} else if (msg.type == 'ptt') {
> > 	 	 const mediaData = await decryptMedia(msg)
> > 	 	 await kill.sendPtt(msg.from, `data:${msg.mimetype};base64,${mediaData.toString('base64')}`)
> > 	 	await kill.sendText(msg.from, `Novo audio apagado:\n\nDe: wa.me/+${msg.from.replace('@c.us', '.')}\nPara: wa.me/+${msg.to}\nAuthor: wa.me/+${msg.author.replace('@c.us', '')}\nQuando: ${msg.t}`) 
> > 		} else return;
> > 	})
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ja coloquei o antimsg la nas functions
> 
> Sinceramente, não encontrei um erro no código ao fazer uma revisão, exceto na parte da functions, pois você não exibiu o funcionamento todo dele.
> 
> Tente criar outro arquivo json pra utilizar ou exiba ao menos o modo que você faz o `fs.writeFile...` na `case` dele.
> 
> Acredito que o erro esteja entre a linha `if` que possui o `isantimsg` e o arquivo `functions.json`.

eu peguei a case do welcome e troquei em cima e as functions mesma coisa cm a index

**Comment by KillovSky** [comment]
> > > eu to tentando fazer um sistema de ativar e desativar para quando alguem apagar uma mensagem e apagar o bot vai mandar aonde foi apagada mas n to consegindo
> > > ```
> > > kill.onMessageDeleted(async (msg) => {
> > > 		const numebot = await kill.getHostNumber() + '@c.us'
> > > 		const isMyBot = msg.author.includes(numebot)
> > > 		const functions = JSON.parse(fs.readFileSync('./lib/config/Gerais/functions.json'))
> > > 		const isantimsg = functions[0].antimsg.includes(msg.chat)
> > > 		if (msg.type == 'image' || msg.type == 'video' || msg.type == 'audio' || msg.type == 'document' || msg.type == 'unknown' && isantimsg && !isMyBot) {
> > > 	  	const tipoArquivo = msg.mimetype.split('/')[1]
> > > 	  	const mediaData = await decryptMedia(msg, uaOverride) 
> > > 	 	 await kill.sendFile(msg.from, `data:${msg.mimetype};base64,${mediaData.toString('base64')}`, 'Deletado.'+`${tipoArquivo}`, `Novo arquivo apagado:\n\nDe: wa.me/+${msg.from.replace('@c.us', '')}\nPara: wa.me/+${msg.to}\nAuthor: wa.me/+${msg.author.replace('@c.us', '')}\nQuando: ${msg.t}`)
> > > 		} else if (msg.type == 'chat') {
> > > 	  	await kill.sendText(msg.from, `Nova mensagem apagada:\n\nDe: wa.me/+${msg.from.replace('@c.us', '.')}\nPara: wa.me/+${msg.to}\nAuthor: wa.me/+${msg.author.replace('@c.us', '')}\nQuando: ${msg.t}\nMensagem: ${msg.body}`)
> > > 		} else if (msg.type == 'ptt') {
> > > 	 	 const mediaData = await decryptMedia(msg)
> > > 	 	 await kill.sendPtt(msg.from, `data:${msg.mimetype};base64,${mediaData.toString('base64')}`)
> > > 	 	await kill.sendText(msg.from, `Novo audio apagado:\n\nDe: wa.me/+${msg.from.replace('@c.us', '.')}\nPara: wa.me/+${msg.to}\nAuthor: wa.me/+${msg.author.replace('@c.us', '')}\nQuando: ${msg.t}`) 
> > > 		} else return;
> > > 	})
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ja coloquei o antimsg la nas functions
> > 
> > Sinceramente, não encontrei um erro no código ao fazer uma revisão, exceto na parte da functions, pois você não exibiu o funcionamento todo dele.
> > 
> > Tente criar outro arquivo json pra utilizar ou exiba ao menos o modo que você faz o `fs.writeFile...` na `case` dele.
> > 
> > Acredito que o erro esteja entre a linha `if` que possui o `isantimsg` e o arquivo `functions.json`.
> 
> eu peguei a case do welcome e troquei em cima e as functions mesma coisa cm a index

Por isso eu preciso ver-las e pedi que mostrasse.

**Comment by dodouuglas** [comment]
> > > > eu to tentando fazer um sistema de ativar e desativar para quando alguem apagar uma mensagem e apagar o bot vai mandar aonde foi apagada mas n to consegindo
> > > > ```
> > > > kill.onMessageDeleted(async (msg) => {
> > > > 		const numebot = await kill.getHostNumber() + '@c.us'
> > > > 		const isMyBot = msg.author.includes(numebot)
> > > > 		const functions = JSON.parse(fs.readFileSync('./lib/config/Gerais/functions.json'))
> > > > 		const isantimsg = functions[0].antimsg.includes(msg.chat)
> > > > 		if (msg.type == 'image' || msg.type == 'video' || msg.type == 'audio' || msg.type == 'document' || msg.type == 'unknown' && isantimsg && !isMyBot) {
> > > > 	  	const tipoArquivo = msg.mimetype.split('/')[1]
> > > > 	  	const mediaData = await decryptMedia(msg, uaOverride) 
> > > > 	 	 await kill.sendFile(msg.from, `data:${msg.mimetype};base64,${mediaData.toString('base64')}`, 'Deletado.'+`${tipoArquivo}`, `Novo arquivo apagado:\n\nDe: wa.me/+${msg.from.replace('@c.us', '')}\nPara: wa.me/+${msg.to}\nAuthor: wa.me/+${msg.author.replace('@c.us', '')}\nQuando: ${msg.t}`)
> > > > 		} else if (msg.type == 'chat') {
> > > > 	  	await kill.sendText(msg.from, `Nova mensagem apagada:\n\nDe: wa.me/+${msg.from.replace('@c.us', '.')}\nPara: wa.me/+${msg.to}\nAuthor: wa.me/+${msg.author.replace('@c.us', '')}\nQuando: ${msg.t}\nMensagem: ${msg.body}`)
> > > > 		} else if (msg.type == 'ptt') {
> > > > 	 	 const mediaData = await decryptMedia(msg)
> > > > 	 	 await kill.sendPtt(msg.from, `data:${msg.mimetype};base64,${mediaData.toString('base64')}`)
> > > > 	 	await kill.sendText(msg.from, `Novo audio apagado:\n\nDe: wa.me/+${msg.from.replace('@c.us', '.')}\nPara: wa.me/+${msg.to}\nAuthor: wa.me/+${msg.author.replace('@c.us', '')}\nQuando: ${msg.t}`) 
> > > > 		} else return;
> > > > 	})
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ja coloquei o antimsg la nas functions
> > > 
> > > 
> > > Sinceramente, não encontrei um erro no código ao fazer uma revisão, exceto na parte da functions, pois você não exibiu o funcionamento todo dele.
> > > Tente criar outro arquivo json pra utilizar ou exiba ao menos o modo que você faz o `fs.writeFile...` na `case` dele.
> > > Acredito que o erro esteja entre a linha `if` que possui o `isantimsg` e o arquivo `functions.json`.
> > 
> > 
> > eu peguei a case do welcome e troquei em cima e as functions mesma coisa cm a index
> 
> Por isso eu preciso ver-las e pedi que mostrasse.

```
				case 'antimsg':
					if (!isGroupMsg) return await kill.reply(from, mess.sogrupo(), id)
					if (isGroupMsg && isGroupAdmins || isGroupMsg && isOwner) {
						if (args.length !== 1) return await kill.reply(from, mess.onoff(), id)
						if (args[0].toLowerCase() == 'on') {
							if (functions[0].antimsg.includes(groupId)) return await kill.reply(from, mess.jaenabled(), id)
							functions[0].antimsg.push(groupId)
							await fs.writeFileSync('./lib/config/Gerais/functions.json', JSON.stringify(functions))
							await kill.reply(from, mess.enabled(), id)
						} else if (args[0].toLowerCase() == 'off') {
							if (!functions[0].antimsg.includes(groupId)) return await kill.reply(from, mess.jadisabled(), id)
							functions[0].antimsg.splice(groupId, 1)
							await fs.writeFileSync('./lib/config/Gerais/functions.json', JSON.stringify(functions))
							await kill.reply(from, mess.disabled(), id)
						} else return await kill.reply(from, mess.kldica1(), id)
					} else if (isGroupMsg) {
						await kill.reply(from, mess.soademiro(), id)
					} else return await kill.reply(from, mess.sogrupo(), id)
					break
```

**Comment by KillovSky** [comment]
Bem, não consigo encontrar problema nenhum no seu código, ja tentou inserir ele em cima da `kill.onMessage`?
Sobre as midias, não tenho muita certeza se você conseguira "baixar" após deletar, afinal, nunca testei isso, mas tente inserir um `console.log(msg)` na `kill.onMessageDeleted` e mostrar, se nem isso exibir erros ou falhas de algo, não faço a menor ideia de onde está seu problema mas aposto em "você não conseguir baixar midias após deleta-las".

**Comment by dodouuglas** [comment]
ele fuciona d boa se eu colocar em um grupo para ele mandar um expecifico ou aonde foi apagado mas a parte de desativar e ativar nao fuciona

**Comment by KillovSky** [comment]
> ele fuciona d boa se eu colocar em um grupo para ele mandar um expecifico ou aonde foi apagado mas a parte de desativar e ativar nao fuciona

Ahhh, ja tentou `msg.chatId` em vez de `msg.chat`?

**Comment by dodouuglas** [comment]
> > ele fuciona d boa se eu colocar em um grupo para ele mandar um expecifico ou aonde foi apagado mas a parte de desativar e ativar nao fuciona
> 
> Ahhh, ja tentou `msg.chatId` em vez de `msg.chat`?

aonde

**Comment by dodouuglas** [comment]
conseguir resolver no `const isantimsg = functions[0].antimsg.includes(msg.chat)` e msg.from no lugar do msg.chat pq n existe chat e o if desse mesma const eu coloquei no começo ai ficou assim
```
		kill.onMessageDeleted(async (msg) => {
		console.log(msg)
		const numebot = await kill.getHostNumber() + '@c.us'
		const isMyBot = msg.author.includes(numebot)
		const functions = JSON.parse(fs.readFileSync('./lib/config/Gerais/functions.json'))
		const isantimsg = functions[0].antimsg.includes(msg.from)
		if(isantimsg) {
		if (msg.type == 'image' || msg.type == 'video' || msg.type == 'audio' || msg.type == 'document' || msg.type == 'unknown' || msg.author == !isMyBot) {
	  	const tipoArquivo = msg.mimetype.split('/')[1]
	  	const mediaData = await decryptMedia(msg, uaOverride) 
	 	 await kill.sendFile(msg.from, `data:${msg.mimetype};base64,${mediaData.toString('base64')}`, 'Deletado.'+`${tipoArquivo}`, `Novo arquivo apagado:\n\nDe: wa.me/+${msg.from.replace('@c.us', '')}\nPara: wa.me/+${msg.to}\nAuthor: wa.me/+${msg.author.replace('@c.us', '')}\nQuando: ${msg.t}`)
		} else if (msg.type == 'chat') {
	  	await kill.sendText(msg.from, `Nova mensagem apagada:\n\nDe: wa.me/+${msg.author.replace('@c.us', '')}\nQuando: ${msg.t}\nMensagem: ${msg.body}`)
		} else if (msg.type == 'ptt') {
	 	 const mediaData = await decryptMedia(msg)
	 	 await kill.sendPtt(msg.from, `data:${msg.mimetype};base64,${mediaData.toString('base64')}`)
	 	await kill.sendText(msg.from, `Novo audio apagado:\n\nDe: wa.me/+${msg.from.replace('@c.us', '.')}\nPara: wa.me/+${msg.to}\nAuthor: wa.me/+${msg.author.replace('@c.us', '')}\nQuando: ${msg.t}`) 
		} else return;
	} else return;
	})
```
