### ISSUE TITLE
converter milissegundos em dias

### ISSUE THREAD

**Issue by Bisgos** [KillovSky/iris#289]
Boa Lucas! olha eu incomodando por aqui agora.
estou adicionando esse sistema de vip no bot, toda estrutura já esta formada porém eu queria adicionar em dias ao invés de milissegundos.
![Screenshot_234](https://user-images.githubusercontent.com/73245241/134441573-0759cb8c-23c5-46bd-a022-deafba5cf482.png)
..
a case é esta aqui.
![Screenshot_235](https://user-images.githubusercontent.com/73245241/134441664-5eb3f140-fe9f-4426-8c9b-133d215e0c50.png)
..
talvez queria dá uma olhada aki tbm..
![Screenshot_236](https://user-images.githubusercontent.com/73245241/134441876-2163a362-0272-4966-81fe-7d4b0386aca9.png)
.
qualquer ajuda é bem vinda! VLW!!

**Comment by KillovSky** [comment]
Basta aplicar uma multiplicação no `args[2]` definindo ele como número primeiro e multiplicando.

```javascript

const timeDays = Number(args[2]) * 86400000
// 86400000 = 1 Dia em milissegundos, isso converte dias para MS

const timeMili = timeDays / 86400000
// Isso converte os MS para dias pegando o valor final do timeDays e dividindo por 86400000

// Após criar isso, mude as 'args[2]' para 'timeDays'

// Modo de uso no WhatsApp "/vip add @user 1" (No WhatsApp apenas digite em dias agora)

// P.S, provalmente você precisará remoldar o sistema para usar as "const's" em vez de "args[2]", mas isso é uma parte que deixo contigo.
```

Boa sorte!

**Comment by wesley0209** [comment]
@Bisgos pode me chamar no whatsapp? wa.me/+553199926748

**Comment by Bisgos** [comment]
sim mano, claro!

**Comment by patulinomods** [comment]
@Bisgos obg mt pelo seu comando, estava com essa ideia ah um tempo , mais nao sabia como codar ela, teria como mandar os codigos aki em texto por favor, vai ajudar muito

**Comment by dodouuglas** [comment]
@Bisgos tem como mandar o script todo?
