### ISSUE TITLE
Iris não inicia

### ISSUE THREAD

**Issue by zyereon** [KillovSky/iris#290]
![BB07EB48-051E-4E98-8829-86D60A276217](https://user-images.githubusercontent.com/69636320/134530088-8cbc2a26-119a-4c8c-9a43-574290f86645.jpeg)

simplesmente da esse erro

**Comment by maradona4** [comment]
Ler #260

**Comment by KillovSky** [comment]
> ![BB07EB48-051E-4E98-8829-86D60A276217](https://user-images.githubusercontent.com/69636320/134530088-8cbc2a26-119a-4c8c-9a43-574290f86645.jpeg)
> 
> simplesmente da esse erro 

Seu nome de usuario tem acentos, não estou muito certo sobre isso atrapalhar ou não o uso do canvas, mas faça o contrario do tutorial, crie uma pasta direto no disco C, onde fica a pasta "Users" e "Windows" e instale a Íris lá, de resto siga o tutorial da #260, **SEM PULAR NADA**.

**Comment by zyereon** [comment]
> > ![BB07EB48-051E-4E98-8829-86D60A276217](https://user-images.githubusercontent.com/69636320/134530088-8cbc2a26-119a-4c8c-9a43-574290f86645.jpeg)
> > simplesmente da esse erro
> 
> Seu nome de usuario tem acentos, não estou muito certo sobre isso atrapalhar ou não o uso do canvas, mas faça o contrario do tutorial, crie uma pasta direto no disco C, onde fica a pasta "Users" e "Windows" e instale a Íris lá, de resto siga o tutorial da #260, **SEM PULAR NADA**.

Deu certo man, muito obrigado
