### ISSUE TITLE
error comando nh

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#291]
![image](https://user-images.githubusercontent.com/79427063/134616085-08c5d024-8cf2-4775-91fb-58d045df9665.png)

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/79427063/134616085-08c5d024-8cf2-4775-91fb-58d045df9665.png)
> 

Na linha [234](https://github.com/KillovSky/iris/blob/main/lib/lang/pt.js#L234) da `pt.js`, mude todos os `.join(...)` para `.toString()` e teste, mas - basicamente, a pesquisa não encontrou resultados.
