### ISSUE TITLE
welcome error

### ISSUE THREAD

**Issue by marru453** [KillovSky/iris#292]
cuando meto alguien el bot no le manda el mensaje y tampoco lo menciona:
es.js

> `exports.welcome = () => { return `
    😈🍋 ⃢⃞⃝꧁ℒ𝒾𝓂ℴ𝓃𝒸𝒾𝓁𝓁ℴ🍋 ⃢⃞⃝꧂😈

🍋 !𝚃𝙴 𝙳Á 𝙻𝙰 𝙱𝙸𝙴𝙽𝚅𝙴𝙽𝙸𝙳𝙰 𝙰𝙻 𝙶𝚁𝚄𝙿𝙾¡ 🍋
"@${event.who.replace('@c.us','')}"

🥵 𝙿𝚞𝚎𝚍𝚎𝚜 𝚎𝚡𝚙𝚛𝚎𝚜𝚊𝚛 𝚝𝚞𝚜 𝚋𝚞𝚎𝚗𝚘𝚜 𝚍𝚎𝚜𝚎𝚘𝚜 𝚌𝚘𝚗 𝚖𝚞𝚌𝚑𝚊𝚜 𝚙𝚊𝚕𝚊𝚋𝚛𝚊𝚜, 𝚙𝚎𝚛𝚘 𝚞𝚗𝚊 𝚍𝚎 𝚕𝚊𝚜 𝚖á𝚜 𝚒𝚖𝚙𝚘𝚛𝚝𝚊𝚗𝚝𝚎𝚜 𝚎𝚜 !𝚋𝚒𝚎𝚗𝚟𝚎𝚗𝚒𝚍𝚘¡ 🥵

• * 𝑬𝒏 𝒆𝒔𝒕𝒆 𝑮𝒓𝒖𝒑𝒐 𝒃𝒖𝒔𝒄𝒂𝒎𝒐𝒔 𝒑𝒆𝒓𝒔𝒐𝒏𝒂𝒔 𝒑𝒂𝒓𝒂 𝒉𝒂𝒄𝒆𝒓 𝒂𝒎𝒊𝒔𝒕𝒂𝒅𝒆𝒔 𝒑𝒂𝒓𝒂 𝒇𝒐𝒓𝒎𝒂𝒓 𝒖𝒏𝒂 𝑮𝒓𝒂𝒏 𝑭𝒂𝒎𝒊𝒍𝒊𝒂 𝒕𝒐𝒅𝒐𝒔 𝒋𝒖𝒏𝒕𝒐𝒔 𝒚 𝒑𝒂𝒔𝒂𝒓𝒍𝒐 𝒈𝒆𝒏𝒊𝒂𝒍 𝒆𝒏𝒕𝒓𝒆 𝒕𝒐𝒅𝒐𝒔 𝒚 𝒅𝒊𝒔𝒇𝒓𝒖𝒕𝒂𝒓 𝒅𝒆 𝒍𝒂𝒔 𝑨𝒄𝒕𝒊𝒗𝒊𝒅𝒂𝒅𝒆𝒔.* ☑️

⚫ 𝑶𝑩𝑳𝑰𝑮𝑨𝑻𝑶𝑹𝑰𝑶 ⚫
➳ ℕ𝕠𝕞𝕓𝕣𝕖 𝕪 𝔼𝕕𝕒𝕕.
➳ ℙ𝕒𝕚𝕤 𝕪 𝔽𝕠𝕥𝕠 𝕆𝕡𝕔𝕚𝕠𝕟𝕒𝕝.

🍋🔥 𝑵𝑶𝑹𝑴𝑨𝑻𝑰𝑽𝑨𝑺 🔥🍋

⚠️ ¡𝐒𝐢 𝐢𝐧𝐜𝐥𝐮𝐦𝐩𝐥𝐞𝐬 𝐥𝐚𝐬 𝐧𝐨𝐫𝐦𝐚𝐬, 𝐓𝐞 𝐕𝐚𝐬 𝐅𝐮𝐞𝐫𝐚!
⚠️ ¡𝐒𝐢 𝐩𝐚𝐬𝐚𝐬 𝐜𝐨𝐧𝐭𝐞𝐧𝐢𝐝𝐨 𝐢𝐧𝐚𝐝𝐞𝐜𝐮𝐚𝐝𝐨, 𝐓𝐞 𝐕𝐚𝐬 𝐅𝐮𝐞𝐫𝐚!
⚠️ ¡𝐒𝐢 𝐦𝐨𝐥𝐞𝐬𝐭𝐚𝐬 𝐚 𝐜𝐮𝐚𝐥𝐪𝐮𝐢𝐞𝐫𝐚, 𝐓𝐞 𝐕𝐚𝐬 𝐅𝐮𝐞𝐫𝐚!
⚠️ ¡𝐋𝐚 𝐏𝐫𝐨𝐭𝐞𝐜𝐜𝐢𝐨́𝐧 𝐜𝐨𝐧𝐭𝐫𝐚 𝐄𝐧𝐥𝐚𝐜𝐞𝐬 𝐝𝐞 𝐖𝐡𝐚𝐭𝐬𝐀𝐩𝐩, 𝐞𝐬𝐭𝐚𝐫𝐚́ 𝐬𝐢𝐞𝐦𝐩𝐫𝐞 𝐚𝐜𝐭𝐢𝐯𝐚𝐝𝐚!
⚠️ ¡𝐋𝐚 𝐏𝐫𝐨𝐭𝐞𝐜𝐜𝐢𝐨́𝐧 𝐜𝐨𝐧𝐭𝐫𝐚 𝐄𝐧𝐥𝐚𝐜𝐞𝐬 𝐝𝐞 𝐈𝐧𝐬𝐭𝐚𝐠𝐫𝐚𝐦, 𝐞𝐬𝐭𝐚𝐫𝐚́ 𝐬𝐢𝐞𝐦𝐩𝐫𝐞 𝐚𝐜𝐭𝐢𝐯𝐚𝐝𝐚!

🍋 ¡𝑬𝑺𝑷𝑬𝑹𝑶 𝑸𝑼𝑬 𝑫𝑰𝑺𝑭𝑹𝑼𝑻𝑬𝑺 𝒀 𝑪𝑶𝑵𝑶𝒁𝑪𝑨𝑺 𝑨 𝑮𝑬𝑵𝑻𝑬! 🍋

🛡️𝑷𝑹𝑶𝑻𝑬𝑪𝑻𝑰𝑶𝑵 𝑩𝒀 𝑳𝑰𝑴𝑶𝑵𝑪𝑰𝑶𝑺🛡️
𝑩𝒚 ⃢⃞⃝꧁ℒ𝒾𝓂ℴ𝓃𝒸𝒾𝓁𝓁ℴ🍋 ⃢⃞⃝꧂` }`

index.js

>`if (event.chat == 'Tu id de grupo') {
     return await kill.sendTextWithMentions(event.chat, `Su mesaje + @${event.who.replace('@c.us','')}`)
}`

**Comment by KillovSky** [comment]
Cuando te hice el código `if` que quería insertar en `index.js` y no en `es.js`, si quieres usar **variables** en `es.js` tienes que **exportar** entre paréntesis obviamente.

```javascript
exports.nome = (var1, var2...) => { return `message ${var1} ${var2}` }
```

Y en el `if`, **NO ES SOLO COPIAR**, debes ingresar tu **ID de grupo** y terminar de construirlo.

```javascript
// EXEMPLO ; EJEMPLO ; EXAMPLE 

if (event.chat == '625382726373-62538372@g.us') {
       return await kill.sendTextWithMentions(event.chat, `Hola @${event.who.replace('@c.us', '')}`)
}

```

Hice un teste y está funcionando, si no te funciona de nuevo, verifique si escribió algo incorrectamente, tenga en cuenta que un solo punto puede causar un error gigante.

Y nunca olvide mostrar su terminal de PC.

**Comment by marru453** [comment]
![IMG_20210926_130128](https://user-images.githubusercontent.com/89472552/134896771-e0720f09-ec9d-4587-b223-1a9d411b3aa5.jpg)

**Comment by KillovSky** [comment]
Tienes que inserar al `@`.

Sigue las instrucciones sin errores, hice una prueba de nuevo y esta me está funcionando ok.

**Comment by marru453** [comment]
@KillovSky  sigue sin funcionar

**Comment by KillovSky** [comment]
> @KillovSky  sigue sin funcionar 

muy extraño, hice exactamente lo que está en la instrucción? Si es así, muestre VIA SCREENSHOT su código COMPLETO.

Pero estoy absolutamente seguro de que el código que pasé funciona, porque lo uso y estoy haciendo muy pruebas, verifique si no está insertando todo en el lugar equivocado.

**Comment by marru453** [comment]
@KillovSky 

> codigo: index.js
`// Configuração do welcome
	kill.onGlobalParticipantsChanged(async (event) => {
		const functions = JSON.parse(fs.readFileSync('./lib/config/Gerais/functions.json'))
		const welcmsg = JSON.parse(fs.readFileSync('./lib/config/Gerais/greetings.json'))
		const numebot = await kill.getHostNumber() + '@c.us'
		const isMyBot = event.who.includes(numebot)
		const isWelkom = functions[0].welcome.includes(event.chat)
		const isFake = functions[0].fake.includes(event.chat)
		const fake = event.who.startsWith(config.DDI)
		const isAnti = functions[0].anti.includes(event.chat)
		const fuck = functions[0].blacklist.includes(event.who)
		const eChat = await kill.getContact(event.who)
		let { pushname, verifiedName, formattedName } = eChat
		pushname = pushname || verifiedName || formattedName
		const gChat = await kill.getChatById(event.chat)
		const { contact, groupMetadata, name } = gChat
		try {
			if (event.action == 'add') {
				if (isAnti && fuck && !isMyBot) {
					await kill.sendText(event.chat, mylang(config.Language).entrace())
					await sleep(2000)
					await kill.removeParticipant(event.chat, event.who)
					await kill.contactBlock(event.who) // Evita ser travado por putinhos
					console.log(color('[BLACKLIST]', 'red'), color(`${pushname} - (${event.who.replace('@c.us', '')}) foi banido do ${name} por ter sido colocado na blacklist...`, 'yellow'))
				} else if (isFake && !fake && !isMyBot) {
					await kill.sendTextWithMentions(event.chat, mylang(config.Language).nofake(event))
					await sleep(4000) // Anti-fake e Black-List não tem anti-flood por segurança, use a var welcOn para inserir
					await kill.removeParticipant(event.chat, event.who)
					await kill.contactBlock(event.who) // Evita ser travado por putinhos
					console.log(color('[FAKE]', 'red'), color(`${pushname} - (${event.who.replace('@c.us', '')}) foi banido do ${name} por usar número falso ou ser de fora do país...`, 'yellow'))
				} else if (isWelkom && !isMyBot && welcOn == 0 && !fuck && fake) {
					welcOn = 1;var onlyThis = 0
                    if (event.chat == '631110323-631110323@g.us') {
                    return await kill.sendTextWithMentions(event.chat, `@${persomention} - @${event.who.replace('@c.us', '')}`)}
					for (let o = 0; o < welcmsg.length; o++) { if (Object.keys(welcmsg[o]).includes(event.chat)) { Object.keys(welcmsg[o]).forEach(async (i) => { await kill.sendText(event.chat, welcmsg[o][i]) });onlyThis = 1;break } }
					if (onlyThis == 1) { console.log(color('[ENTROU]', 'red'), color(`${pushname} - (${event.who.replace('@c.us', '')}) entrou no grupo ${name}...`, 'yellow'));return onlyThis = 0 }
					var profile = await kill.getProfilePicFromServer(event.who)
					if (profile == '' || profile == undefined) profile = 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTQcODjk7AcA4wb_9OLzoeAdpGwmkJqOYxEBA&usqp=CAU'
					const welcomer = await new canvas.Welcome().setUsername(pushname).setDiscriminator(event.who.substring(6, 10)).setMemberCount(groupMetadata.participants.length).setGuildName(name).setAvatar(profile).setText("title", `BEM VINDO`).setText("message", `VOCÊ ESTÁ NO {server}`).setText("member-count", `VOCÊ É O MEMBRO N° {count}`).setColor('border', '#00100C').setColor('username-box', '#00100C').setColor('discriminator-box', '#00100C').setColor('message-box', '#00100C').setColor('title', '#6577AF').setOpacity("username-box", 0.6).setOpacity("discriminator-box", 0.6).setOpacity("message-box", 0.6).setOpacity("border", 0.4).setBackground('https://images.wallpaperscraft.com/image/landscape_art_road_127350_1280x720.jpg').toAttachment()
					await kill.sendFile(event.chat, `data:image/png;base64,${welcomer.toBuffer().toString('base64')}`, 'welcome.png', mylang(config.Language).welcome(pushname, name))
					await kill.sendPtt(event.chat, 'https://www.myinstants.com/media/sounds/welcome-mercador-resident-evil-4.mp3')
					welcOn = 0
					console.log(color('[ENTROU]', 'red'), color(`${pushname} - (${event.who.replace('@c.us', '')}) entrou no grupo ${name}...`, 'yellow'))
				}
			} else if (event.action == 'remove' && isWelkom && !isMyBot && abayo == 0 && !fuck && fake) {
				abayo = 1
				var profile = await kill.getProfilePicFromServer(event.who)
				if (profile == '' || profile == undefined) profile = 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTQcODjk7AcA4wb_9OLzoeAdpGwmkJqOYxEBA&usqp=CAU'
				const bye = await new canvas.Goodbye().setUsername(pushname).setDiscriminator(event.who.substring(6, 10)).setMemberCount(groupMetadata.participants.length).setGuildName(name).setAvatar(profile).setText("title", `ADEUS`).setText("message", `SAIU DO {server}`).setText("member-count", `ELE FOI O MEMBRO N° {count}`).setColor('border', '#00100C').setColor('username-box', '#00100C').setColor('discriminator-box', '#00100C').setColor('message-box', '#00100C').setColor('title', '#6577AF').setOpacity("username-box", 0.6).setOpacity("discriminator-box", 0.6).setOpacity("message-box", 0.6).setOpacity("border", 0.4).setBackground('https://images.wallpaperscraft.com/image/landscape_art_road_127350_1280x720.jpg').toAttachment()
				await kill.sendFile(event.chat, `data:image/png;base64,${bye.toBuffer().toString('base64')}`, 'welcome.png', mylang(config.Language).bye(pushname))
				await kill.sendPtt(event.chat, 'https://media1.vocaroo.com/mp3/1aNWZ9vQa2CT')
				abayo = 0
				console.log(color('[SAIU/BAN]', 'red'), color(`${pushname} - (${event.who.replace('@c.us', '')}) saiu ou foi banido do grupo ${name}...`, 'yellow'))
			}
		} catch (err) { console.log(err);welcOn = 0;abayo = 0 }
	})`

> codigo: es.js
`exports.welcome = (persomention) => { return `
    😈🍋 ⃢⃞⃝꧁ℒ𝒾𝓂ℴ𝓃𝒸𝒾𝓁𝓁ℴ🍋 ⃢⃞⃝꧂😈

🍋 !𝚃𝙴 𝙳Á 𝙻𝙰 𝙱𝙸𝙴𝙽𝚅𝙴𝙽𝙸𝙳𝙰 𝙰𝙻 𝙶𝚁𝚄𝙿𝙾¡ 🍋
"${persomention}"

🥵 𝙿𝚞𝚎𝚍𝚎𝚜 𝚎𝚡𝚙𝚛𝚎𝚜𝚊𝚛 𝚝𝚞𝚜 𝚋𝚞𝚎𝚗𝚘𝚜 𝚍𝚎𝚜𝚎𝚘𝚜 𝚌𝚘𝚗 𝚖𝚞𝚌𝚑𝚊𝚜 𝚙𝚊𝚕𝚊𝚋𝚛𝚊𝚜, 𝚙𝚎𝚛𝚘 𝚞𝚗𝚊 𝚍𝚎 𝚕𝚊𝚜 𝚖á𝚜 𝚒𝚖𝚙𝚘𝚛𝚝𝚊𝚗𝚝𝚎𝚜 𝚎𝚜 !𝚋𝚒𝚎𝚗𝚟𝚎𝚗𝚒𝚍𝚘¡ 🥵

• * 𝑬𝒏 𝒆𝒔𝒕𝒆 𝑮𝒓𝒖𝒑𝒐 𝒃𝒖𝒔𝒄𝒂𝒎𝒐𝒔 𝒑𝒆𝒓𝒔𝒐𝒏𝒂𝒔 𝒑𝒂𝒓𝒂 𝒉𝒂𝒄𝒆𝒓 𝒂𝒎𝒊𝒔𝒕𝒂𝒅𝒆𝒔 𝒑𝒂𝒓𝒂 𝒇𝒐𝒓𝒎𝒂𝒓 𝒖𝒏𝒂 𝑮𝒓𝒂𝒏 𝑭𝒂𝒎𝒊𝒍𝒊𝒂 𝒕𝒐𝒅𝒐𝒔 𝒋𝒖𝒏𝒕𝒐𝒔 𝒚 𝒑𝒂𝒔𝒂𝒓𝒍𝒐 𝒈𝒆𝒏𝒊𝒂𝒍 𝒆𝒏𝒕𝒓𝒆 𝒕𝒐𝒅𝒐𝒔 𝒚 𝒅𝒊𝒔𝒇𝒓𝒖𝒕𝒂𝒓 𝒅𝒆 𝒍𝒂𝒔 𝑨𝒄𝒕𝒊𝒗𝒊𝒅𝒂𝒅𝒆𝒔.* ☑️

⚫ 𝑶𝑩𝑳𝑰𝑮𝑨𝑻𝑶𝑹𝑰𝑶 ⚫
➳ ℕ𝕠𝕞𝕓𝕣𝕖 𝕪 𝔼𝕕𝕒𝕕.
➳ ℙ𝕒𝕚𝕤 𝕪 𝔽𝕠𝕥𝕠 𝕆𝕡𝕔𝕚𝕠𝕟𝕒𝕝.

🍋🔥 𝑵𝑶𝑹𝑴𝑨𝑻𝑰𝑽𝑨𝑺 🔥🍋

⚠️ ¡𝐒𝐢 𝐢𝐧𝐜𝐥𝐮𝐦𝐩𝐥𝐞𝐬 𝐥𝐚𝐬 𝐧𝐨𝐫𝐦𝐚𝐬, 𝐓𝐞 𝐕𝐚𝐬 𝐅𝐮𝐞𝐫𝐚!
⚠️ ¡𝐒𝐢 𝐩𝐚𝐬𝐚𝐬 𝐜𝐨𝐧𝐭𝐞𝐧𝐢𝐝𝐨 𝐢𝐧𝐚𝐝𝐞𝐜𝐮𝐚𝐝𝐨, 𝐓𝐞 𝐕𝐚𝐬 𝐅𝐮𝐞𝐫𝐚!
⚠️ ¡𝐒𝐢 𝐦𝐨𝐥𝐞𝐬𝐭𝐚𝐬 𝐚 𝐜𝐮𝐚𝐥𝐪𝐮𝐢𝐞𝐫𝐚, 𝐓𝐞 𝐕𝐚𝐬 𝐅𝐮𝐞𝐫𝐚!
⚠️ ¡𝐋𝐚 𝐏𝐫𝐨𝐭𝐞𝐜𝐜𝐢𝐨́𝐧 𝐜𝐨𝐧𝐭𝐫𝐚 𝐄𝐧𝐥𝐚𝐜𝐞𝐬 𝐝𝐞 𝐖𝐡𝐚𝐭𝐬𝐀𝐩𝐩, 𝐞𝐬𝐭𝐚𝐫𝐚́ 𝐬𝐢𝐞𝐦𝐩𝐫𝐞 𝐚𝐜𝐭𝐢𝐯𝐚𝐝𝐚!
⚠️ ¡𝐋𝐚 𝐏𝐫𝐨𝐭𝐞𝐜𝐜𝐢𝐨́𝐧 𝐜𝐨𝐧𝐭𝐫𝐚 𝐄𝐧𝐥𝐚𝐜𝐞𝐬 𝐝𝐞 𝐈𝐧𝐬𝐭𝐚𝐠𝐫𝐚𝐦, 𝐞𝐬𝐭𝐚𝐫𝐚́ 𝐬𝐢𝐞𝐦𝐩𝐫𝐞 𝐚𝐜𝐭𝐢𝐯𝐚𝐝𝐚!

🍋 ¡𝑬𝑺𝑷𝑬𝑹𝑶 𝑸𝑼𝑬 𝑫𝑰𝑺𝑭𝑹𝑼𝑻𝑬𝑺 𝒀 𝑪𝑶𝑵𝑶𝒁𝑪𝑨𝑺 𝑨 𝑮𝑬𝑵𝑻𝑬! 🍋

🛡️𝑷𝑹𝑶𝑻𝑬𝑪𝑻𝑰𝑶𝑵 𝑩𝒀 𝑳𝑰𝑴𝑶𝑵𝑪𝑰𝑶𝑺🛡️
𝑩𝒚 ⃢⃞⃝꧁ℒ𝒾𝓂ℴ𝓃𝒸𝒾𝓁𝓁ℴ🍋 ⃢⃞⃝꧂` }`

**Comment by KillovSky** [comment]
Te lo dije arriba, **NO COPIE Y PEGUE, NO FUNCIONA ASÍ**, rehaga todo y siga el tutorial correctamente nuevamente.

**NO OLVIDE CAMBIAR GROUPID Y ESTE TIPO DE FUNCIÓN NO UTILIZA EXPORTS**

```javascript
if (event.chat == 'INSERTA SU GROUP ID') {
       await kill.sendText(event.chat, `INSERTA SU MENSAJE`)
}
```

Repitiendo, **NO COPIA**, pega la id con el comando `/id` e termina.

**Comment by marru453** [comment]
@KillovSky  no entiendo nada

**Comment by marru453** [comment]
@KillovSky 
tengo el id del grupo puesto

**Comment by marru453** [comment]
ReferenceError: persomention is not defined
    at C:\Users\Born4Kill\Desktop\pruebaa\index.js:102:76
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by marru453** [comment]
@KillovSky sigo sin entender nada

**Comment by marru453** [comment]
@KillovSky  el mensaje lo tengo  en es.js, quiero usar el exports.welcome en index.js

**Comment by marru453** [comment]
sigue los pasos que me has dicho y lo arregle
