### ISSUE TITLE
Perfil "Falhar Geral"

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#296]
![image](https://user-images.githubusercontent.com/44541791/134769820-33c7a6ea-6738-4824-bdb1-69cc4834c84b.png)

erro autoDestroy?, eu tenho foto zap

**Comment by dodouuglas** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/134769820-33c7a6ea-6738-4824-bdb1-69cc4834c84b.png)
> 
> erro autoDestroy?, eu tenho foto zap

oq e isso? manda print do script

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/134769820-33c7a6ea-6738-4824-bdb1-69cc4834c84b.png)
> 
> erro autoDestroy?, eu tenho foto zap

Bem, claramente você ou algum membro floodou o comando de profile diversas vezes, ou seja, enviaram o comando muitas e muitas vezes sem esperar, por causa disso a Google te deu um block de IP do tradutor, assim, você não consegue usar nenhum comando que use tradução.

Limite seus usuarios (coloque mais tempo de anti-flood, de um sermão, etc) e também não floode comandos, especifiquei isso no menu principal da Íris, qualquer erro sobre a tradução é causada por usos abusivos do comando.

Se não quiser limitar seus membros, apenas retire a tradução das frases na função `translate(...)`.

**Comment by maradona4** [comment]
Entendi,
![image](https://user-images.githubusercontent.com/44541791/134828305-6c8ff4b2-cbbf-44e7-9d38-5ec2d87cb21c.png)

vou tirar "admin e Vip" talvez
