### ISSUE TITLE
alguns grupo manda msg outros nao

### ISSUE THREAD

**Issue by DeyvissonSnuffs** [KillovSky/iris#297]
em alguns grupos o bot respode
em outros ele nao responde
nao apresenta ne um erro

**Comment by DeyvissonSnuffs** [comment]
![image](https://user-images.githubusercontent.com/85204721/134817964-e6f7b01e-e5d9-4781-a331-05acffe8800f.png)

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/85204721/134817964-e6f7b01e-e5d9-4781-a331-05acffe8800f.png)
> 

Verifique se eles não estão mutados e **SEMPRE** atualize os módulos com `npm update`, está ali, `UPDATE AVALIABLE`, se aparecer, atualize, pode ser a correção de problemas que deseja.

**Comment by DeyvissonSnuffs** [comment]
resolvido, algum adm deu /prefix e alterou pro grupo
