### ISSUE TITLE
reinstalei a iris e não esta iniciando

### ISSUE THREAD

**Issue by MatheusOFC** [KillovSky/iris#298]
![error](https://user-images.githubusercontent.com/77314121/134828281-266c0ec0-b551-4b5e-8e07-842cd216f0f8.png)

mensagem de erro que aparece após eu dar 'npm i '

**Comment by KillovSky** [comment]
> ![error](https://user-images.githubusercontent.com/77314121/134828281-266c0ec0-b551-4b5e-8e07-842cd216f0f8.png)
> 
> mensagem de erro que aparece após eu dar 'npm i ' 

Tente com `--force` e tenha absoluta certeza de ter instalado o NodeJS 14 LTS e ativado a opção Node-Tools.

**Comment by MatheusOFC** [comment]
--force n é conhecido como comando interno e a opção node-tools não aparece nada referente a ela na instalação do nodejs e sim instalei a versão 14.17.6

**Comment by MatheusOFC** [comment]
![IMG-20210927-WA0000](https://user-images.githubusercontent.com/77314121/134998644-f2c35422-411c-431b-8fd3-688b0f046ddc.jpg)
 O erro agr mudou e só aparece quando dou npm start

**Comment by KillovSky** [comment]
#290
