### ISSUE TITLE
problema pra rodar

### ISSUE THREAD

**Issue by passokakk** [KillovSky/iris#299]
![imagem_2021-09-27_102530](https://user-images.githubusercontent.com/91476495/134917418-954eb0ad-af0a-4d2e-b9f0-53e0b7ceeb85.png)

um dia ele caiu e nunca mais voltou, erro ao iniciar...

**Comment by KillovSky** [comment]
Atualize a wa-automate.

**"UPDATE AVALIABLE"** significa que você deve rodar `npm update`, creio que isso possa corrigir.

**Comment by passokakk** [comment]
Certo, acho que essa parte do erro resolveu, agora preciso saber como faço para "resetar" o Qrcode e ler ele novamente, pois reinstalei o Wpp do bot e não tem nada conectado no web wpp

**Comment by KillovSky** [comment]
> Certo, acho que essa parte do erro resolveu, agora preciso saber como faço para "resetar" o Qrcode e ler ele novamente, pois reinstalei o Wpp do bot e não tem nada conectado no web wpp

Apague o `iris.data.json`

**Comment by passokakk** [comment]
resolvido com o #260 
valeu @KillovSky e @kewlz
