### ISSUE TITLE
imagem do erl

### ISSUE THREAD

**Issue by kronosmqr** [KillovSky/iris#3]
![Screenshot_20210120-113521_Termux.jpg](https://user-images.githubusercontent.com/77168280/105189396-af63ed80-5b13-11eb-8db1-4eca6697caa2.jpg)

**Comment by KillovSky** [comment]
Olá, ela é um bot de PC apenas, termux não consegue rodar certos comandos,
pois tem comandos que rodam apenas em um computador.

Em qua, 20 de jan de 2021 11:36, kronosmqr <notifications@github.com>
escreveu:

**Comment by KillovSky** [comment]
É um BOT para PC'S em vista do Termux não dar conta de muitos dos comandos.

**Comment by kronosmqr** [comment]
tendi
