### ISSUE TITLE
Não consigo iniciar

### ISSUE THREAD

**Issue by x000x000x000x** [KillovSky/iris#30]
Initializing WA
SyntaxError: Unexpected token e in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/home/angelo/Imagens/iris/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:137:44)
    at step (/home/angelo/Imagens/iris/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:63:23)
    at Object.next (/home/angelo/Imagens/iris/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:44:53)
    at fulfilled (/home/angelo/Imagens/iris/node_modules/@open-wa/wa-automate/dist/controllers/browser.js:35:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Sempre que tento ligar da isso

**Comment by KillovSky** [comment]
Nunca recebi este erro antes, como está escrito que ocorreu na wa-automate, não tenho certeza, mas tente restaurar um dos backups do level e msgcount.
Os Backups são feitos automaticamente usando a pasta lib/config/bot/backup.
Restaure um dos backups (precisa renomear) e teste, se não funcionar experimente desatualizar a wa-automate, caso não funcione volte e me informe que tentarei ajudá-lo a corrigir!

**Comment by x000x000x000x** [comment]
> Nunca recebi este erro antes, como está escrito que ocorreu na wa-automate, não tenho certeza, mas tente restaurar um dos backups do level e msgcount.
> Os Backups são feitos automaticamente usando a pasta lib/config/bot/backup.
> Restaure um dos backups (precisa renomear) e teste, se não funcionar experimente desatualizar a wa-automate, caso não funcione volte e me informe que tentarei ajudá-lo a 



Eu já fiz de tudo, até falei com o suporte do wa-automate e não resolvi 😐

**Comment by KillovSky** [comment]
Fez uma reinstalação de tudo? Inclusive o NodeJS?
Se não, tente reinstalar do zero e verificar, e obs, use a versão LTS da NodeJS.

**Comment by x000x000x000x** [comment]
> Fez uma reinstalação de tudo? Inclusive o NodeJS?
> Se não, tente reinstalar do zero e verificar, e obs, use a versão LTS da NodeJS.

Sim, eu já instalei 3 versões diferentes e continua

**Comment by x000x000x000x** [comment]
As versões antigas do bot funcionava normalmente

**Comment by x000x000x000x** [comment]
Daí quando resolvi atualizar parou de funcionar

**Comment by x000x000x000x** [comment]
> Como você fez a sua atualização?

Eu apaguei o bot antigo e instalei o novo 🤔

**Comment by KillovSky** [comment]
Testei aqui e não obtive erro algum, meio estranho, por hora preciso que me diga essas informações:

- Sua versão da WA-Automate (Mantenha sempre atualizado com ```npm update```)
- Fez alguma edição?
- Sua versão do NodeJS e NPM (```npm -v``` & ```node -v```)
- Seu sistema operacional
- Você fez a instalação do 'chocolatey' na hora de instalar o NodeJS? (É necessário)

E também tente com a options.js antiga abaixo:

[options.zip](https://github.com/KillovSky/iris/files/6516170/options.zip)

**Comment by x000x000x000x** [comment]
O wa-automate tá na versão mais atualizada , não fiz nenhuma edição,a versão do node é a 14 lts e o npm e o 7, 
Eu testei o bot em 2 sistemas o kde neon e o windows nenhum funcionou

**Comment by KillovSky** [comment]
Como o log ali me diz sobre um possui parse do browser, você possui o chrome instalado ai?
E como disse acima, bote essa options.js antiga e remova o uso do chrome apagando a linha useChrome de dentro.

**Comment by KillovSky** [comment]
Como o log ali me diz sobre um erro de parse do browser (falha ao obter algum tipo de JSON dele)\*, você possui o chrome instalado ai?
E como disse acima, bote essa options.js antiga e remova o uso do chrome apagando a linha useChrome de dentro.
Também tente baixar uma Íris muito antiga pelos commits [Aqui](https://github.com/KillovSky/iris/commits)\*.

**Comment by x000x000x000x** [comment]
> Como o log ali me diz sobre um erro de parse do browser (falha ao obter algum tipo de JSON dele)\*, você possui o chrome instalado ai?
> E como disse acima, bote essa options.js antiga e remova o uso do chrome apagando a linha useChrome de dentro.
> Também tente baixar uma Íris muito antiga pelos commits [Aqui](https://github.com/KillovSky/iris/commits)\*.

Sim, eu tenho o Chrome e instalado inclusive já reinstalei 2 vezes, vou tentar fazer isso se funciona eu aviso🤙

**Comment by KillovSky** [comment]
Ok, desejo-lhe sorte com a instalação!
P.S: Por aqui fiz o teste pelo Kali-Linux Weekend e também não obtive erros.
