### ISSUE TITLE
Como instalar NodeJS 14 LTS 

### ISSUE THREAD

**Issue by Diogoramo** [KillovSky/iris#300]

**Comment by KillovSky** [comment]
> 

?

Bem, isso é extremamente facil, é só acessar o site, clicar em LTS, esperar baixar e instalar, uma pesquisada no Google/Bing/DuckDuckGo e você acha isso facil.

[TUTORIAL](https://www.treinaweb.com.br/blog/instalacao-do-node-js-windows-mac-e-linux)
