### ISSUE TITLE
novo comando

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#304]
quero saber como que faz para fazer um comando que tipo eu do /contar id do grupo 5 (minutos) ai o bot pega todas as mensagens nesse periodo e coloca na db tipo o de mensagem apagada cm a data o nome do grupo e id e a pessoa que mandou

**Comment by patulinomods** [comment]
opa meu mano, basicamente nao sei como fazer o sistema de tempo, mas posso fazer onde se caso se estiver ativa essa funçao ele va isalvar em um .txt, se quiser posso fazer

**Comment by KillovSky** [comment]
> quero saber como que faz para fazer um comando que tipo eu do /contar id do grupo 5 (minutos) ai o bot pega todas as mensagens nesse periodo e coloca na db tipo o de mensagem apagada cm a data o nome do grupo e id e a pessoa que mandou 

Deixarei de pedido, pois o sistema disso em si é complexo e a issues se destina a corrigir erros da Íris e não a ensinar a programar/criar códigos para terceiros, então, apenas aguarde o update ou aprenda o meio abaixo.

1 - Crie uma case com base no ativador de `on` e `off`.

2 - Use o `fs.appendFile` da `case 'resposta'` para adicionar as mensagens em um arquivo.

3 - Use a função `setTimeout` no final da case para que a desativação do comando seja automatica.

**Comment by dodouuglas** [comment]
> opa meu mano, basicamente nao sei como fazer o sistema de tempo, mas posso fazer onde se caso se estiver ativa essa funçao ele va isalvar em um .txt, se quiser posso fazer

o de tempo eu sei fala o resto q eu faço kkk
