### ISSUE TITLE
Anti-Flood de Stickers/Mídia [REQUEST]

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#305]
tem como fazer antiflood de mensagens figurinhas etc usando `isFiltered(from)` ?

**Comment by KillovSky** [comment]
Mesma resposta que passei na #304.

**Comment by KillovSky** [comment]
> tem como fazer antiflood de mensagens figurinhas etc usando `isFiltered(from)` ?

Deixarei de request também, pois é complicado esta em si, mas abaixo segue as etapas para fazer.

1 - Crie uma object com key user e valor 0.

2 - Faça a object adicionar +1 no valor.

3 - Use uma function abaixo da object para limpar a cada 10 segundos (mude conforme queira).

4 - Adicione um if acima da object verificando se o valor da key é superior a por exemplo, 7, se sim, faça o sistema de banimento dentro do if ou use return.

Entendeu? Aposto que não, por isso que estou deixando isto de futura request, é algo mais complicado de explicar.

Ref: #304

**Comment by dodouuglas** [comment]
oq eu entendi foi isso mas pode ta completamente errado kkkkkkk
```
var sla = { } + 1
const antiflood = (from) => {
	msg.add(from)
	setTimeout(() => msg.delete(from), Number(config.Anti_Flood * 1000))
}

if(antiflood > 7) {
await kill.removeParticipant(groupId, user)
}
```

**Comment by KillovSky** [comment]
> oq eu entendi foi isso mas pode ta completamente errado kkkkkkk
> ```
> var sla = { } + 1
> const antiflood = (from) => {
> 	msg.add(from)
> 	setTimeout(() => msg.delete(from), Number(config.Anti_Flood * 1000))
> }
> 
> if(antiflood > 7) {
> await kill.removeParticipant(groupId, user)
> }
> ```

É totalmente diferente da ideia funcional que tenho e seu código vai falhar haha
Apenas espere que eu volte a programar e faça a tão demorada atualização.
