### ISSUE TITLE
varios /id en welcome

### ISSUE THREAD

**Issue by marru453** [KillovSky/iris#306]
https://github.com/KillovSky/iris/issues/292#issuecomment-927363479

**Comment by KillovSky** [comment]
> https://github.com/KillovSky/iris/issues/292#issuecomment-927363479

`event.chat == 'ID 1' || event.chat == 'ID 2'`

`||` significa 'eso o', con eso puedes usar múltiplas ids.

Sugiero estudiar NodeJs ya que esto es cuestión es la interpretación básica de código, si no sabes cómo resolver esto, que es relativamente uno de los más simples, se recomienda aprender desde cero para tener el conocimiento y evitar preguntas con respuestas largas en tiempo, además, aprender a programar puede conseguirle trabajos y esta página de iris no es para enseñanzas de programación.
