### ISSUE TITLE
Erro ao iniciar...

### ISSUE THREAD

**Issue by KingBot422** [KillovSky/iris#307]
O bot ao iniciar da um erro... Havia um erro anterior em um arquivo corrompido do XP mas já resolvido.... Logo em seguida iniciei normalmente o QR code foi gerado... Mas logo depois deu o seguinte erro:![20210928_153455.jpg](https://user-images.githubusercontent.com/88904502/135153007-28f90b8d-0f7b-4568-bf0e-988729c1ea84.jpg)

**Comment by Diogoramo** [comment]
Mesma coisa mano se conseguiu resolver em ???

**Comment by KingBot422** [comment]
> Mesma coisa mano se conseguiu resolver em ???

Ainda não amigo

**Comment by KillovSky** [comment]
#248

O problema está detalhado na sua tela.

`EADDRINUSE = ENDEREÇO (IP) EM USO`

Significa que a sua localhost já está sendo usada como um servidor, acontece bastante em VPS.
