### ISSUE TITLE
Auto desligamento

### ISSUE THREAD

**Issue by patulinomods** [KillovSky/iris#308]
Ola rei **Lucas R**!

vim lhe reportar um erro onde a iris auto desligou, e quendo estou dando _npm start_ ou _node index.js_ a iris nao inicia! print abaixo: 

![image](https://user-images.githubusercontent.com/73912095/135171651-05fb7a2a-ab15-407c-b5a1-6d1711d296b7.png)
![image](https://camo.githubusercontent.com/71b837571c48af3aa60a73dbc9d5936aa359d78efbfa8a6743cbbbc16b80ef4d/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3830353930323039333930363630383138362f3830353931333937323533353539303932322f74656e6f722e676966)

Se puder responder o mais rapido possivel iria ajudar muito

**Comment by KillovSky** [comment]
> Ola rei **Lucas R**!
> 
> vim lhe reportar um erro onde a iris auto desligou, e quendo estou dando _npm start_ ou _node index.js_ a iris nao inicia! print abaixo: 
> 
> ![image](https://user-images.githubusercontent.com/73912095/135171651-05fb7a2a-ab15-407c-b5a1-6d1711d296b7.png)
> ![image](https://camo.githubusercontent.com/71b837571c48af3aa60a73dbc9d5936aa359d78efbfa8a6743cbbbc16b80ef4d/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3830353930323039333930363630383138362f3830353931333937323533353539303932322f74656e6f722e676966)
> 
> Se puder responder o mais rapido possivel iria ajudar muito
> 

Erro de permissão, significa que a Íris não conseguiu acessar o arquivo de logs pois ele precisava ser aberto como administrador, mas como a Íris não foi aberta como administrador entao ela não poderá abrir, mova ela para a area de trabalho que deve funcionar com ou sem admin.
