### ISSUE TITLE
cmd /rank

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#309]
Como tirar TAG: 8926

![image](https://user-images.githubusercontent.com/44541791/135179556-39d94e72-bd90-49fd-8fd1-16c711413ec6.png)

**Comment by KillovSky** [comment]
Apague a `.setDiscriminator(...)`.

**Comment by maradona4** [comment]
![image](https://user-images.githubusercontent.com/44541791/135186735-93b04a26-94cf-40b3-99f2-dc27c2d31276.png)

"missing'

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/135186735-93b04a26-94cf-40b3-99f2-dc27c2d31276.png)
> 
> "missing'

Ah...crap.

Teste com os valores a seguir:

`null`

`' '`

Caso falhe ainda assim, significa que é necessario inserir um número ali.

(E claro, deixar o valor "1" pode levar as pessoas a acharem que estão em primeiro no ranking (sem olha-lo), com isso a moral delas pode crescer e incitar elas a serem mais ativas)

**Comment by maradona4** [comment]
Entendi
