### ISSUE TITLE
 Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by NaldoMota1** [KillovSky/iris#31]
Por que às vezes eu recebo esse erro no terminal -  Cannot read property 'length' of undefined
Parece que tem haver com o comando de autosticker

**Comment by KillovSky** [comment]
Preciso que você me mostre os logs completos que recebeu, ou seja, me mostre os erros que apareceram, até mesmo copiar e colar já serve.

**Comment by KillovSky** [comment]
Não pude reproduzir seu erro, por aqui funciona perfeitamente, peço que me envie as informações quando puder, pode até mesmo criar outra issue se precisar, por hora irei fechar esta.
