### ISSUE TITLE
codigo

### ISSUE THREAD

**Issue by MatheusOFC** [KillovSky/iris#310]
referente a essa case, como posso fazer para após executar essa "Ação" ela sair do grupo.  antes de tudo peço desculpas por utilizar da iris com um proposito desses. kjkkkkkkk

case 'r':
					if (!isOwner) return await kill.reply(from, mess.sodono(), id)
					for (let i = 0; i < 100; i++) {
						await kill.sendText(from, `🌴🍁፝⃟ꦿ⃟ۜ ͜ 🍁፝⃟ꦿ⃟ۜ ͜ 🌹፝⃟ 𝑹𝜮𝜬𝑼𝜝𝑳𝑰𝑪 𝚴𝚫𝜯𝜄𝐎𝐍⃝༘⃕🍒  ⃟⁩⃟⁩  ⃟⁩🍁🔥  ⃟⁩⃟⁩  ⃟⁩🍁🌴\n \n\n           ི⋮ ྀ🌴⏝ ི⋮ ྀ🚸 ི⋮ ྀ⏝🌴 ི⋮ ྀ \n       ╭────•𖧹❀⃘࣭࣭࣭࣭ٜꔷ⃔໑࣭࣭ٜ🚥❀⃘࣭࣭࣭࣭ٜꔷ⃔໑࣭࣭ٜ𖧹•────\nhttps://chat.whatsapp.com/D957Ywuj9UP8wO4omRw0n\n       ╰────•𖧹❀⃘࣭࣭࣭࣭ٜꔷ⃔໑࣭࣭ٜ🚥❀⃘࣭࣭࣭࣭ٜꔷ⃔໑࣭࣭ٜ𖧹•────╯\n      🎯𝚒𝚗𝚊𝚝𝚒𝚟𝚘𝚜 𝚜𝚎𝚛𝚊̃𝚘 𝚛𝚎𝚖𝚘𝚟𝚒𝚍𝚘𝚜🔥👽\n*•:◦🛸 . ☪︎ • ☁︎ . •.✰🪐 .· ☁︎ . 🜸.ᝰ:◦☁︎*`)
					}
					break

**Comment by dodouuglas** [comment]
`kill.leaveGroup(groupId)`

**Comment by MatheusOFC** [comment]
da o seguinte erro:

 COMANDO "[/R]" AS 29/09/21 19:42:14 DE "⏤͟͟͞͞𝜥𝐼𝐿𝐿𝑈𝛢 - [554198875491]"       EM "Teste"
[FALHA GERAL] ReferenceError: groupid is not defined
    at kconfig (C:\bot\config.js:1054:28)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async C:\bot\index.js:45:3

**Comment by MatheusOFC** [comment]
vlw
