### ISSUE TITLE
Cmd Banir

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#313]
Como eu quero /banir on 5541 Teste

Ex: Motivo: Teste

![image](https://user-images.githubusercontent.com/44541791/135394445-3b7a7d61-9a59-456c-b5bc-3670e0041eed.png)

Ex:
Sua Conta Foi Banido(a)
DDD: 5541...
Motivo: Teste

**Comment by KillovSky** [comment]
Não sei para que isso seria útil e não entendi o que você deseja construir, de toda forma houve mudanças sobre a issues.

Sobre seu código, não vejo problemas, apenas o separe usando o `arg.split('|')[...]`.

#316

**Comment by maradona4** [comment]
Entendi, eu acho aquele  comandos /mymsg 

acho pastar custom, "nota": cmd /perfil, talvez vou fazer
