### ISSUE TITLE
Duvida para criar comando

### ISSUE THREAD

**Issue by EmanuelPeixoto** [KillovSky/iris#314]
Tem como criar um comando que pega fotos aleatórias e manda, mas apenas fotos que selecionei, tipo um /dog mas com as fotos que quero, mas aleatório, não me importo que seja armazenado no meu pc ou na nuvem.

**Comment by dodouuglas** [comment]
voce pode pegar de exemplo esse aqui e so mudar o comando e o link e so ir no google e pesquisar as apis das fts que vc quer
```
case 'dog':
				if (side == 1) {
					const list = await axios.get('http://shibe.online/api/shibes')
					await kill.sendFileFromUrl(from, list.data[0], '', '🐕', id)
				} else if (side == 2) {
					const doug = await axios.get('https://nekos.life/api/v2/img/woof')
					await kill.sendFileFromUrl(from, doug.data.url, '', '🐕', id)
				}
				break
```

**Comment by EmanuelPeixoto** [comment]
Mas eu queria usar as fotos que tenho aqui, não queria pegar da internet, tem como?

**Comment by KillovSky** [comment]
Aleatorize elas criando uma variavel com os nomes e usando em um `math random`.

#316
Marquei como um possivel novo sistema de fotos locais.
