### ISSUE TITLE
FreeFire Id

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#317]
FreeFire id
![image](https://user-images.githubusercontent.com/44541791/135524945-c4ec7295-cf48-4627-a04c-340c2f1176e2.png)

cmd 
![image](https://user-images.githubusercontent.com/44541791/135525018-49b2c68e-9f05-40ca-b79b-27c403d000ac.png)

Whatsapp
![image](https://user-images.githubusercontent.com/44541791/135525097-59e7f22f-4880-4e15-aa4a-9ac6ec78ee23.png)
Você talvez não tenha um arquivo .....

**Comment by KillovSky** [comment]
> FreeFire id
> ![image](https://user-images.githubusercontent.com/44541791/135524945-c4ec7295-cf48-4627-a04c-340c2f1176e2.png)
> 
> cmd 
> ![image](https://user-images.githubusercontent.com/44541791/135525018-49b2c68e-9f05-40ca-b79b-27c403d000ac.png)
> 
> Whatsapp
> ![image](https://user-images.githubusercontent.com/44541791/135525097-59e7f22f-4880-4e15-aa4a-9ac6ec78ee23.png)
> Você talvez não tenha um arquivo .....

Não existe foto para enviar ai, você está usando `kill.sendFileFromUrl` ou algo assim, use `kill.sendText`.

#316 - Leia.
