### ISSUE TITLE
fazer a iris responder sem prefix.

### ISSUE THREAD

**Issue by MatheusOFC** [KillovSky/iris#319]
sim eu sei que #335 e pra isso, mas queria que ela respondesse com mais de uma respostas, ou ate melhor que nao sejam respostas aleatórias.

podia ter algo parecido com o comando speak, no qual ela pega uma resposta coerente com o assunto ''mais ou menos kkk''
e responde

**Comment by dodouuglas** [comment]
![image](https://user-images.githubusercontent.com/79427063/135553126-b5b0f076-996a-4a1b-982b-9292c7d69d6f.png)
tem sim 
```
if (!isFiltered(from) && !isMedia && !isCmd) { try { if (chats.includes('bom dia')) await kill.reply(from, 'bom dia', id) } catch (error) { return console.log(error) } }
```
voce pode usar includes q se a palavra tiver "bom dia por ex ele responde" ou voce pode usar toLowerCase() que a palavra tem que tar exatamente do jeito que voce escreveu

**Comment by KillovSky** [comment]
Você realmente quer inserir o servidor simsimi a qualquer mensagem? Isso vai dar sobrecarga, de toda forma, construi aleatorio por segurança, mesmo que insira o simsimi, depois de uns 3 minutos ele te dará block de IP e as respostas aleatorias serão utilizadas.
Se quer que ela responda duas vezes, crie outra `kill.reply`, se quer outro sistema de if, duplique a lonha 319 e edite-a.
