### ISSUE TITLE
Auto Sticker

### ISSUE THREAD

**Issue by anonimo850** [KillovSky/iris#321]
Alguma forma de Corrigir o Auto sticker? Ativa de boas Mas nao Funciona

**Comment by PedroBatistop** [comment]
Preciso de mais informações para reproduzir e/ou checar as razões pelas quais o comando não funciona. Aparece alguma mensagem de erro no console e/ou no whatsapp? Você alterou o código original da íris?

**Comment by anonimo850** [comment]
> Preciso de mais informações para reproduzir e/ou checar as razões pelas quais o comando não funciona. Aparece alguma mensagem de erro no console e/ou no whatsapp? Você alterou o código original da íris?

Tipo eu ativo o Auto Sticker, mas ele nao envia nada automatico, Pelo oq entendi do comando ele envia figurinhas fotos videos etc

**Comment by KillovSky** [comment]
> > Preciso de mais informações para reproduzir e/ou checar as razões pelas quais o comando não funciona. Aparece alguma mensagem de erro no console e/ou no whatsapp? Você alterou o código original da íris?
> 
> Tipo eu ativo o Auto Sticker, mas ele nao envia nada automatico, Pelo oq entendi do comando ele envia figurinhas fotos videos etc

Ele é um comando voltado a transformar fotos e videos em stickers sem precisar usar os comandos, depois de ativar ele, basta enviar as imagens sem nada escrito nelas.

Esse comando **NÃO ENVIA STICKERS DO NADA**, ou seja, ele não pega algo aleatorio do google e te envia, ele converte o que você envia em stickers.
