### ISSUE TITLE
Como arrumar o comando image

### ISSUE THREAD

**Issue by MatheusOFC** [KillovSky/iris#322]
A api da URL  desse comando não funfa mais, tem outra que posso colocar no lugar?

**Comment by PedroBatistop** [comment]
Eu fiz um código que usa a API do Google para mandar as imagens, com isso o comando image nunca mais cai, mas para isso é preciso ter uma conta na Google cloud. É preciso colocar um cartão de crédito na criação da conta do Google cloud, mas fiquei tranquilo, pois o cartão de crédito é só para checar a veracidade da sua conta, nenhuma valor será descontado do cartão a menos que você permita. Se você puder fazer uma conta no Google cloud me avisa que te passo o código.

**Comment by KillovSky** [comment]
> A api da URL  desse comando não funfa mais, tem outra que posso colocar no lugar?

No momento não uma API, mas "estou" trabalhando em um sistema de imagens sem limite ou api's, se quer fixar isso rapido, procure por algum servidor como o `pixabay` ou módulo no site da `npmjs`.

**Comment by MatheusOFC** [comment]
@PedroBatistop poderia me chamar no whats??
se  55 41 98875491
