### ISSUE TITLE
Bot se responder

### ISSUE THREAD

**Issue by patulinomods** [KillovSky/iris#323]
Ola querido criador dessa bela obra de arte chamada de **[iris](https://github.com/KillovSky/iris)** , eu novamente aki para tirar uma simples duvida sobre a **[iris](https://github.com/KillovSky/iris)** , minha duvida nesse momento e se da para o sistema se auto responder, simplificando , eu no whatsapp do/ da bot , eu mandar um comando e o sistema ler a mensagem pelo numero do bot e se responder,

Explicando de outra maneira, o bot mandar /ping ( exemplo ), e ele ler co comando que ele mesmo manou e se responder

**Comment by dodouuglas** [comment]
> Ola querido criador dessa bela obra de arte chamada de **[iris](https://github.com/KillovSky/iris)** , eu novamente aki para tirar uma simples duvida sobre a **[iris](https://github.com/KillovSky/iris)** , minha duvida nesse momento e se da para o sistema se auto responder, simplificando , eu no whatsapp do/ da bot , eu mandar um comando e o sistema ler a mensagem pelo numero do bot e se responder,
> 
> Explicando de outra maneira, o bot mandar /ping ( exemplo ), e ele ler co comando que ele mesmo manou e se responder

tendi nd

**Comment by KillovSky** [comment]
> Ola querido criador dessa bela obra de arte chamada de **[iris](https://github.com/KillovSky/iris)** , eu novamente aki para tirar uma simples duvida sobre a **[iris](https://github.com/KillovSky/iris)** , minha duvida nesse momento e se da para o sistema se auto responder, simplificando , eu no whatsapp do/ da bot , eu mandar um comando e o sistema ler a mensagem pelo numero do bot e se responder,
> 
> Explicando de outra maneira, o bot mandar /ping ( exemplo ), e ele ler co comando que ele mesmo manou e se responder

#123
