### ISSUE TITLE
@open-wa/wa-automate

### ISSUE THREAD

**Issue by luc070801** [KillovSky/iris#324]
me ajude estou tendo esse erro @open-wa/wa-automate

**Comment by dodouuglas** [comment]
> me ajude estou tendo esse erro @open-wa/wa-automate

tem qual erro? tem como mandar print?

**Comment by luc070801** [comment]
![config json - iris-main - Visual Studio Code 01_10_2021 22_13_02](https://user-images.githubusercontent.com/91641605/135699311-f5df8b50-3dba-47a2-a192-ca14377a69a6.png)

**Comment by luc070801** [comment]
segui atentamente copiando igualmente tudo ensinado no tutorial do 
JogaCom Bisgos porem na hora que dei o start da esse erro e sou totalmente iniciante em linguagem de programacao e nao consigo saber qual e esse erro

**Comment by dodouuglas** [comment]
> segui atentamente copiando igualmente tudo ensinado no tutorial do JogaCom Bisgos porem na hora que dei o start da esse erro e sou totalmente iniciante em linguagem de programacao e nao consigo saber qual e esse erro

da npm i primeiro

**Comment by luc070801** [comment]
deu o mesmo erro. Obrigado pela ajuda mais vou desistir de rodar esse projeto

**Comment by KillovSky** [comment]
Preciso saber qual sua versão do NodeJs, forneça a maior quantidade que puder de informações, e claro, ja tentou instalar na area de trabalho e pelo cmd vez do visual code?

**Comment by KillovSky** [comment]
Estou transferindo o suporte do problema para a issue #327.
Continue com os detalhes por lá.
