### ISSUE TITLE
Erro no /flip coroa ou cara

### ISSUE THREAD

**Issue by prokda** [KillovSky/iris#325]
O servidor que envia a figurinha de cara e coroa caiu, agora o comando não está funcionando mais.
Qual outro jeito pro comando voltar a funcionar?

![error flip](https://user-images.githubusercontent.com/79275944/135702943-480f0103-5b09-4bcb-aa7b-9a4498aad2b8.png)

**Comment by KillovSky** [comment]
> O servidor que envia a figurinha de cara e coroa caiu, agora o comando não está funcionando mais.
> Qual outro jeito pro comando voltar a funcionar?
> 
> ![error flip](https://user-images.githubusercontent.com/79275944/135702943-480f0103-5b09-4bcb-aa7b-9a4498aad2b8.png)
> 
> 
> 

Esse erro é causado por um uso **EXTREMAMENTE ABUSIVO** do comando, apenas espere e controle seus usuarios para que não ocorra de novo quando voltar.
