### ISSUE TITLE
cmd /broad

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#326]
![image](https://user-images.githubusercontent.com/44541791/135704417-8c052911-701a-4643-9964-fe5284875023.png)

Como anunciar Transmissão  'image'?

/broad -image -all ?
assim

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/135704417-8c052911-701a-4643-9964-fe5284875023.png)
> 
> Como anunciar Transmissão  'image'?
> 
> /broad -image -all ?
> assim

Basta marcar uma imagem, video, documento, audio ou qualquer coisa com o comando.
Se houver uma midia marcada, a Íris vai entender e enviar ela junto.

**Comment by maradona4** [comment]
Entendi
