### ISSUE TITLE
erro no /play

### ISSUE THREAD

**Issue by MatheusSan03** [KillovSky/iris#329]
![image](https://user-images.githubusercontent.com/78276706/135728525-6457363a-0f35-4e46-99f6-d2b8b51e14c4.png)

acontece esse erro no /play

**Comment by xinarai123** [comment]
atualize teu navegador e veja se funciona, apos isso se quiser vai na config.js e troque seu user agent ( pesquise no chorome my user agent)

**Comment by PedroBatistop** [comment]
#331
