### ISSUE TITLE
Problema com alguns comandos 

### ISSUE THREAD

**Issue by zyereon** [KillovSky/iris#330]
![7FA69F02-0793-40A2-8BE1-EEB937557138](https://user-images.githubusercontent.com/69636320/135730440-6bb5ae0a-4286-43f6-8f45-d07168a3863a.jpeg)

Bot estava funcionando normalmente, até que começou a dar esse erro há algumas horas atrás, e parou de funcionar o comando /sticker dando erro no mesmo e em outros comandos

**Comment by DeyvissonSnuffs** [comment]
npm i --save @open-wa/wa-automate@latest
npm i --force

digite isso antes de iniciar o terminal

**Comment by zyereon** [comment]
> npm i --save @open-wa/wa-automate@latest npm i --force
> 
> digite isso antes de iniciar o terminal

Fiz esse processo e continua com o msm erro

**Comment by PedroBatistop** [comment]
#331
