### ISSUE TITLE
Erro ao fazer qualquer comando

### ISSUE THREAD

**Issue by herberth25** [KillovSky/iris#331]
wve
![1633208049475](https://user-images.githubusercontent.com/91803269/135731537-158528c1-2e0a-47d9-b4f1-761a002c94e9.jpg)

eu faço qualquer comando, e simplesmente aparece esse erro... alguém sabe oq eu posso fazer?

**Comment by xinarai123** [comment]
tente atualizar teu navegador e avise se resolveu...

**Comment by herberth25** [comment]
> tente atualizar teu navegador e avise se resolveu...

infelizmente não mano, atualizei o chrome mas continua da mesma forma.

tava normal até hoje a tarde, aí começaram a floodar em um grupo, e agora ele está assim. qualquer comando que execulto, aparece esse erro :(

**Comment by xinarai123** [comment]
> uer comando que executo, aparece esse erro :(

no pv vai de boa?, vai na config.s e troca o user agente pra ver se resolve ( pra ver qual o teu e so pesquisar no chorome my user agent), se nao resolver tente apagar a pasta node-modules e o arquivo package-lock.json apos isso de npm install, npm update e npm start pra ver se resolveu

**Comment by herberth25** [comment]
> > uer comando que executo, aparece esse erro :(
> 
> no pv vai de boa?, vai na config.s e troca o user agente pra ver se resolve ( pra ver qual o teu e so pesquisar no chorome my user agent), se nao resolver tente apagar a pasta node-modules e o arquivo package-lock.json apos isso de npm install, npm update e npm start pra ver se resolveu

no pv n vai tambem, e não deu certo mano :(

**Comment by PedroBatistop** [comment]
> wve ![1633208049475](https://user-images.githubusercontent.com/91803269/135731537-158528c1-2e0a-47d9-b4f1-761a002c94e9.jpg)
> 
> eu faço qualquer comando, e simplesmente aparece esse erro... alguém sabe oq eu posso fazer?

Isso acontece devido a um pequeno erro no WA AUTOMATE espere algumas horas que tudo voltará ao normal. Não esqueça de manter seus módulos atualizados com npm update.

**Comment by PedroBatistop** [comment]
O problema cidade devido a um pequeno erro no "kill.reply", que como eu te disse logo será resolvido pela equipe do WA AUTOMATE. Uma dica não oficial que eu posso te dar é para trocar todos os "kill.reply" para "kill.sendText", claro, se você souber fazer isso, até que o problema esteja resolvido.

**Comment by KillovSky** [comment]
Basta esperarem correção por parte da wa-automate, pela xx vez, **NÃO É PROBLEMA DE PROGRAMAÇÃO DA ÍRIS, ISSO É DEVIDO A UM BUG NO WHATSAPP WEB E É NECESSARIO ESPERAR A OPEN-WA TENTAR CORRIGIR OU NÃO, NÃO HÁ NADA QUE EU E OS OUTROS COLABORADORES DA ÍRIS POSSAMOS FAZER ALÉM DE DAR UMA SOLUÇÃO TEMPORARIA.**

Solução:

Baixe `NotePad++` (procure google) ou qualquer programa que permita substituir tudo de uma vez.

Faça um backup dos arquivos ou seja, crie copias deles pra caso der problema e para reverter quando o update estiver ok.

Procure por localizar e substituir (Control + F).

Digite `kill.reply` em localizar.

Digite `kill.sendText` em substituir.

Clique em **SUBSTITUIR TUDO**.

**Você pode sair para testar já, a parte abaixo é para corrigir problemas mais serios, tenha em mente que isso pode quebrar alguns comandos mas corrigir os que não estão funcionando.**

Continuando...

Apague os quadrados e insira `, id)` em localizar.

Insira `)` em substituir, e clique em **SUBSTITUIR TUDO**.

O formato final deve estar assim.

`await kill.sendText(from, •••)`

Para evitar que os noobs novatos se confundam, **NÃO PRECISA COLOCAR •••, É UM EXEMPLO**.

Após isso salve e inicie.

**NÃO ABRA ISSUES COM REFERENCIA A ESSA SOLUÇÃO OU PROBLEMA, SE DER ERROS COMO POR EXEMPLO, CARACTERES EM FALTA, BASTA IR ATÉ A LINHA E CORRIGIR MANUALMENTE**.

No Linux você pode usar o `NotePadQQ` (procure google), ou usar o comando `sed`.

`sed -i 's/reply/sendText/g'` por exemplo, ou seja...

`sed -i 's/Palavrs_Para_Localizar/Palavra_Para_Substituir/g'`.
