### ISSUE TITLE
Saiu do Grupos

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#332]
Pessoa que ele saiu grupos, contato salvo level.json, como remover automaticamente a conta level.json ? ou ele não tem uma conta, level.json registrado?

cmd /ranking, deu puts... utrapassa 10....

contato banido ou saiu

**Comment by KillovSky** [comment]
Descreva melhor seu problema pois dessa forma é "impossivel" entender.
Mas se entendi algo, você quer resetar o XP quando alguem sair?
Refaça o sistema da #293 na `index.js`.
E **LEMBRE-SE QUE NÃO FORNECEMOS MAIS CÓDIGOS** -> #316

**Comment by KillovSky** [comment]
> Pessoa que ele saiu grupos, contato salvo level.json, como remover automaticamente a conta level.json ? ou ele não tem uma conta, level.json registrado?
> 
> cmd /ranking, deu puts... utrapassa 10....
> 
> contato banido ou saiu

Descreva melhor seu problema pois dessa forma é "impossivel" entender.
Mas se entendi algo, você quer resetar o XP quando alguem sair?
Refaça o sistema da #293 na `index.js`, na `goodbye`.*
E **LEMBRE-SE QUE EU NÃO FORNEÇO AJUDA A PEDIDOS DESTE TIPO DESDE A** -> #316

**Comment by maradona4** [comment]
Ok
