### ISSUE TITLE
cpf

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#333]
quero saber como q faz para ele tirar print da tela e mandar

**Comment by KillovSky** [comment]
Leia, qualquer pagina de programação no google possui instruções disto.

https://digitalinnovation.one/artigos/extraindo-dados-de-sites-com-puppeteer-javascript-web-scrapping

#316

**Comment by dodouuglas** [comment]
> Leia, qualquer pagina de programação no google possui instruções disto.
> 
> https://digitalinnovation.one/artigos/extraindo-dados-de-sites-com-puppeteer-javascript-web-scrapping
> 
> #316
> 
> `await page.screenshot(.....)`

ja conseguir
