### ISSUE TITLE
error error error

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#336]
o bot ta dando error em tudo 
![image](https://user-images.githubusercontent.com/79427063/135764389-cced005f-bf54-4fa4-b811-7c9116c290d7.png)

**Comment by maradona4** [comment]
Eu tmb, aparece "id" sempre erro

acabei fazer npm update, sem erro meu pc console log

**Comment by KillovSky** [comment]
#329
#330
#331
#337

Não é bug na programação da Íris, portanto, **NÃO TEM NADA QUE POSSAMOS FAZER, AGUARDE UM UPDATE DA WA-AUTOMATE**.
