### ISSUE TITLE
error /play 

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#337]
Deu msg "Puts utrapassa"

![image](https://user-images.githubusercontent.com/44541791/135764980-d21b32e0-2141-4b22-9e46-3440f3eb40a5.png)

Erro code
 TypeError: _0x2d79c6[(_0x2f1340(...) + _0x2f1340(...) + "es")]
 
 ja existe npm update, mas continuar error

**Comment by maradona4** [comment]
Esse mesmo igual #329

**Comment by KillovSky** [comment]
**A resposta continua a mesma**, não é um bug de responsabilidade dos dev's da Íris, apenas aguarde uma correção da wa-automate ou tire a `kill.sendLinkWithAutoPreview`.
