### ISSUE TITLE
Erro comandos

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#338]
![image](https://user-images.githubusercontent.com/44541791/135878597-66a62244-6b06-4712-b8e7-2d09418ea682.png)

Porque Falhar ao iniciado, meus comandos normais sem erro
já teste npm update, vezes

**Comment by KillovSky** [comment]
#336

**Comment by maradona4** [comment]
Vish, tem como marcar pessoa "ID" ? 

SendText nao tem marcar pessoa?
