### ISSUE TITLE
Chrome nao carregando

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#339]
![image](https://user-images.githubusercontent.com/44541791/135890802-10b6296c-58ec-46c8-a8a2-cb50d8f7ecea.png)

Não é possível acessar esse site? whastapp fora do ar?

**Comment by dodouuglas** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/135890802-10b6296c-58ec-46c8-a8a2-cb50d8f7ecea.png)
> 
> Não é possível acessar esse site? whastapp fora do ar?

sim, wpp insta e face

**Comment by maradona4** [comment]
Agr Voltou, kkkk
