### ISSUE TITLE
Shutdown ou Page Crash

### ISSUE THREAD

**Issue by turtleSP** [KillovSky/iris#34]
Depois de ligar o bot e passados algumas 2h ~ 3h o bot dá crash ou shutdown na consola
Não tem nenhum script para dar npm start automático quando ele fecha o nodejs?

**Comment by KillovSky** [comment]
Preciso que me mostre o seu terminal quando isso ocorrer, se for somente uma mensagem sem quaisquer logs de erros se torna um tanto difícil saber a causa, mas experimente fazer um teste com o módulo PM, ele auto reinicia sua BOT após certo tempo.

**Comment by turtleSP** [comment]
Como posso testar esse módulo PM
![Uploading Screenshot_1.png…]()

**Comment by turtleSP** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/84879009/119814483-5a315180-bee2-11eb-819d-cc81c3e4f438.png)

**Comment by KillovSky** [comment]
Pode ser que o Linux esteja matando o navegador, você está usando Chrome?

Se não, instale-o e teste.

Já para o caso do PM2, primeiro instale ele com `npm i` .

```npm i pm2 --g```

Depois rode:

```pm2 start index.js```
```pm2 monit```

Isso faz com que caso seu BOT obtenha erros, o PM2 reinicie ele automaticamente.

**Comment by KillovSky** [comment]
Irei encerrar por aqui pois causei um erro opcional semelhante fechando o processo com o task manager e o PM2 funcionou perfeitamente, se ainda tiver erros peço que abra uma nova issue, sinta-se a vontade para comentar mais nesta também.
