### ISSUE TITLE
canvas mensagem de boas vindas

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#340]
quando alguem entra nesse grupo ele da erro, eu testei em outro e foi d boa 
![image](https://user-images.githubusercontent.com/79427063/135946958-d3c882c4-f632-4b09-883b-d2ff18670b13.png)

**Comment by KillovSky** [comment]
> quando alguem entra nesse grupo ele da erro, eu testei em outro e foi d boa 
> ![image](https://user-images.githubusercontent.com/79427063/135946958-d3c882c4-f632-4b09-883b-d2ff18670b13.png)
> 

404 é um erro bem especifico e vago ao mesmo tempo.

Está dizendo que não encontrou o servidor, portanto, pode ser referente a queda das redes sociais.

Ainda acontece agora que elas voltaram?

Faça um teste depois de limpar o PC com `CCleaner` e apagar a pasta `Logs` - Faça isso com a Íris desligada!
