### ISSUE TITLE
problema na instalação dos modulos e inicialização do bot

### ISSUE THREAD

**Issue by SrWalker7** [KillovSky/iris#344]
já fiz tudo que ta na #327 e nada.

![iris](https://user-images.githubusercontent.com/90977277/136500388-db8126ff-e368-4162-8477-cc279d08c3ab.PNG)
![iris2](https://user-images.githubusercontent.com/90977277/136500393-e254c709-5caf-4b71-bb13-6f5e638e038e.PNG)

**Comment by SrWalker7** [comment]
Nada ainda.

**Comment by KillovSky** [comment]
> Nada ainda.
> 

Já tentou instalar na area de trabalho? Em muitas issues notei que sempre instalam direto na raiz, o que é um problema relativamente grave, devido as permissões em alguns computadores.
Se não der, siga a dica do Douglas acima.
