### ISSUE TITLE
Figurinhas Automatico

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#345]
![image](https://user-images.githubusercontent.com/44541791/136632729-c5ffee47-7c3e-49a0-9fae-f158736bd742.png)

pq ele(a) mandar todo hora stickers?

![image](https://user-images.githubusercontent.com/44541791/136632751-2b19ff03-243b-46b8-a0f6-60be222d9254.png)

**Comment by KillovSky** [comment]
Hmmm, isso não me acontece aqui, você fez alguma edição relacionada aos stickers?

De toda forma, como eu ja disse em centenas de issues, os "bugs" podem estar relacionados a infinitos problemas, não dá pra eu advinhar - ~~Não sem os sistemas de espionagem da Íris e.e~~ - o que aconteceu sem uma boa lista de detalhes de como você executa a Íris, por isso, não esqueça - novamente - de inserir tudo que puder.

(Exemplos: Quais comandos relacionados a sticker você ativou? - Você fez edições? - Você floodou a Íris? - etc...)

Mas minha teoria é que a Íris detectou alguma coisa como midia no seu grupo (que possivelmente possui auto-sticker ligado), tentou converter em sticker MP4, mas ficou muito pesado (ou deu invalido) e a wa-automate enviou esse no lugar do video.

De qualquer forma, não tenho a minima ideia de como corrigir, pois nunca me ocorreu, faltam informações na sua issue e por fim, o código **normalmente** não permite que isso ocorra, exceto se for como eu descrevi na teoria, é a unica forma que me vem em mente.
