### ISSUE TITLE
[RELOAD]

### ISSUE THREAD

**Issue by zyereon** [KillovSky/iris#349]
![D5ECC710-119D-4B6A-A923-0580CF256F1E](https://user-images.githubusercontent.com/69636320/136659332-d0451d45-50b6-497a-a578-4ffbbd7bd5f8.jpeg)

O bot ontem parou de funcionar alguns comandos, como o /kick e /steal, que o mesmo diz “marque a pessoa desejada” e outros como o /play, no gitbash começou a dar problema de “[RELOAD] isso pode ser ignorado - TIMEOUT e dps CONNECTED, como resolver ?

**Comment by KillovSky** [comment]
> 
> ![D5ECC710-119D-4B6A-A923-0580CF256F1E](https://user-images.githubusercontent.com/69636320/136659332-d0451d45-50b6-497a-a578-4ffbbd7bd5f8.jpeg)
> 
> O bot ontem parou de funcionar alguns comandos, como o /kick e /steal, que o mesmo diz “marque a pessoa desejada” e outros como o /play, no gitbash começou a dar problema de “[RELOAD] isso pode ser ignorado - TIMEOUT e dps CONNECTED, como resolver ?

Reinicie ele e tente rodar o comando marcando com @, além disso, fique atento a updates da wa-automate (rodar `npm update` uma vez por dia), ela estar atualizada é essencial para os comandos.

**Comment by KillovSky** [comment]
Acontece somente com você ou consegue roubar outras pessoas?
Fez alguma edição?
Já tentou tirar a Íris do grupo, limpar as mensagens e colocar ela de novo?
Funciona em outros grupos?
Está usando um WhatsApp modificado?

De toda forma, responda as perguntas e tente limpar o PC com `CCleaner`, apagar a pasta `logs`, rodar `npm cache clean --force`, depois usar `npm update --force` e iniciar a Íris após limpar o WhatsApp no celular, também tire as permissões da Íris em ler os contatos, camera, etc.
