### ISSUE TITLE
Navegador

### ISSUE THREAD

**Issue by Nhamin** [KillovSky/iris#35]
opa eu instalei a iris no pc, mas eu queria usar ela com outro navegador que não seja o google, como poderia prosseguir com isso?, já que o chrome puxa muito aqui para mim '-'

**Comment by KillovSky** [comment]
Você pode usar o puppeteer com o Firefox e todos os navegadores baseados no chromium, embora não recomendado, o chrome é útil para o funcionamento de muitos comandos como o de envio de vídeos.

Para configurar um navegador, insira isso na sua `options.js`, que está dentro da pasta `lib`, você deve inserir isso antes de `chromiumArgs`.

```executablePath: 'local_do_navegador',```

Um exemplo usando o `Microsoft Edge` no Windows seria:

```executablePath: 'C:\\Users\\KillovSky\\AppData\\Local\\Microsoft\\Edge SxS\\Application\\msedge.exe',```

Mas não confie cegamente nesse exemplo, verifique primeiro a localização do seu navegador antes de inserir o seu local.
