### ISSUE TITLE
Não realizei nenhuma alteração, porém quando inicializo, ou tento, ele apresenta a msg:

### ISSUE THREAD

**Issue by dypblue** [KillovSky/iris#352]
Não realizei nenhuma alteração, porém quando inicializo, ou tento, ele apresenta a msg: 
You have used the useChrome (--use-chrome) config option. In order to improve startup time please use "executablePath": "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" to save a few seconds on next startup.

Como resolvo?

_Originally posted by @dypblue in https://github.com/KillovSky/iris/discussions/348_

**Comment by KillovSky** [comment]
Você não possui chrome instalado?
Se tem Chrome, abra a `functions.js` e insira isso dentro da options, acima da `useChrome`...

```javascript
executablePath: "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
```

Se caso seu Chrome esteja instalado em outro local, apenas mude o endereço dentro das aspas.
Caso falhe, troque as barras por barras duplas.
`C:\ -> C:\\`

**Comment by dypblue** [comment]
Agora ele chega no QR lê mas nao continua o processo, mesmo alterando o arquivo para vincular a outro cel.

**Comment by dypblue** [comment]
Reinstalei tudo. Mudei a pasta. Agora aparece isso.
![image](https://user-images.githubusercontent.com/72712203/137579960-8c501b02-02b1-45a6-a3be-7788b6276981.png)

**Comment by KillovSky** [comment]
> Reinstalei tudo. Mudei a pasta. Agora aparece isso.
> ![image](https://user-images.githubusercontent.com/72712203/137579960-8c501b02-02b1-45a6-a3be-7788b6276981.png)
> 

Instalar em outro HD com arquitetura diferente da do Windows pode causar isso.
Instale na area de trabalho e evite colocar em pastas com nomes que tem espaços ou acentos.
