### ISSUE TITLE
killua aqui

### ISSUE THREAD

**Issue by MatheusOFC** [KillovSky/iris#353]
como posso fazer pro ''antiFlood'' dar ban ao invez de ignorar e nao so dar ban em flood de cmnds mas tbm em mensagens normais.

aproveitando a pergunta se eu coloca Await kill.contactBlock(user) antes do } ,na parte de "Mensagens no pv" ele da block ?

**Comment by KillovSky** [comment]
Apenas insira `kill.removeParticipant(...)` dentro do `if` do **ANTI-FLOOD**.

Sim, se inserir isso dentro do `if`, ele dará block.

Tenha em mente que eu e os colaboradores da Íris não daremos suporte a pedidos de códigos ou códigos não projetados por nós, desde a #316.
