### ISSUE TITLE
como faz login ?

### ISSUE THREAD

**Issue by Projectwolfdevs** [KillovSky/iris#355]
BOMBER-API
НОМЕР
ПОВТОРОВ

**Comment by KillovSky** [comment]
> BOMBER-API
> НОМЕР
> ПОВТОРОВ
> 

Isso poderia ser facilmente decifrado utilizando um **TRADUTOR**.

De toda forma, `НОМЕР` é número em russo, ou seja, é onde insere um alvo.

`ПОВТОРОВ` é repetições, ou seja, quantidade de ataques.

E `Bomber` eu nem preciso explicar.

Leia a página inicial da Íris, se ficar pular os tutoriais e avisos, **você pode estar perdendo a sua alma :)** [Ehehehe](https://github.com/KillovSky/iris/blob/main/config.js#L17)
