### ISSUE TITLE
Erro no Youtube.Dl

### ISSUE THREAD

**Issue by LukasJaSc** [KillovSky/iris#359]
Opa Lucas, antes de ontem eu fui iniciar a bot e por algum motivo tá dando erro no console ao iniciar ela, dizendo que é o "youtube-dl-exec' e "python >= 2" (no caso a versão), ele tenta ler a pasta do youtube-dl-exec porém ela não existe, até desinstalei a pasta dela e instalei novamente achando que era erro na versão da íris. Da uma olhada pra mim no link do print em baixo :)

Obs: Não fiz nenhum tipo de alteração nos códigos e comandos, eu simplesmente reiniciei o meu PC e quando tentei, deu esse erro.

https://user-images.githubusercontent.com/92343590/136870104-27f36ec5-dff6-427f-88a1-73b6e397629f.png

**Comment by xinarai123** [comment]
nao sei se funciona mas tente a-pagar a pasta logs, node_modules e o arquivo package-lock.json, apos isso rode o comando npm install , npm update e por garantia npm i youtube-dl-exec e tente iniciar a iris novamente....

**Comment by LukasJaSc** [comment]
Então eu fiz exatamente o que tu pediu e deu o mesmo erro, apaguei as pastas e rodei os comandos mas não consegui rodar de novo :(
