### ISSUE TITLE
problemas no anti-porn

### ISSUE THREAD

**Issue by MatheusOFC** [KillovSky/iris#364]
![Captura de tela 2021-10-17 175328](https://user-images.githubusercontent.com/77314121/137644618-0a5e7e84-ecc9-44d4-9c08-3c5184df601d.png)

sempre que mandam alguma foto/video aparece esse erro.

ja tentei fazer o que foi indicado na #219 mas não funcionou. 

erro começou aparecer após ativar antiporn, msm o desativando o erro continua.

**Comment by KillovSky** [comment]
Verifique se o arquivo `functions.json` da pasta `lib/config/Gerais` não corrompeu.
Modelo padrão:

```JSON
[{"anti":[],"silence":[],"antilinks":[],"antiporn":[],"antitrava":[],"blacklist":[],"fake":[],"pt":[],"es":[],"en":[],"nsfw":[],"sticker":[],"welcome":[],"xp":[],"thieves":[],"companions":[]}]
```

**Comment by MatheusOFC** [comment]
n nao corrompeu, como disse ja fiz o que disse no #219
