### ISSUE TITLE
baixar imagem

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#365]
quero saber como q faz para fazer o bot baixar imagem quando alguem da um comando junto com a imagem ou marcando ela ai ele baixa a imagem com o nome o numero da pessoa igual o de musica pra eu fazer um comando pra pegar o texto que ta escrito na ft e mandar

**Comment by KillovSky** [comment]
[DecryptMedia](https://docs.openwa.dev/pages/How%20to/decrypt-media.html).

**Comment by KillovSky** [comment]
> quero saber como q faz para fazer o bot baixar imagem quando alguem da um comando junto com a imagem ou marcando ela ai ele baixa a imagem com o nome o numero da pessoa igual o de musica pra eu fazer um comando pra pegar o texto que ta escrito na ft e mandar

[DecryptMedia](https://docs.openwa.dev/pages/How%20to/decrypt-media.html)
