### ISSUE TITLE
Gostaria de saber como usar alguns comandos que da erro.

### ISSUE THREAD

**Issue by Gabrielxsousa** [KillovSky/iris#366]
![WhatsApp Image 2021-10-18 at 09 55 44](https://user-images.githubusercontent.com/89111352/137735068-440d5bc2-15cb-4663-88cb-6fc545f4d520.jpeg)
Gostaria de saber o porque quando ou usar o /Ghost, /Bomb, entre outros não funciona,.. 
Obrigado pela atenção.

**Comment by KillovSky** [comment]
> ![WhatsApp Image 2021-10-18 at 09 55 44](https://user-images.githubusercontent.com/89111352/137735068-440d5bc2-15cb-4663-88cb-6fc545f4d520.jpeg)
> Gostaria de saber o porque quando ou usar o /Ghost, /Bomb, entre outros não funciona,.. 
> Obrigado pela atenção.

Estão marcados como futuros updates, até lá é necessario esperar.

Sobre o Bomb, ele funciona, ele apenas não envia mensagens dizendo que funcionou, mas ele iniciou e está funcionando de fundo.
