### ISSUE TITLE
bug com ranking

### ISSUE THREAD

**Issue by lonnykkkj** [KillovSky/iris#37]
opa, eu de novo, enfim quando eu dava /ranking antigamente ele aparecia o nick da pessoa no whatsapp e agora eu dou /ranking e dá o wa.me/+55xxxx da pessoa, como eu poderia arrumar isso? se tiver como, pq eu procurei no pt.js e nao achei nada parecido, caso possa me ajudar vlw ai mano, se n der tudo bem, ah e no /level também aparece o número, no level nao me importo muito porém no ranking é do que mais preciso agora

**Comment by KillovSky** [comment]
Ah, isso é um sistema de "segurança" pra impedir que o comando tenha erros! Ou seja, quando ela vai adquirir o seu nome, pode ocorrer daquele nome ser ilegível ou algo assim, portanto, caso a Íris obtenha erros lendo o nome da pessoa, ela automaticamente insere o wa me em vez do nome para que o comando não obtenha erros.

**Comment by lonnykkkj** [comment]
ata é pq em todos do ranking tá assim, mas muitas pessoas usam nick normal sem letra mod, o emoji conta como isso? pq antes mostrava até letra modificada e com simbolos especiais, agr não mais

**Comment by KillovSky** [comment]
Entendo, um pouco estranho mas de uma coisa tenho certeza, isso ocorre pois ela não conseguiu adquirir o nome do player.

**Comment by lonnykkkj** [comment]
será q n tem como tirar essa segurança?

**Comment by KillovSky** [comment]
Não é nada recomendável, pode fazer sua BOT sofrer um erro e parar de funcionar, mas se quiser, você deve abrir a `config.js` e procurar pela case do ranking.

Lá procure e mude a linha `board` de:

 `board += `${i + 1} → *${getTheName}*\n➸ *Mensagens*: ${msgcount[i].msg}\n➸ *XP*: ${nivel[i].xp}\n➸ *Level*: ${nivel[i].level}\n➸ *Patente*: ${role}\n\n` }`

Para:

`board += `${i + 1} → *${aRandNe.pushname}*\n➸ *Mensagens*: ${msgcount[i].msg}\n➸ *XP*: ${nivel[i].xp}\n➸ *Level*: ${nivel[i].level}\n➸ *Patente*: ${role}\n\n` }`

Mas irei advertir novamente, isso **NÃO É RECOMENDÁVEL.**

Quaisquer erros desfaça a modificação o quanto antes para evitar corrupção dos arquivos `Level.json` & `MsgCount.json` além de desligamentos inesperados da Íris.

**Comment by KillovSky** [comment]
Não é nada recomendável, pode fazer sua BOT sofrer um erro e parar de funcionar, mas se quiser, você deve abrir a `config.js` e procurar pela case do ranking.

Lá procure e mude a linha `board` de:

 ```board += `${i + 1} → *${getTheName}*\n➸ *Mensagens*: ${msgcount[i].msg}\n➸ *XP*: ${nivel[i].xp}\n➸ *Level*: ${nivel[i].level}\n➸ *Patente*: ${role}\n\n````

Para:

```board += `${i + 1} → *${aRandNe.pushname}*\n➸ *Mensagens*: ${msgcount[i].msg}\n➸ *XP*: ${nivel[i].xp}\n➸ *Level*: ${nivel[i].level}\n➸ *Patente*: ${role}\n\n````

Mas irei advertir novamente, isso **NÃO É RECOMENDÁVEL.**

Quaisquer erros desfaça a modificação o quanto antes para evitar corrupção dos arquivos `Level.json` & `MsgCount.json` além de desligamentos inesperados da Íris.*
