### ISSUE TITLE
nao ta funcionando a funcao de /welcome 

### ISSUE THREAD

**Issue by pablorere** [KillovSky/iris#373]
![image](https://user-images.githubusercontent.com/65947059/138572288-2ea9c1df-aa9f-4478-a726-f5fe6638c852.png)

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/65947059/138572288-2ea9c1df-aa9f-4478-a726-f5fe6638c852.png)
> 

Não é erro no código da Íris, é por parte da wa-automate, WhatsApp sempre está atualizando o servidor, então espere a wa-automate e rode `npm update` sempre que houver uma versão nova dela, você pode ver se tem reiniciando, aparecera "new update avaliable",  também tem a opção deles fazerem um update por injeção, o que não precisa de atualização, apenas reiniciar a Íris.
Resumindo, espere, rode `npm update` sempre que puder, faça reinicios as vezes e claro, **LEIA AS ISSUES FECHADAS ANTES DE POSTAR UMA NOVA POIS ESSE PROBLEMA JÁ EXISTE!**
