### ISSUE TITLE
blacklist parou de funcionar 

### ISSUE THREAD

**Issue by BruZim03** [KillovSky/iris#379]
Ja tem um tempo que a iris não ta banindo mais quem vai pra blacklist

**Comment by KillovSky** [comment]
Você está com o canvas/módulos atualizado? Ai diz que ele não ta conseguindo acessar o servidor.
Se sim, apague da linha `var profile` até `await kill.sendFile`, isso vai remover o uso do `canvas`.
Teste também sem o welcome e tenha **COMPLETA** certeza de que seus módulos estão atualizados antes disso -> `npm update`.

**Comment by BruZim03** [comment]
bom, agr não está dando nenhum erro, porem continua sem remover o contato :(

e ta tudo atualizado sim

**Comment by KillovSky** [comment]
> bom, agr não está dando nenhum erro, porem continua sem remover o contato :(
> 
> e ta tudo atualizado sim

Tente fazer uma reinstalação.
