### ISSUE TITLE
loop infinito na inicialização

### ISSUE THREAD

**Issue by herberth25** [KillovSky/iris#380]
![1635497858739](https://user-images.githubusercontent.com/91803269/139407051-ffc7fb11-9225-4692-acbe-78781c9c057e.jpg)
fiz o processo do #263 mas não resolveu

**Comment by herberth25** [comment]
e como faço para atualizar?

eu tentei com npm i @open/wa-automate 4.23.6

mas não vai

**Comment by herberth25** [comment]
![1635601663839](https://user-images.githubusercontent.com/91803269/139535424-2816d8ca-89ee-4d24-b8f0-2be018900afe.jpg)

**Comment by KillovSky** [comment]
`npm update`, leia a #377.

**Comment by herberth25** [comment]
f meu bot kkk
