### ISSUE TITLE
Bug Inicialização

### ISSUE THREAD

**Issue by YuriTotoso** [KillovSky/iris#382]
![Captura de tela 2021-10-30 143633](https://user-images.githubusercontent.com/70677666/139543399-2a8b6c6e-c36f-4432-a0e5-f08007d6dda8.png)

**Comment by YuriTotoso** [comment]
Eu desconectei ela do whatsapp, e agora está dando este erro

**Comment by KillovSky** [comment]
Apague a pasta `"Logs"` e tente.

**Comment by YuriTotoso** [comment]
> Apague a pasta `"Logs"` e tente.

Apaguei, agora tá um loop infinito, já atualizei com o npm i e npm update mas só aparece isso: (comentário abaixo)

**Comment by YuriTotoso** [comment]
> Apague a pasta `"Logs"` e tente.

Descobri, é só esperar, ele verifica que n tem autenticação em nenhum ZAP, e manda o qr depois de umas 3h kkkkkkk
