### ISSUE TITLE
Falha no Puppeteer em Windows 

### ISSUE THREAD

**Issue by markoswythor** [KillovSky/iris#383]
Erro apareceu depois de atualizar o node e atualizar a Open-wa, bot fica com instabilidades frequentemente. O erro ainda seria   resolvido desta forma? #370 

**Erro:**
![image](https://user-images.githubusercontent.com/76796419/139562644-f189458b-6fa0-42e6-94d0-588e253ec9f6.png)

**Ultimo erro era:**
_Falha de inicialização do Puppeteer [Browser] em VPS_

**Solução do ultimo erro:**
_Apenas movi da pasta ROOT para HOME_

**Comment by KillovSky** [comment]
Erro de referencia ao p`uppeteer`, se remover a pasta `Logs` e passar um `CCleaner` não ajudar, é um problema com correção por parte da `wa-automate| pois **não é bug por parte do código da Íris.**
