### ISSUE TITLE
sendListMessage

### ISSUE THREAD

**Issue by markoswythor** [KillovSky/iris#384]
boa tarde, sei que não está ajudando no desenvolvimento de códigos mas queria deixar essa issue em aberto para quem **pudesse ajudar**, estou tentando fazer a iris enviar a List Message e digitei os códigos desta forma:

![image](https://user-images.githubusercontent.com/76796419/139727022-3d01b004-4839-4f02-bd67-d439572031f6.png)
 
Se alguém souber o que fiz de errado (a iris não está me enviando e uso o whatsapp normal) e estar podendo ajudar fico grato, já ajuda também outras pessoas que estão tentando adicionar  

no console:
![image](https://user-images.githubusercontent.com/76796419/139728039-2e7f8beb-c0d5-404e-b820-f1e4e4b221d8.png)

**Comment by markoswythor** [comment]
cancela, tem que comprar uma licença para poder usar

**Comment by dodouuglas** [comment]
> cancela, tem que comprar uma licença para poder usar

kkkkkkkkkkkkkk

**Comment by maradona4** [comment]
Ele tava tentando por lista e button mais os desenvolvendores do openwa falaram q tem q pagar ;-;

**Comment by dodouuglas** [comment]
> Ele tava tentando por lista e button mais os desenvolvendores do openwa falaram q tem q pagar ;-;

eu sei kkkk

**Comment by maradona4** [comment]
kkk pois e
