### ISSUE TITLE
cmd /add  error removeParticipants

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#385]
![image](https://user-images.githubusercontent.com/44541791/139827111-1b16148a-b3cf-49d5-a724-56a4a02572ff.png)

code
![image](https://user-images.githubusercontent.com/44541791/139827337-26d98007-d101-4120-9d29-0481264429d8.png)

**Comment by KillovSky** [comment]
O código - aparentemente - não possui erro nenhum, o problema é com o servidor, deve ser resolvido automaticamente após a `Wa-Automate` fazer os novos `patches.json`, arquivo baixado na inicialização, ou uma atualização por parte deles, esteja atento a ambos.
Para baixar os patches, reinicie quando puder.
Para baixar um update, use `npm update`.
