### ISSUE TITLE
Converter MP4>MP3 sem limite

### ISSUE THREAD

**Issue by freitas666** [KillovSky/iris#386]
é possível retirar o limite para download de musicas? Eu digo... gerei um comando que ele baixa do YouTube e converte porém musicas acima de 5 minutos ele não baixa...

Alguma ideia?

**Comment by KillovSky** [comment]
Isso é por que o WhatsApp tem limite de `64 megabytes` para os envios.
Se desejar testar sem limitações, leia a página de configuração [Aqui](https://github.com/KillovSky/iris/blob/main/.readme/pt/config.md).

É estranho pelo `/Play` não possuir limitadores, então considere que pode ser causado pelo limite do WhatsApp.

O limitador seria esse:

```javascript
matchFilter: `filesize < ${Number(config.Download_Size)}M` })
```

Mas ele não está no `/Play` e sim no `/Video`.

Agora se seu código não for o da Íris, não poderei ajudar pois estou apenas oferecendo suporte ao código original - que possui suporte ao que você quer fazer.
