### ISSUE TITLE
erro crash timeout

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#387]
![image](https://user-images.githubusercontent.com/44541791/140383985-67799736-76c3-4554-bde8-e1fe78297df3.png)

deu crash parou?

**Comment by KillovSky** [comment]
Erro sem muita explicação, aparentemente tem relação com servidor do WhatsApp, possivelmente problema de acesso.

De toda forma, não acho que isso ocorra repetidas vezes, se acontecer apenas uma vez, considere que isso é um problema isolado e não bug definitivo, enfim, mantenha sua `Wa-Automate` e o `WhatsApp` atualizados e faça reinicios constantes, além disso, limpe o telefone, PC e o WhatsApp.

**Comment by KillovSky** [comment]
Erro sem muita explicação, aparentemente tem relação com servidor do WhatsApp, possivelmente problema de acesso.

Baseando-se nos nomes das URL's, houve uma desconexão forçada do QR-Code do WhatsApp, dando um problema.

De toda forma, não acho que isso ocorra repetidas vezes, até por que é raro, se acontecer apenas uma vez, considere que isso é um problema isolado e não bug definitivo, enfim, mantenha sua `Wa-Automate` e o `WhatsApp` atualizados e faça reinicios constantes, além disso, limpe o telefone, PC e o WhatsApp e tente não conectar o WhatsApp em diversos locais.

**Comment by maradona4** [comment]
Ok Obg!
