### ISSUE TITLE
Erro no Windows 11 ou outra coisa...

### ISSUE THREAD

**Issue by guicker172** [KillovSky/iris#388]
![image](https://user-images.githubusercontent.com/80110265/140445272-88cdc69d-a1c0-488c-83d0-97f04f001be4.png)
![image](https://user-images.githubusercontent.com/80110265/140445287-7aa86835-8f84-4515-92da-2787eef1c66f.png)
Me ajuda ai pf

**Comment by guicker172** [comment]
obs: ja reinstalei o canvas e o npm nada funcionou

**Comment by KillovSky** [comment]
#215
