### ISSUE TITLE
cmd  /Iris 

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#389]
Problema repsosta automático

![Screenshot_20211106-012713_WhatsApp](https://user-images.githubusercontent.com/44541791/140597822-e3374ca0-2ae0-4215-a49b-6a661ae81c40.jpg)

**Comment by KillovSky** [comment]
Não há nada que eu possa fazer sobre, em vista disto não ser problema na Íris e sim no servidor, mas anotei para tentar fazer um sistema diferente depois.

P.S: Abra a case Íris e terá um `if` que verifica se a resposta está ok, insira essa mensagem ali no `if`, ou quebre o link, ou seja, apague o `await axios.get(...)` e insira `''` ou `null` no seu lugar.
