### ISSUE TITLE
Erro na inicialização

### ISSUE THREAD

**Issue by KingBot422** [KillovSky/iris#391]
Ao dar NPM I e logo em seguida o NPM START
Aparece o seguinte:![20211113_131338.jpg](https://user-images.githubusercontent.com/88904502/141650966-656bff58-2144-4d57-a195-5be59b303b70.jpg)

**Comment by KillovSky** [comment]
Me informe a sua versão do `node` e `npm`, aparentemente você está usando versões muito antigas ou está usando um `node` de arquitetura diferente do sistema.
Por isso, informe aqui e tente atualizar eles.

**Comment by KillovSky** [comment]
> Ao dar NPM I e logo em seguida o NPM START
> Aparece o seguinte:![20211113_131338.jpg](https://user-images.githubusercontent.com/88904502/141650966-656bff58-2144-4d57-a195-5be59b303b70.jpg)

#229

**Comment by KillovSky** [comment]
#229
