### ISSUE TITLE
Erro /level (canvas)

### ISSUE THREAD

**Issue by markoswythor** [KillovSky/iris#392]
quando da /level aparece isso ai e a iris para de funcionar ;-;

![image](https://user-images.githubusercontent.com/76796419/141660296-2c458a6a-4d49-466c-9701-4cdd683e73d4.png)

**Comment by KillovSky** [comment]
Siga o tutorial [daqui](https://github.com/KillovSky/iris/issues/301#issuecomment-931649653) e mude a `const/var` do `case 'level':` que irá funcionar, mas mantenha-se atento ao nome da `const/var`, pode ser diferente.
