### ISSUE TITLE
Cmd /novidades

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#393]
Deu erro função 

'i.replace'

![Screenshot_20211113-233338_WhatsApp](https://user-images.githubusercontent.com/44541791/141665195-d1d14f80-099f-4a2d-a5bb-7e0706e7ab74.jpg)

![image](https://user-images.githubusercontent.com/44541791/141665247-6299b106-2b75-4ebc-bc81-cba2099598b4.png)

**Comment by KillovSky** [comment]
#316

**Comment by GabrielOjea** [comment]
Manda Número, eu ajudou @maradona4

**Comment by maradona4** [comment]
> Manda Número, eu ajudou @maradona4

Id #272 tem número aqui

**Comment by GabrielOjea** [comment]
Blz
