### ISSUE TITLE
Falhar Geral 

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#395]
![image](https://user-images.githubusercontent.com/44541791/142302535-e1f5bc06-ec1d-44bf-a59b-1d310fbf6846.png)

Whastapp comecou ON, digite /menu, depois bot fechou auomatico crash console nodeJS

**Comment by KillovSky** [comment]
Erro referente a `Wa-Automate/Puppeteer`, rodar `npm update` deve resolver.

**Comment by maradona4** [comment]
Sim, mas continuar mesmo

**Comment by markoswythor** [comment]
> Sim, mas continuar mesmo

adiciona isso: multiDevice: true,  na sua functions.js acima do authTimeout: 0,

eu fiz isso eu deu certo que é pra ver se vc está na versão beta ou normal, se vc estiver na normal põe false

**Comment by KillovSky** [comment]
> > Sim, mas continuar mesmo
> 
> adiciona isso: multiDevice: true,  na sua functions.js acima do authTimeout: 0,
> 
> eu fiz isso eu deu certo que é pra ver se vc está na versão beta ou normal, se vc estiver na normal põe false

Se ativar isso, tire o `chromiumArgs` pois ele causa problemas.

**Comment by markoswythor** [comment]
> Se ativar isso, tire o `chromiumArgs` pois ele causa problemas.

O whatsapp e a openwa infelizmente tá forçando a ativação ;-; vários comandos estão problemáticos, fora que essa versão da muito atraso dps q o bot fica mais de 24h ativo
