### ISSUE TITLE
Erro em criar gif

### ISSUE THREAD

**Issue by DeyvissonSnuffs** [KillovSky/iris#399]
![Screenshot_2021-11-22-08-45-39-623_com fmwhatsapp](https://user-images.githubusercontent.com/85204721/142856344-ef98fe11-d06a-4910-b681-80504fc84339.jpg)
![IMG_20211122_084727](https://user-images.githubusercontent.com/85204721/142856460-2b7c6785-af6d-4750-85e1-1d96bbfa9b81.jpg)

**Comment by KillovSky** [comment]
Você instalou os requisitos corretamente e instalou TODOS eles?
