### ISSUE TITLE
Npm install erro

### ISSUE THREAD

**Issue by manokillzero** [KillovSky/iris#400]
esse é meu erro quando dou npm install na iris 
 
 C:\xampp\htdocs>cd iris

C:\xampp\htdocs\iris>npm install
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated brainly-scraper-v2@1.1.2: The latest version is available, immediately update to get the update.
npm WARN deprecated axios@0.20.0: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm ERR! code 1
npm ERR! path C:\xampp\htdocs\iris\node_modules\youtube-dl-exec
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npx bin-version-check-cli python ">=2"
npm ERR! node:internal/modules/cjs/loader:960
npm ERR!   const err = new Error(`Cannot find module '${request}'`);
npm ERR!               ^
npm ERR!
npm ERR! Error: Cannot find module 'C:\Users\manoe\AppData\Local\npm-cache\_npx\7b761a280cf4a94b\node_modules\lines-and-columns\build\index.mjs'
npm ERR!     at createEsmNotFoundErr (node:internal/modules/cjs/loader:960:15)
npm ERR!     at finalizeEsmResolution (node:internal/modules/cjs/loader:953:15)
npm ERR!     at resolveExports (node:internal/modules/cjs/loader:482:14)
npm ERR!     at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:102:18)
npm ERR!     at Object.<anonymous> (C:\Users\manoe\AppData\Local\npm-cache\_npx\7b761a280cf4a94b\node_modules\parse-json\index.js:4:36)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   path: 'C:\\Users\\manoe\\AppData\\Local\\npm-cache\\_npx\\7b761a280cf4a94b\\node_modules\\lines-and-columns\\package.json'
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\manoe\AppData\Local\npm-cache\_logs\2021-11-23T17_27_00_214Z-debug.log

**Comment by KillovSky** [comment]
Rode a instalação na **Área de Trabalho** via CMD e tenha certeza de ter instalado os requisitos da Íris, além disso, instale também `Python` e `Visual C++ Redist AIO`.
Antes de rodar a instalação utilize `npm cache clean --force`, passe `CCleaner` **se quiser** e em seguida rode o `npm i`.

**Comment by manokillzero** [comment]
agora aparece esse erro

C:\Users\manoe\OneDrive\Área de Trabalho\iris>npm install
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated brainly-scraper-v2@1.1.2: The latest version is available, immediately update to get the update.
npm WARN deprecated axios@0.20.0: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm ERR! code 1
npm ERR! path C:\Users\manoe\OneDrive\Área de Trabalho\iris\node_modules\youtube-dl-exec
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npx bin-version-check-cli python ">=2"
npm ERR! node:internal/modules/cjs/loader:960
npm ERR!   const err = new Error(`Cannot find module '${request}'`);
npm ERR!               ^
npm ERR!
npm ERR! Error: Cannot find module 'C:\Users\manoe\AppData\Local\npm-cache\_npx\7b761a280cf4a94b\node_modules\lines-and-columns\build\index.mjs'
npm ERR!     at createEsmNotFoundErr (node:internal/modules/cjs/loader:960:15)
npm ERR!     at finalizeEsmResolution (node:internal/modules/cjs/loader:953:15)
npm ERR!     at resolveExports (node:internal/modules/cjs/loader:482:14)
npm ERR!     at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:102:18)
npm ERR!     at Object.<anonymous> (C:\Users\manoe\AppData\Local\npm-cache\_npx\7b761a280cf4a94b\node_modules\parse-json\index.js:4:36)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   path: 'C:\\Users\\manoe\\AppData\\Local\\npm-cache\\_npx\\7b761a280cf4a94b\\node_modules\\lines-and-columns\\package.json'
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\manoe\AppData\Local\npm-cache\_logs\2021-11-25T17_17_21_999Z-debug.log

**Comment by KillovSky** [comment]
`One Drive com Área de Trabalho`?

Por acaso você criou uma pasta chamada `Área de Trabalho` e está tentando instalar dentro dela?

Se sim, quis dizer para acessar e instalar na pasta `C://Users/(Seu Nome)/Desktop` e não criar uma pasta com o nome.

Tente fazer tudo do zero, ou seja, desinstale e baixe baixe todos os programas corretamente, faça no lugar correto dessa vez e me envie o que aparece ao digitar:

`npm -v`

`node -v`

E também sua versão do Windows e **TODAS** as informações que puder mandar, se for muito grande, insira elas em um `.txt` e anexe em vez de publicar, ecomizaria muito tempo.

Pra finalizar, mande também o arquivo `debug` que aparece no final do erro.

**Comment by lonnykkkj** [comment]
caraca o meu deu o mesmo erro, vou ver se essas explicações me ajudam, se nao eu vou ter que ir pro virtual box mesmo
