### ISSUE TITLE
Melhora na disponibilidade de informações

### ISSUE THREAD

**Issue by VauP** [KillovSky/iris#402]
Acredito que o projeto carece de informações de contato e possibilidades de ajuda por colaboradores.

Além de um link para um grupo do whatsapp (que não está mais funcionando) não há nenhuma outra informação sobre como entrar em contato com o responsável pelo projeto, dificultando assim, a forma de contato.

**Comment by KillovSky** [comment]
É uma boa questão, não estou atualizando tudo de pequenas partes pois estou fazendo uma correção geral simplesmente ENORME.
O link atual é este [aqui](https://bit.ly/BOT-IRIS), você o encontra no meu perfil.

Embora tenha um grupo, sou o unico nele que pode ajudar (embora tenhamos desenvolvedores, sou o criador da Íris e do grupo, então eu sou o unico de lá quem conhece todas as linhas do código), mas como atualmente estou trabalhando e ando ocupado demais, iria ser inconveniente receber mensagens de pedidos, perguntas e outros, pois eu acabaria perdendo - de novo - noticias do trabalho, familia e outros.

Por isso, o suporte por WhatsApp foi encerrado e conta apenas com esta página hoje, sendo o grupo apenas pra quem quer curtir, e o suporte sendo neste repositorio github, assim como milhares de projetos fazem.
