### ISSUE TITLE
falha aleatória

### ISSUE THREAD

**Issue by markoswythor** [KillovSky/iris#403]
tem algo que eu possa fzr, do nada tomo ban quando aparece essa msg
 (do nada mesmo, sem dar nenhum cmd)
 
![image](https://user-images.githubusercontent.com/76796419/143512313-70c4d896-be45-4a80-9dc8-8e6a10dabf27.png)

**Comment by KillovSky** [comment]
Esse erro só acontece quando o ban acontece, pois o sistema leva um erro, geralmente, os banimentos tem haver com usos muito excessivos, isso faz com que o WhatsApp bloqueie o seu IP e impeça criações de novos WhatsApp's com base nele, ou algo assim, para evitar, use moderadamente e quando criar um WhatsApp espere um tempo antes de inserir uma BOT, além disso, use VPN do mesmo país do código de área.
