### ISSUE TITLE
npm install erro

### ISSUE THREAD

**Issue by Willkyz** [KillovSky/iris#406]
poderia me explicar porque esse erro esta acontecendo?

npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated brainly-scraper-v2@1.1.2: The latest version is available, immediately update to get the update.
npm WARN deprecated axios@0.20.0: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm ERR! code 1
npm ERR! path C:\Users\LNV\Downloads\iris-main\node_modules\youtube-dl-exec
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npx bin-version-check-cli python ">=2"
npm ERR! Error: Couldn't find version of `python`
npm ERR!     at binaryVersion (file:///C:/Users/LNV/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version/index.js:55:8)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm ERR!     at async binaryVersionCheck (file:///C:/Users/LNV/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version-check/index.js:14:18)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\LNV\AppData\Local\npm-cache\_logs\2021-11-28T02_28_06_744Z-debug.log
PS C:\Users\LNV\Downloads\iris-main> ^C
PS C:\Users\LNV\Downloads\iris-main>

**Comment by wesley0209** [comment]
#377 acho que isso ia te ajudar
