### ISSUE TITLE
no me inicia el iris en el portatil

### ISSUE THREAD

**Issue by marru453** [KillovSky/iris#407]
C:\Users\Marru\Desktop\iris-main\iris-main>npm start index.js

> iris@3.1.1 start
> node index.js "index.js"

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@open-wa/wa-automate'
Require stack:
- C:\Users\Marru\Desktop\iris-main\iris-main\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Marru\Desktop\iris-main\iris-main\index.js:1:28)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\Marru\\Desktop\\iris-main\\iris-main\\index.js' ]
}

**Comment by KillovSky** [comment]
Usted tienes que usar `npm i`.

**Comment by marru453** [comment]
He probado todo y sigue dando el mismo error, tengo todo instalado y todos Microsoft visual

**Comment by KillovSky** [comment]
Usa #377

**Comment by KillovSky** [comment]
#377

**Comment by marru453** [comment]
@KillovSky  Hice todos esos pasos, borré todo y lo descargué de nuevo y nada

**Comment by marru453** [comment]
No se porque en mi portátil no me carga el iris

**Comment by KillovSky** [comment]
> No se porque en mi portátil no me carga el iris

Cuál es su versión de `NodeJS`, S.O, etc?
Envía todo lo que puedas.

**Comment by marru453** [comment]
@KillovSky  NodeJS v16.13.1, Python 3.10.0, SO DE 64bits, si quieres algo más me lo dices

**Comment by marru453** [comment]
ya lo arregle era un error de ffmpeg, pero tengo un problema de libwebp que mi sistema no lo reconoce

**Comment by KillovSky** [comment]
> ya lo arregle era un error de ffmpeg, pero tengo un problema de libwebp que mi sistema no lo reconoce

`LibWebP` ya no es necesario, ha ejecutado `npm i --force`?

Se si, desinstale todo con el `Revo Unistaller` e hace desde cero, **EN LA MISMA ARQUITECTURA DEL SISTEMA Y TAMBIEN USA LA NODE-TOOLS**, intente instalar en la carpeta raíz, el `C://`.

**Comment by marru453** [comment]
@KillovSky   bot me función bien, lo malo que el libwebp no me funciona bien el CMD no lo detecta y puesto el path bien pero no funciona

**Comment by KillovSky** [comment]
> @KillovSky   bot me función bien, lo malo que el libwebp no me funciona bien el CMD no lo detecta y puesto el path bien pero no funciona 

Tienes que insertar en `PATH` la carpeta con el `.exe`, es la carpeta `BIN`.

**Comment by marru453** [comment]
@KillovSky hice lo mismo y nada sigue dando error, libwebp es necesario para iris?

**Comment by KillovSky** [comment]
> @KillovSky hice lo mismo y nada sigue dando error, libwebp es necesario para iris?

Como comenté anteriormente, era una dependencia de `Wa-Automate` que **ya no necesita** ser instalado.

**Comment by marru453** [comment]
@KillovSky muchísimas gracias, entonces ya no hace falta seguir intentando arreglarlo, el único falló que tenía era de fffmpeg que tenía una versión vieja y estaba dañada al descargar una nueva versión funcionó bien.
