### ISSUE TITLE
inicialização

### ISSUE THREAD

**Issue by lonnykkkj** [KillovSky/iris#41]
bot não tá entrando, ele fica Client is ready infinitamente, vou esperar e ver mas ja tou ha 30 min e nada...

**Comment by PedroBatistop** [comment]
Boa tarde, eu resolvi esse problema apagando a pasta "node modules" e reinstalando os módulos usando "npm i".

**Comment by lonnykkkj** [comment]
vou testar

**Comment by lonnykkkj** [comment]
continuou assim :/

**Comment by PedroBatistop** [comment]
Tente apagar o arquivo "Iris.data.json". Você vai precisar reescanear o código QR do Whatsapp web. Caso dê certo, não deixe de informar aqui.

**Comment by lonnykkkj** [comment]
eu já recarreguei o codigo qr, e não deu nada, fiz dnv e mesmo assim não foi

**Comment by KillovSky** [comment]
Olá, primeiramente obrigado ao @PedroBatistop por toda a ajuda que vem me dando.
Agora quanto a sua issue...que coisa estranha de acontecer, existem alguns motivos que posso pensar.

1 - Na inicialização o **"Axios"** é chamado para baixar a **"package.json"** mais recente e verificar a versão, se isso não é executado por um motivo, normalmente daria um erro grande e seria ignorado e a BOT iria iniciar normalmente, mas se por algum motivo isso entrar em loop e não terminar, pode ser a causa, tente remover o `axios.get` da `index.js`.

2 - O seu WhatsApp no telefone, se estiver sendo morto por algum aplicativo ou economia de bateria, obteria esse erro também, se estiver com um imune, troque-o para um teste.

3 - Uma WA-Automate desatualizada pode também causar problemas por conta de contantes updates do nosso lendário programador da WA-Automate.

4 - Uma Íris desatualizada também pode ser problemática de iniciar, mantenha sempre a versão mais recente para constantes correções de inicialização.

5 - Sua internet, não ela em si, mas seu DNS ou provedor pode bloquear certos acessos, verifique se mudar eles pode resolver ou algo assim, na minha teoria, isso não faz sentido, mas talvez possa funcionar se o problema for um bloqueio - o que é raríssimo.

Caso nenhuma dessas soluções funcione, reinstale do zero, se não corrigir, refaça em outro PC ou crie outra machine na sua VPS, no caso de ser o goormide, tende outro container.

Estarei esperando por sua resposta, lembre-se também de sempre mostrar a tela do seu PC para que eu possa entender totalmente, mesmo que não mostre erro nenhum, pode conter detalhes que passam despercebidos.

**Comment by KillovSky** [comment]
Estarei fechando aqui então caso ocorra problemas reabra a issue com todas as informações possíveis e obrigado pela sua contribuição ao me dizer um possível bug, até outra hora sz
