### ISSUE TITLE
se é possível adicionar alguma foto/gif acoplado ao comando menu

### ISSUE THREAD

**Issue by akami-is-back** [KillovSky/iris#417]
Lucas desculpa estar incomodando ae jão,mass eu queria saber se teria possibilidades de quando enviar o comando prefix (menu) a bot respondesse com uma foto acoplada como tem por exemplo na roleta de apostas.

**Comment by KillovSky** [comment]
Leia as funções aqui -> [Funções Wa-Automate](https://docs.openwa.dev/classes/api_Client.Client.html).

**Comment by KillovSky** [comment]
> Lucas desculpa estar incomodando ae jão,mass eu queria saber se teria possibilidades de quando enviar o comando prefix (menu) a bot respondesse com uma foto acoplada como tem por exemplo na roleta de apostas.

Leia as funções aqui -> [Funções Wa-Automate](https://docs.openwa.dev/classes/api_Client.Client.html)

**Comment by KillovSky** [comment]
> Lucas desculpa estar incomodando ae jão,mass eu queria saber se teria possibilidades de quando enviar o comando prefix (menu) a bot respondesse com uma foto acoplada como tem por exemplo na roleta de apostas.

Leia as funções aqui -> [Funções Wa-Automate](https://docs.openwa.dev/classes/api_Client.Client.html)

**Comment by patulinomods** [comment]
Opa meu mano, tudo bem? e possivel sim!

coloque essa linha na `case 'menu'`  👍 

`kill.sendFileFromUrl(from, "LINK DA IMAGEM", 'NOME DA IMAGEM.png', mess.menu(pushname, time, theMsg, uzrXp, getReqXP(uzrlvl), uzrlvl, mping, patente), id)`

**Nota:** Lembre de mudar a parte onde ta escrito `LINK DA IMAGEM` , pelo link da imagem que deseja que seja enviada, e a parte `NOME DA IMAGEM` , pelo nome que deseja que a imagem tenha
