### ISSUE TITLE
sempre que eu tento baixar uma musica com "/play' ela diz que o download foi excedido o tamanho máximo  

### ISSUE THREAD

**Issue by NiceSopinha** [KillovSky/iris#418]
> COMANDO "[/PLAY]" AS 09/12/21 11:22:18 DE "Sopinha - [55***********]"
[PLAY] → Obtive erros no comando /play → Command failed with exit code 1: C:\xampp\htdocs\iris\node_modules\youtube-dl-exec\bin\youtube-dl.exe https://youtu.be/0vEPVBtkyaU --no-warnings --no-call-home --no-check-certificate --prefer-free-formats --youtube-skip-dash-manifest --referer https://youtu.be/0vEPVBtkyaU -x --audio-format mp3 -o ./lib/media/audio/5567964437301.mp3
ERROR: ffprobe/avprobe and ffmpeg/avconv not found. Please install one.
[youtube] 0vEPVBtkyaU: Downloading webpage
[download] Destination: lib\media\audio\5567964437301.mp3
[download] 100% of 3.03MiB in 00:51                  - Você pode ignorar.

**Comment by KillovSky** [comment]
Faça tudo que está na #92 ou instale a versão em desenvolvimento da Íris que remove a necessidade de instalação do `FFmpeg` -> #416

**Comment by KillovSky** [comment]
Corrigido na [Versão DEV](https://github.com/KillovSky/iris/commit/d16291a4a44e0849ca7b51089c81219a37627df2).
