### ISSUE TITLE
broad com falhas

### ISSUE THREAD

**Issue by lonnykkkj** [KillovSky/iris#42]
Not a contact. Unlock this feature and support open-wa by getting a license: https://get.openwa.dev/l/5551920012110

toda vez que eu faço uma broad ela falha, e fala que não foi possível enviar para todos, no meu terminal fala para mim obter uma licença na open-wa, eu lembro de ter visto isso aqui na github ou nos arquivos, mas nao me lembro exatamente, pode me ajudar?

**Comment by PedroBatistop** [comment]
Bom dia. Comigo isso costuma acontecer quando o open-wa está desatualizado. Atualize seus módulos utilizando "npm update". Se der certo, ou se não der certo, não esqueça de avisar aqui.

**Comment by KillovSky** [comment]
Isso ocorre com o -all ou -pv correto? Isso é por que a WA-Automate bloqueia envio de mensagens no PV para quem não for parte dos seus contatos ou nunca tiver mandado mensagens para a BOT.
Não é lá bem um bug, mas sim uma limitação da própria WA-Automate, tendo em vista isso, irei tentar fazer uma "correção" que fará esse erro ser ignorado, obrigado pela Issue.

**Comment by lonnykkkj** [comment]
olha eu dou /broad -all texto aqui, e a iris manda: O broadcast falhou em alguma parte especifica, mas se algumas mensagens foram enviadas, isso significa que a wa-automate bloqueou o envio, pois enviar mensagens a pessoas que não fazem parte dos contatos é algo que eles deixam de recuso pago. aí eu vou no whatsapp do bot e tem alguns numeros que usam o bot que não foram enviado as mensagens, mas obrigado aí

**Comment by KillovSky** [comment]
Entendi, então ainda houve bloqueio mesmo com mensagens, ainda assim cai na limitação da Wa Automate mesmo, eu que agradeço.
