### ISSUE TITLE
Open Wa

### ISSUE THREAD

**Issue by patulinomods** [KillovSky/iris#420]
**Erro ao instalar modulo**

Ola criador dessa bela obra de arte, tudo bem? estou tendo dificultade para instalar o modulo "principal" da iris, no caso o _open wa_
tendo dar _npm i @open-wa/wa-automate_ do que na hora de startar a iris da que esse modulo n foi encontrado, ai dps tentei dar _npm i @open-wa/wa-automate --force_ e continua no mesmo erro

**Print:**

![image](https://user-images.githubusercontent.com/73912095/145590540-ebac49bb-1f3e-4cc8-8de9-99989f04686b.png)

**Comment by KillovSky** [comment]
Leia a #377
