### ISSUE TITLE
Versão Unstable (Dev) da Íris | Open-Beta

### ISSUE THREAD

**Issue by coelhobugado** [KillovSky/iris#421]
/roleta apos perder ou ganhar mesmos as apostas sendo feitas com i-coins diz que ganhamos ou  perdemos XP oque acaba confundindo os jogadores

/loteria mesmo apos alguem ganhar valor nao vai pro ganhador kkkkkk

/tictac nao tem ganhador em 1 partida ganhei e a partida nao acabou depois o bot marcou 3 tbm e nao acabou, caso eu de um comando repetido retorna um erro do bot ao invez de um aviso que ja esta marcado

/welcome tenho a impressao que ele nao esta dando boas vindas nem despedidas

( sei que aqui e pra falar falhas mas slk essa "atualizaçao" ta pika dmais muitos comandos novos que e a primeira vez que vejo tanto em bots de zap quanto de telegram e discord. O criador e os desenvolvedores ultrapassaram a onipotencia dps dessa)

**Comment by KillovSky** [comment]
Muito obrigado pelos elogios!

Darei meu melhor para corrigir as falhas que você descreveu, desta forma faremos uma BOT melhor.

Apenas aguarde pela atualização do projeto ;)

**Comment by maradona4** [comment]
@KillovSky  tambem 

![image](https://user-images.githubusercontent.com/44541791/145626753-c9575bd6-88ab-42d8-8995-2570db4cf64a.png)

**Comment by PedroBatistop** [comment]
> @KillovSky tambem
> 
> ![image](https://user-images.githubusercontent.com/44541791/145626753-c9575bd6-88ab-42d8-8995-2570db4cf64a.png)

Vai em .\lib\config\Gerais\message.json e muda "log" para "nolog"

**Comment by maradona4** [comment]
> 

deu certo

**Comment by KillovSky** [comment]
Algumas correções executadas na [Versão DEV](https://github.com/KillovSky/iris/commit/d16291a4a44e0849ca7b51089c81219a37627df2).
