### ISSUE TITLE
Auto Recarregamento da Config.js 

### ISSUE THREAD

**Issue by DeyvissonSnuffs** [KillovSky/iris#423]
Retirei o // porem nao atualiza a config em tempo real
ainda tenho que da restart
await watchFile('./config.js')

**Comment by KillovSky** [comment]
Tente usar a versão nova da Íris.

**Comment by DeyvissonSnuffs** [comment]
o beta ?

**Comment by KillovSky** [comment]
> o beta ?

Isso, se preferir a antiga, lembre-se de que não é apenas remover o `//`, tem que inserir o `require` na `onMessage`, leia as instruções de outras issues ou leia a `index.js`.
