### ISSUE TITLE
Versão Unstable (Dev) da Íris | Open-Beta

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#426]
boa tarde

Meu pc tomada desligo automatico, erro arquivo level.json

![image](https://user-images.githubusercontent.com/44541791/145729265-79a34c6c-a24d-49ac-8e03-29f8167dd5ae.png)

achei que BACKUP tem um problema de erro
![image](https://user-images.githubusercontent.com/44541791/145729290-30e87f25-7cb1-4a6c-94f6-9a0747e893ea.png)

**Comment by dodouuglas** [comment]
e so colocar um [] no level.son igual ta no 
https://github.com/KillovSky/iris/blob/main/lib/config/Gerais/level.json

**Comment by KillovSky** [comment]
Basicamente, você ignorou os requisitos da Íris, nunca pule o tutorial.

[Leia-me](https://github.com/KillovSky/iris/tree/dev#requisitos)

> e so colocar um [] no level.son igual ta no 
https://github.com/KillovSky/iris/blob/main/lib/config/Gerais/level.json

Nunca coloque um `[]`, o código não é mais `array` e sim `object`.

**Comment by maradona4** [comment]
![image](https://user-images.githubusercontent.com/44541791/146644769-347341b5-dacd-4e64-92e0-96528c43dca1.png)

nao achei pastar recuperada

**Comment by marru453** [comment]
Es un problema de sintaxis, intenta usar corchetes, comas, doble comas, ect
