### ISSUE TITLE
Erro membersIds.map is not a function

### ISSUE THREAD

**Issue by zyereon** [KillovSky/iris#430]
Agora de noite todos os numeros que eu uso para o bot começaram a dar esse erro, é realmente alguma coisa referente ao wa automate ? vai ter que esperar uma atualização por parte deles, não ?
![image](https://user-images.githubusercontent.com/69636320/146289752-ada990cb-591c-4136-9722-024f9daf6eee.png)

**Comment by Try2swipe** [comment]
Mesmo aqui

**Comment by DeyvissonSnuffs** [comment]
erro no wa automate
esperar eles corrigir

**Comment by KillovSky** [comment]
Sim, pelo log do terminal foi um erro no código principal deles.

**Comment by KillovSky** [comment]
Corrigido pela `Wa-Automate`, se houver o mesmo problema para você **ainda** (futuras referências), use `npm update` ou reinstale.
