### ISSUE TITLE
erro ao executar "npm start"

### ISSUE THREAD

**Issue by SimpleDioney** [KillovSky/iris#431]
![image](https://user-images.githubusercontent.com/62361235/146470820-dd3dd2d6-0ef7-4157-9f9c-4ebb76804ec0.png)

**Comment by KillovSky** [comment]
#215, sistema operacion diferente mas deve funcionar, se falhar, use `sudo` **APENAS PARA INSTALAR**.
Também pode ter problema referente aos nomes das pastas e locais.

**Comment by SimpleDioney** [comment]
Sistema operacional é o linux, já usei esse bot nesse sistema. Não entendi a parte do sido...

**Comment by KillovSky** [comment]
Rode `sudo npm i` para forçar a permissão de instalação no sistema, se houver problema de permissão isso deve resolver, se você souber usar, também pode usar `chmod`, se claro, for erros de permissão.
Se não for, faça a atualização do sistema com `sudo apt update` e siga os passos de instalação da branch `dev` da Íris, você pode achar ela indo em `discussions` aqui na github.

**Comment by SimpleDioney** [comment]
eu tentei o "sudo npm i" e nao funcionou, estou agora fznd o upgrade. fui na discussions mas n achei como instalar a branch dev

**Comment by SimpleDioney** [comment]
Acabei de achar como instala a branch dev.

**Comment by SimpleDioney** [comment]
Fiz tudo que você me indicou, continua o mesmo erro.

**Comment by KillovSky** [comment]
Tente fazer isso:

```bash
sudo rm -rf node_modules package-lock.json Logs
npm cache clean --force
npm i
```

Se isso não funcionar, leia outras issues daqui do mesmo problema e tente verificar essa solução apresentada na repo do módulo oficial.

```bash
sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
```

**Comment by EmanuelPeixoto** [comment]
eu já tive problema com o canvas e o linux, @SimpleDioney tente dar npm i canvas e veja se vai dar um erro 404 na hora de download

**Comment by SimpleDioney** [comment]
@EmanuelPeixoto fiz o comando e deu isso
![image](https://user-images.githubusercontent.com/62361235/146551959-787f3abe-df25-452d-8d01-0759845a49cb.png)

**Comment by SimpleDioney** [comment]
testei tudo e deu nisso:
![image](https://user-images.githubusercontent.com/62361235/146553272-a5126c2e-3927-424a-85fd-24c42abdd277.png)

**Comment by KillovSky** [comment]
> testei tudo e deu nisso:
> ![image](https://user-images.githubusercontent.com/62361235/146553272-a5126c2e-3927-424a-85fd-24c42abdd277.png)
> 

Esse erro já é dentro um módulo que está dentro de outro módulo, pelo visto, sua versão do `NodeJS` pode estar dando incompatibilidade, tente usar o tutorial do `Node Source` na página inicial da Íris, use a versão 14 e teste.

**Comment by KillovSky** [comment]
> @EmanuelPeixoto fiz o comando e deu isso
> ![image](https://user-images.githubusercontent.com/62361235/146551959-787f3abe-df25-452d-8d01-0759845a49cb.png)
> 

Já aqui, você está rodando no lugar errado.

Se não for familiarizado com o `Linux`, você deve assistir aos tutoriais ou usar `Windows/VM/VPS`, por conta dos problemas mais avançados que podem ocorrer no `Linux`.

**Comment by SimpleDioney** [comment]
Eu executei o comando dentro e fora da pasta para ter certeza do que estava fazendo, irei tentar o node 14

**Comment by SimpleDioney** [comment]
![Uploading 16398644002368789988496095997836.jpg…]()

**Comment by KillovSky** [comment]
> ![Uploading 16398644002368789988496095997836.jpg…]()
> 

Sua imagem é invalida, não é possivel ver.
Presumo que não tenha funcionado, portanto, apague os arquivos, todos os `node_modules` e em seguida apague a pasta `Iris`, digite isso:

```bash
node -v # Me mande isso primeiro

npm -v # Me mande isso primeiro

sudo apt remove nodejs-* python-*
# O -* força a apagar todos os pacotes que o node e python usam, não é o recomendado mas nesse caso quem sabe...

cd Downloads # Ou qualquer pasta do /Home/User

sudo apt install python nodejs -y

git clone https://github.com/KillovSky/iris.git

cd iris

npm i --force # CERTIFIQUE-SE DE ESTAR COM O NODE LTS E O NPM MAIS RECENTE!
```

Se falhar, não tenho ideias, pode ser mais conveniente olhar o repositorio do `Canvas` e `NPM CLI`.

**Comment by SimpleDioney** [comment]
funcionou! muito obrigado

**Comment by SimpleDioney** [comment]
aopa, estou tentando rodar a branch dev, esta dando erro no npm start, dessa vez nao e com o canvas...

ja tentei tudo que fiz anteriormente com sua ajuda aqui.

![image](https://user-images.githubusercontent.com/62361235/151667964-57a44a2d-9537-4aaa-b40a-37df69a019d5.png)

**Comment by SimpleDioney** [comment]
![image](https://user-images.githubusercontent.com/62361235/151669143-3a8e9fa7-5482-4c37-a748-c182859b000f.png)
