### ISSUE TITLE
TimeoutError: Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by marru453** [KillovSky/iris#432]
TimeoutError: Navigation timeout of 30000 ms exceeded
    at C:\Users\Marru\Desktop\iris-main\node_modules\puppeteer\lib\cjs\puppeteer\common\LifecycleWatcher.js:106:111
hice todo borre la carpeta de log y iris.data.js y nada sigue dando este error y no se a que se debe.

**Comment by maradona4** [comment]
#278

**Comment by marru453** [comment]
@maradona4 En mi caso esa opción la hice varias veces y sigue dando el mismo error. Hasta borre node-modulos y lo instalé nuevamente, borre iris-data, log y sigue dando el mismo error.

**Comment by KillovSky** [comment]
Si no muestra su pantalla, para vermos si está funcionando la `Wa-Automate`, es difícil.
Por lo que puedo decir, es un problema con la velocidad de su computadora - por ahora -, intente reinstalar `node` si es necesario.
