### ISSUE TITLE
Bklist não funciona

### ISSUE THREAD

**Issue by Try2swipe** [KillovSky/iris#435]
Bklist não funciona
![bklist](https://user-images.githubusercontent.com/60209241/146665919-e0bda9ca-a270-4f77-8fcd-84f126e0d200.png)

**Comment by KillovSky** [comment]
Irei averiguar hoje e o informarei sobre.

**Comment by KillovSky** [comment]
Farei uns testes hoje mais tarde e irei verificar por bugs.
Como você não exibiu seu terminal, não sei se houve erros nele, também não sei a versão da sua Íris, por isso, peço que espere e envie informações sobre.

**Comment by Try2swipe** [comment]
![bklist1](https://user-images.githubusercontent.com/60209241/146821231-74e53292-5b86-4f64-b4df-dfcc5c36588c.png)
![bklist3](https://user-images.githubusercontent.com/60209241/146821233-a491fd81-201a-49f2-8f23-46dad4978fa1.png)
![bklist2](https://user-images.githubusercontent.com/60209241/146821234-6f1d09d9-4773-4afa-bb06-37aee38c4e53.png)

**Comment by KillovSky** [comment]
Enviarei uma atualização hoje para o `Branch Dev`, se houver tempo claro, é preciso esperar até lá.

**Comment by Try2swipe** [comment]
Obrigado!

**Comment by KillovSky** [comment]
Fixado, leia a descrição da [versão 3.2.3](https://github.com/KillovSky/iris/commit/ee90668e6aab658a76650e2c352651821689318e).

Foto que mostra a correção funcionando ->
 #![Screenshot_2021-12-23-19-47-30-717_com.whatsapp_1.jpg](https://user-images.githubusercontent.com/55511420/147297427-2373cb38-d318-42a5-a2f0-e99420cb460c.jpg)
