### ISSUE TITLE
Comando signo

### ISSUE THREAD

**Issue by Guixaviertga** [KillovSky/iris#437]
![IMG_20211221_084047](https://user-images.githubusercontent.com/96479111/146932426-950a4b9d-3e45-4764-a40c-a77c54923858.jpg)
Parou de funcionar recentemente, não mexi no código

**Comment by KillovSky** [comment]
Irei analisar, obrigado.

**Comment by KillovSky** [comment]
Corrigido na [3.2.4](https://github.com/KillovSky/iris/commit/fd77fd9a5e12871413ce6f599b80f469098f0330)!

**Comment by KillovSky** [comment]
Fiz a correção desse comando agora na [Versão 3.2.4](https://github.com/KillovSky/iris/commit/fd77fd9a5e12871413ce6f599b80f469098f0330), não esqueça de ter instalado `Git Bash` e `GOW` - Apenas se estiver no `Windows`, pois o `Linux` já possui as ferramentas.
