### ISSUE TITLE
Erro mess.fail

### ISSUE THREAD

**Issue by BruZim03** [KillovSky/iris#438]
Você já me ajudou com isso no WhatsApp, mas eu esqueci como que resolvia, to ligando a íris em uma vps, e com um tempo ligada, ela da esse erro

![Screenshot_9](https://user-images.githubusercontent.com/77207248/146957360-ffc455cf-9133-490e-b1e5-c2e6157dfe78.png)

linha do erro: 	await kill.simulateTyping(from, true);await kill.reply(from, mess.fail(), id)

tem como mandar a linha do jeito certo?

**Comment by KillovSky** [comment]
Faça uma reinstalação da Íris e use a `Dev Branch` e poste os resultados que obter.

**Comment by BruZim03** [comment]
> 

pode me explicar como fazer isso?

**Comment by KillovSky** [comment]
Vá na #416 e clique em `nova Íris`, em seguida, leia a página.

**Comment by BruZim03** [comment]
tem outro jeito de resolver ? quando tento instalar a dev, fica travado na instalação e não instala direito

**Comment by KillovSky** [comment]
Remova `mess.fail()` e insira qualquer coisa no lugar, **COM ASPAS!**

Exemplo -> `"erro"`.
