### ISSUE TITLE
Botoes nao pega

### ISSUE THREAD

**Issue by patulinomods** [KillovSky/iris#439]
oi lindo, to tentando usar os botoes com whatsapp business, fiz todas as modificaçoes ditas na #257 , mans ela nao manda os botoes, tenho minha duvida, sera que eh porque estou com o multipleDevices on? 

Codigo dos botoes:

case 'teste2':
			await kill.sendButtons(from, 'msg de baixo',  [
                {
                    "id":"id1",
                    "text": "msg1"
                },
                {
                    "id":"id2",
                    "text": "msg2"
                },
                {
                    "id":"id3",
                    "text": "msg3"
                }
            ],"msg principal")
			break

![image](https://user-images.githubusercontent.com/73912095/147170697-cf90b9c1-d15b-4830-84c7-bab36572b9a6.png)

Obs: Quando voce ira add a funçao de enviar lista? so uma duvida memo

**Comment by KillovSky** [comment]
Talvez, faça um código baseado na [linha 3375](https://github.com/KillovSky/iris/blob/dev/config.js#L3335) da `Branch Dev` e teste.
Sobre a lista, no momento não é opção, limitação por parte de API's, também não vejo tanta necessidade de criar uma lista se já existe um sistema de botões, só precisa fazer os mesmos se adequarem aos comandos, irei analisar em breve sobre criação de verificadores em botões.
