### ISSUE TITLE
errro comando /play

### ISSUE THREAD

**Issue by DeyvissonSnuffs** [KillovSky/iris#440]
> COMANDO "[.PLAY]" AS 23/12/21 01:23:08 DE "pedroㅤꪰ - [557598032449]"
[PLAY] → Obtive erros no comando .play → Evaluation failed: TypeError: Cannot read properties of undefined (reading 'id')
at Object.window.<computed>.<computed> [as sendLinkWithAutoPreview] (__puppeteer_evaluation_script__:1:194326) - Você pode ignorar.

ja vi outras issue mais nao conseguir resolver

**Comment by DeyvissonSnuffs** [comment]
ja tirei todos os id do comando
e substituir o reply por SendText

**Comment by KillovSky** [comment]
Atualize a `Wa-Automate` com `npm update` e limpe a Íris, apagando a pasta Logs`, passe um `CCleaner` no `Google Chrome` e teste, o erro não foi na Íris e sim na `Wa-Automate`.

**Comment by KillovSky** [comment]
Peço desculpas pela minha falha em relação aos comandos, @PedroBatistop me informou sobre onde estava o erro, o mesmo seria na Íris, fiz a correção agora na [Versão 3.2.4](https://github.com/KillovSky/iris/commit/fd77fd9a5e12871413ce6f599b80f469098f0330), experimente e divirta-se!

**Comment by DeyvissonSnuffs** [comment]
deu certo obrigado
