### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by BruZim03** [KillovSky/iris#441]
Deixar uma sugestão aqui, um comando pra editar a foto tema natalino, eu sei que é besta, mas um comando onde edita a foto e coloca sla, uma barba de Papai Noel e um gorro, enfim, é um comando só pra zoar msm

**Comment by KillovSky** [comment]
Verei o que posso fazer.

**Comment by KillovSky** [comment]
Não é possivel por hora com minha habilidade por conta da vasta quantidade de fotos diferentes, deixando o chapeu e bigode impossivel de ajustar, quem sabe futuramente quando eu tiver um conhecimento maior.
