### ISSUE TITLE
Comando das Guildas não está funcionando

### ISSUE THREAD

**Issue by playboyander** [KillovSky/iris#442]
Os comandos: "/Thieves e /Companions" não estão funcionando.
sempre que executados aparece a seguinte mensagem:
 "⚠️ - O comando /thieves não existe, reveja nossa lista em /menu para continuar."

Mesmo com os comandos estando no Menu e tendo gente em ambas as guildas

<img width="276" alt="arruma ai kilovin" src="https://user-images.githubusercontent.com/96602003/147303941-1156f390-0ddd-404b-b2a8-fe000b87f7a9.PNG">

**Comment by KillovSky** [comment]
Os menus não são atualizados.

Use -> `/myguild thieves`.

**Comment by maradona4** [comment]
Deu "[MYGUILD] → Obtive erros no comando "/myguild" → "Cannot read properties of undefined (reading 'guild')" - Você pode ignorar."

**Comment by playboyander** [comment]
estou tendo o mesmo erro com o comando /myguild

[MYGUILD] → Obtive erros no comando "/,$,#,.,\,@,-,=,?,+,!,&,:,;,^,>,<,|myguild" → "Cannot read properties of undefined (reading 'guild')" - Você pode ignorar.

**Comment by KillovSky** [comment]
Correção saindo em breve, estejam atentos para a versão rápida na versão `3.2.4`.

**Comment by KillovSky** [comment]
Fiz a correção desse comando agora na [Versão 3.2.4](https://github.com/KillovSky/iris/commit/fd77fd9a5e12871413ce6f599b80f469098f0330), verifique e divirta-se!
