### ISSUE TITLE
apos o erro do "npm start"

### ISSUE THREAD

**Issue by SimpleDioney** [KillovSky/iris#443]
bom, apos resolver o erro ao iniciar, o bot funcionou, porem apos eu reinicia-lo apareceu isso:
![image](https://user-images.githubusercontent.com/62361235/147306992-078f5eec-a7e3-4a78-9007-7d456d3f7465.png)

**Comment by SimpleDioney** [comment]
consegui resolver apagando a pasta "chrome" dentro de logs, porem vou ter q fazer isso sempre?

**Comment by KillovSky** [comment]
Abra a `index.js` e remova a linha que possui `tools('others').clearFile(...)`.

**Comment by KillovSky** [comment]
Abra a `index.js` e remova a primeira linha que possui `tools('others').clearFile(...)`.
