### ISSUE TITLE
Iris versão 3.2.3 

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#444]
cmd /vote

1 - 
![image](https://user-images.githubusercontent.com/44541791/147318228-ee586655-c69f-4771-b76f-3c2004ee20d3.png)

2- 
![image](https://user-images.githubusercontent.com/44541791/147318236-7b417012-381b-4800-b89e-57e9398c4cd5.png)

**Comment by KillovSky** [comment]
Irei corrigir em breve.

**Comment by marru453** [comment]
De dónde sacaste la versión esa?

**Comment by Try2swipe** [comment]
Aparte de este bug, el bug más importante es que al usar /poll después de haber votado, dice que no hay una votación activa. 

![image](https://user-images.githubusercontent.com/60209241/147374377-fd48df26-57c2-4236-8aa3-325f4b5df37d.png)

**Comment by KillovSky** [comment]
Fiz a correção desse comando agora na [Versão 3.2.4](https://github.com/KillovSky/iris/commit/fd77fd9a5e12871413ce6f599b80f469098f0330), experimente e seja livre para postar os resultados se desejar ;)
