### ISSUE TITLE
erro apos dar comando npm i 

### ISSUE THREAD

**Issue by sealewd** [KillovSky/iris#447]
![erro iris 4](https://user-images.githubusercontent.com/80061478/147376043-f7340ee4-5a96-4d77-b2b0-e8ec938447b8.PNG)

**Comment by KillovSky** [comment]
Você postou a issue antes da imagem ser 100% enviada, peço que edite para que ela apareça corretamente.

**Comment by KillovSky** [comment]
Seu `NodeJS` é muito antigo, instale a versão `LTS`.
