### ISSUE TITLE
Errores - Poll/Vote - Version 3.2.4

### ISSUE THREAD

**Issue by Try2swipe** [KillovSky/iris#448]
1. Solo se puede utilizar el comando /poll antes de que alguien haya votado por uno de los candidatos.
2. Solo una persona puede votar, después ya no es posible que nadie más vote.

**Versión**
![Errores4](https://user-images.githubusercontent.com/60209241/147380114-ddb20af5-afec-4f08-9e7f-14980f1cbf1a.png)

Terminal
![Errores5](https://user-images.githubusercontent.com/60209241/147380123-ca8bbfec-7dc8-4f28-9f9c-20f256061a8b.png)

Chat de WhatsApp

![Errores1](https://user-images.githubusercontent.com/60209241/147380130-6fbf0ddc-b47d-4784-9b99-77ea110e469c.png)
![Errores2](https://user-images.githubusercontent.com/60209241/147380131-48052689-f8c2-4093-91ee-62f006ed5e46.png)
![Errores3](https://user-images.githubusercontent.com/60209241/147380133-34eb5743-d40e-4bc1-ae0d-1a46383b0df5.png)

**Comment by KillovSky** [comment]
Esto es extraño, hice una verificación antes de la actualización, pero gracias por avisarme, verificaré y haré otra corrección en el comando.

**Comment by maradona4** [comment]
@KillovSky  /shop 3 

deu "Cannot set properties of undefined (setting 'xp')"

shop.js

Linha 42

Caractere 58

**Comment by Try2swipe** [comment]
> Esto es extraño, hice una verificación antes de la actualización, pero gracias por avisarme, verificaré y haré otra corrección en el comando.

Gracias!

**Comment by KillovSky** [comment]
Prueba la [Versión 3.2.5](https://github.com/KillovSky/iris/commit/b742993aacd35ad06d7b1427e395becf43182923).
