### ISSUE TITLE
atualizar ou criar uma nova lista para a iris beta

### ISSUE THREAD

**Issue by coelhobugado** [KillovSky/iris#450]
voce poderia por favor atualizar essa lista colocando os sites aonde tem que criar as api suas funçoes e talls ou criar uma pra iris dev... https://github.com/KillovSky/iris/blob/main/.readme/pt/config.md

**Comment by KillovSky** [comment]
Olá, primeiro estou focado em finalizar o código mas irei fazer a documentação assim que possivel.
