### ISSUE TITLE
comando Antispam de instagram

### ISSUE THREAD

**Issue by marru453** [KillovSky/iris#451]
config.js:
> linea 110: `const isAntiSpams = isGroupMsg ? functions[0].isantiSpams.includes(groupId) : false`

> linea 240: `// Anti Spams de grupo
		if (isGroupMsg && !isGroupAdmins && isBotGroupAdmins && isAntiSpams && !isOwner && oneLink == 0 && !isBot) {
			try {
				if (chats.match(new RegExp(/(https:\/\/www.instagram.com)/gi))) {
					oneLink = 1; const gplka = await kill.inviteInfo(chats)
					if (gplka) {
						console.log(color('[BAN]', 'red'), color('Link de grupo detectado, removendo participante...', 'yellow'))
						await kill.removeParticipant(groupId, user).then(async () => { await kill.sendTextWithMentions(from, mess.baninjusto(user) + 'WhatsApp Link.');return oneLink = 0 })
					} else { console.log(color('[ALERTA]', 'yellow'), color('Link de grupo invalido recebido...', 'yellow'));oneLink = 0 }
				}
			} catch (error) { return oneLink = 0 }
        }`

error al ejecutar los comandos.
[FALHA GERAL] TypeError: Cannot read properties of undefined (reading 'includes')
    at kconfig (C:\Users\Marru\Desktop\bot de prueba\config.js:111:61)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\Marru\Desktop\bot de prueba\index.js:46:3

**Comment by KillovSky** [comment]
#316
