### ISSUE TITLE
quiero crear un menu con buttones?

### ISSUE THREAD

**Issue by marru453** [KillovSky/iris#453]
sigue todos los pasos pero a la hora de crear me sale un error

>menu buttons `case 'menu':
				const theMsg = await gaming.getValue(user, nivel, 'msg')
				const uzrXp = await gaming.getValue(user, nivel, 'xp')
				const uzrlvl = await gaming.getValue(user, nivel, 'level')
				const mping = processTime(t, moment())
				id = message.type == "buttons_response" ? message.quotedMsgObj.id : message.id
				await kill.sendButtons(from, 'By Rei Ayanami & Lúcifer', [
		        {
		        "id": "1",
		        "text": "!stickers"
		         }
	            ], 'LISTA DE MENUS')
				await kill.reply(from, mess.menu(pushname, time, theMsg, uzrXp, getReqXP(uzrlvl), uzrlvl, mping, patente), id)
				break`

error cmd: 
[FALHA GERAL] TypeError: Assignment to constant variable.
    at kconfig (C:\Users\Marru\Desktop\bot de prueba\config.js:3599:8)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\Marru\Desktop\bot de prueba\index.js:46:3

**Comment by KillovSky** [comment]
#316

**Comment by marru453** [comment]
@KillovSky  sigue los pasos que pusiste y a la hora de crear el menu me sale ese error, y cuando quito el comando de la línea 3599, me sale el bot pero separado del menú
