### ISSUE TITLE
Duvida

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#454]
textpro.me  nao conseguir abre

acho meu DNS? 

failed, reason: getaddrinfo EAI_AGAIN textpro.me

titulo erro "EAI_AGAIN"

![image](https://user-images.githubusercontent.com/44541791/147393176-f318b832-c2d2-41ba-975b-40c7e905296e.png)

**Comment by KillovSky** [comment]
> textpro.me  nao conseguir abre
> 
> acho meu DNS? 
> 
> failed, reason: getaddrinfo EAI_AGAIN textpro.me
> 
> titulo erro "EAI_AGAIN"
> 
> ![image](https://user-images.githubusercontent.com/44541791/147393176-f318b832-c2d2-41ba-975b-40c7e905296e.png)
> 

Troque seu DNS, houve uma falha nele, não há erros comigo.

**Comment by maradona4** [comment]
Okey
