### ISSUE TITLE
Botones - Poll - 3.2.4

### ISSUE THREAD

**Issue by Try2swipe** [KillovSky/iris#455]
Al utilizar un botón para el comando /vote, se registra el voto pero no responde con el mensaje confirmando que la votación fue exitosa. Este es un error que ocurre desde la versión 3.1.1.

**Whatsapp**
![image](https://user-images.githubusercontent.com/60209241/147394987-f05a01a7-363c-421f-b568-34aee0358566.png)
![image](https://user-images.githubusercontent.com/60209241/147394988-009c80fb-0339-4052-aaef-5210de01b389.png)

**Código del botón**
![image](https://user-images.githubusercontent.com/60209241/147395030-5e67321b-808a-4aec-9897-0055fa2e11b3.png)

**Terminal**
![image](https://user-images.githubusercontent.com/60209241/147395020-8d5f4cf0-9420-46a1-a96f-90d424a96bdc.png)

**Comment by KillovSky** [comment]
Intenta con las correciones del [Release 3.2.5](https://github.com/KillovSky/iris/commit/b742993aacd35ad06d7b1427e395becf43182923).
Lea al #316.
