### ISSUE TITLE
Erro no comando signo

### ISSUE THREAD

**Issue by Guixaviertga** [KillovSky/iris#456]
![IMG-20211225-WA0020](https://user-images.githubusercontent.com/96479111/147395754-0d421fb7-05a9-459b-86e7-36f0e828c080.jpg)

**Comment by KillovSky** [comment]
Você fez a instalação do `Git Bash`, adicionou ele ao `PATH` do windows e instalou `GOW`?

Se não, instale todos e adicione o `Git Bash` ao `PATH`.

Aqui segue um comando que adiciona automaticamente o `Git Bash` ao `PATH`.

```bash
> set PATH=%PATH%;C:\Program Files\Git\bin
```

Tenha em mente que o local pode ser diferente, por isso, verifique se a pasta acima possui um arquivo chamado `bash.exe`, se sim, está certo.
Se não, procure o `bash.exe` e insira o local dele no lugar de `C:\Program Files\Git\bin`.

**Comment by Guixaviertga** [comment]
Fiz todo o procedimento e reiniciei o pc
Testei e funcionou, obrigado

**Comment by JohnEdwardMS** [comment]
no meu caso funcionou com comando:
```
setx /M path "%path%;C:\Program Files\Git\bin"
```
