### ISSUE TITLE
npm i - console loop infinito

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#457]
![image](https://user-images.githubusercontent.com/44541791/147397262-8293c0dc-13ea-4b35-87fa-bf85609c6fd1.png)
 
 npm i
 instalação parou?

**Comment by marru453** [comment]
Prueba con npm i -y

**Comment by maradona4** [comment]
> Prueba con npm i -y

![image](https://user-images.githubusercontent.com/44541791/147398110-a56bd06d-c068-4760-b5a1-df31b38539c2.png)
no funciona sigue así

**Comment by marru453** [comment]
@maradona4  entonces que les falto poner algun comando

**Comment by marru453** [comment]
@maradona4  acabo de arreglarlo, borra la carpeta de node-modulos y log y usa npm i

**Comment by KillovSky** [comment]
Abra o `Git Bash` e rode isso:

```bash
> rm -rf node_modules package-lock.json Logs
> npm cache clean --force
> npm i
```

E diga se funcionou.
Se você estiver usando `Proxy` ou `VPN`, instale sem usar eles.

**Comment by maradona4** [comment]
Deu certo funcionar
![image](https://user-images.githubusercontent.com/44541791/147423323-d6fa97fc-399c-42f3-b909-0caea9558bc1.png)
