### ISSUE TITLE
error iris version 3.2.5

### ISSUE THREAD

**Issue by marru453** [KillovSky/iris#458]
C:\Users\Marru\Desktop\iris>npm i -y
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! network Socket timeout
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Marru\AppData\Local\npm-cache\_logs\2021-12-26T11_41_15_729Z-debug-0.log

**Comment by KillovSky** [comment]
#405

**Comment by marru453** [comment]
@KillovSky no era de internet ya que la otra version se instalaba es porque antes tenia los archivos de node dañados borre la carpeta de node-modulos y log y lo installe de nuevo
