### ISSUE TITLE
A MINHA IRIS NÃO CONSEGUE MANDAR MENSAGEM DE TEXTO

### ISSUE THREAD

**Issue by n2005s** [KillovSky/iris#459]
Por exemplo*PREFIX* Menu, ai não aparece o Menu para saber os comandos saca?
Então queria saber uma possivel solução

**Comment by marru453** [comment]
Esta trabajando en ello, cuál versión tienes?

**Comment by KillovSky** [comment]
Reinicie o PC, apague a pasta `Logs` e o arquivo `package-lock.json` e rode `npm update`.
Certifique-se de tentar usar a `Íris 3.2.5` também.
