### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by YuriTotoso** [KillovSky/iris#46]
Como coloca o numero dono? já tentei varias vezes e não funciona, comecei a ver o bot hoje, quem me ajudar ficarei agradecido demais

**Comment by PedroBatistop** [comment]
Bom dia! Vá no caminho lib/config/Bot, abra o arquivo config.json, caso não tenha um programa específico para abrir arquivos .json, pode abrir com o bloco de notas mesmo, e edite a parte entre aspas e depois dos dois pontos de "owner". Há alguns tutoriais no YouTube ensinando a como instalar a Íris, creio que possa te ajudar também, além de ler os readmes. Caso tiver mais dúvidas fique livre para perguntar, caso não tiver mais, fique livre para fechar esse help.

**Comment by YuriTotoso** [comment]
> Bom dia! Vá no caminho lib/config/Bot, abra o arquivo config.json, caso não tenha um programa específico para abrir arquivos .json, pode abrir com o bloco de notas mesmo, e edite a parte entre aspas e depois dos dois pontos de "owner". Há alguns tutoriais no YouTube ensinando a como instalar a Íris, creio que possa te ajudar também, além de ler os readmes. Caso tiver mais dúvidas fique livre para perguntar, caso não tiver mais, fique livre para fechar esse help.

isso eu entendi, só que n vai, já tentei editar o numero, só que continua dizendo que não sou dono, já tentei e varias formas, e não vai, precisa colocar o 9 na frente do numero? e oq significa aquele ddi? desculpa muitas perguntas ;-; é pq achei o bot ontem

**Comment by PedroBatistop** [comment]
Vamos lá. DDI é um prefixo internacional, se seu número for brasileiro, o DDI padrão é "55". Sim, precisa colocar o 9 na frente. O número do dono deve ser configurado da seguinte forma:

DDI + Os 9 númeor do seu número + "@c.us"

Ex.: Se seu número for 912345678, ficará assim: 55912345678@c.us

A linha do config.json ficará assim: 

"owner": ["55912345678@c.us", "551398....@c.us"],

Lembrando que se você quiser colocar mais de um dono, só precisa editar o segundo número ali da linha. Por exemplo, se o número do primeiro dono for 912345678 e do segundo dono for 987654321, ficará assim na linha do código:

"owner": ["55912345678@c.us", "55987654321@c.us"],

Obs.: Talvez seu problema seja que você está colocando o número do BOT como Owner, isso está errado. O Owner precisa ser um número diferente do número do BOT.

**Comment by YuriTotoso** [comment]
> Vamos lá. DDI é um prefixo internacional, se seu número for brasileiro, o DDI padrão é "55". Sim, precisa colocar o 9 na frente. O número do dono deve ser configurado da seguinte forma:
> 
> DDI + DDD + Os 9 números do seu número + "@c.us"
> 
> Ex.: Se seu número for 21912345678, ficará assim: [5521912345678@c.us](mailto:5521912345678@c.us)
> 
> A linha do config.json ficará assim:
> 
> "owner": ["[5521912345678@c.us](mailto:5521912345678@c.us)", "[551398....@c.us](mailto:551398....@c.us)"],
> 
> Lembrando que se você quiser colocar mais de um dono, só precisa editar o segundo número ali da linha. Por exemplo, se o número do primeiro dono for 21912345678 e do segundo dono for 21987654321, ficará assim na linha do código:
> 
> "owner": ["[5521912345678@c.us](mailto:5521912345678@c.us)", "[5521987654321@c.us](mailto:5521987654321@c.us)"],
> 
> Obs.: Talvez seu problema seja que você está colocando o número do BOT como Owner, isso está errado. O Owner precisa ser um número diferente do número do BOT.

AAAAAAAAhhhhhhh, não sabia que precisava colocar o @c.us, já ate funcionou, muitoooo obrigado, pela paciência também kkkkk, vcs que produzem esse bot, são fodas dms :)

**Comment by PedroBatistop** [comment]
Fico feliz que tenha dado certo. Semrpe que precisar é só perguntar. Muito obrigado!
