### ISSUE TITLE
Menu incompleto

### ISSUE THREAD

**Issue by DeyvissonSnuffs** [KillovSky/iris#460]
Minha irmã não aparece leia mais 
O menu simplesmente tá incompleto
![IMG_20211227_022835](https://user-images.githubusercontent.com/85204721/147437685-ca248775-a441-4a7f-9a60-96dfe2cc6030.jpg)

**Comment by KillovSky** [comment]
Isso não é bug na Íris e sim no seu celular, até por que o menu parece cortado, geralmente, é só forçar o app a fechar e abrir de novo.

**Comment by DeyvissonSnuffs** [comment]
![Screenshot_2021-12-27-10-35-28-621_com whatsapp w4b](https://user-images.githubusercontent.com/85204721/147476805-5f11de49-391f-45d7-8394-cc688a9f9e46.jpg)
No número oficial da iris aparece menu o.o com msm celular
