### ISSUE TITLE
Grupos Limite/Resquíto

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#461]
![Screenshot_20211226-160938_WhatsAppBusiness](https://user-images.githubusercontent.com/44541791/147458671-495ae812-1f2a-448b-8acb-c9586708ab98.jpg)

Deu texto grande

**Comment by KillovSky** [comment]
A correção vai sair na `3.2.6`.

**Comment by KillovSky** [comment]
Leia a descrição do [Update 3.2.6](https://github.com/KillovSky/iris/commit/056c014cb53f8d61010f062a64549e614ba847a8) e divirta-se com as melhorias!
