### ISSUE TITLE
Bug : nao aparece o nome do comando

### ISSUE THREAD

**Issue by Guixaviertga** [KillovSky/iris#462]
![IMG_20211227_093154](https://user-images.githubusercontent.com/96479111/147476533-e9b34377-b28c-4daa-95a3-82425a86bba9.jpg)
Cmd não apresenta falha

**Comment by marru453** [comment]
pasa una captura del fallo en cmd, asi el dueño sabra el error cual es y lo arreglara en la siguiente actualización

**Comment by Guixaviertga** [comment]
Percebi que o problema é no meu whats
