### ISSUE TITLE
Comando Broad

### ISSUE THREAD

**Issue by DeyvissonSnuffs** [KillovSky/iris#463]
Na íris 3.2.5
O /broad só envia texto
Mais imagens não tá indo 
Não dá erro
E não executar o comando

**Comment by maradona4** [comment]
Também

**Comment by KillovSky** [comment]
Irei fazer uma verificação e corrigir os bugs encontrados, aguardem a `Release 3.2.6`.

**Comment by DeyvissonSnuffs** [comment]
Certo

**Comment by KillovSky** [comment]
Leia a descrição do [Update 3.2.6](https://github.com/KillovSky/iris/commit/056c014cb53f8d61010f062a64549e614ba847a8) e divirta-se com as melhorias!
