### ISSUE TITLE
Ranking

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#467]
Como vejom numéro lista 

pessoa saiu os grupos, EXP aberto

ranking deu puts utrapassa

![image](https://user-images.githubusercontent.com/44541791/147527051-d2561efe-0beb-4cc1-843e-b26b0966d868.png)

console.log(tools('others').color(`${i + 1} [RANKING] - `, 'yellow'))
							
						versão 3.2.5

**Comment by KillovSky** [comment]
![IMG-20211228-WA0021.jpg](https://user-images.githubusercontent.com/55511420/147561900-f5aa0434-3235-48f4-a0f4-1b540ab4746a.jpg)

**Comment by maradona4** [comment]
a vdd
