### ISSUE TITLE
Erro Íris na vps

### ISSUE THREAD

**Issue by BruZim03** [KillovSky/iris#468]
Tô ligando a íris na vps, após algum tempo ligada, ela desliga dando esse erro

![Screenshot_20211228-083414_1](https://user-images.githubusercontent.com/77207248/147562411-e3467e91-5e34-4bfd-a4e1-34b5fcd3109f.png)

**Comment by KillovSky** [comment]
Aparentemente seu navegador crashou, pode ser que a `VPS` esteja fechando ele, enfim, você instalou `Chrome`?

**Comment by BruZim03** [comment]
instalei sim

**Comment by KillovSky** [comment]
Instale o `PM2` e use por ele para um teste.

**Comment by BruZim03** [comment]
Creio que minha vps não aguentou PM2, então nem consegui ligar e fazer esse teste

**Comment by KillovSky** [comment]
Muito estranho, você seguiu o tutorial de instalação corretamente? Se sim, o problema está sendo a sua VPS matando os processos, pode ser falta de memoria ou algo assim.

**Comment by BruZim03** [comment]
config da vps
Cores: 1
RAM: 1024 Mb
HDD: 8 Gb

um erro diferente dessa vez
![image](https://user-images.githubusercontent.com/77207248/147679862-bcfe1023-9226-4d82-9e6e-0466d00f9989.png)

**Comment by BruZim03** [comment]
conseguir dar uns jeito reiniciando a vps, pode fechar essa issue
