### ISSUE TITLE
Comandos não respondeu

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#469]
bot não respondeu 

/geral e /ativos 
eu tem grupos mais membros 194, versão 3.2.5 iris-dev  BlackJack

**Comment by KillovSky** [comment]
Vou verificar

**Comment by KillovSky** [comment]
Vai ser fixado na `3.2.6`, em breve a versão será lançada.

**Comment by KillovSky** [comment]
Leia a descrição do [Update 3.2.6](https://github.com/KillovSky/iris/commit/056c014cb53f8d61010f062a64549e614ba847a8) e divirta-se com as melhorias!
