### ISSUE TITLE
Bug do WhatsApp

### ISSUE THREAD

**Issue by lonnykkkj** [KillovSky/iris#47]
então cara, eu uso imune no bot pq travazaps usam ele, tipo ele tá em grupo de fcc e tal, então eu uso imune, e sempre deu tudo certo nunca aconteceu nada de mais, aí ante ontem ele começou a bugar, tipo ele funciona normal aí ele do nada parou de receber mensagem, ele parou as 15:49 e voltou só as 7 da manhã de ontem, tipo as vezes ele voltava recebia algumas mensagens por 2 minutos ou menos e caía dnv, aí ontem arrumou e caiu dnv de tarde, eu pensei que era um bug do próprio whatsapp, aí eu troquei de whatsapp e mesmo assim não foi, dai perguntei pra um amigo e ele disse q era do whatsapp web, q tinha q desconectar e conectar e n foi, deletei o whatsapp web do  bot e coloquei de novo e não foi, sabe me dizer se o culpado é meu whatsapp/celular ou é algo da iris? foi mal pelo texto grande

**Comment by KillovSky** [comment]
Isso pode estar relacionado ao modo de economia do telefone, verifique se seu WhatsApp utiliza isso, basicamente, seu telefone está "matando" o WhatsApp, isso já ocorreu comigo e tirar o modo de economia resolveu.
