### ISSUE TITLE
⠀

### ISSUE THREAD

**Issue by LucasLIOM** [KillovSky/iris#471]
⠀

**Comment by LucasLIOM** [comment]
Ah sim, não sei se eu comentei na aba certa então peço desculpas pelo inconveniente.

**Comment by KillovSky** [comment]
> Opa Lucas, então cara eu estou querendo falar com você sobre isso a algum tempo mas sempre esqueci, é o seguinte, existe um cara (passo o nome dele depois) que está se passando como criador/programador da íris, ele removeu o comando criador e o about, por sorte dei o comando About e estava lá ainda, por algum motivo o cara me bloqueou no bot e não quis falar comigo nem me desbloquear, enfim ele tá literalmente se passando por programador, o que eu acho uma puta sacanagem o cara fazer isso, admiro pacas o teu projeto e acompanho a bastante tempo. Se você quiser mais detalhes ou algo do tipo, eu tenho o número dele, o número do bot e os prints, se quiser conversar comigo no privado sobre isso fica a sua disposição, abraços!

Boa noite! Agradeço por informar uma possivel quebra no contrato, todavia, falei com os devs responsáveis pelo `BOT Kaotic` e foi feita uma verificação por quebras de contrato de uso desse projeto.

Não houve nenhuma quebra de contrato, eles mantiveram os créditos e explicaram a situação do atual problema, da qual ao meu ver, se trata de uma simples discussão.

Portanto, nada será feito, pois eles estão cumprindo com excelencia os termos de uso.

Como estou respondendo isso se você apagou o post?

A `Github` mantém o historico de edições, tudo que você posta é armazenado em versões que ficam livres para qualquer um ver.

![Screenshot_2021-12-28-22-09-11-694_com.whatsapp_1.jpg](https://user-images.githubusercontent.com/55511420/147618389-0b7dff8a-18ec-4a56-9284-58f0172ad36b.jpg)

**Comment by KillovSky** [comment]
> Opa Lucas, então cara eu estou querendo falar com você sobre isso a algum tempo mas sempre esqueci, é o seguinte, existe um cara (passo o nome dele depois) que está se passando como criador/programador da íris, ele removeu o comando criador e o about, por sorte dei o comando About e estava lá ainda, por algum motivo o cara me bloqueou no bot e não quis falar comigo nem me desbloquear, enfim ele tá literalmente se passando por programador, o que eu acho uma puta sacanagem o cara fazer isso, admiro pacas o teu projeto e acompanho a bastante tempo. Se você quiser mais detalhes ou algo do tipo, eu tenho o número dele, o número do bot e os prints, se quiser conversar comigo no privado sobre isso fica a sua disposição, abraços!

Boa noite! Agradeço por informar uma possivel quebra no contrato, todavia, falei com os devs responsáveis pelo `BOT Kaotic` e foi feita uma verificação por quebras de contrato de uso desse projeto.

Não houve nenhuma quebra de contrato, eles mantiveram os créditos e explicaram a situação do atual problema, da qual ao meu ver, se trata de uma simples discussão.

Portanto, nada será feito, pois eles estão cumprindo com excelencia os termos de uso.

Como estou respondendo isso se você apagou o post?

A `Github` mantém o historico de edições, tudo que você posta é armazenado em versões que ficam livres para qualquer um ver.

![Screenshot_2021-12-28-22-09-11-694_com.whatsapp.jpg](https://user-images.githubusercontent.com/55511420/147618506-c4f459ae-639a-4494-b6f5-4776b9e2070a.jpg)
