### ISSUE TITLE
problema Node_modules

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#474]
![image](https://user-images.githubusercontent.com/44541791/147686469-67f7d216-1d4b-421e-a71b-2a1a4cc4b75b.png)

todo dias erro a vezes 

ja usei /npm update
e apagar logs e limpezar cache assim

Pastar Klona

```
		for (i=0, list=Object.getOwnPropertyNames(x); i < list.length; i++) {
			if (Object.hasOwnProperty.call(tmp, k=list[i]) && tmp[k] === x[k]) continue;
			set(tmp, k, Object.getOwnPropertyDescriptor(x, k));
		}
```

**Comment by KillovSky** [comment]
Esse erro não é na Íris em si, parece ser um erro de tratamento de `Object's`, o que pode ser referente ao `Puppeteer` que se remete a `Wa-Automate`, pois o código da Íris não utiliza o módulo `Klona`, tente reinstalar mas no `Disco Local C:\`.

**Comment by maradona4** [comment]
Deu certo, normal pc
