### ISSUE TITLE
erro na linha } else if (Object.keys(cmds['global']).includes(command)) {

### ISSUE THREAD

**Issue by DeyvissonSnuffs** [KillovSky/iris#475]
![image](https://user-images.githubusercontent.com/85204721/147840627-52c3b054-7936-4796-8cb8-12ad9cd456ad.png)
![image](https://user-images.githubusercontent.com/85204721/147840602-f59762d3-b161-4e1b-9d70-80a5c17cfa4e.png)

**Comment by DeyvissonSnuffs** [comment]
erro nos comando
antiporn 
greet
antifake

**Comment by KillovSky** [comment]
Farei uma analise para o update, sobretudo, me parece que os erros são referentes a sua pasta `Gerais`, você está restaurando um backup muito antigo?
Apenas Backups da `3.2.5` são compatíveis com a `3.2.5`, se você tentar restaurar um Backup da `3.2.4`, esses erros podem ocorrer.

**Comment by KillovSky** [comment]
Não obtive erros nos testes usando a versão `3.2.5`, aparentemente o erro é somente ai, espere a atualização da `3.2.6` e teste-a.

**Comment by KillovSky** [comment]
Leia a descrição do [Update 3.2.6](https://github.com/KillovSky/iris/commit/056c014cb53f8d61010f062a64549e614ba847a8) e divirta-se com as melhorias!
