### ISSUE TITLE
iris-dev blackJack 3.2.5 

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#477]
Falhar Auto Sticker

![Screenshot_20220103-135124_WhatsApp](https://user-images.githubusercontent.com/44541791/147957411-ac9a1a35-d376-4863-a638-d25333f6a40a.jpg)

![Screenshot_20220103-135129_WhatsApp](https://user-images.githubusercontent.com/44541791/147957379-50ee0ef9-5fc0-4dca-be1e-672e81e868fb.jpg)

**Comment by KillovSky** [comment]
Obrigado por informar, farei a verificação agora e uma correção para enviar na `3.2.6`.

Se eu estiver certo, até amanha de tarde é o prazo para o lançamento dessa versão, se nada ocorrer, claro.

**Comment by jacksonw8** [comment]
![image](https://user-images.githubusercontent.com/96899937/147969859-394a19b3-016e-4a3b-89cc-cdb00f7aa712.png)

![image](https://user-images.githubusercontent.com/96899937/147969920-7c65b427-3e1c-403f-83fd-833c96f5c3d5.png)

![image](https://user-images.githubusercontent.com/96899937/147969937-7c3edade-2faf-4f14-b43c-462d8f87898a.png)

![image](https://user-images.githubusercontent.com/96899937/147969968-a55673e3-bf2e-4bba-897b-9fcde20ddc48.png)


![image](https://user-images.githubusercontent.com/96899937/147969989-996bdf7d-fad2-4c82-8ea1-ecbf37a43158.png)


erro ao dar o comando /botfoto na versao iris 3.1.1, onde eu consigo a versao mais recente da iris ?

**Comment by KillovSky** [comment]
Leia a descrição do [Update 3.2.6](https://github.com/KillovSky/iris/commit/056c014cb53f8d61010f062a64549e614ba847a8) e divirta-se com as melhorias!

**Comment by maradona4** [comment]
Oba
