### ISSUE TITLE
erro no comando /botfoto iris 3.1.1

### ISSUE THREAD

**Issue by jacksonw8** [KillovSky/iris#478]
![image](https://user-images.githubusercontent.com/96899937/147969859-394a19b3-016e-4a3b-89cc-cdb00f7aa712.png)

![image](https://user-images.githubusercontent.com/96899937/147969920-7c65b427-3e1c-403f-83fd-833c96f5c3d5.png)

![image](https://user-images.githubusercontent.com/96899937/147969968-a55673e3-bf2e-4bba-897b-9fcde20ddc48.png)

![image](https://user-images.githubusercontent.com/96899937/147969989-996bdf7d-fad2-4c82-8ea1-ecbf37a43158.png)

erro ao dar o comando /botfoto na versao iris 3.1.1, onde eu consigo a versao mais recente da iris a 3.2.6?

**Comment by KillovSky** [comment]
Tente instalar a [Versão 3.2.6](https://github.com/KillovSky/iris/tree/dev) e divirta-se!
Não esqueça de ler a descrição do [Update 3.2.6](https://github.com/KillovSky/iris/commit/056c014cb53f8d61010f062a64549e614ba847a8).
