### ISSUE TITLE
BUG -> Anti Adicionar em Chats

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#479]
![image](https://user-images.githubusercontent.com/44541791/148064279-78d84856-f006-4f90-8d25-816f9ae5ac2b.png)

**Comment by maradona4** [comment]
oki

**Comment by KillovSky** [comment]
Corrigi os BUG's descritos aqui, o update com as correções vai demorar pois vai trazer algo inovador e extremamente dificil de criar rapidamente, por isso, precisarei de muito tempo, espero que vocês entendam e agradeço pela paciência.

**Comment by KillovSky** [comment]
Corrigi os BUG's descritos aqui, o update com as correções vai demorar pois vai trazer algo inovador e extremamente dificil de criar rapidamente, por isso, precisarei de muito tempo, espero que vocês entendam e agradeço pela paciência.
A issue permanecerá aberta até o lançamento da nova edição da Íris.

**Comment by maradona4** [comment]
Ok😉
