### ISSUE TITLE
Caiu a conta

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#481]
Conta caindo nível 0, coin, xp etc.

Antes
![Screenshot_20220104-191254_WhatsApp](https://user-images.githubusercontent.com/44541791/148131341-618578aa-f9a6-4c3f-8b64-fcf114244bcc.jpg)

Depois
![Screenshot_20220104-191244_WhatsApp](https://user-images.githubusercontent.com/44541791/148131363-44a00b69-dfa7-49d6-a1d8-f0e69aadbeb9.jpg)

**Comment by KillovSky** [comment]
Não faço a menor ideia do por que isso ocorreu se for um bug, mas baseado na `#` de usuario dele, a localização dele no arquivo `level.json` mudou.

Isso significa que:

1. Você usou o comando em dois grupos diferentes, a Íris tem um sistema de XP diferente para cada grupo, ou seja, o XP de um grupo não é considerado em outro grupo.

2. Você ou a Íris fizeram uma edição no arquivo em tempo real.

3. A Íris rodou um comando que fez com que esperasse mais de 5 horas (???), enquanto isso, ela não armazenou as mudanças no sistema, escrevendo o arquivo de 5 horas atrás novamente e perdendo todos os avanços.

A opção 3 é praticamente "quase impossivel", pois a Íris auto-atualiza os `JSON's`, mas nunca se sabe se houve um problema do tipo.

A opção 1 se encaixa totalmente na descrição do seu problema.

**Comment by maradona4** [comment]
Sim mas outro diferente lvl 0, 

grupos real, era nível 3, então o nível 0 pode acontecer caiu a conta lvl 0
configuração  função gaming.js  object "Keys"

**Comment by maradona4** [comment]
![image](https://user-images.githubusercontent.com/44541791/148254303-0cb34f28-5940-4022-89c5-2c01bbb06248.png)

undefined

não fiz editar gaming.js
![image](https://user-images.githubusercontent.com/44541791/148254493-f3a8420b-df57-478b-add8-d9cd91e40edb.png)

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/148254303-0cb34f28-5940-4022-89c5-2c01bbb06248.png)
> 
> undefined
> 
> não fiz editar gaming.js
> ![image](https://user-images.githubusercontent.com/44541791/148254493-f3a8420b-df57-478b-add8-d9cd91e40edb.png)
> 

Faça uma reinstale e não edite nada, pelo que estou vendo, você pode ter feito edições incorretas nos parametros `addValue`, pois o sistema de `level.json` está totalmente incorreto, isso não ocorre comigo, portanto, se você fez edicões, o problema está nelas.

**Comment by KillovSky** [comment]
Faça uma reinstalação e não edite nada, pelo que estou vendo, você pode ter feito edições incorretas nos parametros `addValue`, pois o sistema de `level.json` está totalmente incorreto, isso não ocorre comigo, portanto, se você fez edicões, o problema está nelas.

P.S: Pelo seu modo de falar, você aparenta não ser brasileiro, por isso, fica muito dificil entender o que você escreve em português, peço que por gentileza, em futuras issues e comentarios, use um tradutor ou fale no seu idioma nativo/idioma que domina completamente, para que as mensagens não se tornem tão confusas.

**Comment by maradona4** [comment]
Entendi
