### ISSUE TITLE
Aguarde

### ISSUE THREAD

**Issue by patulinomods** [KillovSky/iris#482]
Ola caro desenvolvedor dessa arte, estava usando a verçao normal da iris e ela tambem estava com o mesmo erro que irei citar abaixo, ate que mudei para a iris dev e continuou, o erro basicamente e que qualquer mensagem recebida no whatsapp web no servidor(vps) da iris , esta chegando os comandos e as mensagens no **Aguarde** do whatsapp, isso ett ocorre um serio erro na hora da iris detectar os comandos , pois como a mensagem esta chegando no aguarde , os comandos estao contando como mensagens

![image](https://user-images.githubusercontent.com/73912095/148219373-05b35fff-b636-4b47-9a6c-db38b24bfea3.png)

**Comment by KillovSky** [comment]
Esse erro não é na Íris e sim no WhatsApp do seu telefone, é bastante comum em WhatsApp's modificados e imunes, o problema é automaticamente corrigido depois de um tempo, basta ficar conectado na internet com o WhatsApp do celular aberto e claro, limpe as mensagens, telefone, pasta da Íris e outros, por fim, clique em `Ler Mais` e leia o que o WhatsApp diz.
