### ISSUE TITLE
BUG -> Contar, NoAdmins, AllAdmins, Sticker, Arquivar, Github e outros

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#483]
4 comandos erro

CMD GitHub
![image](https://user-images.githubusercontent.com/44541791/148307644-7c8f25d2-342a-4775-a0d6-4444e1d2273c.png)

CMD Stalkig e /contar 
![image](https://user-images.githubusercontent.com/44541791/148307682-f617c5ce-67a9-4ba5-948a-9515f7b52b67.png)

CMD Sticker -Fill
![image](https://user-images.githubusercontent.com/44541791/148313970-0f44aa6a-68b9-4555-bae0-4d9fdcf3e416.png)

comandos esta funcionar -cut -circle e sticker normal , erro -fill

**Comment by maradona4** [comment]
> /arquivar

a vdd, tambem /noadmin e /alladmin

**Comment by KillovSky** [comment]
Entendido, vou verificar

**Comment by MenezesKvl** [comment]
Onde eu consigo baixar a iris 3.2.6????

**Comment by KillovSky** [comment]
> Onde eu consigo baixar a iris 3.2.6????

#416

**Comment by ruip005** [comment]
Welcome > 'remove' não ta dando n

**Comment by KillovSky** [comment]
Corrigi os BUG's descritos aqui, o update com as correções vai demorar pois vai trazer algo inovador e extremamente dificil de criar rapidamente, por isso, precisarei de muito tempo, espero que vocês entendam e agradeço pela paciência.
A issue permanecerá aberta até o lançamento da nova edição da Íris.

**Comment by KillovSky** [comment]
> Welcome > 'remove' não ta dando n 

Crie uma outra issue e detalhe-a.

**Comment by gabrieldias1999** [comment]
> Corrigi os BUG's descritos aqui, o update com as correções vai demorar pois vai trazer algo inovador e extremamente dificil de criar rapidamente, por isso, precisarei de muito tempo, espero que vocês entendam e agradeço pela paciência. A issue permanecerá aberta até o lançamento da nova edição da Íris.

Olá, tem alguma data pra nova versão da Íris?

**Comment by KillovSky** [comment]
> > Corrigi os BUG's descritos aqui, o update com as correções vai demorar pois vai trazer algo inovador e extremamente dificil de criar rapidamente, por isso, precisarei de muito tempo, espero que vocês entendam e agradeço pela paciência. A issue permanecerá aberta até o lançamento da nova edição da Íris.
> 
> Olá, tudo bom? Tem alguma data pra nova versão da Íris com esses problemas resolvidos?

Sem uma data especifica, pode ser que eu envie a atualização sem terminar o RPG, ou seja, talvez eu adie o RPG para uma futura atualização, desta forma, o update sairia bem rapidinho.
