### ISSUE TITLE
BUG -> AFK Mode

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#485]
AFK Off

![Screenshot_20220108-003520_WhatsApp](https://user-images.githubusercontent.com/44541791/148630223-78d446d8-8bb0-4a5f-a67a-73d835717929.jpg)
⁸

**Comment by KillovSky** [comment]
Estranho, darei uma olhads hoje.

**Comment by KillovSky** [comment]
Estranho, darei uma olhada hoje.
Apenas espere por uma atualização se for um BUG.
P.S -> Desligar o `AFK` não precisa de `|`, apenas `/AFK off`.

**Comment by KillovSky** [comment]
Corrigi os BUG's descritos aqui, o update com as correções vai demorar pois vai trazer algo inovador e extremamente dificil de criar rapidamente, por isso, precisarei de muito tempo, espero que vocês entendam e agradeço pela paciência.
A issue permanecerá aberta até o lançamento da nova edição da Íris.
