### ISSUE TITLE
Botoes

### ISSUE THREAD

**Issue by patulinomods** [KillovSky/iris#487]
Ola lucas, tudo bem? ett , estou obtendo uma dificultade no uso dos botoes, estou usando a verçao dev da iris. E o seguinte, na verçao dev da iris, o codigo sem modificaçao alguma, ja vem feito para utilizar os botoes, certo? entao, ate mesmo o comando /menu ja vem com os botoes, mas o poblema que  ela nao envia os botoes, aparece "digitando..." mas n manda os botoes de forma alguma, e tmb nao tem erro no console. Espero sua ajuda

**Comment by KillovSky** [comment]
Fez o teste no PV e está com todos os módulos atualizados e no Chrome?

**Comment by patulinomods** [comment]
sim

**Comment by patulinomods** [comment]
Creio que esta tudo atualizado, o chroe tambem, pois acabei de pegar uma vps e baixar o chrome

**Comment by dodouuglas** [comment]
> Ola lucas, tudo bem? ett , estou obtendo uma dificultade no uso dos botoes, estou usando a verçao dev da iris. E o seguinte, na verçao dev da iris, o codigo sem modificaçao alguma, ja vem feito para utilizar os botoes, certo? entao, ate mesmo o comando /menu ja vem com os botoes, mas o poblema que ela nao envia os botoes, aparece "digitando..." mas n manda os botoes de forma alguma, e tmb nao tem erro no console. Espero sua ajuda

como q ve a versao dev?

**Comment by KillovSky** [comment]
> Creio que esta tudo atualizado, o chrome tambem, pois acabei de pegar uma vps e baixar o chrome

Tente limpar a `VPS` apagando -> `Logs, Iris_Data, Package_lock.json`.

Abra o `index.js` e remova a linha `tools('others').clearFile(...)` que executa a limpeza do Chrome.

Desligue o acesso ao `WhatsApp Web` do telefone, ou seja, desconecte o `WhatsApp Web`.

Rode `npm update` - Esteja usando a versão LTS mais recente.

Ligue e escaneie o QR, faça um teste.

----

> Como ver a versão DEV?

Leia a discussions, sempre esteve escrito lá.

**Comment by patulinomods** [comment]
Entao, fiz tudo para limpar a vps, agora instalei a verçao mais recente do nodejs, mas quando vou dar npm start, ocorre um erro no canvas:

![image](https://user-images.githubusercontent.com/73912095/149205284-16c854b3-479b-45b0-9a3e-b3419f08f923.png)

**Comment by patulinomods** [comment]
Arrumei o bug do canvans deletando canvascord e o canvas e refazendo a instalaçao individual dos dois, mas mesmo assim ela nao envia os botoes:

![image](https://user-images.githubusercontent.com/73912095/149205833-d080cb89-f6a6-4677-9ffb-36ec7d8d7f35.png)

**Comment by KillovSky** [comment]
Tente sem o `Multiple-Devices`, se mesmo assim não enviar, mande uma issue para a `Wa-Automate`.

**Comment by KillovSky** [comment]
Não houve erros em meus testes e outras BOT's que conheço, tente fazer a reinstalação, pode ser que seja um erro local que aconteceu no dia.

![IMG_20220117_122624.png](https://user-images.githubusercontent.com/55511420/149797412-14dc220c-6c3f-4a3c-9be0-98bbfde575af.png)

**Comment by patulinomods** [comment]
Mandei mensagem para o open-wa, agora e so esperar responderem, nao e a primeira vez que isso ocorre comigo, a umas 3 vps que esse erro vem acontecendo , caso arrumem notificarei voce e os outros
