### ISSUE TITLE
Comando /corno e outros

### ISSUE THREAD

**Issue by patulinomods** [KillovSky/iris#488]
Ola lucas , eu aki dnv e o seguite, todos os comandos que precisa de algum arquivo , tupo o /corno e outros, nao esta funcionando, um exemplo e o /atirar ( nao lembro se eh esse o comando) , aparece assim _"Tau pessoa atirou em tau pessoa com uma undefinid"_ e que no caso era para esta aparecendo _"Tau pessoa atirou em tau pessoa com uma ak47"_ , tmn nao da erro

Print:

![image](https://user-images.githubusercontent.com/73912095/148839031-009e0103-5b32-42cb-bfe2-4b2d01b37c32.png)

**Comment by KillovSky** [comment]
Faça esse [Tutorial](https://github.com/KillovSky/iris/issues/456#issuecomment-1001087525).
