### ISSUE TITLE
BUG -> Loteria não funciona por conter código inválido

### ISSUE THREAD

**Issue by swatky** [KillovSky/iris#492]
Olá, ao testar a loteria, notamos que quando se ganha i'coin, aparece que o ganho foi "indefinido" como na imagem abaixo:
![image](https://user-images.githubusercontent.com/40281950/149430287-eb3e5b19-b47d-49d1-a38a-28a7f9cf8420.png)
E quando se compra uma loteria nova, mostra que o ultimo ganhador, ganhou 0 de premium, seja ele xp, dima, etc.
![image](https://user-images.githubusercontent.com/40281950/149430351-2728ac5d-5edd-4e2b-9c98-e0734808b499.png)

![image](https://user-images.githubusercontent.com/40281950/149430373-9daff04b-f42c-4ce0-a98b-f9ebdd36a24f.png)

**Comment by KillovSky** [comment]
Vou fazer um teste para ver onde está o erro, aguarde por informações.

**Comment by KillovSky** [comment]
Corrigi os BUG's descritos aqui, o update com as correções vai demorar pois vai trazer algo inovador e extremamente dificil de criar rapidamente, por isso, precisarei de muito tempo, espero que vocês entendam e agradeço pela paciência.
A issue permanecerá aberta até o lançamento da nova edição da Íris.

**Comment by swatky** [comment]
Muito obrigado pela ajuda, estarei no aguardo do lançamento.
