### ISSUE TITLE
Ajuda em modificação do bot

### ISSUE THREAD

**Issue by EmanuelPeixoto** [KillovSky/iris#493]
Primeiramente desculpa, sei que você não ajuda modificações, mas não sei mais o que fazer, quero fazer algo para após X tempo o bot reiniciar automaticamente, mas o config.js só roda quando recebe mensagem, onde que ele fica em loop direto pra mim colocar essa parte do reload após um tempo?

**Comment by KillovSky** [comment]
Na `Index.js`, faça um sistema usando `setTimeout`, é o local que você procura.
