### ISSUE TITLE
BUG -> Comando Clear falha na limpeza de mensagens

### ISSUE THREAD

**Issue by coelhobugado** [KillovSky/iris#495]
comando clear doidao da vida antes apagava td mas agora so o chat aonde mandei a mensagem e da esse erro: 

(node:8088) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'msgs')
    at Object.window.<computed>.<computed> [as reply] (__puppeteer_evaluation_script__:1:202045)
    at ExecutionContext._evaluateInternal (C:\Users\gabri\alfred\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (C:\Users\gabri\alfred\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8088) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:8088) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by KillovSky** [comment]
A mensagem de amore é enviada quando a pessoa usa um comando que precisa que ela espere terminar antes de usar novamente, não é um BUG (talvez seja, mas se você não mostrar uma print é dificil saber).

**Comment by coelhobugado** [comment]
o comando /clear essta com "defeito" antes quando eu dava o comando ele apagava todas as conversas do zap agora ele so apaga do chat aonde mando, se mando no pv ele apaga so a do pv se mando em um grupo ele apaga so desse grupo....

**Comment by KillovSky** [comment]
> o comando /clear essta com "defeito" antes quando eu dava o comando ele apagava todas as conversas do zap agora ele so apaga do chat aonde mando, se mando no pv ele apaga so a do pv se mando em um grupo ele apaga so desse grupo....

Entendido, fiz uma correção hoje ao reescrever alguns comandos do zero, o `clear` é um deles, irei enviar na 3.2.7, até lá, peço que possa ser paciente, agradeço!
