### ISSUE TITLE
Como eu tiro esse script do menu?

### ISSUE THREAD

**Issue by MenezesKvl** [KillovSky/iris#496]

**Comment by KillovSky** [comment]
Se você não mostrar o que quer remover é impossivel que eu leia sua mente ou advinhe, detalhe seu problema com problemas obtidos e tire uma print mostrando.

**Comment by MenezesKvl** [comment]
Quando digita menu aparece um script com todos os comandos logo a baixo, como eu removo isso ???

**Comment by KillovSky** [comment]
> Quando digita menu aparece um script com todos os comandos logo a baixo, como eu removo isso ??? 

Procure pela `case 'menu':` e apague a linha `kill.reply` que está acima do `break`.
