### ISSUE TITLE
Como coloco pra ativar o autosticker nas conversas privadas

### ISSUE THREAD

**Issue by peraltakw** [KillovSky/iris#497]
Como faço pra ativar o autosticker nas conversas privadas, queria essa opção pra não precisar usar comando nenhum

**Comment by KillovSky** [comment]
Isso "ainda" não é possivel pois o sistema é limitado a grupos.

Todavia, você pode deslimitar isso indo até a linha do `Auto-Sticker`, basta procurar `await kill.sendImageAsSticker`, em cima dele vai ter um `if` e na frente `isGroupMsg`, se você apagar o `isGroupMsg && `, o sistema passará a funcionar em privados, todavia, é necessario ativar o `autosticker` no PV, e claro, isso pode ser problematico, podendo causar **BAN** no WhatsApp - inclusive, mesmo se usado em grupos - o meio de não ser banido é não floodar o sistema de `Auto-Sticker`.

Marcarei isso como uma futura feature a ser construida.

**Comment by peraltakw** [comment]
Obrigado então não irei ativar no momento não.. Muito obrigado pela informação
