### ISSUE TITLE
[BUG / PARCIAL] -> Erro 404 no sistema de welcome

### ISSUE THREAD

**Issue by Guixaviertga** [KillovSky/iris#499]
![Captura de Tela (161)](https://user-images.githubusercontent.com/96479111/150603634-b2d10499-0d9a-4a57-857d-fe628246166c.png)
![Captura de Tela (162)](https://user-images.githubusercontent.com/96479111/150603637-3f0b56b7-1a05-423a-99cf-69278f420f7c.png)
![Screenshot_2022-01-21-18-21-35-421_com gbwhatsapp](https://user-images.githubusercontent.com/96479111/150607969-215cf0a9-e35f-4e42-a4ac-c7abba444227.jpg)

**Comment by dodouuglas** [comment]
me manda essa mensagem de erro kkk

**Comment by KillovSky** [comment]
Verifique se os usuarios estão com fotos de perfil que podem ser vistas por todos, esse erro me diz que a foto de perfil não conseguiu ser acessada pois "não existe", irei trabalhar em um fix que não use canvas quando isso acontecer.

O erro de softban é auto-explicativo, esse erro só acontece quando a pessoa proibe a função de adicionar em grupos, por isso, não é um BUG, apenas inseri a mensagem de erro na resposta, para capturar uma informação maior caso ocorra um erro diferente.
