### ISSUE TITLE
download commands don't work

### ISSUE THREAD

**Issue by zaskker** [KillovSky/iris#50]
I do not speak english very well
I have a problem using the download commands, I put a maximum of 64mb and it tells me that it exceeds the sending limit and an audio file is not larger than 4mb, why does this error occur? can you help me?

Obtive erros no comando !play → Command failed with exit code 1: C:\Users\Franco\Desktop\iris-main\node_modules\youtube-dl-exec\bin\youtube-dl.exe https://youtu.be/doLMt10ytHY --no-warnings --no-call-home --no-check-certificate --prefer-free-formats --youtube-skip-dash-manifest --referer https://youtu.be/doLMt10ytHY -x --audio-format mp3 -o ./lib/media/audio/551238716313.mp3
ERROR: ffprobe/avprobe and ffmpeg/avconv not found. Please install one.
[youtube] doLMt10ytHY: Downloading webpage
[download] Destination: lib\media\audio\551238716313.mp3
[download] 100% of 3.60MiB in 00:00                   - Você pode ignorar.

**Comment by PedroBatistop** [comment]
Make sure you installed FFmpeg correctly. For a tutorial on installing FFmpeg on Windows 7/8, see WikiHow (https://pt.wikihow.com/Instalar-o-FFmpeg-no-Windows), for Windows 10 see SoundArtifacts (https://soundartifacts.com/pt/how-to/186-how-to-install-ffmpeg-on-windows-10-amp-add-ffmpeg-to-windows-path.html).

**Comment by zaskker** [comment]
> Asegúrese de haber instalado FFmpeg correctamente. Para obtener un tutorial sobre la instalación de FFmpeg en Windows 7/8, consulte WikiHow ( https://pt.wikihow.com/Instalar-o-FFmpeg-no-Windows ), para Windows 10 consulte SoundArtifacts ( [https://soundartifacts.com/ pt / how-to / 186-how-to-install-ffmpeg-on-windows-10-amp-add-ffmpeg-to-windows-path.html](https://soundartifacts.com/pt/how-to/186-how-to-install-ffmpeg-on-windows-10-amp-add-ffmpeg-to-windows-path.html) ).

Thanks men! It worked
