### ISSUE TITLE
Problema com parâmetro ID

### ISSUE THREAD

**Issue by patulinomods** [KillovSky/iris#501]
Consegui uma parceria com uma pessoa do tiktok, e o meu bot fica  dando esse bug e se auto desligando, como antes eu n ligava muito , nao tinha poblema, mais agr ela vai divulgar o bot para mais de 400 mil pessoas, se puder me ajudar a arrumar esse bug . 
Nao sei pq ele ocorre , a principio , pensei que era o comando /tits , mas fui ver o console mais para cima e n dava erro quando executava esse comando

![image](https://user-images.githubusercontent.com/73912095/150705654-f148378e-981d-4257-b5d4-dd61966ada0f.png)

**Comment by KillovSky** [comment]
Esse erro é na `puppeteer`, ou seja, por parte da `Wa-Automate`.

Sua versão está desatualizada, rode `npm update` e teste, pode ser que a atualização da `Wa-Automate` seja a correção disto.

**Comment by maradona4** [comment]
Eu também, outra pessoa apaga a mensagem mais rápido...

![image](https://user-images.githubusercontent.com/44541791/150708251-97674727-1ace-401a-88cc-55ed408a4c82.png)

este "ID", bot  marca onde mensagem, acho que apagar mensagem bot falha, este usando "kill.reply" marca mensagem "ID"

usar "sendText" sei la..

**Comment by patulinomods** [comment]
Acabei de fazer oque voce pediu, e esta dando a mesma coisa:

![image](https://user-images.githubusercontent.com/73912095/150709017-12b97a1c-e335-43ad-8d20-f0b97ad91116.png)

**Comment by patulinomods** [comment]
> Eu também, outra pessoa apaga a mensagem mais rápido...
> 
> ![image](https://user-images.githubusercontent.com/44541791/150708251-97674727-1ace-401a-88cc-55ed408a4c82.png)
> 
> este "ID", bot marca onde mensagem, acho que apagar mensagem bot falha, este usando "kill.reply" marca mensagem "ID"
> 
> usar "sendText" sei la..

Percebi uma coisa, nois dois estamos usando o git bash, sera que tem algo a ver? se for , basicamente ferrou, pois ai outros comandos vai parar de pegar

**Comment by KillovSky** [comment]
> Esse erro é na `puppeteer`, ou seja, por parte da `Wa-Automate`.
> 
> Sua versão está desatualizada, rode `npm update` e teste, pode ser que a atualização da `Wa-Automate` seja a correção disto.

A `ID` no caso não está lendo, como o @maradona4 disse, embora isso seja muito estranho pois BUG's assim são bem dificies de ocorrer, troque `kill.reply` por `kill.sendText`, notei que você não costuma usar `await`, saiba que isso é necessario nos comandos, deixar sem await é claramente não usar `promise`, a maioria dos comandos e sistemas da Íris usa `promise`, ou seja, `await`, e claro, verifique se o BUG ocorre em um comando da Íris ou algo que você criou, se você criou um comando e ele está dando este erro, é por que alguma coisa segue errada no seu código, e isto é o parametro `ID` ou onde ele deveria estar.

Caso seja o que o @maradona4 disse sobre mensagens apagadas, é conveniente criar uma `var` fora do sistema (como a `var region`) que armazene a `ID` anterior e utilize ela no caso da `ID` nova ser `null`, isso eu farei pois é dificil demais dar uma explicação de como fazer.

**Comment by KillovSky** [comment]
Fiz o teste e não me ocorreu com as versões mais recentes da `Wa-Automate`, pode ser um problema isolado a somente esse dia/versão dela.
