### ISSUE TITLE
Erro ao ligar na vps

### ISSUE THREAD

**Issue by BruZim03** [KillovSky/iris#504]
Fiz uma reinstalação da iris antiga e da esse erro ao ligar

![Screenshot_10](https://user-images.githubusercontent.com/77207248/150826319-1618c7d9-d1fb-46ce-aaec-7fb6d0e55c66.png)

**Comment by patulinomods** [comment]
tente `npm i @open-wa/wa-automate`
So para tirar umas duvidas, Esta usando qual tipo de vps, qual verçao da iris ( verçao dev ou verçao normal)?

**Comment by BruZim03** [comment]
> patulinomods

deu certo, vlw
