### ISSUE TITLE
Duvida

### ISSUE THREAD

**Issue by MokZueira12** [KillovSky/iris#505]
![image](https://user-images.githubusercontent.com/62519017/150847168-4c257168-698a-48cd-8fc2-e8c531840289.png)
Oi, queria saber se tem alguma forma que na hora que eu adiciono o bot em algum grupo, ele ira mencionar todos os membros com a msg do print

**Comment by KillovSky** [comment]
No sistema atual não é possivel, você pode fazer isso adicionando `kill.sendTextWithMentions` em vez de `kill.sendText` na `index.js` e adicionar a variavél que contém os membros na mensagem, é um tantinho dificil, então irei marcar como feature a ser construida, darei noticias no próximo update.

#316
