### ISSUE TITLE
Ajuda /mix, /corno  Iris 3.2.6

### ISSUE THREAD

**Issue by prokda** [KillovSky/iris#506]
Killovsky, consegue ajudar em relação ao mix, corno.
Fiz o tutorial do #456, adicionei a git ao PATH, mas ainda nada.

![image](https://user-images.githubusercontent.com/79275944/151087633-63a47360-9d0b-45b7-944e-ad7c0586d114.png)

**Comment by KillovSky** [comment]
Tente abrir a Íris pelo Git Bash, as vezes, adicionar ao `PATH` pode não funcionar (o que é estranho), todavia, usar o `Git Bash` será um sucesso.

Certifique-se de que:

. - Após inserir o `bash.exe` na `PATH`, você reiniciou o terminal ou PC.

. - Que instalou `GOW`.

. - Que o `PATH` foi alterado corretamente.

Tente por fim, caso não queira usar o `Git Bash`, digitar `bash` no terminal que você costuma usar e então abrir a Íris com o `npm start`.

**Comment by KillovSky** [comment]
Tente abrir a Íris pelo `Git Bash`, as vezes, adicionar ao `PATH` pode não funcionar (o que é estranho), todavia, usar o `Git Bash` será um sucesso.

Certifique-se de que:

. - Após inserir o `bash.exe` na `PATH`, você reiniciou o terminal ou PC.

. - Que instalou `GOW`.

. - Que o `PATH` foi alterado corretamente.

Tente por fim, caso não queira usar o `Git Bash`, digitar `bash` no terminal que você costuma usar e então abrir a Íris com o `npm start`.

**Comment by KillovSky** [comment]
Tente abrir a Íris pelo `Git Bash`, as vezes, adicionar ao `PATH` pode não funcionar (o que é estranho), todavia, usar o `Git Bash` será um sucesso.

Certifique-se de que:

- Após inserir o `bash.exe` na `PATH`, você reiniciou o terminal ou PC.

- Que instalou `GOW`.

- Que o `PATH` foi alterado corretamente.

Tente por fim, caso não queira usar o `Git Bash`, digitar `bash` no terminal que você costuma usar e então abrir a Íris com o `npm start`.

**Comment by prokda** [comment]
Vlw men mais uma vez, rodei pelo git bash e tá fumegando.
