### ISSUE TITLE
Performance is not defined

### ISSUE THREAD

**Issue by Lucas-LIOM** [KillovSky/iris#507]
Instalei a Íris por um outro computador, fiz a instalação certa do Node.js, instalei todos os módulos e importei as dependências, porém quando tento iniciar pelo terminal usando ```npm start``` ( o "padrão") porém ele dá esse erro de _TROUBLESHOTING_:

![image](https://user-images.githubusercontent.com/92343590/151164987-bb6ec211-4f86-43ae-afac-8b12a433b1e0.png)

Antes estava dando este erro, aparentemente consegui resolver mudando o diretório da pasta do Chrome. O problema desse _TROUBLESHOTING_ era justamente quando a Iris não encontrava a pasta do Chrome, logo quando eu movi ela parou de dar este erro, então a pasta ficou nesse caminho, acredito eu que esteja corretíssimo:

  ```C:\Program Files\Google\Chrome\Application\chrome.exe```

Agora ele dá esse novo erro de *Performance is not defined*, eu rodei a internet tentando achar algumas soluções porém não encontrei nada, tento rodar pelo ```Git Bash``` ou em outro terminal porém nada funciona também. Acreditei que fosse a pasta da minha bot então eu clonei seu repositório e instalei, porém deu a mesma coisa:

![image](https://user-images.githubusercontent.com/92343590/151162929-9d6d4b58-7503-43f4-8718-edf31206d693.png)

Então agora eu não sei o que fazer, o computador que estou usando é um PC limpo, fiz a instalação do zero mas nada adiantou, rodei  com ```pm2 start index.js``` mas não resolveu (ele até executa pelo PM2, porém a Iris não inicia, ela fica reiniciando over over over again). Se alguém tiver a solução me avise please <3

![image](https://user-images.githubusercontent.com/92343590/151164616-68c7ffa7-9548-4e48-900d-5a7890ff5c47.png)

**Comment by KillovSky** [comment]
Tente fazer a instalação da `Íris 3.2.6` -> #416

Sobre o `Chrome`, configure o local dele na `config.json`, no paramêtro `Chrome_Path`, basta trocar o `null` por aspas e inserir o local dentro.

Este erro que você mostrou é um BUG no código da `Wa-Automate`, basta esperar uma atualização por parte deles.

Mas creio que esse erro seja isolado pois não estou recebendo o mesmo, por isso, tente a `Íris 3.2.6`.

**Comment by Lucas-LIOM** [comment]
Ok então, vou tentar fazer essa instalação, de qualquer forma obrigado <3
