### ISSUE TITLE
comando detect

### ISSUE THREAD

**Issue by Guixaviertga** [KillovSky/iris#508]
![Captura de Tela (164)](https://user-images.githubusercontent.com/96479111/151264988-c8bc5fef-f982-4aeb-8616-59ebbec2ad00.png)

**Comment by patulinomods** [comment]
O erro esta na configuraçao das chaves api / api key do "ACR", verifique o arquivo _config.json_ localizado em _lib -> config -> gerais -> config.json_ , e verifique se as informaçoes fornecidas pela ACR estao corretas

**Comment by KillovSky** [comment]
Parece que houve má configuração da `ACR_Host`, um dos parâmetros da `config.json`, verifique o arquivo conforme instruções do @patulinomods.
