### ISSUE TITLE
bomb

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#509]
![image](https://user-images.githubusercontent.com/79427063/151381852-fdb5ebc0-6b2b-41c7-990d-503d1662c4c3.png)

**Comment by patulinomods** [comment]
Opa, beleza? subistitua esse _mess.bombstd_ por: _"Spam iniciado"_ ( obs: com as aspas )

**Comment by maradona4** [comment]
Pastar lang > pt.js

![image](https://user-images.githubusercontent.com/44541791/151443051-ab5f8ee8-7a75-469d-af9f-4cea051505b0.png)

**Comment by KillovSky** [comment]
https://github.com/KillovSky/iris/issues/108#issuecomment-895517518
