### ISSUE TITLE
Novo comando [Não Oficial / Já incluso no futuro update]

### ISSUE THREAD

**Issue by patulinomods** [KillovSky/iris#510]
O comando basicamente colori fotos antigas / preto e branco usando a API do [Deepai](https://deepai.org/), onde ela faz o upload da imagem para o telegram, e com o link da imagem do telegram ela faz a request na api do deepai, Codigo abaixo:

[Clique aki e veja o codigo](https://pastebin.com/raw/vAes9D5r) ( obs: so pega na verçao dev da iris, caso n utilize a verçao dev, ela se encontra [aki](https://github.com/KillovSky/iris/tree/dev))

**Exemplo do que esse comando faz:**

![image](https://user-images.githubusercontent.com/73912095/151438081-ec908007-9deb-4fdd-9d8e-dbcdb701c998.png)

_Obs: Quem for usar, por favor deixar os cretidos a mim ( Ruan Pablo )_

**Comment by maradona4** [comment]
![image](https://user-images.githubusercontent.com/44541791/151442842-48125a06-1a4d-406e-8136-6cff0cf3c3e6.png)

**Comment by patulinomods** [comment]
Poderia me mandar print do final do erro no console pfv?

**Comment by KillovSky** [comment]
Olá, agradeço, porém já fiz esse e muitos outros comandos de `Machine Learning` para enviar na `3.2.7`, todavia, obrigado por postar os códigos para os usuarios, seu código é similar ao meu e deve ser bem visto até a atualização.

**Comment by maradona4** [comment]
![image](https://user-images.githubusercontent.com/44541791/151571211-ea8c2efa-153d-450a-9ad2-5a1a3c5ae104.png)

**Comment by pablorere** [comment]
descobirmos terceirizacao de bots

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/151571211-ea8c2efa-153d-450a-9ad2-5a1a3c5ae104.png)
> 

`"Please activate your account..."`
