### ISSUE TITLE
erro no npm i

### ISSUE THREAD

**Issue by MatheusSan03** [KillovSky/iris#511]
mathe@itamachi MINGW64 ~/Documents/Nova pasta/iris (dev)
$ npm i
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated superagent@4.1.0: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>. Thanks to @shadowgate15, @spence-s, and @niftylettuce. Superagent is sponsored by Forward Email at <https://forwardemail.net>.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau

> youtube-dl-exec@2.0.2 preinstall C:\Users\mathe\Documents\Nova pasta\iris\node_modules\youtube-dl-exec
> npx bin-version-check-cli python ">=2"

npx: installed 91 in 16.827s
Error: Couldn't find version of `python`
    at binaryVersion (file:///C:/Users/mathe/AppData/Roaming/npm-cache/_npx/11024/node_modules/bin-version-check-cli/node_modules/bin-version/index.js:55:8)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async binaryVersionCheck (file:///C:/Users/mathe/AppData/Roaming/npm-cache/_npx/11024/node_modules/bin-version-check-cli/node_modules/bin-version-check/index.js:14:18)
npm WARN notsup Unsupported engine for @open-wa/wa-automate@4.30.7: wanted: {"node":">=12.18.3","npm":">=7.9.0"} (current: {"node":"14.17.5","npm":"6.14.14"})
npm WARN notsup Not compatible with your version of node/npm: @open-wa/wa-automate@4.30.7
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/darwin-arm64@4.1.5 (node_modules\@ffmpeg-installer\ffmpeg\node_modules\@ffmpeg-installer\darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/darwin-arm64@4.1.5: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/darwin-x64@4.1.0 (node_modules\@ffmpeg-installer\ffmpeg\node_modules\@ffmpeg-installer\darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/darwin-x64@4.1.0: wanted {"os":"darwin","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-arm@4.1.3 (node_modules\@ffmpeg-installer\ffmpeg\node_modules\@ffmpeg-installer\linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-arm@4.1.3: wanted {"os":"linux","arch":"arm"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-arm64@4.1.4 (node_modules\@ffmpeg-installer\ffmpeg\node_modules\@ffmpeg-installer\linux-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-arm64@4.1.4: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-ia32@4.1.0 (node_modules\@ffmpeg-installer\ffmpeg\node_modules\@ffmpeg-installer\linux-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-ia32@4.1.0: wanted {"os":"linux","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-x64@4.1.0 (node_modules\@ffmpeg-installer\ffmpeg\node_modules\@ffmpeg-installer\linux-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-x64@4.1.0: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/win32-ia32@4.1.0 (node_modules\@ffmpeg-installer\ffmpeg\node_modules\@ffmpeg-installer\win32-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/win32-ia32@4.1.0: wanted {"os":"win32","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN notsup Unsupported engine for @discordjs/collection@0.2.4: wanted: {"node":">=16.0.0","npm":">=7.0.0"} (current: {"node":"14.17.5","npm":"6.14.14"})
npm WARN notsup Not compatible with your version of node/npm: @discordjs/collection@0.2.4
npm WARN notsup Unsupported engine for @open-wa/wa-automate-types-only@4.30.7: wanted: {"node":">=12.18.3","npm":">=7.9.0"} (current: {"node":"14.17.5","npm":"6.14.14"})
npm WARN notsup Not compatible with your version of node/npm: @open-wa/wa-automate-types-only@4.30.7
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: nice-napi@^1.0.2 (node_modules\piscina\node_modules\nice-napi):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for nice-napi@1.0.2: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN swagger-stats@0.99.2 requires a peer of prom-client@>= 10 <= 13 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! youtube-dl-exec@2.0.2 preinstall: `npx bin-version-check-cli python ">=2"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the youtube-dl-exec@2.0.2 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mathe\AppData\Roaming\npm-cache\_logs\2022-01-28T13_50_31_203Z-debug.log
![image](https://user-images.githubusercontent.com/78276706/151559050-7b694a53-3bc3-4025-a4b4-6ac013a824aa.png)

**Comment by MatheusSan03** [comment]
eu colei o codigo tbm pq n ia caber no print

**Comment by KillovSky** [comment]
Use esse tutorial -> https://github.com/KillovSky/iris/issues/377#issuecomment-951801151
