### ISSUE TITLE
BUG -> Problema no sistema de checar o valor de XP (Privado)

### ISSUE THREAD

**Issue by pablorere** [KillovSky/iris#513]
![image](https://user-images.githubusercontent.com/65947059/151643127-f71bde76-7f79-4ee7-aa44-6f387f115cf3.png)
[FALHA GERAL] TypeError: Cannot read properties of undefined (reading 'xp')
 no erro e essa linha 
![image](https://user-images.githubusercontent.com/65947059/151643369-e73aef8f-d8b1-44a8-bc45-14219eca897c.png)

**Comment by KillovSky** [comment]
Seu sistema de XP corrompeu, restaure um backup ou baixe o `level.json` original ou edite-o e insira no lugar do atual.

Também pode ser referente a uma edição mal-sucedida nos códigos, ou claro, que você tenha colocado o `level.json` antigo, que é muito diferente e incompativel.

Modo de edição:

Abra o `level.json` e apague tudo, insira apenas `{}` dentro, salve e inicie. 

Se você editou os códigos de algum comando que utilize o XP, desfaça.

**Comment by KillovSky** [comment]
Fiz a verificação e isso é um BUG no quesito de separação de `chat's` no `level.json`, por hora, remova as linhas que você mostrou e isso corrige, elas não irão afetar gravemente o sistema, portanto, é seguro.

A correção disso sairá na `3.2.7`.

**Comment by pablorere** [comment]
> 

nao corrige na real nem inicia

**Comment by KillovSky** [comment]
> > 
> 
> nao corrige na real nem inicia
> ![image](https://user-images.githubusercontent.com/65947059/151665434-c7b34d28-40e0-4cbd-bcf8-58e4cc088aa3.png)
>  quando inicio sem a linha ou o bloco enteiro aparece isso 
> 

É por que você apagou errado, apague exatamente as mesmas linhas que você mostrou.

**Comment by pablorere** [comment]
> > > 
> > 
> > 
> > nao corrige na real nem inicia
> > ![image](https://user-images.githubusercontent.com/65947059/151665434-c7b34d28-40e0-4cbd-bcf8-58e4cc088aa3.png)
> > quando inicio sem a linha ou o bloco enteiro aparece isso
> 
> É por que você apagou errado, apague exatamente as mesmas linhas que você mostrou.

![image](https://user-images.githubusercontent.com/65947059/151665673-ef9d9431-c623-4bdf-95d4-ba403a5a842e.png)
esse bloco?

**Comment by KillovSky** [comment]
> > > > 
> > > 
> > > 
> > > nao corrige na real nem inicia
> > > ![image](https://user-images.githubusercontent.com/65947059/151665434-c7b34d28-40e0-4cbd-bcf8-58e4cc088aa3.png)
> > > quando inicio sem a linha ou o bloco enteiro aparece isso
> > 
> > É por que você apagou errado, apague exatamente as mesmas linhas que você mostrou.
> 
> ![image](https://user-images.githubusercontent.com/65947059/151665673-ef9d9431-c623-4bdf-95d4-ba403a5a842e.png)
> esse bloco? 
> 

Isso, apague apenas ele.

**Comment by KillovSky** [comment]
> > > > 
> > > 
> > > 
> > > nao corrige na real nem inicia
> > > ![image](https://user-images.githubusercontent.com/65947059/151665434-c7b34d28-40e0-4cbd-bcf8-58e4cc088aa3.png)
> > > quando inicio sem a linha ou o bloco enteiro aparece isso
> > 
> > É por que você apagou errado, apague exatamente as mesmas linhas que você mostrou.
> 
> ![image](https://user-images.githubusercontent.com/65947059/151665673-ef9d9431-c623-4bdf-95d4-ba403a5a842e.png)
> esse bloco? 
> 

Isso, apague ele, se preferir, apague o de baixo também, ele pode ajudar mais ainda.

(O que está escrito sobre adicionar a Íris ao Ranking)

**Comment by pablorere** [comment]
> > > > > 
> > > > 
> > > > 
> > > > nao corrige na real nem inicia
> > > > ![image](https://user-images.githubusercontent.com/65947059/151665434-c7b34d28-40e0-4cbd-bcf8-58e4cc088aa3.png)
> > > > quando inicio sem a linha ou o bloco enteiro aparece isso
> > > 
> > > 
> > > É por que você apagou errado, apague exatamente as mesmas linhas que você mostrou.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/65947059/151665673-ef9d9431-c623-4bdf-95d4-ba403a5a842e.png)
> > esse bloco?
> 
> Isso, apague ele, se preferir, apague o de baixo também, ele pode ajudar mais ainda.
> 
> (O que está escrito sobre adicionar a Íris ao Ranking)

ok obrigado funcionou por agr
