### ISSUE TITLE
erro com os botoes

### ISSUE THREAD

**Issue by SimpleDioney** [KillovSky/iris#515]
![image](https://user-images.githubusercontent.com/62361235/151672160-c3a23ecb-2e6c-4baf-a6da-45bfebe1d4ac.png)

**Comment by KillovSky** [comment]
Esse erro é muito incomum, nunca me aconteceu durante o uso da DEV e durante a construção do uso de botões, mas aqui segue uma forma de corrigi-lo, se você editou a Íris, certifique-se de que o problema não seja o seu script antes de fazer isso.

```javascript

// Mudar de:
 
const​ ​id​ ​=​ ​message​.​type​ ​==​ ​"buttons_response"​ ? ​message​.​quotedMsgObj​.​id​ : ​message​.​id

// Para:

const​ ​id​ ​=​ ​message​.​id
```

Isso vai fazer as marcações sairem totalmente erradas de mensagens, mas, vai servir para parar o erro.

**Comment by SimpleDioney** [comment]
Por incrível que pareça eu não editei nem uma linha kkk, mas irei tentar isso ai

**Comment by SimpleDioney** [comment]
bom, vamos la, eu fiz a edicao que tu disse, nao aparece mais o erro, de fato, mas tambem nao envia a msg do comando

**Comment by SimpleDioney** [comment]
fiz um teste, e se eu digitar, funciona perfeitamente, erro esta nos botoes msm

**Comment by SimpleDioney** [comment]
Tem alguma ideia de como eu posso resolver

**Comment by KillovSky** [comment]
Ola, desculpe a demora, tiro os finais de semana pra descansar.

De toda forma, este erro não me ocorre, você está usando o `Multiple_Devices`?

De qualquer forma, apague a pasta da Íris e reinstale, não edite nada e ligue.

**Comment by KillovSky** [comment]
Ola, desculpe a demora, tiro os finais de semana pra descansar.

De toda forma, este erro não me ocorre, você está usando o `Multiple_Devices`?

Por hora, apague a pasta da Íris e reinstale, não edite nada e ligue.

**Comment by SimpleDioney** [comment]
Sim, eu uso o multiple devices, irei fazer oque você disse e dps deixar de usar o multiple devices para ver se resolve

**Comment by KillovSky** [comment]
> Sim, eu uso o multiple devices, irei fazer oque você disse e dps deixar de usar o multiple devices para ver se resolve

Ah, explicado, não é um problema na Íris, leia isso aqui -> https://github.com/open-wa/wa-automate-nodejs/issues/2426#issuecomment-1019364524

**Comment by SimpleDioney** [comment]
Eu fiz oque disse, ate sai do multiple devices antes de instalar, e esta dando o mesmo erro
![image](https://user-images.githubusercontent.com/62361235/151850108-d93e398e-2ee4-46bc-9eb8-e3c35b39a5ce.png)

**Comment by SimpleDioney** [comment]
Muito bem, vamos lá, eu usava um whatsapp anti trava e pensei: bom deve ser isso, né!?
Desinstalei e instalei o normal, reiniciei o bot e conectei.
Ai meu whatsapp crashou e o console não passava do 

> "finalizing client"

E tá assim até agora!

**Comment by SimpleDioney** [comment]
Ah, vale ressaltar que eu testei com a 

> branch 
 e com o 
> normal !

**Comment by KillovSky** [comment]
Seu grupo possui as mensagens temporarias? Se sim, desative e apague a pasta `Logs`, `.node-persist` e os arquivos `Iris_Data_QR` e `package-lock.json`.
Então rode `npm update` e depois `npm start`.

Caso não tenha...

Saia de todos os grupos primeiro e então limpe todas as mensagens ou reinstale o WhatsApp (Sem backups!)

**Comment by SimpleDioney** [comment]
Resolvido, era o whatsapp imune que estava causando o problema mesmo!
