### ISSUE TITLE
Cloud crash

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#516]
![image](https://user-images.githubusercontent.com/44541791/151672940-0a4b03c9-4a46-48a5-bc66-4ca4d2ae2e8d.png)

**Comment by KillovSky** [comment]
Ele deu algum erro no sistema de verificação por pornografia, talvez a imagem que enviaram possa ser invalida.

Você fez alguma edição nos parametros do `upload` ou na `config.js`?

Se sim, desfaça e teste.

Voltando, este erro parece ser isolado, pois não o recebi nos meus testes.

Tente inserir um `try { ... } catch { ... }` na função de `upload`.

**Comment by maradona4** [comment]
![image](https://user-images.githubusercontent.com/44541791/151678795-4de47af9-f6c7-46ad-a8a0-0424c0e49d2b.png)

**Comment by maradona4** [comment]
![image](https://user-images.githubusercontent.com/44541791/151678857-eb005f86-b604-46bb-a859-f6263a3f1d61.png)

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/151678857-eb005f86-b604-46bb-a859-f6263a3f1d61.png)
> 

Este não é o código que criei, houve sim edicões, restaure o código original do `Anti-Porn` da versão `Dev`.

**Comment by maradona4** [comment]
Deu certo funciono

**Comment by maradona4** [comment]
![image](https://user-images.githubusercontent.com/44541791/152042502-f232c876-a3e7-4dd1-ba54-4968c1f75986.png)
