### ISSUE TITLE
3.2.6 reconhece apenas comandos do dono 

### ISSUE THREAD

**Issue by wesley0209** [KillovSky/iris#517]
![IMG_20220131_121006](https://user-images.githubusercontent.com/83685462/151822617-f13da709-56bd-4a24-b0d8-a0489551510e.jpg)

**Comment by KillovSky** [comment]
Pelo visto, alguma edição feita na `config.js` danificou, desfaça as edicões que você fez e verifique-as antes de ligar.
Também rode `npm update` antes de ligar, por segurança.

**Comment by wesley0209** [comment]
> Pelo visto, alguma edição feita na `config.js` danificou, desfaça as edicões que você fez e verifique-as antes de ligar. Também rode `npm update` antes de ligar, por segurança.

Obg
