### ISSUE TITLE
Iniciar node

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#518]
5 vezes iniciar erro . mas eu ja apagar Logs,  temp, %temp% e prefetch tudos limpar 

continuar erro iniciar

![image](https://user-images.githubusercontent.com/44541791/151895865-214b1a83-b4ce-4ec0-80af-49a707498f75.png)

**Comment by wesley0209** [comment]
Up

**Comment by KillovSky** [comment]
Aparentemente é um problema com a `Wa-Automate` em vista do criador dela postar uma issue referenciando a conexão ser aprovada antes do QR.

Desconecte do WhatsApp Web pelo celular, apague a pasta `Logs`, `.node-persist` e os arquivos `Iris_Data_QR` e `package-lock.json` e tente.

Evite desconectar até que eles postem uma atualização que corrija.

Se precisar fazer edições no código, use a função `tools("reload").watchFile("Local do arquivo 1", "Local do Arquivo 2")`

O 1 é referente a localização desde a pasta principal e a 2 é referente a localização sobre a pasta `functions`.

Dê uma olhada na `index.js` para entender, lá tem essa função.

**Comment by wesley0209** [comment]
> Aparentemente é um problema com a `Wa-Automate` em vista do criador dela postar uma issue referenciando a conexão ser aprovada antes do QR.
> 
> Desconecte do WhatsApp Web pelo celular, apague a pasta `Logs`, `.node-persist` e os arquivos `Iris_Data_QR` e `package-lock.json` e tente.
> 
> Evite desconectar até que eles postem uma atualização que corrija.
> 
> Se precisar fazer edições no código, use a função `tools("reload").watchFile("Local do arquivo 1", "Local do Arquivo 2")`
> 
> O 1 é referente a localização desde a pasta principal e a 2 é referente a localização sobre a pasta `functions`.
> 
> Dê uma olhada na `index.js` para entender, lá tem essa função.

Como proceder na iris 3.1.1? Está com o mesmo problema

**Comment by KillovSky** [comment]
Siga os mesmos passos.

**Comment by KillovSky** [comment]
Siga o mesmo procedimento, porém, se precisar testar um código novo, é conveniente fazer isso fora do WhatsApp e apenas inserir o código quando o mesmo tiver finalizado, precisando apenas inserir na Íris a mensagem de resposta.

**Comment by wesley0209** [comment]
> 

Funcionou. Obg amigo
