### ISSUE TITLE
Erro (não sei qual)

### ISSUE THREAD

**Issue by SimpleDioney** [KillovSky/iris#520]
Bom, o erro aconteceu da seguinte maneira:
Minha amiga mandou uma msg, o bot deu algum problema e toda msg ele enviava uma msg de erro.
![16438454333167530722947941251907](https://user-images.githubusercontent.com/62361235/152256621-1e78bd2a-4b57-49ff-80ae-47d7242fac50.jpg)

**Comment by SimpleDioney** [comment]
![Screenshot_20220202-220950](https://user-images.githubusercontent.com/62361235/152264529-4fcb1143-cfd7-4002-b0c5-d689b9aef140.png)

**Comment by KillovSky** [comment]
#513
