### ISSUE TITLE
reload

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#521]
![image](https://user-images.githubusercontent.com/79427063/152358994-fc8341c8-4b78-47f8-b21a-59c62f7a0ca4.png)

**Comment by KillovSky** [comment]
Erro da `Wa-Automate` em relação ao `Puppeteer`, irei verificar se posso corrigir eu mesmo em breve, mas resumidamente, não é um BUG na Íris.

(Caso futuramente seja considerado ser, irei reabrir a issue e marcar para correção)

**Comment by KillovSky** [comment]
Erro da `Wa-Automate` em relação ao `Puppeteer`, irei verificar se posso corrigir eu mesmo em breve, mas, resumidamente, não é um BUG na Íris.

(Caso futuramente seja considerado ser, irei reabrir a issue e marcar para correção)
