### ISSUE TITLE
Problema no npm start (Target.setAutoAttach)

### ISSUE THREAD

**Issue by Thalsee** [KillovSky/iris#523]
![image](https://user-images.githubusercontent.com/87314159/152646875-414d548d-a4f0-4b9a-8670-05904840e451.jpeg)

**Comment by KillovSky** [comment]
Problema com o PC e não a Íris, ele está fechando o `Chrome`.

Tente inserir o local do Chrome na `config.json`, no `Chrome_Path`.

Basta trocar `null` por `"Local do Chrome/chrome.exe"`.

**Comment by Thalsee** [comment]
Já tinha feito isso e também não deu certo. 
undefined:29
  "Chorme_Patch": "C:\Program Files\Google\Chorme\Application\chorme.exe"

SyntaxError: Umexpected token P in JSON at position 1302

**Comment by KillovSky** [comment]
> Já tinha feito isso e também não deu certo. 
> undefined:29
>   "Chorme_Patch": "C:\Program Files\Google\Chorme\Application\chorme.exe"
> 
> SyntaxError: Umexpected token P in JSON at position 1302

É preciso inserir `\\` no lugar de `\`.

Ou seja, seria `C:\\Program Files\\Google\\Chorme\\Application\\chrome.exe`.

Não esqueça de **NÃO** remover a virgula que vem depois das aspas.

Tenha total certeza de escrever o local corretamente.

**Comment by KillovSky** [comment]
> Já tinha feito isso e também não deu certo. 
> undefined:29
>   "Chorme_Patch": "C:\Program Files\Google\Chorme\Application\chorme.exe"
> 
> SyntaxError: Umexpected token P in JSON at position 1302

É preciso inserir `\\` no lugar de `\`.

Ou seja, seria `"Chrome_Path": "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",`

Não esqueça de **NÃO** remover a virgula que vem depois das aspas.

Tenha total certeza de escrever o local corretamente.

**Comment by Thalsee** [comment]
> > Já tinha feito isso e também não deu certo. 
> > undefined:29
> >   "Chorme_Patch": "C:\Program Files\Google\Chorme\Application\chorme.exe"
> > 
> > SyntaxError: Umexpected token P in JSON at position 1302
> 
> É preciso inserir `\\` no lugar de `\`.
> 
> Ou seja, seria `"Chrome_Path": "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",`
> 
> Não esqueça de **NÃO** remover a virgula que vem depois das aspas.
> 
> Tenha total certeza de escrever o local corretamente.

O mesmo erro do começo esta se repetindo, o PC fecha o navegador, já tentei reinstalar o Chrome e mesmo assim não deu certo.

ProtocolError: Protocol error (Target.setAutoAttach) : Target closed.

**Comment by KillovSky** [comment]
Na `options.js`, remova a linha `'--single-process'` e a virgula no final de `'--no-zygote'​,`.

Salve e tente ligar.

Se não funcionar, reinstale e não mexa em nada, apenas inicie.

**Comment by Thalsee** [comment]
Fiz a reinstalação completa, iniciei e deu certo, obrigado.
