### ISSUE TITLE
Chat with simsimi: sim . vuiz . net! - Free Simsimi API stopped working

### ISSUE THREAD

**Issue by nobresyz** [KillovSky/iris#524]
Chat with simsimi: sim . vuiz . net! - Free Simsimi API stopped working

Como posso resolver por favor?

**Comment by KillovSky** [comment]
Leia a #389 ou instale a `DEV`.

#416 `<- Link da versão DEV, peço que **LEIA OS NOVOS TUTORIAIS!**`

Instalar a `DEV` é recomendado apenas para quem utiliza o **Português** ou quer as enormes funções e correções adicionadas, a tradução dos outros idiomas não está finalizada e **VAI** causar erros se utilizada em `Inglês` ou `Espanhol`.

**Comment by KillovSky** [comment]
Leia a #389 ou instale a `DEV`.

#416 `<- Link da versão DEV, não esqueça de ler os novos tutoriais da página para evitar issues`.

Instalar a `DEV` é recomendado apenas para quem utiliza o **Português** ou quer as enormes funções e correções adicionadas, a tradução dos outros idiomas não está finalizada e **VAI** causar erros se utilizada em `Inglês` ou `Espanhol`.
