### ISSUE TITLE
BUG -> Bloquear comandos globalmente [NoCMD]

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#525]
Erro include

![Screenshot_20220206-234032_WhatsApp](https://user-images.githubusercontent.com/44541791/152716295-7f34c2c6-b940-4ddf-ae6f-44546feed813.jpg)

**Comment by KillovSky** [comment]
Me mostre a linha `339` da sua `config.js`.

**Comment by maradona4** [comment]
![image](https://user-images.githubusercontent.com/44541791/152905215-d345422a-4fd8-4c2b-a18b-1faee7da0461.png)

**Comment by maradona4** [comment]
```
		// Desativador de comandos específicos em grupos, FT. Pedro B.
		if (isCmd && !isOwner) {
			if (Object.keys(blockcmd.yes).includes(chatId) || blockcmd.global.length !== 0) {
				if (blockcmd.yes[chatId].includes(command) && !isGroupAdmins || blockcmd.global.includes(command)) {
					await kill.reply(from, 'Não posso executar esse comando pois um administrador / Meu dono requisitou sua desativação.', id)
					return console.log(tools('others').color('> [DISABLED]', 'red'), tools('others').color(`Ignorando comando ${command.toUpperCase} de ${pushname} - [${sender.id.replace('@c.us', '')}] pois o comando foi desabilitado...`, 'yellow'))
				}
			}
		}
```

**Comment by KillovSky** [comment]
Certo, é um bug na desativação global, irei corrigir em breve.

**Comment by KillovSky** [comment]
Certo, é um bug no desativador global de comandos, vou corrigir na `3.2.7`.
Por hora...

Mudar `blockcmd.global.includes(command)` para `blockcmd.global && blockcmd.global.includes(command)`, talvez ajude.

Não feche a issue caso resolva.

**Comment by maradona4** [comment]
Ok ;)
