### ISSUE TITLE
Encerrar BOT e reiniciar configurações

### ISSUE THREAD

**Issue by mvmvasconcelos** [KillovSky/iris#527]
Duas dúvidas bem básicas:
Há algum comando para desligar o bot com segurança (no caso for preciso desligar o pc ou algo assim) ou é só fechar o console?
Há algum comando para dar um "refresh" após alguma alteração no arquivo ter sido feita?

**Comment by mvmvasconcelos** [comment]
Achei o comando pra encerrar o bot, **/shutdown** e o **/restart** para reiniciar, mas precisa ser o dono e não estava reconhecendo meu número mas consegui fazer funcionar. Entretanto o restart está dando erro, aí preciso iniciar o servidor novamente.

![image](https://user-images.githubusercontent.com/38293927/153007089-8f407743-a3e9-46b8-b8a1-4f499ae823f6.png)

**Comment by KillovSky** [comment]
#521 <- Estarei tentando isolar o erro pra evitar os problemas e o funcionando.
Todavia, por hora você tem uma segunda forma de reiniciar.

Instale `PM2` e inicie a Íris com `pm2 start index.js`.

Vá no WhatsApp e rode `/cmd pm2 restart 0` para reiniciar a Íris por completo.

Se você estiver usando outros programas com `PM2`, insira o número da index dele no lugar do `0`, a index pode ser obtida juntamente com a execução da Íris, rodando o comando, no terminal do PC, `pm2 monit`.
