### ISSUE TITLE
canvas erro

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#528]
![image](https://user-images.githubusercontent.com/79427063/153093442-233a5457-69a5-47aa-afd1-3ff6843e59ab.png)

**Comment by KillovSky** [comment]
Você não especificou o comando que deu erro, mas baseando no log, que diz `index.js`, suponho que seja o `Welcome` ou `Goodbye`.

#499 <- Por hora, o que da pra fazer, é trocar a ` `​${​profile​}​`​` no `welcome.js` para o link de uma imagem.

**Comment by KillovSky** [comment]
Você não especificou o comando que deu erro, mas baseando no log, que diz `index.js`, suponho que seja o `Welcome` ou `Goodbye`.

#499 <- Por hora, o que da pra fazer, é trocar a `"${​profile​}"` no `welcome.js` para o link de uma imagem.
