### ISSUE TITLE
Erro quando dou npm start

### ISSUE THREAD

**Issue by tioxand33** [KillovSky/iris#529]
![Uploading 16445139696563956425333000217180.jpg…]()

**Comment by KillovSky** [comment]
?

Você não esperou a imagem ser enviada corretamente.

**Comment by tioxand33** [comment]
![Uploading 16445262552523249702317286443564.jpg…]()

**Comment by KillovSky** [comment]
> ![Uploading 16445262552523249702317286443564.jpg…]()
> 

Você errou de novo, espere o upload estar finalizado, fecharei a issue por hora.
