### ISSUE TITLE
Loop ao iniciar 

### ISSUE THREAD

**Issue by smartywolf** [KillovSky/iris#53]
https://ibb.co/GJJC0jZ

"Session data most likely expired due to manual host account logout. Please re-authenticate this s ession."

**Comment by maradona4** [comment]
eu tambem

**Comment by PedroBatistop** [comment]
Isso ocorreu devido a um problema com o wa-automate. Problema que já foi resolvido. Para garantir que sua íris inicie corretamente apague o arquivo "íris.data.json" e atualize seus módulos com "npm update".

**Comment by NaldoMota1** [comment]
errooooooooo

**Comment by maradona4** [comment]
> Isso ocorreu devido a um problema com o wa-automate. Problema que já foi resolvido. Para garantir que sua íris inicie corretamente apague o arquivo "íris.data.json" e atualize seus módulos com "npm update".

Funcionar Flw ;)

**Comment by KillovSky** [comment]
Rode isso ```npm i @open-wa/wa-automate@4.8.1``` e tente iniciar, alguns computadores incluso o meu, não atualizam a Wa-Automate automaticamente com o ```npm update```.

**Comment by NaldoMota1** [comment]
![Captrurar](https://user-images.githubusercontent.com/71650872/125097306-61847700-e0ac-11eb-90b3-9da1ed25c890.PNG)
 recebo esse erro ao atualizar

**Comment by NaldoMota1** [comment]
vou tentar

> Rode isso `npm i @open-wa/wa-automate@4.8.1` e tente iniciar, alguns computadores incluso o meu, não atualizam a Wa-Automate automaticamente com o `npm update`.

vou tentar isso

**Comment by KillovSky** [comment]
> ![Captrurar](https://user-images.githubusercontent.com/71650872/125097306-61847700-e0ac-11eb-90b3-9da1ed25c890.PNG)
>  recebo esse erro ao atualizar

Esse erro é relacionado a **permissão** de criar pastas, você esta instalando a Iris na sua pasta `users` que para alguns, é problematica.
Reinstale a Iris pela sua `Area de Trabalho`.

**Comment by NaldoMota1** [comment]
recebo o mesmo erro usando o comando npm i @open-wa/wa-automate@4.8.1

**Comment by NaldoMota1** [comment]
instalei na área de trabalho

**Comment by KillovSky** [comment]
> instalei na área de trabalho

Peço que crie uma nova issue para o autor dessa não ficar enfurecido (não entra no tema do loop haha, logo não acharão o erro caso queiram ver se alguém também obteve o mesmo).

**Comment by maradona4** [comment]
![image](https://user-images.githubusercontent.com/44541791/125104455-c7c0c800-e0b3-11eb-8a2c-0b3bd257676f.png)
 o meu funcionar

**Comment by smartywolf** [comment]
seu node está desatualizado, baixe a versão 14

**Comment by NaldoMota1** [comment]
Resolvi o meu. O problema estava no npm que estava desatualizado e não era mais compatível com open wa
