### ISSUE TITLE
bug ao iniciar iris pela primeira vez

### ISSUE THREAD

**Issue by LeirbaC** [KillovSky/iris#530]
Olá como vai? Estou com um problema apos usar  `npm i` eu tento rodar com `npm start` porém recebo esse erro, sabe como eu posso resolver?
![image](https://user-images.githubusercontent.com/98467450/153516505-6352b2d0-b315-4266-bf52-b40826ae517e.png)

**Comment by KillovSky** [comment]
Esse problema é na `Deepai` e não na `Íris`.

Tente uma reinstalação, tenha certeza de ter seguido as informações a seguir.

. - Nada de espaços e simbolos no nome da pasta.

. - Tenha certeza de ter os requisitos minimos.

Se nada resolver, fale com a `DeepAI` no repositorio deles.

**Comment by LeirbaC** [comment]
> Esse problema é na `Deepai` e não na `Íris`.
> 
> Tente uma reinstalação, tenha certeza de ter seguido as informações a seguir.
> 
> . - Nada de espaços e simbolos no nome da pasta.
> 
> . - Tenha certeza de ter os requisitos minimos.
> 
> Se nada resolver, fale com a `DeepAI` no repositorio deles.

> 

Renomeei a pasta para irisDev, rodei várias vezes `npm i` e `npm start` porém nada ainda, vc acha que teria algo a ver com a versão do node ou do npm? minha versão do node é 14.17.3 e npm é 6.14.15

**Comment by LeirbaC** [comment]
> Pode ser que sim, tente atualizar para a `LTS` mais recente.
> 
> P.S - Você tentou apagar e instalar do zero?

bom, atualizei o node e npm pra LTS, node: `16.13.2` e npm `8.3.1`, também tentei utilizar o `yarn` no lugar do npm, reclonando o projeto e tentando do zero algumas vezes, porém ocorre o mesmo problema  :/
Estranho é que já rodei anteriormente a Iris da branch `main`, o problema está ocorrendo só com a da `dev`.

Testei retirar o modulo da `deepAI` do package e reinstalar do zero sem ele, retirei todas as menções a `deepai` do código e funcionou, vou utilizar assim e no fim de semana vou verificar se é algum problema na versão desse modulo já que na main com uma versão anterior funcionava, no mais obrigado pelo suporte e tenha um bom dia :)

**Comment by PedroBatistop** [comment]
> Olá como vai? Estou com um problema apos usar `npm i` eu tento rodar com `npm start` porém recebo esse erro, sabe como eu posso resolver? ![image](https://user-images.githubusercontent.com/98467450/153516505-6352b2d0-b315-4266-bf52-b40826ae517e.png)

dê um downgrade até que a equipe do deepai resolva esse BO
rode `npm i deepai@1.0.17` e deverá resolver
