### ISSUE TITLE
comando pra mandar msg pra todo mundo

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#532]
quando eu do o comando q eu mudei pra bc ai fica bc -all msg ele manda a mensagem 
[Transmissão de octopi]
|| msg q eu coloquei
mais eu n sei da aonde ta vindo esse ||
![image](https://user-images.githubusercontent.com/79427063/153701865-19c7439a-ec05-4eb1-94de-e8969aa1564f.png)

**Comment by PedroBatistop** [comment]
Pode mandar print do como você usou o comando, por favor?

**Comment by KillovSky** [comment]
> > Pode mandar print do como você usou o comando, por favor?
> 
> eu so dei !bc -all msg 
> e ele coloca um ||

Precisamos de um print do uso pra entender, conforme pedido pelo Pedro.

A Íris não insere esse `||` e a `Wa-Automate` também não, o erro está sendo por ai, pode ser um bug isolado, por isso, precisamos **VER UMA PRINT** do seu modo de uso.

**Comment by dodouuglas** [comment]
> > > Pode mandar print do como você usou o comando, por favor?
> > 
> > 
> > eu so dei !bc -all msg
> > e ele coloca um ||
> 
> Precisamos de um print do uso pra entender, conforme pedido pelo Pedro.
> 
> A Íris não insere esse `||` e a `Wa-Automate` também não, o erro está sendo por ai, pode ser um bug isolado, por isso, precisamos **VER UMA PRINT** do seu modo de uso.

![image](https://user-images.githubusercontent.com/79427063/154188167-47d0ade3-a773-41c1-9d49-c7b9c2d87687.png)

**Comment by dodouuglas** [comment]
eu sou coloquei bcc e aumentei o body.slice ali pra 8
![image](https://user-images.githubusercontent.com/79427063/154188238-fcea33da-40b5-4ee5-bbb3-2a867b9aae00.png)

**Comment by dodouuglas** [comment]
coloquei 9 e foi mais n faz sentido isso
da aonde ele ta tirando o ||

**Comment by KillovSky** [comment]
> > > > Pode mandar print do como você usou o comando, por favor?
> > > 
> > > 
> > > eu so dei !bc -all msg
> > > e ele coloca um ||
> > 
> > Precisamos de um print do uso pra entender, conforme pedido pelo Pedro.
> > 
> > A Íris não insere esse `||` e a `Wa-Automate` também não, o erro está sendo por ai, pode ser um bug isolado, por isso, precisamos **VER UMA PRINT** do seu modo de uso.
> 
> ![image](https://user-images.githubusercontent.com/79427063/154188167-47d0ade3-a773-41c1-9d49-c7b9c2d87687.png)
> 

Bro...isso é a letra `L`.
Ele estava pegando o ultimo `L` do `-all`.
Não é um `|`.

Experimente usar a `Dev` ou defina a `body.slice` com valor de `10`, conforme você disse.

Leia o tutorial que upei na `DEV`, esse "erro" não é uma falha da Íris e sim de edição.

A `body.slice` sempre deve ser calculada com:

- Tamanho de letras do comando.
+
- Tamanho de letras do argumentos, "-all" por exemplo.
+
- Quantidade de espaços entre comando e argumento.
+
- Valor de 1, para pegar a primeira letra da resposta que quer obter.

Ou seja...

- Comando = 3
- Argumento = 4
- Espaços = 2
- Valor extra = 1

Valor da `body.slice` = `10`.

**Comment by KillovSky** [comment]
> > > > Pode mandar print do como você usou o comando, por favor?
> > > 
> > > 
> > > eu so dei !bc -all msg
> > > e ele coloca um ||
> > 
> > Precisamos de um print do uso pra entender, conforme pedido pelo Pedro.
> > 
> > A Íris não insere esse `||` e a `Wa-Automate` também não, o erro está sendo por ai, pode ser um bug isolado, por isso, precisamos **VER UMA PRINT** do seu modo de uso.
> 
> ![image](https://user-images.githubusercontent.com/79427063/154188167-47d0ade3-a773-41c1-9d49-c7b9c2d87687.png)
> 

Bro...isso é a letra `L`.
Ele estava pegando o ultimo `L` do `-all`.
Não é um `|`.

Experimente usar a `Dev` ou defina a `body.slice` com valor de `10`, conforme você disse.

Leia o tutorial que upei na `DEV`, esse "erro" não é uma falha da Íris e sim de edição.

A `body.slice` sempre deve ser calculada com:

- Tamanho de letras do comando.

+

- Tamanho de letras do argumentos, "-all" por exemplo.

+

- Quantidade de espaços entre comando e argumento.

+

- Valor de 1, para pegar a primeira letra da resposta que quer obter.

Ou seja...

- Comando = 3
- Argumento = 4
- Espaços = 2
- Valor extra = 1

Valor da `body.slice` = `10`.

**Comment by KillovSky** [comment]
> > > > Pode mandar print do como você usou o comando, por favor?
> > > 
> > > 
> > > eu so dei !bc -all msg
> > > e ele coloca um ||
> > 
> > Precisamos de um print do uso pra entender, conforme pedido pelo Pedro.
> > 
> > A Íris não insere esse `||` e a `Wa-Automate` também não, o erro está sendo por ai, pode ser um bug isolado, por isso, precisamos **VER UMA PRINT** do seu modo de uso.
> 
> ![image](https://user-images.githubusercontent.com/79427063/154188167-47d0ade3-a773-41c1-9d49-c7b9c2d87687.png)
> 

Bro...isso é a letra `L`.
Ele estava pegando o ultimo `L` do `-all`.
Não é um `|`.

Experimente usar a `Dev` ou defina a `body.slice` com valor de `10`, conforme você disse.

Leia o tutorial que upei na `DEV`, esse "erro" não é uma falha da Íris e sim de edição.

A `body.slice` sempre deve ser somada no calculo feito com:

- Tamanho de letras do comando.
- Tamanho de letras do argumentos, "-all" por exemplo.
- Quantidade de espaços entre comando e argumento.
- Valor de 1, para pegar a primeira letra da resposta que quer obter.

Ou seja...

- Comando = 3
- Argumento = 4
- Espaços = 2
- Valor extra = 1

Valor da `body.slice` = `10`.

**Comment by KillovSky** [comment]
> > > > Pode mandar print do como você usou o comando, por favor?
> > > 
> > > 
> > > eu so dei !bc -all msg
> > > e ele coloca um ||
> > 
> > Precisamos de um print do uso pra entender, conforme pedido pelo Pedro.
> > 
> > A Íris não insere esse `||` e a `Wa-Automate` também não, o erro está sendo por ai, pode ser um bug isolado, por isso, precisamos **VER UMA PRINT** do seu modo de uso.
> 
> ![image](https://user-images.githubusercontent.com/79427063/154188167-47d0ade3-a773-41c1-9d49-c7b9c2d87687.png)
> 

Bro...isso é a letra `L`.
Ele estava pegando o ultimo `L` do `-all`.
Não é um `|`.

Experimente usar a `Dev` ou defina a `body.slice` com valor de `10`.

Leia o tutorial que upei na `DEV`, esse "erro" não é uma falha da Íris e sim de edição, você alterou a `case` mas esqueceu de calcular a `body.slice`.

A `body.slice` é a soma dos caracteres na mensagem, ou seja, o valor da `body.slice` deve ser calculado, com soma, ao analisar os seguintes valores:

- Tamanho de letras do comando.
- Tamanho de letras do argumentos, "-all" por exemplo.
- Quantidade de espaços entre comando e argumento.
- Valor de 1, para pegar a primeira letra da resposta que quer obter.

Ou seja...

- Comando = 3
- Argumento = 4
- Espaços = 2
- Valor extra = 1

Valor da `body.slice` = `10`.

**Comment by PedroBatistop** [comment]
Isso não é um | e sim um l(L). Aumente o slice para 10.
