### ISSUE TITLE
DeepAI Erro

### ISSUE THREAD

**Issue by cafusneu** [KillovSky/iris#533]
Estou tendo este problema ao iniciar, procurei algum erro semelhanete aqui para tentar resolver, mas não achei.

![Sem título](https://user-images.githubusercontent.com/99569224/153735522-cee6d92c-e297-4d9c-96fd-8e584c401690.png)

**Comment by gabrieldiaspereira** [comment]
É o mesmo problema da https://github.com/KillovSky/iris/issues/530, aparentemente é um problema na versão do deepai tente rodar `npm i deepai@1.0.17` pra usar uma versão mais antiga(https://github.com/KillovSky/iris/issues/530#issuecomment-1036595655)
