### ISSUE TITLE
Problema apos iniciar

### ISSUE THREAD

**Issue by Mateusj25** [KillovSky/iris#535]
![Screenshot_1](https://user-images.githubusercontent.com/56654201/153784681-98259660-369f-4ef4-ab3a-8e77adb5b9ac.png)
estou tendo esse problema toda vez que inicio fica on por uns 5s e depois desconecta

**Comment by KillovSky** [comment]
#512

**Comment by KillovSky** [comment]
#518 <- Problema similar, veja se isso resolve.

**Comment by Mateusj25** [comment]
Infelizmente não resolveu

**Comment by KillovSky** [comment]
> Infelizmente não resolveu 

Tente rodar `npm update` e então ligar, se falhar, tente apagar a pasta `Logs` e iniciar.

Verifique também se o `Multiple_Devices` não está ativado na `config.json` e que o `Chrome` está atualizado.

**Comment by Mateusj25** [comment]
Whatsapp atualizou e a função mutilpe divices tá ativa sempre (não está como beta mais) tem como rodar o bot mesmo assim? (O problema do motivo do post era antes da função mutilpe divices ser permanente)

**Comment by KillovSky** [comment]
Sim, não será problema, porém, depende da `WA-Automate` fazer uma atualização sobre.
Por hora, evite usar `Multiple-Devices`.

**Comment by Mateusj25** [comment]
Acho que me expressei mal, não tem opção mais de "não usar mutilpe divices" agora está como versão fixa pro whatsapp (pelo menos o normal) não tem jeito de usar sem essa opção? (E desculpe por tirar tanto do seu tempo mas não saberia resolver esse tipo de coisa sozinho) obg pela ajuda que deu até agora

**Comment by KillovSky** [comment]
Relaxa, entendi inicialmente, quis dizer para não inserir `true` na `Multiple_Devices` da `config.json`.

E novamente repito, relaxe pô, estamos na página de suporte, isso é feito para todos usarem, isso não tira meu tempo, pois, sou livre pra responder a qualquer momento.

**Comment by Mateusj25** [comment]
Eu não tô conseguindo achar a linha com a Multiple_Devices dentro da pasta config.js eu estou usando notpad ++ pra ver o arquivo

**Comment by KillovSky** [comment]
É a `JSON`.

A localização é `/lib/config/Gerais/config.json`.

**Comment by Mateusj25** [comment]
![IMG_20220215_121931101.jpg](https://user-images.githubusercontent.com/56654201/154092131-f8801bda-bf76-42c7-9d76-0b94f685dbe1.jpg) Essa opção nem aparece aqui

**Comment by KillovSky** [comment]
Você está usando a `3.1.1`, dê uma olhada na versão `DEV 3.2.6` da Íris -> #416

**Comment by Mateusj25** [comment]
Apareceu esse texto de erro no whatsapp:
😵 _Ooops, algo de errado aconteceu comigo, de uma olhada nos detalhes abaixo e se puder envie isso ao meu host [wa.me/Insira aqui seu número] ou use o_ */help!*

#️⃣  - "/menu"

❓- "Error"

❌ - "Evaluation failed: Error: MsgKey error: don't have a matching constructor
    at new c (https://web.whatsapp.com/bootstrap_qr.4df23620fb7636625f64.js:61:365980)
    at Object.t.createQuotedMsg (https://web.whatsapp.com/bootstrap_qr.4df23620fb7636625f64.js:60:473888)
    at g._getQuotedMsgObj (https://web.whatsapp.com/bootstrap_qr.4df23620fb7636625f64.js:60:450353)
    at g.quotedMsgObj (https://web.whatsapp.com/bootstrap_qr.4df23620fb7636625f64.js:60:449520)
    at __puppeteer_evaluation_script__:1:204906
    at Array.filter (<anonymous>)
    at Object.window.<computed>.<computed> [as reply] (__puppeteer_evaluation_script__:1:204556)"

📅 - "15/02/22 15:07:04"

❗ - "Erro não detalhado, descrição acima."

📁 - "    at new c (https"

🧶 - "Linha #//web.whatsapp.com/bootstrap_qr.4df23620fb7636625f64.js

🔍 - "Caractere #61"

**Comment by KillovSky** [comment]
Tente usar o `NodeJS LTS`, também é necessario esperar uma atualização da `Wa-Automate`, fique atento a isso.

**Comment by Mateusj25** [comment]
Agora tá funcionando sem problemas aparentemente, muito obrigado pela atenção e desculpa qualquer coisa

**Comment by KillovSky** [comment]
Que isso pô, sou o suporte, eu quem agradeço por escolher a Íris.
Qualquer questão estarei por aqui.
