### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by eduardosspinheio** [KillovSky/iris#539]
Bom dia!!

Mano como faço pra configurar as APIs....Pois são apis aí não sei onde achar....E oq significa esses comandos!!
Será que tem como me ajudar?
Desculpe está te incomodando, é pq o meu conhecimento é muito pouco, aí praticamente não sei nada, e como o bot é novo não achei tutorial!

![Uploading Screenshot_2022-02-21-08-21-57-692_com.android.chrome.jpg…]()

**Comment by gabrieldiaspereira** [comment]
Tem tudo explicado aqui: https://github.com/KillovSky/iris/blob/main/.readme/pt/config.md#como-obter-uma-api-key
Nesse mesmo link tem explicado para que serve cada api e como obter a key de cada um..
Mas resumindo o fluxo para você seria entrar nos links que tem lá, criar uma conta em cada site, obter a `API KEY` e colocar no `config.json`

**Comment by KillovSky** [comment]
Use o tutorial de instalação do Bisgos, ele mostra a criação das API's e configuração.

#28
