### ISSUE TITLE
Bot /kick

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#54]
![Screenshot_20210709-125848_WhatsApp](https://user-images.githubusercontent.com/44541791/125106108-a3fe8180-e0b5-11eb-89c6-1055d5cd228d.jpg)

Nao funcionar kick teste

**Comment by KillovSky** [comment]
Quem você quer remover é administrador? Pois não estou recebendo erros com o Kick, ele me funciona perfeitamente.
Então, você fez edicões? O alvo é administrador? Ele bane se marcar a mensagem?

**Comment by smartywolf** [comment]
Quanta pegadinha em um print só, provavelmente o @Bot seja dono do grupo, no caso seria impossível banir ele .

**Comment by KillovSky** [comment]
> Quanta pegadinha em um print só, provavelmente o @bot seja dono do grupo, no caso seria impossível banir ele .

Realmente pode ser isso, Íris não bane os donos de grupo, admins e o dono dela, aqui me funciona perfeito não importa como use.
@maradona4 irei fechar a issue, tente com a nova versão da Íris, se obter erros abra uma nova com todas as informações possíveis, obrigado!
