### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by eduardosspinheio** [KillovSky/iris#540]
Por que quando início ele, e dou o comando o primeiro comando aparece isso??

![16454967942896307182608917187194](https://user-images.githubusercontent.com/100093936/155051814-3fdca429-f749-42f5-9c58-dd39b14d3b6b.jpg)
![Screenshot_2022-02-21-23-26-24-334_com whatsapp](https://user-images.githubusercontent.com/100093936/155051942-03b4f4f7-a1a9-431e-818a-47ef7d4d6c1c.jpg)
![Screenshot_2022-02-21-23-26-28-455_com whatsapp](https://user-images.githubusercontent.com/100093936/155051948-e61b70ca-603f-4ceb-9bb6-186bb6a6b94c.jpg)

**Comment by KillovSky** [comment]
Primeiro de tudo, não rode a Íris na sua pasta Raiz, isso é extremamente perigoso se você utilizar algum comando de terminal por ela.

Segundo, você está com as mensagens temporarias ativadas?

Terceiro, você está usando os módulos atualizados?

E por fim, isso ocorre somente neste grupo ou em todos? E quando no PV?

**Comment by KillovSky** [comment]
Primeiro de tudo, não rode a Íris na sua pasta Raiz, isso é extremamente perigoso se você utilizar algum comando de terminal por ela.

Segundo, você está com as mensagens temporarias ativadas?

Terceiro, você está usando os módulos atualizados?

E por fim, isso ocorre somente neste grupo ou em todos? E quanto no PV?

**Comment by eduardosspinheio** [comment]
Tá bom irei tirar da pasta raiz!!
As mensagens temporárias não estão ativadas!!
Como assim, módulos atualizados?? Se o Whats está atualizado?
Não testei em outros grupos, mais irei testar e te falo!!

**Comment by KillovSky** [comment]
> Tá bom irei tirar da pasta raiz!!
> As mensagens temporárias não estão ativadas!!
> Como assim, módulos atualizados?? Se o Whats está atualizado?
> Não testei em outros grupos, mais irei testar e te falo!!

Pra atualizar os módulos, rode `npm update`, é necessario fazer isso de tempos em tempos.

**Comment by eduardosspinheio** [comment]
Assim que chegar em casa, provavelmente a noite, irei tentar, e aí te falo....Mas obrigado

**Comment by eduardosspinheio** [comment]
Consegui, o problema era naquele grupo mesmo, obrigado!!
Como faço pra adicionar áudios, fotos, quando alguém manda certo tipo de mensagem?

**Comment by eduardosspinheio** [comment]
Vlw

**Comment by eduardosspinheio** [comment]
Obrigado
