### ISSUE TITLE
[2 NUMEROS NO MESMO BOT]

### ISSUE THREAD

**Issue by wesley0209** [KillovSky/iris#541]
Teria como usar dois números no mesmo BOT na versão 3.2.6?

**Comment by KillovSky** [comment]
#115

**Comment by wesley0209** [comment]
> #115
> 
> Quanto mais sessões, mais gastos de memoria RAM.
> 
> Vou trazer um sistema padrão pra ter isso facilmente, na `3.2.7`.

Ou não tem como utilizar na versão MD?

**Comment by KillovSky** [comment]
Não sei te dizer, pois só "utilizo" a Íris, mas deve ser possivel sim, fazer o uso de dois bots diferentes ou iguais no mesmo número.

Desde que não utilizem a mesma arquitetura e sistema de **Login**, se for rodar na mesma pasta.

Íris salva o **Login** em `Base64` no arquivo `Iris_Data_QR`.

Se o outro BOT não utiliza isso ou tem arquivos com nomes diferentes (todos os arquivos da Íris são essenciais, não sobreponha), não vejo problemas para se rodar.

**Comment by wesley0209** [comment]
> 

Não amigo eu quis dizer utilizar dois numeros na mesma pasta da iris, igual o exemplo da issue #115 porém utilizando MD, eu coloquei isso create({ sessionId: 'iris2' }).then(kill => start(kill)); na index da versão 3.2.6 mas o qr code que é gerado é pra versão normal do whatsapp web, e eu queria um qr code em MD

**Comment by KillovSky** [comment]
> > 
> 
> Não amigo eu quis dizer utilizar dois numeros na mesma pasta da iris, igual o exemplo da issue #115 porém utilizando MD, eu coloquei isso create({ sessionId: 'iris2' }).then(kill => start(kill)); na index da versão 3.2.6 mas o qr code que é gerado é pra versão normal do whatsapp web, e eu queria um qr code em MD 

Ah isso, tente usar isso aqui por agora -> `create({ sessionId: 'iris2', multiDevice: true }).then(kill => start(kill))`.

**Comment by KillovSky** [comment]
> > 
> 
> Não amigo eu quis dizer utilizar dois numeros na mesma pasta da iris, igual o exemplo da issue #115 porém utilizando MD, eu coloquei isso create({ sessionId: 'iris2' }).then(kill => start(kill)); na index da versão 3.2.6 mas o qr code que é gerado é pra versão normal do whatsapp web, e eu queria um qr code em MD 

Ah isso, tente usar isso aqui por agora -> `create({ sessionId: 'iris2', multiDevice: true }).then(kill => start(kill))`

**Comment by wesley0209** [comment]
Deu certo, muito obrigado
