### ISSUE TITLE
[NOME DO GRUPO]

### ISSUE THREAD

**Issue by wesley0209** [KillovSky/iris#546]
![IMG_20220302_092018](https://user-images.githubusercontent.com/83685462/156360608-5db7c5f1-1744-4302-8f2a-b89385ca809c.jpg)

Iris 3.1.1 está não está puxando o nome do grupo.

Ps: não houve alteração no código

PS2: estou utilizando MD mas na versão normal também está com o mesmo erro

**Comment by KillovSky** [comment]
Execute esse comando no WhatsApp e mostre seu terminal.

`/exec console.log(name)`

**Comment by KillovSky** [comment]
Execute esse comando no WhatsApp e mostre seu terminal.

`/exec console.log(JSON.stringify(name))`

**Comment by wesley0209** [comment]
> Execute esse comando no WhatsApp e mostre seu terminal.
> 
> `/exec console.log(JSON.stringify(name))`

![IMG_20220302_100250](https://user-images.githubusercontent.com/83685462/156366851-141852fc-3596-483d-8aa2-0e63bfd204e5.jpg)

**Comment by KillovSky** [comment]
Pelo que vejo, não consegue ler o nome, houve alguns casos de erros assim, não existe uma solução especifica.

Tente sair do grupo, limpar o WhatsApp, reinstalar a Íris, entrar no grupo novamente e testar.

E claro, como você fala português, é altamente recomendavel usar a `Íris 3.2.6`, por ser uma versão extremamente melhorada.

**Comment by KillovSky** [comment]
Pelo que vejo, não consegue ler o nome, houve alguns casos de erros assim, não existe uma solução especifica.

Todavia, você pode tentar mudar as variaveis `name` na `index.js` para realizar testes.

Por exemplo:

`name.toString()`
`name.join('')`

E assim vai.

Ou, tente sair do grupo, limpar o WhatsApp, reinstalar a Íris, entrar no grupo novamente e testar.

E claro, como você fala português, é altamente recomendavel usar a `Íris 3.2.6` - #416 -, por ser uma versão extremamente melhorada.

**Comment by KillovSky** [comment]
Pelo que vejo, não consegue ler o nome, houve alguns casos de erros assim, não existe uma solução especifica.

Todavia, você pode tentar mudar as variaveis `name` na `index.js` para realizar testes.

Por exemplo:

`name.toString()`
`name.join('')`

E assim vai.

Ou, tente sair do grupo, limpar o WhatsApp, reinstalar a Íris, entrar no grupo novamente e testar.

E claro, como você fala português, é altamente recomendavel usar a `Íris 3.2.6` - #416 -, por ser uma versão extremamente melhorada, ela é considerada unstable apenas nos idiomas `Inglês` e `Espanhol`, sendo totalmente **ESTAVÉL** na `3.2.6`.

**Comment by KillovSky** [comment]
Pelo que vejo, não consegue ler o nome, houve alguns casos de erros assim, não existe uma solução especifica.

Todavia, você pode tentar mudar as variaveis `name` na `index.js` para realizar testes.

Por exemplo:

`name.toString()`
`name.join('')`

E assim vai.

Ou, tente sair do grupo, limpar o WhatsApp, reinstalar a Íris, entrar no grupo novamente e testar.

E claro, como você fala português, é altamente recomendavel usar a `Íris 3.2.6` - #416 -, por ser uma versão extremamente melhorada, ela é considerada unstable apenas nos idiomas `Inglês` e `Espanhol`, sendo totalmente **ESTAVÉL** no `Português`.

**Comment by wesley0209** [comment]
obg
