### ISSUE TITLE
[CRASHANDO]

### ISSUE THREAD

**Issue by wesley0209** [KillovSky/iris#547]
![Screenshot_2022-03-03-23-22-13-524_com microsoft rdc androidx](https://user-images.githubusercontent.com/83685462/156743736-a70d3c6f-51dd-4bef-ae80-b4c282d836dc.jpg)

Consegue me dizer o motivo desse erro? Nunca me aconteceu antes e já uso a Íris a mais de um ano. Aconteceu mais de 5 vezes ontem. Todos os programas estão atualizados.

**Comment by KillovSky** [comment]
Esse problema tem haver com a `heap` ou seja, baseado nos comandos utilizados acima, é possivel que seja uma falha por causa de *numeros exuberadamente grandes*, por um valor de `if` inadequado (isso é erro meu), por uma má execução matematica ou por memoria insuficiente, por exemplo, verifique se a pessoa usou marcando uma mensagem e usando marcação por `@` ao mesmo tempo.

Isso explicaria, ou seja:

1. Erro causado por falta de memoria para alocação - bem dificil de ser isto, mas, não é impossivel.

2. Falha causada por utilização de um número extremamente grande, é bem possivel.

3. Erro causado por uma forma de utilização que o `if` de não inclui, (Usar por `@` e marcando mensagem ao mesmo tempo), incomum, mas pode ser isto.

4. Erro causado pela soma a um valor nulo ou alem do limite calculado pelo `JS`, ou seja, tentar adicionar `x` valor ao `null` ou `NaN` ou `Infinity` (embora `Infinity` seja um valor "matematico" utilizavel, precisarei verificar), abra o `level.json` e localize os números de quem foi agiotado e quem estava agiotando valores e procure por `NaN`, `null`, `undefined` ou algo fora do padrão, como não ter nenhum valor, isso explicaria o erro de uma forma totalmente possivel.

5. Uma mistura de todos esses acima - isso seria quase impossivel...quase.

**Comment by KillovSky** [comment]
Esse problema tem haver com a `heap` ou seja, **o processo de memoria do Node.JS**, baseado nos comandos utilizados acima, é possivel que seja uma falha por causa de **valores exuberadamente grandes**, por um valor de `if` inadequado (isso é erro meu), por uma má execução matematica ou por memoria insuficiente, por exemplo, verifique se a pessoa usou marcando uma mensagem e usando marcação por `@` ao mesmo tempo.

Isso explicaria, ou seja:

1. Erro causado por falta de memoria para alocação - bem dificil de ser isto, mas, não é impossivel.

2. Falha causada por utilização de um número extremamente grande, é bem possivel.

3. Erro causado por uma forma de utilização que o `if` de não inclui, (Usar por `@` e marcando mensagem ao mesmo tempo), incomum, mas pode ser isto.

4. Erro causado pela soma a um valor nulo ou alem do limite calculado pelo `JS`, ou seja, tentar adicionar `x` valor ao `null` ou `NaN` ou `Infinity` (embora `Infinity` seja um valor "matematico" utilizavel, precisarei verificar), abra o `level.json` e localize os números de quem foi agiotado e quem estava agiotando valores e procure por `NaN`, `null`, `undefined` ou algo fora do padrão, como não ter nenhum valor, isso explicaria o erro de uma forma totalmente possivel.

5. Uma mistura de todos esses acima - isso seria quase impossivel...quase.

**Comment by wesley0209** [comment]
Suspeitei que seria isso. Só acontece com o nolimit ligado, muitas pessoas flodando ao mesmo tempo, rsrsrs. Obrigado vou colocar um limite

**Comment by wesley0209** [comment]
> Esse problema tem haver com a `heap` ou seja, **o processo de memoria do Node.JS**, baseado nos comandos utilizados acima, é possivel que seja uma falha por causa de **valores exuberadamente grandes**, por um valor de `if` inadequado (isso é erro meu), por uma má execução matematica ou por memoria insuficiente, por exemplo, verifique se a pessoa usou marcando uma mensagem e usando marcação por `@` ao mesmo tempo.
> 
> Isso explicaria, ou seja:
> 
> 1. Erro causado por falta de memoria para alocação - bem dificil de ser isto, mas, não é impossivel.
> 2. Falha causada por utilização de um número extremamente grande, é bem possivel.
> 3. Erro causado por uma forma de utilização que o `if` de não inclui, (Usar por `@` e marcando mensagem ao mesmo tempo), incomum, mas pode ser isto.
> 4. Erro causado pela soma a um valor nulo ou alem do limite calculado pelo `JS`, ou seja, tentar adicionar `x` valor ao `null` ou `NaN` ou `Infinity` (embora `Infinity` seja um valor "matematico" utilizavel, precisarei verificar), abra o `level.json` e localize os números de quem foi agiotado e quem estava agiotando valores e procure por `NaN`, `null`, `undefined` ou algo fora do padrão, como não ter nenhum valor, isso explicaria o erro de uma forma totalmente possivel.
> 5. Uma mistura de todos esses acima - isso seria quase impossivel...quase.
> 
> Edit: Caso seja um problema na alocação de memoria, utilize o seguinte tutorial:
> 
> 1. Abra a `package.json`.
> 2. Mude `node index.js` para `node --max-old-space-size=XX` index.js`.
> 3. Mude `XX` para a quantidade de memoria **EM MEGABYTES** que deseja utilizar, não insira um valor maior que sua **memoria RAM**.
> 4. Salve e inicie.

Obg
