### ISSUE TITLE
BACKUP

### ISSUE THREAD

**Issue by coelhobugado** [KillovSky/iris#549]
"
[BACKUP] → O Backup obteve uns problemas mas você pode ignorar - ou não. → "Command failed: bash -c 'zip -r "lib/config/Backup/05-03-22 # 21-13-35.zip" lib/config/Gerais'
bash: zip: command not found

**Comment by maradona4** [comment]
https://github.com/bmatzelle/gow/releases

Melhor Usar "Git Bash Here.exe"

**Comment by KillovSky** [comment]
Isso é por que você não leu as explicações sobre requisitos, **NUNCA** pule os termos, você pode estar vendendo a sua alma sem nem prestar atenção no botão de **concordo**.

Instale o requisito postado no comentario do @maradona4 e isso vai funcionar.
