### ISSUE TITLE
ranking Error

### ISSUE THREAD

**Issue by NaldoMota1** [KillovSky/iris#55]
como resolver o erro que aparece dizendo que "não temos nem 10 jogadores ainda..." O ranking estava completo

**Comment by PedroBatistop** [comment]
Isso ocorre devido a algum erro com um ou mais "jogadores" que estão entre os 10 primeiros do ranking. Preste bastante atenção, pois se fizer algo errado pode acabar com o seu level.json, faça um backup antes para evitar quaisquer problemas. Para resolver esse erro, primeiro, precisamos saber quem é o "jogador" problemático, que está causando o erro, para isso, desligue sua Íris, se estiver ligada, adicione a seguinte linha `console.log(nivel[i].id)` abaixo de `var aRandNe = await kill.getContact(nivel[i].id)` na case 'ranking', salve e ligue sua Íris. Dê o comando de ranking e no sue concole será registrado os IDs de quem está no ranking, o último desses IDs é o problemático, salve esse ID. Desligue sua Íris, vá até o arquivo **level.json** e procure pleo ID problemático que vc achou no passo anterior, feito isso apague esse ID como no exemplo a seguir:

`{"id":"xxx@c.us","xp":167018,"level":181},{"id":"yyy@c.us","xp":164647,"level":152},{"id":"zzz@c.us","xp":120167,"level":206},`
Digamos que o ID **yyy** é o problemático, apague **tudo o que está dentro das chaves**, deve ficar assim:
`{"id":"xxx@c.us","xp":167018,"level":181},{"id":"zzz@c.us","xp":120167,"level":206},`
_Tome cuidado com as vírgulas, elas são importantes e não podem faltar!_

Feito isso, inicie sua Íris novamente e verifique se o erro ainda persiste, se persistir, refaça todos os passos de novo até que o erro desapareça.

**Comment by NaldoMota1** [comment]
> Isso ocorre devido a algum erro com um ou mais "jogadores" que estão entre os 10 primeiros do ranking. Preste bastante atenção, pois se fizer algo errado pode acabar com o seu level.json, faça um backup antes para evitar quaisquer problemas. Para resolver esse erro, primeiro, precisamos saber quem é o "jogador" problemático, que está causando o erro, para isso, desligue sua Íris, se estiver ligada, adicione a seguinte linha `console.log(nivel[i].id)` abaixo de `var aRandNe = await kill.getContact(nivel[i].id)` na case 'ranking', salve e ligue sua Íris. Dê o comando de ranking e no sue concole será registrado os IDs de quem está no ranking, o último desses IDs é o problemático, salve esse ID. Desligue sua Íris, vá até o arquivo **level.json** e procure pleo ID problemático que vc achou no passo anterior, feito isso apague esse ID como no exemplo a seguir:
> 
> `{"id":"xxx@c.us","xp":167018,"level":181},{"id":"yyy@c.us","xp":164647,"level":152},{"id":"zzz@c.us","xp":120167,"level":206},`
> Digamos que o ID **yyy** é o problemático, apague **tudo o que está dentro das chaves**, deve ficar assim:
> `{"id":"xxx@c.us","xp":167018,"level":181},{"id":"zzz@c.us","xp":120167,"level":206},`
> _Tome cuidado com as vírgulas, elas são importantes e não podem faltar!_
> 
> Feito isso, inicie sua Íris novamente e verifique se o erro ainda persiste, se persistir, refaça todos os passos de novo até que o erro desapareça.

Vou fazer vlw
