### ISSUE TITLE
Iris pedindo pra ler Qr code sempre ao ligar

### ISSUE THREAD

**Issue by coelhobugado** [KillovSky/iris#550]
ultimamente ativei o Multi-dispositivos do zap e agora sempre ao ligar ele pede pra ler o qr code  mesmo ja tendo o arquivo iris_login ( Multiple_Devices esta em true ja)

**Comment by KillovSky** [comment]
Abra a `index.js` e remova a linha `tools​(​'others'​)​.​clearFile​(​'./logs/Chrome'​,​ ​0​,​ ​true​)`, isso deve resolver.

**Comment by coelhobugado** [comment]
> Abra a `index.js` e remova a linha `tools​(​'others'​)​.​clearFile​(​'./logs/Chrome'​,​ ​0​,​ ​true​)`, isso deve resolver.

fiz isso apos ligar o bot deu wlcome pro grupo todo mais  de 150 welcomes e fotos nao sei se ira acontecer toda vez que eu ligar

**Comment by KillovSky** [comment]
> > Abra a `index.js` e remova a linha `tools​(​'others'​)​.​clearFile​(​'./logs/Chrome'​,​ ​0​,​ ​true​)`, isso deve resolver.
> 
> fiz isso apos ligar o bot deu wlcome pro grupo todo mais  de 150 welcomes e fotos nao sei se ira acontecer toda vez que eu ligar

Isso é estranho, eu tenho certeza que limitei o welcome para evitar isso, a menos que tenha mais de 200 participantes...

De toda forma, não vai ocorrer novamente desde que você não apague a pasta `Logs`.

Uma correção para isso vem em breve.

**Comment by coelhobugado** [comment]
mesmo apos apagar da esse erro ( ele avisa que todos entraram novamente mas dessa vez n flodou o grupo 287 participantes) 

 at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  originalMessage: 'Execution context was destroyed.'
}
ProtocolError: Protocol error (Runtime.callFunctionOn): Execution context was destroyed.
    at C:\Users\gabri\alfred\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:230:24
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Users\gabri\alfred\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:226:16)
    at ExecutionContext._evaluateInternal (C:\Users\gabri\alfred\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:204:50)
    at ExecutionContext.evaluate (C:\Users\gabri\alfred\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:27)
    at DOMWorld.evaluate (C:\Users\gabri\alfred\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:97:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  originalMessage: 'Execution context was destroyed.'
}
ProtocolError: Protocol error (Runtime.callFunctionOn): Execution context was destroyed.
    at C:\Users\gabri\alfred\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:230:24
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Users\gabri\alfred\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:226:16)
    at ExecutionContext._evaluateInternal (C:\Users\gabri\alfred\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:204:50)
    at ExecutionContext.evaluate (C:\Users\gabri\alfred\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:27)
    at DOMWorld.evaluate (C:\Users\gabri\alfred\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:97:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  originalMessage: 'Execution context was destroyed.'
}
- Injecting scripts
- Base inject: 164ms
- WAPI inject: 215ms
- Checking session integrity
- Session integrity check passed
- Launch inject: 725ms

**Comment by KillovSky** [comment]
> mesmo apos apagar da esse erro ( ele avisa que todos entraram novamente mas dessa vez n flodou o grupo 287 participantes) 
> 
>  at processTicksAndRejections (internal/process/task_queues.js:95:5) {
>   originalMessage: 'Execution context was destroyed.'
> }
> ProtocolError: Protocol error (Runtime.callFunctionOn): Execution context was destroyed.
>     at C:\Users\gabri\alfred\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:230:24
>     at new Promise (<anonymous>)
>     at CDPSession.send (C:\Users\gabri\alfred\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:226:16)
>     at ExecutionContext._evaluateInternal (C:\Users\gabri\alfred\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:204:50)
>     at ExecutionContext.evaluate (C:\Users\gabri\alfred\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:27)
>     at DOMWorld.evaluate (C:\Users\gabri\alfred\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:97:24)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5) {
>   originalMessage: 'Execution context was destroyed.'
> }
> ProtocolError: Protocol error (Runtime.callFunctionOn): Execution context was destroyed.
>     at C:\Users\gabri\alfred\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:230:24
>     at new Promise (<anonymous>)
>     at CDPSession.send (C:\Users\gabri\alfred\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:226:16)
>     at ExecutionContext._evaluateInternal (C:\Users\gabri\alfred\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:204:50)
>     at ExecutionContext.evaluate (C:\Users\gabri\alfred\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:27)
>     at DOMWorld.evaluate (C:\Users\gabri\alfred\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:97:24)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5) {
>   originalMessage: 'Execution context was destroyed.'
> }
> - Injecting scripts
> - Base inject: 164ms
> - WAPI inject: 215ms
> - Checking session integrity
> - Session integrity check passed
> - Launch inject: 725ms
> 
> 

Esse erro é na `Wa-Automate`, atualize ela, houve um update 4 horas atrás, mas, também tente abrir a `options.js` e inserir `waitForRipeSession: true,`.

Caso você não saiba mexer, procure a linha `authTimeout​: ​0​,` e insira em baixo dela.
