### ISSUE TITLE
Como faço pra por áudio no bot quando alguém digita determinada palavra o bot mandar um áudio???

### ISSUE THREAD

**Issue by MenezesKvl** [KillovSky/iris#552]

**Comment by KillovSky** [comment]
#316 <- Essa página é destinada a correção de problemas envolvendo os códigos oficiais.

Abra a `config.js` e leia a linha 582 do código (DEV branch) e de uma olhada nas funções por [aqui](https://docs.openwa.dev/classes/api_Client.Client.html#sendPtt) e no `Tutorial de Edição PT-BR.txt`.
