### ISSUE TITLE
Não está mandando Sticker quando rola o comando Flip, como eu resolvo isso ?

### ISSUE THREAD

**Issue by MenezesKvl** [KillovSky/iris#553]
case 'flip':
					if (!isxp) return await kill.reply(from, mess.needxpon(), id)
					if (tools('gaming').isLimit(sender.id, daily, 'games') == 1) return await kill.reply(from, mess.limitgame(), id)
					const gamerFlip = parseInt(tools('gaming').getValue(sender.id, nivel, chatId, 'coin'))
					if (isNaN(args[1]) || !tools('others').isInt(args[1]) || Number(args[1]) >= gamerFlip) return await kill.reply(from, mess.gaming(gamerFlip), id)
					var iFlip = tools('others').randomNumber(config.Iris_Coin, gamerFlip * 2)
					let flipSor = await tools('others').randomNumber(1, 2) == 1
					if (argl[0] == 'cara' && flipSor == 1) {
						await kill.sendStickerfromUrl(from, 'https://i.ibb.co/3kVQqRQ/Pics-Art-png.png://i.ibb.co/LJjkVK5/heads.png', {
							method: 'get'
						}, {
							author: config.Sticker_Author,
							pack: config.Sticker_Pack,
							keepScale: true
						})
						await kill.reply(from, mess.flipwin(iFlip) + ' "cara".', id)
						tools('gaming').addValue(sender.id, Number(iFlip), nivel, chatId, 'coin')
					} else if (argl[0] == 'coroa' && flipSor == 2) {
						await kill.sendStickerfromUrl(from, 'https://https://i.ibb.co/3kVQqRQ/Pics-Art-png.png.ibb.co/wNnZ4QD/tails.png', {
							method: 'get'
						}, {
							author: config.Sticker_Author,
							pack: config.Sticker_Pack,
							keepScale: true
						})
						await kill.reply(from, mess.flipwin(iFlip) + ' "coroa".', id)
						tools('gaming').addValue(sender.id, Number(iFlip), nivel, chatId, 'coin')
					} else if (argl[0] == 'coroa' || argl[0] == 'cara') {
						await kill.reply(from, mess.fliplose(iFlip) + ` "${argl[0]}".`, id)
						tools('gaming').addValue(sender.id, Number(-iFlip), nivel, chatId, 'coin')
					} else return await kill.reply(from, mess.fliphow(), id)
					if (objconfig.noLimits == 0) return tools('gaming').addLimit(sender.id, daily, 'games')
				break

**Comment by maradona4** [comment]
Servidor ta offline 
Não é possível acessar esse siteVerifique se há um erro de digitação em https.
Se o endereço estiver correto, [tente executar o Diagnóstico de Rede do Windows](javascript:diagnoseErrors()).
DNS_PROBE_FINISHED_NXDOMAIN

você usou "https://https//i.ibb.co/3kVQqRQ/Pics-Art-png.png.ibb.co/wNnZ4QD/tails.png"

**Comment by MenezesKvl** [comment]
Ssim, eu usei o link
https://https//i.ibb.co/3kVQqRQ/Pics-Art-png.png.ibb.co/wNnZ4QD/tails.png
Porém ele está correto, ainda sim não manda o sticker


Aqui abaixo está  a case completa... poderia me dizer o que pode está
correndo de errado ??


case 'flip':
if (!isxp) return await kill.reply(from, mess.needxpon(), id)
if (tools('gaming').isLimit(sender.id, daily, 'games') == 1) return await
kill.reply(from, mess.limitgame(), id)
const gamerFlip = parseInt(tools('gaming').getValue(sender.id, nivel,
chatId, 'coin'))
if (isNaN(args[1]) || !tools('others').isInt(args[1]) || Number(args[1]) >=
gamerFlip) return await kill.reply(from, mess.gaming(gamerFlip), id)
var iFlip = tools('others').randomNumber(config.Iris_Coin, gamerFlip * 2)
let flipSor = await tools('others').randomNumber(1, 2) == 1
if (argl[0] == 'cara' && flipSor == 1) {
await kill.sendStickerfromUrl(from, '
https://i.ibb.co/3kVQqRQ/Pics-Art-png.png://i.ibb.co/LJjkVK5/heads.png', {
method: 'get'
}, {
author: config.Sticker_Author,
pack: config.Sticker_Pack,
keepScale: true
})
await kill.reply(from, mess.flipwin(iFlip) + ' "cara".', id)
tools('gaming').addValue(sender.id, Number(iFlip), nivel, chatId, 'coin')
} else if (argl[0] == 'coroa' && flipSor == 2) {
await kill.sendStickerfromUrl(from, 'https://
https://i.ibb.co/3kVQqRQ/Pics-Art-png.png.ibb.co/wNnZ4QD/tails.png', {
method: 'get'
}, {
author: config.Sticker_Author,
pack: config.Sticker_Pack,
keepScale: true
})
await kill.reply(from, mess.flipwin(iFlip) + ' "coroa".', id)
tools('gaming').addValue(sender.id, Number(iFlip), nivel, chatId, 'coin')
} else if (argl[0] == 'coroa' || argl[0] == 'cara') {
await kill.reply(from, mess.fliplose(iFlip) + ` "${argl[0]}".`, id)
tools('gaming').addValue(sender.id, Number(-iFlip), nivel, chatId, 'coin')
} else return await kill.reply(from, mess.fliphow(), id)
if (objconfig.noLimits == 0) return tools('gaming').addLimit(sender.id,
daily, 'games')
break

Em sáb., 12 de mar. de 2022 11:04 PM, Mateus-Santos <
***@***.***> escreveu:

**Comment by KillovSky** [comment]
Seu link está duplicado, existem dois links pra envio, isso impede o comando de enviar, faça a edição sugerida pelo @maradona4.
