### ISSUE TITLE
comando profile não funciona, alguem sabe como resolver?

### ISSUE THREAD

**Issue by herberthsfc** [KillovSky/iris#556]
![16477859949463655911973439686183](https://user-images.githubusercontent.com/76819767/159166948-2f2ff624-a569-4895-9c02-19feed017c31.jpg)

**Comment by KillovSky** [comment]
Isso não é um erro no sistema da Íris mas sim no `Wa-Automate/WhatsApp-Web`.
Tente rodar `npm update` caso tenha atualizações da `Wa-Automate`, mantenha seu `Chrome` atualizado também, e por fim, se caso não estiver usando a [Íris 3.2.6](#316), instale-a, já que você aparenta ser Brasileiro e usar o `PT-BR`.

**Comment by KillovSky** [comment]
Isso não é um erro no sistema da Íris mas sim no `Wa-Automate/WhatsApp-Web`.
Tente rodar `npm update` caso tenha atualizações da `Wa-Automate`, mantenha seu `Chrome` atualizado também, e por fim, se caso não estiver usando a [Íris 3.2.6](https://github.com/KillovSky/iris/discussions/416), instale-a, já que você aparenta ser Brasileiro e usar o `PT-BR`.
