### ISSUE TITLE
PROBLEM CREATING IRIS ON REPLIT.COM, INSTALLATION ERRORS The puppeteer@13.5.1 installation script failed.

### ISSUE THREAD

**Issue by EdvamSantos** [KillovSky/iris#557]
ERROR OCCURS WHEN INSTALLING FROM REPLIT.COM

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@13.5.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@13.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output a

**Comment by KillovSky** [comment]
Tente usar `npm i --force`, caso falhe, pode ser algo referente a um bloqueio no proprio `Replit`.
