### ISSUE TITLE
Erro Na Iris

### ISSUE THREAD

**Issue by Nhamin** [KillovSky/iris#56]
carrega dai da sempre fica dando esse Erro aqui e fica dando reconect sempre c esse mesmo erro '-'...... Session data most likely expired due to manual host account logout. Please re-authenticate this session.
                                                                                                  ┃

┃   @open-wa/wa-automate                                                                            ┃
┃    💬 🤖 The most reliable NodeJS whatsapp library for chatbots with advanced features.           ┃
┃   Version: 3.16.1                                                                                 ┃
┃   Check out the latest changes: https://github.com/open-wa/wa-automate-nodejs#latest-changes      ┃
┃                                                                                                   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
- Starting
- Version: 3.16.1
- Initializing WA
- Launching Browser
- Generating patch hash
- Downloaded patches in 0.578s
- Setting Up Browser
- Loading session data
- Navigating to WA
- Page loaded in 971ms: 200
- Browser Launched
- Debug info: {
  "WA_VERSION": "2.2126.10",
  "PAGE_UA": "WhatsApp/2.2108.8 Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
  "WA_AUTOMATE_VERSION": "3.16.1 UPDATE AVAILABLE: 4.8.2",
  "BROWSER_VERSION": "HeadlessChrome/91.0.4472.124",
  "OS": "Windows 10",
  "START_TS": 1625932286799
}
- Downloading patches from https://cdn.openwa.dev/patches.json
- Authenticating
- Session data most likely expired due to manual host account logout. Please re-authenticate this session.

**Comment by PedroBatistop** [comment]
#53
