### ISSUE TITLE
Bot extremamente lento

### ISSUE THREAD

**Issue by marciovdc** [KillovSky/iris#560]
Gostaria de saber se alguém pode me ajudar, pois, eu instalei a iris pura, porém ela fica extremamente lenta. Demora para responder e no log demora entre um a dois minutos para ela mostrar que recebeu uma mensagem. Minha conexão é de extrema qualidade, o computador está no cabo e celular que uso pro bot numa rede WiFi 5Ghz do lado do roteador. Eu já não sei mais o que fazer.

**Comment by KillovSky** [comment]
Isso é devido ao servidor do WhatsApp que está lento devido ao `Multiple_Devices`.

A Íris somente reconhece a conexão como finalizada quando as mensagens terminam de baixar, ou seja, limpe seu WhatsApp e escaneie o QR novamente, certifique-se de estar nas versões mais recentes da `Wa-Automate`, e tente usar a `Íris DEV` se estiver na `Main`.
