### ISSUE TITLE
iris crasha com qual quer comando

### ISSUE THREAD

**Issue by BruZim03** [KillovSky/iris#561]
Assim que uso qual quer comando, ela responde o comando e se desliga
Instalei a iris sem mexer em nada, e rodei npm update

![erro](https://user-images.githubusercontent.com/77207248/163239296-1071ee8c-d2d0-4c2c-a454-9c7baa534b23.png)

**Comment by KillovSky** [comment]
Erro referente a `Wa-Automate` e seu grupo, saia do mesmo e teste.

Se houver mensagens temporárias ligadas, desative.
