### ISSUE TITLE
Duvida

### ISSUE THREAD

**Issue by MokZueira12** [KillovSky/iris#562]
Oi, gostaria de saber se tem algum jeito de impedir que o bot de ban em numero fake que algum adm adicionou no grupo, sem precisar desativar o "antifake" e nem remover o adm do bot

**Comment by KillovSky** [comment]
> Oi, gostaria de saber se tem algum jeito de impedir que o bot de ban em numero fake que algum adm adicionou no grupo, sem precisar desativar o "antifake" e nem remover o adm do bot

Nesta versão atual da Github, não.
Todavia, no update (demorado), isso já foi inserido, apenas aguarde, por hora, o jeito é usar os meios ditos por você.
