### ISSUE TITLE
Ajuda com API's

### ISSUE THREAD

**Issue by WS-JOSYEL** [KillovSky/iris#563]
OI, onde coloca a api do SIMISIMI ( a que faz a iris falar, pois está indisponivel)?

E também onde consigo ou compro as outras Api's?

**Comment by KillovSky** [comment]
Está um pouco desatualizado, mas siga isso:

[Configurações](https://github.com/KillovSky/iris/blob/main/.readme/pt/config.md)

No caso da `API SimSimi`, use [este site](http://developer.simsimi.com).

Basta procurar o nome da `API` no `Google` que você encontrará tudo o restante que precisa.
