### ISSUE TITLE
Erro no comando "npm i" (Windows)

### ISSUE THREAD

**Issue by LV-zl** [KillovSky/iris#564]
Quando tento executar o comando "npm i" no Visual Studio Code, recebo os seguintes erros:

npm ERR! code 1
npm ERR! path C:\iris-main\node_modules\youtube-dl-exec
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npx bin-version-check-cli python ">=2"
npm ERR! Error: Couldn't find version of `python`
npm ERR!     at binaryVersion (file:///C:/Users/Casa/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version/index.js:55:8)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm ERR!     at async binaryVersionCheck (file:///C:/Users/Casa/AppData/Local/npm-cache/_npx/7b761a280cf4a94b/node_modules/bin-version-check/index.js:14:18)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Casa\AppData\Local\npm-cache\_logs\2022-04-18T04_32_08_049Z-debug-0.log
PS C:\iris-main>

Se alguém puder me ajudar, agradeço.

**Comment by KillovSky** [comment]
Olhe a #536.

**Comment by KillovSky** [comment]
Olhe a #536 & #538, elas possuem "diferentes" soluções.
