### ISSUE TITLE
Comando sem prefixo

### ISSUE THREAD

**Issue by MenezesKvl** [KillovSky/iris#566]
Olá bom dia, esse comando quando eu escrevo "oi" teoricamente era pra responder automáticamente a resposta que eu escrevi por ex "oi bom dia, porém se eu digitar alguma palavra que contenha esse oi vai responder em seguida a resposta que editei, exemplo se eu digitar "foi" "boi" "goiaba" ele vai mandar exatamente o "oi bom dia" ...
Aqui está o comando
try {
	if(message.body.includes('oi')) {
		await kill.reply(from, ('oe coisa linda6'), id)
				}
			} catch (error) {
				
			}
Como eu resolvo??

**Comment by KillovSky** [comment]
Troque:

`message.body.includes('oi')`

Por:

`body == 'oi'`

Ou:

`message.body == 'oi'`

Se por acaso não funcionar com o maiúsculo, tente usar este:

`(message.body.toLowerCase()) == 'oi'`

Ou:

`(body.toLowerCase()) == 'oi'`
