### ISSUE TITLE
FALHA NO COMANDO ' /ATTP ' 

### ISSUE THREAD

**Issue by leonardoLV3** [KillovSky/iris#567]
Quando tento executar o comando ' /attp ' na Iris Bot, recebo a seguinte mensagem:
"_Ops, por algum motivo obtive erros com esse comando_ [...]"

*E no Terminal (Linux Fedora 35) Aparece o seguinte:

[FALHA GERAL] Error: getaddrinfo ENOTFOUND undefined
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'undefined',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      DNT: 1,
      'Upgrade-Insecure-Requests': 1,
      'User-Agent': 'axios/0.25.0'
    },
    method: 'get',

Tem alguma forma de consertar o comando ' /attp '?

**Comment by KillovSky** [comment]
Use a `Branch Dev` da Íris.

#416
