### ISSUE TITLE
BUG -> Comando menu não configurado para modo Múltiplos Dispositivos

### ISSUE THREAD

**Issue by Bisgos** [KillovSky/iris#568]
Boa Lucas!
primeiramente desculpa se já tiver esse erro por aqui, pois procurei e não achei.
Seguinte não está aparecendo as opções ao executar o comando /menu
![Screenshot_1](https://user-images.githubusercontent.com/73245241/164956613-59a2e750-d25e-441b-96f6-4c674424b955.png)
.

**Comment by KillovSky** [comment]
Isso é algo que errei ao configurar a Íris para um o `Multi_Devices`, peço desculpas, mas não poderei prover a solução diretamente pois o código novo em desenvolvimento sofreu muitas mudanças, sendo inútil para a `Íris Dev` aberta, porém, acesse a `case 'menu` e de uma olhada na `mess.menu(...)`, copie-a e insira em uma nova linha com `await kill.reply(from, mess.menu(...), id)`, lembre-se de mudar a `mess.menu` para o valor correto (ou seja, pegue o que está dentro dos parenteses da outra).
