### ISSUE TITLE
Erro após casamento.

### ISSUE THREAD

**Issue by Bisgos** [KillovSky/iris#573]
depois de casar-se fica aparecendo mensagem de erro depois de qualquer mensagem, mesmo sem comando
![Screenshot_20](https://user-images.githubusercontent.com/73245241/167223031-8604697d-63c4-49c2-a17b-4653a6207c89.png)
.

**Comment by KillovSky** [comment]
Esse erro é bem confuso, diz ser no `puppeteer` mas tem referências a `Wa-Automate` e ao código da Íris.

Tente reiniciar, acredito que já tentou, mas se não funcionar, apague a sessão na pasta `sessions` e leia o QR novamente.

Após conectar, teste em outro grupo.

**Comment by Bisgos** [comment]
bom! tentei o que vc disse e não deu certo! 
se serve de ajuda ao fazer os testes notei que o erro ocorre apenas quando expira o tempo, antes do tempo expirar funciona normal, divorcio tbm funciona normalmente.

**Comment by KillovSky** [comment]
Entendi, vou revisar o código logo de manhã na segunda-feira e expor uma correção, se simples de realizar.

**Comment by KillovSky** [comment]
O código não possui nenhum erro por aqui, tente fazer uma reinstalação ou apagar a pasta `sessions` e reconectar a Íris, caso não funcione, reabra está issue que eu darei outra soluções que eu encontrar até lá.
