### ISSUE TITLE
BUG -> Anti-Fake não funciona / Solução

### ISSUE THREAD

**Issue by BruZim03** [KillovSky/iris#574]
Ativei o anti fake e a iris não identifica o fake, ja liguei o walcome e ele identifica os numero, porem não bane, no console não aparece nenhum erro, nem aparece a mensagem de quando entra fake

**Comment by KillovSky** [comment]
É um erro meu, peço desculpas, fiz alguns testes e a correção consiste na remoção do `!` no parâmetro `some` na `welcome.js`, para corrigir basta entrar no arquivo `welcome.js` e trocar a linha:

```javascript
const isFake = functions.fake.includes(events.chat) && !config.DDI.some(i => !events.who.startsWith(i))
```
Por:

```javascript
const isFake = functions.fake.includes(events.chat) && !config.DDI.some(i => events.who.startsWith(i))
```

Isso corrige, atualizarei na versão `3.2.8` assim que eu puder.

**Comment by KillovSky** [comment]
Corrigido na `V3.3.0`.
