### ISSUE TITLE
NOVO CMD

### ISSUE THREAD

**Issue by herberthsfc** [KillovSky/iris#575]
agora, os bots no termux, tem o comando delete, que apaga tanto as mensagens do bot, quanto a mensagem de qualquer membro de um grupo. será que pode sair um comando desse pra iris?👉🏿👈🏿

**Comment by KillovSky** [comment]
Primeiramente, peço desculpas pelo texto grande e claro, se houver diversas funções muito simples de fazer, mas que ainda não construi, como por exemplo, um comando pra emojis aleatorios, nomes aleatorios e outros simples, estes tipos de comando estão em ultima etapa dos meus updates, pois meu foco é em criar e aprimorar comandos com certa dificuldade, como o `21`, `chess` ou `RPG`, por isso, eu esqueço ou deixo de lado estes comandos simples e divertidos para pessoas "normais", peço que qualquer um com ideias, poste, assim posso fazer comandos divertidos para todos!

Não sei lhe dizer sobre essa função, posso estar errado em dizer as coisas a seguir e peço desculpa se estiver mas temos os seguintes pontos a considerar:

1. - Essa função quebra os sistemas da API do WhatsApp? Ou seja, ela existe naturalmente no WhatsApp? Se não existe nem versão BETA, pode ser um risco imenso a segurança dos meus usuarios tentar inserir essa função, assim como a dita "selo do WhatsApp", que na verdade é apenas uma falsificação de marcação de mensagem ou status, não é um selo de verdade, e claro, essas informações de falsificação não existem no servidor oficial do WhatsApp, considero isso um risco grande a segurança por usar dados inexistentes.

2. - Se for uma função naturalmente suportada, deverá ser feita uma implementação por parte da nossa base de controle, a Wa-Automate, se for colocado, irei implementar desde que seja uma feature gratuita e não seja um risco, avisarei aqui ou na descrição de uma atualização futura.

3. - Ao ser criada, se futuramente for o caso, essa função é muito útil, tanto quanto perigosa, pois podem apagar outras mensagens em abuso, levando a banimento do WhatsApp, ou apagar mensagens que tenham caracter judicial, o que implicaria um pouco com a lei, portanto, precisaria verificar o quão bom seria fazer isto, pois um dos meus focos é a segurança e privacidade dos meus usuarios.

Acredito que esses sejam os pontos principais, mas vamos seguir com fé que isso possa ser uma função oficial no WhatsApp e que a `Wa-Automate` implemente-a gratuitamente, se o fizerem, eu garanto que irei tentar construir!

**Comment by KillovSky** [comment]
Release 3.3.2 possui o recurso solicitado:

https://github.com/KillovSky/iris/commit/80d49accd4d02ed4e879f4062ad81a2a9f4b04a4
