### ISSUE TITLE
Como altero pra ganhar XP em vez de COINS, na Roleta?

### ISSUE THREAD

**Issue by herberthsfc** [KillovSky/iris#578]
por favor, alguem pode me ajudar?

**Comment by KillovSky** [comment]
Você precisa editar dezenas de linhas, pois ganharia **MUITO POUCO XP**.
Mas se quiser, basta trocar `coin` por `xp` nas `cases`,  ou seja, encontre as linhas `addValue` e troque os valores delas.

#316
