### ISSUE TITLE
Não consigo usar o comando /dono

### ISSUE THREAD

**Issue by NoHeroMonster** [KillovSky/iris#58]
![image](https://user-images.githubusercontent.com/87252668/125181317-051f7580-e1da-11eb-98dc-25fb586314ba.png)
![image](https://user-images.githubusercontent.com/87252668/125181365-69423980-e1da-11eb-9d91-2b4b2a1d7121.png)

**Comment by KillovSky** [comment]
O erro é que você editou até o parâmetro owner ali, o owner se começa com letra maiúscula, ```Owner```, e no seu está ```owner```, ajuste isso e deve funcionar.

**Comment by NoHeroMonster** [comment]
![image](https://user-images.githubusercontent.com/87252668/125181476-701d7c00-e1db-11eb-9610-ddc87c4d0d7e.png)

Eu tinha editado por que não estava dando, e continua não funcionando

**Comment by luizrn** [comment]
estava com o mesmo problema, removi o 9 a mais do meu número e funcionou

**Comment by KillovSky** [comment]
> estava com o mesmo problema, removi o 9 a mais do meu número e funcionou

Já corrigido na #59.
