### ISSUE TITLE
Erro. Não inicia. Alguem pode me ajudar?

### ISSUE THREAD

**Issue by herberthsfc** [KillovSky/iris#580]
![Capturar_2022_06_22_16_57_48_638](https://user-images.githubusercontent.com/76819767/175125317-cea5c259-611d-4e3c-b5db-e4549db4d389.png)

**Comment by KillovSky** [comment]
Seu arquivo `level.json` está corrompido, restaure o `level.json` antigo por meio de um dos backups da pasta `Backups`, se não tiver desativado eles.

Sempre procure por erros similares já existentes em vez de criar uma nova issue, demora muito tempo para responder, sendo que a resposta já foi postada em uma mesma pergunta feita por aqui.
