### ISSUE TITLE
[BUG] -> Aniversário do grupo / Anti-adicionar em grupos

### ISSUE THREAD

**Issue by Witputinfo7** [KillovSky/iris#582]
Olá Lucas, quando a minha íris é adicionada em qualquer grupo acontece de ela da erro pra qualquer mensagem enviada no grupo, seja mensagem normal ou comando, como consigo resolver isso? Atenciosamente.
![IMG_20220629_105004](https://user-images.githubusercontent.com/108410970/176453534-dd489e66-9a7b-4c4d-97d2-c356b4bde583.jpg)

**Comment by Witputinfo7** [comment]
Bem, solucionou este problema, obrigado pela ajuda, mas mesmo que não seja muito importante este problema até por que essa versão apresenta alguns erros consecutivos mas pelo o que eu andei lendo a íris ainda não está pronta, mas sem enrolação o problema é que ela não tá saindo do grupo mesmo enviando a mensagem de quantidade de membros abaixo da exigida e suponho que aconteça o mesmo pra quando ela tá no máximo de grupos configurado e não saía... Qual talvez seja a solução para esse erro?
![IMG_20220629_172137](https://user-images.githubusercontent.com/108410970/176538330-27809025-a837-47c8-9405-ba514c4d52b3.jpg)

**Comment by KillovSky** [comment]
Se você estiver como dono na `config.json`, ela não vai sair, ela não sai de grupos que tenham o dono ou algum VIP dentro.

Quanto a mensagem, deve ter um erro de código para que ela seja enviada mesmo percebendo que o dono ou um VIP estão lá, mas isso exige uma verificação minha, irei fazer a correção e enviar na próxima atualização caso tenha um erro do tipo.

Obrigado por informar!

**Comment by KillovSky** [comment]
Corrigido na `V3.3.0`.
