### ISSUE TITLE
Erros com comandos

### ISSUE THREAD

**Issue by marciovdc** [KillovSky/iris#585]
Olá Devels, estou com erros na Íris com Todos os comandos. Ela não chega a parar, porém, dá o mesmo erro com qualquer comando:

😵 _Ooops, algo de errado aconteceu comigo, de uma olhada nos detalhes abaixo e se puder use o_ */help!*

#️⃣ - "/stickers"

❓- "Error"

❌ - "Evaluation failed: Error: Unexpected null or undefined: this.quotedParticipant
    at t.default (https://web.whatsapp.com/:2:400)
    at y._getQuotedMsgObj (https://web.whatsapp.com/bootstrap_qr.f74b98c729dd38392a5f.js:75:604223)
    at y.quotedMsgObj (https://web.whatsapp.com/bootstrap_qr.f74b98c729dd38392a5f.js:75:603942)
    at pptr://__puppeteer_evaluation_script__:1:222572
    at Array.filter (<anonymous>)
    at window.<computed>.<computed> [as reply] (pptr://__puppeteer_evaluation_script__:1:222222)"

📅 - "23/07/22 21:26:12"

❗ - "Erro não detalhado, descrição acima."

📁 - " at t.default (https"

🧶 - "Linha #//[web.whatsapp.com/](http://web.whatsapp.com/)

🔍 - "Caractere #2"

**Comment by KillovSky** [comment]
Parece similar ao https://github.com/KillovSky/iris/issues/535#issuecomment-1040613623 e outros problemas postados antes...ao que tudo aparenta, sempre que ocorre um erro desses, é por uma atualização do WhatsApp Web, que acaba por 'quebrar' os sistemas da `Wa-Automate`, que os corrige fazendo patches que são aplicados ao ligar, de toda forma...

Isso ocorre somente em um grupo? Você está na Íris mais recente? Você possui tudo atualizado? Está usando mensagens temporárias? Alguma outra informação útil?

Envie as respostas e tente fechar e rodar `npm update`, depois ligue e veja se está funcionando e informe aqui.

**Comment by marciovdc** [comment]
Isso ocorre somente em um grupo? Não 
Você está na Íris mais recente? Sim
Você possui tudo atualizado? Sim
Está usando mensagens temporárias? Não 

Alguma outra informação útil? A solução que encotrei foi remover o bot e realizar a reinistalação e rodar um npm update antes de iniciar, após isso a iris não apresentou erros. Vou ficar monitorando, verifiquei nas issues do wa-automate e tinha reclamações sobre o erro.

Mas valeu KillovSky vc é D+.
