### ISSUE TITLE
Ideia - clonar grupo

### ISSUE THREAD

**Issue by ruip005** [KillovSky/iris#587]
Novo comando para clonar grupo - Como assim clonar grupo?
O comando irá adicionar participantes de outros grupos e irá adicionar no seu

Imagine o grupo X tem 107 membros com o comando de clonar grupo eu consigo adicionar esses 107 membros no meu exceto caso algum desses esteja com privacidade de grupos privada (não permite que outros contactos adicionem ele em grupos)

**Comment by KillovSky** [comment]
Já vi outros BOT's com uma implementação similar e já pensei sobre, resolvendo por não fazer algo assim, por conta de:

1. Risco de segurança, pois é algo que pode te banir do WhatsApp.

2. Pode ser usado contra você, mesmo que eu insira centenas de regras de segurança para impedir isso.

3. Viola a privacidade dos usuários da Iris, tenho um voto de prezar pela segurança e liberdade de todos, esse comando viola essa liberdade.

Mas quem sabe eu traga algo similar para ajudar com a recriação de um grupo usando os mesmos valores, afinal, meu grupo é extremamente pesado mesmo que seja totalmente limpo, seria bom recriar tudo automaticamente...então, quem sabe futuramente em alguma atualização esse sistema seja feito por uma necessidade e não para violar os direitos de usuários...bem, apenas aguarde, se ela for lançada irei avisar nesta issue!
