### ISSUE TITLE
Antilinks não funfa

### ISSUE THREAD

**Issue by ruip005** [KillovSky/iris#588]
Ativo mas não faz nada quando alguém envia

**Comment by KillovSky** [comment]
Mostre a mensagem enviada que não foi detectada.

E lembre-se, o `antilinks` é para links de grupo.
`Anylinks` para qualquer link.
`Safelinks` para casos de virus, propaganda, porno ou similares.
`Antiporn` para links pornográficos apenas.

**Comment by ruip005** [comment]
Ativei primeiramente o antilinks testei com um link para entrar em um gp de whatsapp e o bot n fez nada e na console não fez nada
Ativei o anylinks mandei link de grupo e video do yt e também n fez nada

**Comment by KillovSky** [comment]
> Ativei primeiramente o antilinks testei com um link para entrar em um gp de whatsapp e o bot n fez nada e na console não fez nada
> Ativei o anylinks mandei link de grupo e video do yt e também n fez nada

Tente fazer uma reinstalação, sair e entrar do grupo e  limpar o WhatsApp, aparentemente isso pode ser um erro de leitura da mensagem por problemas com o grupo.

**Comment by ruip005** [comment]
Reinstalei vps e bot v3.3.2 mas mesmo assim não é detectado nenhum link e na log na consola identifica como mensagem
