### ISSUE TITLE
erro ao iniciar o bot

### ISSUE THREAD

**Issue by kacarlos23** [KillovSky/iris#589]
![image](https://user-images.githubusercontent.com/85625929/187914495-1ca4d735-de85-4b5f-9491-c7fdc35db56e.png)

ja instalei o gow e adicionei ele ao path, e tentei instalar o shelljs de varias maneiras, mas continua dando esse erro

**Comment by PedroBatistop** [comment]
Já tentou rodar `npm i shelljs`? Se sim, dá algum erro? Mande o erro aqui.
