### ISSUE TITLE
O problema não era a letra minuscula :/ 

### ISSUE THREAD

**Issue by NoHeroMonster** [KillovSky/iris#59]
![image](https://user-images.githubusercontent.com/87252668/125181636-30f02a80-e1dd-11eb-8848-f09260aa7aa6.png)

**Comment by KillovSky** [comment]
Olá novamente, a letra maiuscula contribui e muito para causar o erro, mas se não foi ela, você está inserindo o número corretamente? Pois fiz os testes aqui e não obtive erro algum com ela.
O modo para inserir é `numero sem simbolos + @c.us`.
Exemplo: `551209876543@c.us`, também deixe os outros conteudos em branco, ou seja, apague tudo que estiver dentro das outras aspas no parametro Owner, você também pode apagar inclusive as aspas e deixar apenas a que contém seu número, também tenha em mente de que o número digitado não pode ser o número que você roda a Iris e sim o número da qual você vai digitar o comando, identico ao WhatsApp, se no WhatsApp não tiver o 9 adicional após o DDD, não insira o 9 adicional, ele geralmente não existe nas operadoras que não são a VIVO - ao menos no WhatsApp.

Exemplo de configuração correta:

```Owner: ['551234567890@c.us'],```

**Comment by KillovSky** [comment]
Tente fazer uma reinstalação do zero com a nova versão, no caso de persistência tente com outro número e se não resolver, abra uma issue com todas as informações que puder, obrigado!

**Comment by NoHeroMonster** [comment]
Eu não sei o que houve, mas refiz a instalação e deixei nos mesmos parametros e funcionou!

**Comment by KillovSky** [comment]
> Eu não sei o que houve, mas refiz a instalação e deixei nos mesmos parametros e funcionou!

Excelente! Espero que goste da Íris - mesmo com os problemas da beta! ;D
