### ISSUE TITLE
Arquivo corrompido

### ISSUE THREAD

**Issue by WillianPaulino** [KillovSky/iris#591]
![Screenshot_2](https://user-images.githubusercontent.com/72257810/190439064-e23eb387-f9fd-4e2f-89b2-6a4d9367c883.png)

Como posso resolver ?

**Comment by PedroBatistop** [comment]
Parece que algum dos seus JSONs corrompeu, é recomendável que você restaure um backup ou os reinstale do 0.

**Comment by PedroBatistop** [comment]
> > Parece que seus JSONs corrompeu, quase certo que foi o `config.json`, é recomendado que você restaure um backup ou os reinstale do 0.
> 
> config.json da Iris, no caso ?

sim

**Comment by WillianPaulino** [comment]
> > > Parece que seus JSONs corrompeu, quase certo que foi o `config.json`, é recomendado que você restaure um backup ou os reinstale do 0.
> > 
> > 
> > config.json da Iris, no caso ?
> 
> sim

Tentei fazer o que disse, mas não mudou nada. Continua aparecendo o mesmo.

**Comment by PedroBatistop** [comment]
Tente baixar o arquivo `lib\config\Settings\config.json` do GitHub novamente e refaça as alterações. Sempre recomendo refazer a instalação toda do 0, excluir os arquivos atuais da Íris, salvar os arquivos necessários, caso tenha, como o level.json, e fazer o download da mesma do GitHub novamente, rode os comandos `npm i` e `npm update`. Tenha certeza de que está usando as versão recomendada do Node. Se não fizer uma instalação do 0, exclua a pasta `node_modules` e o arquivo `package-lock.json`, rode os comandos `npm i` e `npm update`.

**Comment by KillovSky** [comment]
Você pode tentar restaurar o último arquivo zip da pasta de Backups, basta extrair e substituir por cima, se precisar reinstalar, você pode executar o tools.sh, ele te fará a configuração automaticamente, facilitando, mas faça uma copia de segurança antes.

**Comment by PedroBatistop** [comment]
Como houve uma demora assumo que o problema esteja resolvido, estou fechando essa issue. Se o problema persistir sinta-se livre para fazer mais um comentário nessa issue.
