### ISSUE TITLE
[Node.js] -> Inicialização | Core Dumped

### ISSUE THREAD

**Issue by WillianPaulino** [KillovSky/iris#592]
![Captura de tela de 2022-09-23 18-09-07](https://user-images.githubusercontent.com/72257810/192057136-03cef90d-875c-4688-b420-3db5216f35fa.png)

**Comment by KillovSky** [comment]
Esse é um erro relativo do sistema operacional, acredito eu ser uma falha do kernel.

O erro pode ser diversas coisas, todavia, ele conseguiu ser corrigido pelo @TioDasTrevas1 simplesmente configurando a key `Auto_Update` como `false`, ou seja, vá na `config.JSON` e procure por `Auto_Update`, na frente estará escrito `true`, basta mudar para `false`, se funcionar diga.

**Comment by WillianPaulino** [comment]
Boa noite! Fiz o que você sugeriu, porém, continuo com o mesmo problema.

**Comment by WillianPaulino** [comment]
> Boa noite! Fiz o que você sugeriu, porém, continuo com o mesmo problema.

![Captura de tela de 2022-09-23 21-23-44](https://user-images.githubusercontent.com/72257810/192071974-f58a1b00-9995-4dd6-9e47-aa735691fdda.png)

**Comment by KillovSky** [comment]
O problema já se torna mais confuso pois existem infinitas razões do por que isso falhou...

Tente fazer a reinstalação do seu Node.js seguindo os passos descritos na página inicial, depois tente fazer edições na `config.json` e `sessions.json` seguindo os tutoriais, que também estão na página inicial.

**Comment by WillianPaulino** [comment]
Olá. Eu mudei de sistema operacional, botei o Windows 8.1. Agora eu consigo iniciar a iris, porém fico com a tela mostrada abaixo, não aparece mais nada além disso: 
![image](https://user-images.githubusercontent.com/72257810/192111238-1a751de4-052e-4cea-8f1c-b40458883674.png)

**Comment by JohnEdwardMS** [comment]
> Olá. Eu mudei de sistema operacional, botei o Windows 8.1. Agora eu consigo iniciar a iris, porém fico com a tela mostrada abaixo, não aparece mais nada além disso: ![image](https://user-images.githubusercontent.com/72257810/192111238-1a751de4-052e-4cea-8f1c-b40458883674.png)

Sempre aparece isso mesmo e é normal pra mim, só mandar uma mensagem pro BOT e se responder é pq ta funcionando corretamente.

**Comment by WillianPaulino** [comment]
> > Olá. Eu mudei de sistema operacional, botei o Windows 8.1. Agora eu consigo iniciar a iris, porém fico com a tela mostrada abaixo, não aparece mais nada além disso: ![image](https://user-images.githubusercontent.com/72257810/192111238-1a751de4-052e-4cea-8f1c-b40458883674.png)
> 
> Sempre aparece isso mesmo e é normal pra mim, só mandar uma mensagem pro BOT e se responder é pq ta funcionando corretamente.

Esse é o problema, mando várias mensagens após esse resultado e não tenho nenhuma resposta.

**Comment by KillovSky** [comment]
Resolvido por meio do suporta via [Telegram](t.me/PROJETOIRIS).

Raiz do problema: Módulo `sharp`.

Motivo: Processador ou Componentes do PC "muito antigos".

Explicação: O módulo `sharp` não possui suporte adequado a computadores mais "antigos".

Solução: Fazer downgrade do módulo `sharp` para uma versão igual ou inferir a `0.27.2`.

Solução explicativa simples, não recomendada:

1. - Para não precisar fazer as configurações, instalações ou edições todas novamente, você pode simplesmente rodar `npm i sharp@0.27.2` na pasta de instalação da sua Íris, faça isso sempre que atualizar a Íris, os módulos ou baixar novamente.

Solução "mais segura" e explicativa por etapas:

1. - Delete a sua Íris e baixe novamente, não faça nenhuma instalação ou configuração ainda.

2. - Por seguranca extra, rode `npm cache clear --force && rm -rf node_modules package-lock.json` no `Git Bash`, no `Terminal Linux` ou no `Terminal` do seu sistema, se o `rm` não funcionar, apague a pasta `node_modules` se existir.

3. - Vá e abra a `package.json`.

4. - Localize a linha: `"sharp": "^0.30.5"`.

5. - Mude para: `"sharp": "0.27.2",`.

6. - Rode a instalação.

7. - Edite os arquivos necessários.

8. - Inicie com sua forma favorita e seja feliz.
