### ISSUE TITLE
[BUG/WA AUTOMATE] -> Inicialização obteve erro de mdOptedIn

### ISSUE THREAD

**Issue by herberthsfc** [KillovSky/iris#595]
![16673921884697642885681669800577](https://user-images.githubusercontent.com/76819767/199490065-230d834a-3aba-4c52-bc16-d4dd525ac10a.jpg)

**Comment by KillovSky** [comment]
Este não é um erro da Íris, mas sim de uma lib importantíssima dela, leia mais aqui: https://github.com/open-wa/wa-automate-nodejs/issues/2936

Apenas aguarde uma atualização do módulo e rode `npm update` quando sair.

Ps: Não sei se ativar a `GH_Patch` da `sessions.json` pode corrigir, mas faça um teste.

Como?

Vá na pasta `Settings`, abra o `Sessions.json` e mude a linha:

`"GH_Patch": "Opcional | True | False",`

Para:

`"GH_Patch": true,`

Se não funcionar ou caso queira desfazer, os valores padrões estão na `Sessions_Default.json`, ou insira `false` ou basta copiar o valor acima e inserir.

Evite ao máximo ficar utilizando o `GH_Patch`, só use quando obter erros com a inicialização comum e jamais use por muito tempo, verifique depois de algumas horas se consegue iniciar de forma comum, ou seja, com o `GH_Patch` desativado.

Se ligar, **NÃO REINICIE** até a issue ser resolvida!

**Comment by KillovSky** [comment]
Corrigido ao deletar os arquivos de sessão e escanear o QR novamente.
