### ISSUE TITLE
ERRO ao iniciar o bot

### ISSUE THREAD

**Issue by eduardoo1911** [KillovSky/Iris#596]
Ao dar um "npm start" dá o seguinte erro:
![error](https://user-images.githubusercontent.com/77181496/201442989-32b7723a-8c2f-4f6a-a84e-61286a37a785.png)

como resolver isso?

**Comment by PedroBatistop** [comment]
Provável que tenha dado erro na instalação dos módulos, `npm i`. Por favor, mande uma print do erro.

**Comment by eduardoo1911** [comment]
![image](https://user-images.githubusercontent.com/77181496/201444512-29092c38-b5fd-43e3-94ca-67e4f500d441.png)

esse é o erro que aparece

**Comment by PedroBatistop** [comment]
#584

**Comment by eduardoo1911** [comment]
consegui resolver fazendo esse passo a passo:

"Eu estava com esse problema junto com muitos aqui e não consegui resolver de jeito algum.
Único método que consegui pra resolver foi:
Abrir arquivo package.json
Deletar toda line 69 ("youtube-dl-exec": "^2.0.0",)
Salvar
"npm i" novamente."

Após isso funcionou tranquilamente.

encontrei por aí nas issues. Vlw
