### ISSUE TITLE
[ERRO] Inicialização Npm

### ISSUE THREAD

**Issue by PANINOBR** [KillovSky/Iris#597]
Olá toda vez que inicio o (npm start) ele aparece uma lista de erros enormes, já está instalado o node lts, pyton 64, mas mesmo assim o erro continua usei várias vezes o npm update e npm i deletei a line do ''youtube'' no package.json mesmo assim não resolveu no npm i, print abaixo

![image](https://user-images.githubusercontent.com/48421679/201501638-8a124c18-0d01-4d89-969b-f0f7749b02a9.png)

![image](https://user-images.githubusercontent.com/48421679/201501651-05f5a260-0c6e-4ae1-af64-bd17661f7731.png)

**Comment by PANINOBR** [comment]
Consegui resolver algumas partes de erros era uma incompatibilidade da versão do node (19) fui na github e mudei a versão para a (14 old)  que reconheceu algumas coisas, porém agora ele está dando erro do youtube como eu havia citado na mensagem acima print abaixo

![image](https://user-images.githubusercontent.com/48421679/201502371-42ca0000-afc1-4df6-9cdc-3c237089b75b.png)

**Comment by PANINOBR** [comment]
Consegui resolver o erro da parte do youtube dl forçando o npm i, por agora o erro é na parte do qr code quando (conecto no celular) ele conecta normal, porém no cmd ele fica aparecendo o qr code na tela e não faz mais nada não respondendo os comandos print abaixo

![image](https://user-images.githubusercontent.com/48421679/201503037-82466d90-695a-4133-a77c-1a47238f2dc9.png)

**Comment by KillovSky** [comment]
Desculpe não ter respondido, estou tendo uma semana muito ocupada, mas enfim, isso foi corrigido por parte da `wa-automate` por aqui: https://github.com/open-wa/wa-automate-nodejs/issues/2930

Você conseguiu usar?

**Comment by PANINOBR** [comment]
assim, thanks
