### ISSUE TITLE
Oracle

### ISSUE THREAD

**Issue by 6ixBR** [KillovSky/Iris#598]
A Oracle está dando uma VPS gratuita e para sempre, porém não estou conseguindo instalar a íris, está dando erro na instalação do Google Chrome, existe alguma imagem que funciona? 

Se alguém puder fazer um vídeo explicando certinho, desde como configurar desde a criação da VPS até a instalação da íris, eu agradeceria demais.

os sistemas operacionais possíveis na VPS são estes:

![image](https://user-images.githubusercontent.com/116978765/204560728-72fe0899-b52a-42a2-8c6a-adbd59ad568d.png)

**Comment by 6ixBR** [comment]
os sistemas operacionais possíveis na VPS são:

Ubutu, CentOS, Oracle Linux e Oracle Linux VPS.

**Comment by KillovSky** [comment]
Insira a imagem de erro da instalação do Chrome, e tenha em mente que seu S.O deve ser x64 ("amd64" = "x86_64") para funcionar, caso ele seja um sistema x86 ("i386") ou com arquitetura diferente da suportada pelo Chrome, você vai obter estes erros mesmo, podendo pular a instalação do chrome, perdendo diversas funcões, como o `/Play`.

Por mais que eu "odeie" Ubuntu, acredito que ele seja a opção mais fácil desta lista, existem tutoriais na página de tutoriais, basta clica aqui ---> #28

**Comment by 6ixBR** [comment]
atualizei a VPS, reiniciei ela, fiz o download do Chrome e aparece esta mensagem de erro quando tento instala-lo:

![image](https://user-images.githubusercontent.com/116978765/204578689-cc3c63ec-19bf-48e7-8951-1696853224d5.png)

**Comment by Cobra-Mafia** [comment]
Olá, ja tentou usar o passo a passo do manual de instalação para VPS linux?
tente segui esse passo a passo aqui.
https://github.com/KillovSky/iris/files/9254464/Instalacao.txt

Abraços

**Comment by 6ixBR** [comment]
usei este mesmo, e dá o mesmo erro kkkk

**Comment by Cobra-Mafia** [comment]
me passe o link do site do Oracle para eu fazer uma conta lá e testar e tentar atualizar esse passo a passo que lhe passei.

**Comment by 6ixBR** [comment]
teria como usar o chromium?

**Comment by 6ixBR** [comment]
> Insira a imagem de erro da instalação do Chrome, e tenha em mente que seu S.O deve ser x64 ("amd64" = "x86_64") para funcionar, caso ele seja um sistema x86 ("i386") ou com arquitetura diferente da suportada pelo Chrome, você vai obter estes erros mesmo, podendo pular a instalação do chrome, perdendo diversas funcões, como o `/Play`.
> 
> Por mais que eu "odeie" Ubuntu, acredito que ele seja a opção mais fácil desta lista, existem tutoriais na página de tutoriais, basta clica aqui ---> #28

essa função /play é crucial para o funcionamento do bot?

**Comment by 6ixBR** [comment]
é foda, VPS muito boa, gratuita que não instala a íris completamente.

![image](https://user-images.githubusercontent.com/116978765/204612018-0ccf5885-5fd5-417a-b810-d2bf861335d5.png)

**Comment by marciovdc** [comment]
Eu consegui fazer ela funcionar, usando dois nucleos intel, 16gm de ram, linux ubuntu 20 minimal, inclusive usei o filezilla para trasferir os arquivos de backup, a iris está operacional .

**Comment by KillovSky** [comment]
> atualizei a VPS, reiniciei ela, fiz o download do Chrome e aparece esta mensagem de erro quando tento instala-lo:
> 
> ![image](https://user-images.githubusercontent.com/116978765/204578689-cc3c63ec-19bf-48e7-8951-1696853224d5.png)
> 
> tentei instalar as dependências uma por uma, e mesmo assim aparece que ela não está funcionando.

Sua Oracle não permite pois falta um gerenciador de janelas X11, nesse caso, o Chrome não conseguiria abrir sem.

Você pode pular esse passo, Chrome, apesar de ser um requisito a vários comandos, é opcional para o funcionamento geral.

Você pode inclusive usar qualquer navegador baseado no `chromium` na Íris, como o `Microsoft Edge`, arriscando perder alguns comandos.

Ou você pode tentar os passos abaixo para rodar a versão `rpm`, que é mais recomendada no Oracle, por se tratar de uma distro com base no `"redhat"`:

```bash
wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm

sudo yum install ./google-chrome-stable_current_x86_64.rpm
```

Creio que deverá funcionar.

**Comment by KillovSky** [comment]
> é foda, VPS muito boa, gratuita que não instala a íris completamente.
> 
> ![image](https://user-images.githubusercontent.com/116978765/204612018-0ccf5885-5fd5-417a-b810-d2bf861335d5.png)
> 

Processador baseado em `ARM`?

Cara...não sei se isso pode ser o problema, mas o Chrome não possui versão para ARM, você pode enviar o resultado do comando `uname -a`?

De preferência antes de rodar os comandos acima ou rodar outros comandos de instalação novamente, acredito que darão erro se for realmente um sistema ARM e não AMD64 como disse lá acima.

**Comment by KillovSky** [comment]
> Eu consegui fazer ela funcionar, usando dois nucleos intel, 16gm de ram, linux ubuntu 20 minimal, inclusive usei o filezilla para trasferir os arquivos de backup, a iris está operacional .

Alguns membros do desenvolvimento do projeto conseguiram a façanha de rodar em apenas 512MBs de RAM e um processador ruim, fiquei até surpreso.

Íris é leve e roda bem, mas depende muito do que o seu sistema operacional faz de fundo, a maior parte do consumo da Íris é apenas no navegador, no caso, uns 60-80% da memoria consumida dela é o Chrome/Chromium.

Mas isso não tira o fato de que estes navegadores por si só já são uns tremendos comedores de memoria RAM, o que me surpreende, pois rodaram a Íris em 512MBs de RAM, com velocidade boa e usando Chrome ainda!

**Comment by 6ixBR** [comment]
> > é foda, VPS muito boa, gratuita que não instala a íris completamente.
> > ![image](https://user-images.githubusercontent.com/116978765/204612018-0ccf5885-5fd5-417a-b810-d2bf861335d5.png)
> 
> Processador baseado em `ARM`?
> 
> Cara...não sei se isso pode ser o problema, mas o Chrome não possui versão para ARM, você pode enviar o resultado do comando `uname -a`?
> 
> De preferência antes de rodar os comandos acima ou rodar outros comandos de instalação novamente, acredito que darão erro se for realmente um sistema ARM e não AMD64 como disse lá acima.

ele dá arm64

**Comment by 6ixBR** [comment]
vi tbm que algumas versões do python não funcionam na versão arm64 e para instalar o chrominium no ubuntu você precisa instalar os repositórios do debian

**Comment by KillovSky** [comment]
Como seu sistema é ARM, você dificilmente deve conseguir instalar e rodar 100% do sistema de forma funcional.

Tenho minhas dúvidas se você consegue até mesmo efetuar a instalação do Canvas, que é vital.

De toda forma, pule a instalação do Chrome e siga os próximos passos do tutorial que você estava seguindo, e reze para funcionar, se obter erros, mostre aqui, embora provavelmente não seja possível corrigir devido a arquitetura do processador, que é incompatível com diversos requisitos da Íris.

Esclarecendo uma coisa antes, alguns haters sempre vem em minhas redes sociais falar que a Íris é "obesa", ruim e algumas ofensas, provavelmente dirão que essa issue é a prova disso e surgirão fake news sobre o consumo da Íris e coisas degradando a imagem dela - vem acontecendo muito - entretanto já aviso, esse problema de arquitetura não possui nada haver com o consumo de memoria e demais informações dela, não caiam em fake news sobre ela, problemas desse tipo são de responsabilidade dos módulos que ela usa, tais como `canvas`, `youtube-dl-exec` e `chrome`, não são responsabilidade dos DEVs do `Projeto Íris`, se você - quem estiver lendo e for hater - estiver planejando espalhar fake news sobre isso, favor ir ** ***** o quanto antes.

Voltando ao assunto, se funcionar, use o comando `/nocmd -global` para desativar o `play`, `video` e `ytsearch`, desative também qualquer comando relacionado a envio de videos e documentos e não menos importante, desative os comandos que derem o erro: `Unsupported Media Type`.

**Comment by 6ixBR** [comment]
ok

**Comment by 6ixBR** [comment]
não consegui de jeito algum kkk, me desculpem, eu tentei

**Comment by PedroBatistop** [comment]
> A Oracle está dando uma VPS gratuita e para sempre, porém não estou conseguindo instalar a íris, está dando erro na instalação do Google Chrome, existe alguma imagem que funciona?
> 
> Se alguém puder fazer um vídeo explicando certinho, desde como configurar desde a criação da VPS até a instalação da íris, eu agradeceria demais.
> 
> os sistemas operacionais possíveis na VPS são estes:
> 
> ![image](https://user-images.githubusercontent.com/116978765/204560728-72fe0899-b52a-42a2-8c6a-adbd59ad568d.png)

![image](https://user-images.githubusercontent.com/80703967/205953842-59ab57f4-aa60-4927-88f6-78bc38d39735.png)

```
 sudo yum install liberation-fonts
 sudo yum install libXScrnSaver.x86_64 libappindicator-gtk3.x86_64
 sudo yum install vulkan
 sudo yum -y install alsa-lib-devel
 sudo yum -y install libgbm
 wget https://dl.google.com/linux/linux_signing_key.pub
 sudo rpm --import linux_signing_key.pub
 wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
 sudo rpm -ivh google-chrome-stable_current_x86_64.rpm
```

**Comment by 6ixBR** [comment]
funcionou para você amigo?

**Comment by 6ixBR** [comment]
o cara comentou, apagou e é isso ai, q se **** kkkkkkkkk

**Comment by PedroBatistop** [comment]
> o cara comentou, apagou e é isso ai, q se **** kkkkkkkkk

Funcionou sim, mas foi em outra imagem de VPS. Resolvi apagar pois confundi as coisas.

**Comment by PedroBatistop** [comment]
Você ainda pode escolher uma instância baseada em arquitetura que nao seja ARM, mas com a memória e OCPU limitados a 1. Conseguindo instalar assim a íris.
