### ISSUE TITLE
Level UP 1+

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#60]
![image](https://user-images.githubusercontent.com/44541791/125181708-faff7600-e1dd-11eb-9fbe-2c05e834d495.png)

bot nao mandar msg lvl UP ?
![image](https://user-images.githubusercontent.com/44541791/125181718-18ccdb00-e1de-11eb-9129-86d452b5df67.png)

**Comment by KillovSky** [comment]
Estranho, isso não acontece comigo, mas tenho uma ideia geral de onde você está obtendo o erro, agradeço por informar e tomarei em conta de tentar fazer uma correção caso eu ache indicios de um BUG.

![IMG_20210711_022633.jpg](https://user-images.githubusercontent.com/55511420/125183761-7158a400-e1ef-11eb-8bd1-8a305bee5318.jpg)

**Comment by maradona4** [comment]
Entendi

**Comment by maradona4** [comment]
não conseguir, testar tudo, o bot não enviou, meus grupos pessoais 40 membros online, Level up bugado

**Comment by maradona4** [comment]
eu acho esse cmd /give -xp @eu 100
bot nao manda level up+

**Comment by KillovSky** [comment]
> eu acho esse cmd /give -xp @eu 100
> bot nao manda level up+

Realmente tem um problema, ele somente envia a mensagem caso a pessoa tenha XP suficiente para dois niveis, agradeço, irei fazer uma correção geral e atualizar.

**Comment by maradona4** [comment]
Blz
