### ISSUE TITLE
error quando da um comando

### ISSUE THREAD

**Issue by dodouglas123** [KillovSky/Iris#601]
```
[FALHA GERAL] TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.exports.kconfig (C:\Users\fdoug\Desktop\Iris-main\lib\functions\config.js:327:31)
```

**Comment by PedroBatistop** [comment]
Issue resolvida no Discord.

Devido a uma atualização recente do wa automate deu umas inconsistências em algumas propriedades.
Eu resolvi da seguinte forma:

`const quoMens =
      (message.quotedMsg !== null && message.quotedMsg !== undefined)
        ? message.quotedMsg
        : (message.quotedMsgObj !== null && message.quotedMsgObj !== undefined)
          ? message.quotedMsgObj
          : {};
    const quotObjmes =
    (message.quotedMsgObj !== null && message.quotedMsgObj !== undefined) ? message.quotedMsgObj : quoMens;`
