### ISSUE TITLE
erro ao iniciar

### ISSUE THREAD

**Issue by pablorere** [KillovSky/Iris#602]
[FALHA GERAL] TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.exports.kconfig (D:\Iris-main\lib\functions\config.js:326:28)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by PedroBatistop** [comment]
Poderia enviar o log de erro completo?

Peço que compreenda o seguinte, pois esta pode ser a causa do erro:
A lib que a Íris utiliza sofreu um takedown enviado pelo dono do WhatsApp, fazendo com que a mesma não tivesse escolha a não ser desistir, ou seja, a lib nãop terá mais atualizações e supoprte, fazendo com que ao passra do tempo pare de funcionar, portanto, estamos descontinuando a Íris com essa lib, as coisas vão mudar totalmente, esperamos que possamos usar uma lib nova como whatsappweb.js sem problemas, mas caso isso não seja possível, utilizaremos o baileys não oficial apenas, se caso o WhatsApp derrube todas as libs que possamos usar, pode ser que não conseguiremos, neste caso, daremos nossa carta de adeus, espero que isso não seja uma opção e que tenhamos sorte, estaremos tentando desenvolver novos projetos.

Edições feitas por terceiros no código da Íris também pode causar mau funcionamento.

**Comment by pablorere** [comment]
D:\Iris-main\start.js:18
tools('config').kconfig('test', 'test');
               ^

TypeError: Cannot read property 'kconfig' of undefined
    at Object.<anonymous> (D:\Iris-main\start.js:18:16)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47


agora aparece isso

**Comment by pablorere** [comment]
> Poderia enviar o log de erro completo?
> 
> Peço que compreenda o seguinte, pois esta pode ser a causa do erro: A lib que a Íris utiliza sofreu um takedown enviado pelo dono do WhatsApp, fazendo com que a mesma não tivesse escolha a não ser desistir, ou seja, a lib nãop terá mais atualizações e supoprte, fazendo com que ao passra do tempo pare de funcionar, portanto, estamos descontinuando a Íris com essa lib, as coisas vão mudar totalmente, esperamos que possamos usar uma lib nova como whatsappweb.js sem problemas, mas caso isso não seja possível, utilizaremos o baileys não oficial apenas, se caso o WhatsApp derrube todas as libs que possamos usar, pode ser que não conseguiremos, neste caso, daremos nossa carta de adeus, espero que isso não seja uma opção e que tenhamos sorte, estaremos tentando desenvolver novos projetos.
> 
> Edições feitas por terceiros no código da Íris também pode causar mau funcionamento.

nao tem erro no log so ali na tela mesmo

**Comment by KillovSky** [comment]
Use isto: https://github.com/KillovSky/Iris/issues/601#issuecomment-1545639871

**Comment by pablorere** [comment]
> Use isto: [#601 (comment)](https://github.com/KillovSky/Iris/issues/601#issuecomment-1545639871)

ja usei e nao funciona a linha do erro e diferente

**Comment by KillovSky** [comment]
Não recomendo mas...

```javascript
// Mudar:
const quotedMsg = Object.keys(quoMens).length !== 0 && quotObjmes.id !== quoMens.id ? await kill.getMessageById(quoMens.id) : quoMens;

// Para:
const quotedMsg = Object.keys(quoMens).length !== 0 && quotObjmes?.id !== quoMens?.id ? await kill.getMessageById(quoMens?.id) : quoMens;
```

Basicamente, insira `?` antes dos `.` dos códigos, isso se chama `operador de coalescência nula`, não é boa prática, mas deve resolver.

**Comment by sn00wzz** [comment]
tô com esse mesmo problema, e nenhuma solução funcionou 😔

**Comment by KillovSky** [comment]
Abra a **config.js**, vá na linha **326** e troque-a para essa:

```
const quotedMsg = quotObjmes?.id == quoMens?.id ? quoMens : await kill.getMessageById(quoMens?.id || id);
```

**Comment by KillovSky** [comment]
Abra a **config.js**, vá na linha **326** e troque-a para essa:

```javascript
const quotedMsg = quotObjmes?.id == quoMens?.id ? quoMens : await kill.getMessageById(quoMens?.id || id);
```

Faça o mesmo tipo de solução para qualquer linha com erros similares.

**Comment by KillovSky** [comment]
Issue com confirmação de ter sido resolvida pelo discord.
