### ISSUE TITLE
pergunta

### ISSUE THREAD

**Issue by Nhamin** [KillovSky/Iris#606]
como consigo acessar as pastas da vps, botei a iris na vps porem queria adicionar uns comandos a ela. porém nao me recordo do app para conseguir acessar as pastas em si dela

**Comment by KillovSky** [comment]
Varia de VPS a VPS, se a sua tiver SFTP (ou SSH), use isso: [WinSCP](https://winscp.net/eng/download.php)

**Comment by KillovSky** [comment]
Essa é considerada a última issue para o Projeto Íris antigo, tenha em mente que as soluções mais antigas, apartir dessa issue, podem não servir para o novo código.

Se estiver em dúvidas, pergunte e estaremos a disposição para resolver as novas issues referentes ao novo código construído com @WhiskeySockets (Baileys).
