### ISSUE TITLE
[Melhoria] -> Utilizar o Baileys da NPM em vez do repositório GitHub

### ISSUE THREAD

**Issue by lucassaud** [KillovSky/Iris#608]
```
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated @adiwajshing/baileys@5.0.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
```

no package.json:
    "@whiskeysockets/baileys": "^6.5.0",
    "fs": "^0.0.1-security",
    
    
 com isso já resolve os dois avisos que estão sendo gerados no Ruindows11.

**Comment by KillovSky** [comment]
Woa, não cheguei a saber que havia um pacote na NPM já, sempre estive usando a github do Baileys para instalação (https://github.com/WhiskeySockets/Baileys/issues/43#issuecomment-1535550135), mas tendo um módulo na NPM, isso resolve e ajuda muito mais!

Estarei inserindo aqui e atualizando o código, marcarei você na pull, já que isso também resolverá em tese nosso problema com alguns computadores e telefones usando node 20 e caindo na instalação antiga.

Novamente, muito obrigado!

**Comment by lucassaud** [comment]
Chará, fico muito feliz em lhe ajudar, quero lhe pedir outra coisa, tem como colocar algo no seu codigo para ser opcional o lance de download de video do youtube? quando vou instalar da alguns erros relacionados ao python, eu não vou usar nada de download do youtube. na verdade eu estou somente testando o codigo que você escreveu para ver o que posso melhorar no codigo do meu bot. eu criei um bot para um restaurante usando baileys, me chama no zap: +5516996509803 e tu pode testar meu bot funcionando em: +5516997888800.

o meu bot usa banco de dados mariadb, gera graficos de estatisticas e tem um monte de função legal. mas nada de download, ja que é especifico para restaurante.  bora conversar no wpp, eu quero agora criar uma interface web para logar o cliente, na verdade preciso criar uma interface onde 62 lojas vão ler o qr code.

**Comment by KillovSky** [comment]
Isso é simples, você só precisa deletar a pasta YouTube e remover o YouTube da instalação pelo `package-json`.

O sistema atual da Íris funciona em sistema de módulo, todos os arquivos se conectam a base, se um arquivo é removido, e não for vital, como as pastas de comandos, você pode remover e será como se ele nunca tivesse existido, fazendo a Íris não rodar mais tal sistema e nem reconhecer sua existência.

Sobre seu BOT, parece bem trabalhoso, fique a vontade para usar os códigos da Íris seguindo a licença dela (MIT).

Estarei censurando seu número pois sempre há alguém idiota para ficar fazendo ataques a inocentes, acredite, sempre tem.

Mas estarei indo lá para falar contigo, novamente, obrigado pela dica do módulo no NPM.

**Comment by KillovSky** [comment]
Problema resolvido e apontado na changelog, com crédito ao autor da issue (@lucassaud) pela sugestão.

Confira: [Changelog da versão 1.0.2](https://github.com/KillovSky/iris/blob/main/.github/CHANGELOG.md)
