### ISSUE TITLE
console Adm

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#61]
problema erro npm start

![image](https://user-images.githubusercontent.com/44541791/125203470-dabbcf80-e24e-11eb-8d4a-3d39fe16d7ad.png)

**Comment by KillovSky** [comment]
Esse é um bug isolado, não é referente a Íris mas sim ao módulo `Canvas`, não possuo uma resposta de correção para ele, mas por ter algo relacionado ao modulo `fs`, suspeito que possa ser referente ao local que você possa ter instalado a Íris ou a instalação em si, pois não vi algo relacionado a instalação do canvas na hora do seu `npm i`, tente em outra pasta e se puder, rode com `--force` para forçar a instalação do canvas.

**Comment by maradona4** [comment]
Valeu, agr funcionar iniciado
