### ISSUE TITLE
n aparece o menu quando eu mando 

### ISSUE THREAD

**Issue by pablorere** [KillovSky/Iris#610]
![Imagen de WhatsApp 2023-10-18 a las 14 23 29_0aa23942](https://github.com/KillovSky/Iris/assets/65947059/9e96e99b-fddb-44e8-b277-d10e5c2a9e0e)
![image](https://github.com/KillovSky/Iris/assets/65947059/2892e52b-baab-46bf-9640-2fae0bcc9db8)
e aparece isso no bot

**Comment by PedroBatistop** [comment]
Parece que necesita instalar Bash. Si está utilizando Windows, es posible que pueda instalarlo utilizando: https://gitforwindows.org/

**Comment by KillovSky** [comment]
Sempre leia o tutorial.
Ever read the guide.
Siempre lee el manual.
Selalu baca panduan.

https://github.com/KillovSky/Iris#requisitos-de-windows-e-ordem-de-instala%C3%A7%C3%A3o-downloads
