### ISSUE TITLE
Erro ao instalar dependências via NPM 

### ISSUE THREAD

**Issue by Kaally** [KillovSky/Iris#615]
### Você está usando a versão mais recente da Íris?

- [X] Sim, estou utilizando a versão mais recente da Íris

### Você seguiu corretamente as instruções de instalação?

- [X] Sim, segui todas as instruções de instalação conforme os guias

### Você tentou atualizar os módulos usando o comando "npm update"?

- [X] Sim, estou tentando com os módulos completamente atualizados

### Qual é a versão do NodeJS que você está usando?

![image](https://github.com/KillovSky/Iris/assets/119092658/8afd90f2-145f-4e72-af2b-b9d1e8f30538)

### Qual é a versão do NPM que você está usando?

![image](https://github.com/KillovSky/Iris/assets/119092658/36497f40-81ab-486c-b826-45d2eaa29092)

### Qual é a versão do Python que você está usando?

![image](https://github.com/KillovSky/Iris/assets/119092658/50010be9-aee1-44b9-a41b-9e25e3df7da0)

### Qual é o seu sistema operacional? Marque todos os sistemas nos quais o erro ocorreu para você.

Linux

### Em que tipo de função ocorre o erro?

Comandos, Outros (Inserir detalhes nas Informações Adicionais)

### Você desligou a Íris de maneira não convencional, como desconectar o PC da tomada?

- [X] Sim, a Íris foi desligada de forma não convencional

### Você editou a Íris em tempo real sem reiniciar após a edição?

- [X] Sim, fiz edições na Íris enquanto ela estava em execução (Inserir detalhes nas Informações Adicionais)

### Você tentou usar o mesmo número em dois ou mais Bots ao mesmo tempo?

- [X] Sim, estou usando o mesmo número em dois ou mais Bots ao mesmo tempo

### Você está usando algum servidor, VPN, proxy ou serviço similar?

Outros (Inserir detalhes nas Informações Adicionais)

### Há mais alguma informação que você gostaria de compartilhar? Descreva as Informações Adicionais.

![image](https://github.com/KillovSky/Iris/assets/119092658/0fbe332a-ad01-4558-a4af-2bba8bfa5d6b)

um conflito de dependências entre diferentes versões do pacote "sharp" em dois módulos: "wa-sticker-formatter" e "@whiskeysockets/baileys". O "wa-sticker-formatter" requer uma versão mínima de "^0.30.0" do "sharp", enquanto o "@whiskeysockets/baileys" requer uma versão mínima de "^0.32.2".

O npm está indicando que encontrou a versão "^0.30.7" do "sharp" no  projeto principal, que é incompatível com a versão mínima exigida pelo "@whiskeysockets/baileys".

**Comment by KillovSky** [comment]
Olá, parabéns por seguir a template!

Esse erro é devido ao Baileys atualizar e forçar o uso de um sharp que e incompatível com canvas.

Como você está no Linux, apenas digite `npm i --force` ou troque a versão do `sharp` no package json para `^0.32.2`, note que somente sistemas Linux e MacOS podem fazer isso, sistemas Windows acabarão por causar infinitos bugs em **TODOS OS COMANDOS CANVAS E SHARP**.

Abaixo é a explicação para quem tiver esse erro com Windows.

Conforme explicado nas redes sociais, é impossível usar Sharp e Canvas no mesmo computador Windows, mas a Íris faz um trick para isso, no entanto, com a atualização do Baileys, ele passou a forçar o uso de versões mais recentes e isso bloqueia a instalação da Íris, conforme referenciado aqui por outro DEV também: https://github.com/WhiskeySockets/Baileys/issues/576

A única forma de corrigir fácil por agora é executando `npm i --force`, mas em breve, será inserido nos tutoriais o que deve ser feito, com o passar dos meses, Windows se tornará mais e mais problemático de instalar.

Em si, o problema só afeta o Windows, e a correção permanente futura será apenas questão de tempo a parar de funcionar, talvez meses ou anos, quando isso ocorrer, é provável que não poderemos mais usar a Íris em Windows ou terei que fazer mudanças radicais, isso se canvas continuar a utilizar versões pré-compiladas desatualizadas de requisitos, conforme dito aqui: https://github.com/lovell/sharp/issues/3007#issuecomment-988662604

Saiba mais no [Canal de Atualizações da Íris no WhatsApp](https://linktr.ee/killovsky).

Resumindo, a melhor sugestão minha? Pode ser melhor usar Linux no futuro, além de poder usar Sharp e Canvas juntos, você terá um baita aumento de velocidade e funcionalidade na Íris.

**Comment by Kaally** [comment]
O Windows sempre complicando

Mas no linux consegui reverter a situação da seguinte maneira:

```bash
npm i --force
```

![image](https://github.com/KillovSky/Iris/assets/119092658/f5bed4b9-f248-49b1-9f28-138245cf155e)

Bom parece que teremos que mudar de bibliotecas futuramente.

**Comment by KillovSky** [comment]
Ótimo, por ser um Linux, deve seguir operando sem problemas!

Fecharei a issue agora, mas deixarei fixada até a atualização 1.1.2 que vem com os tutoriais atualizados.
