### ISSUE TITLE
Error "Start- OK" 

### ISSUE THREAD

**Issue by bennyJCc** [KillovSky/Iris#617]
### Você está usando a versão mais recente da Íris?

- [X] Sim, estou utilizando a versão mais recente da Íris

### Você seguiu corretamente as instruções de instalação?

- [X] Sim, segui todas as instruções de instalação conforme os guias

### Você tentou atualizar os módulos usando o comando "npm update"?

- [X] Sim, estou tentando com os módulos completamente atualizados

### Qual é a versão do NodeJS que você está usando?

actual

### Qual é a versão do NPM que você está usando?

actual

### Qual é a versão do Python que você está usando?

actual

### Qual é o seu sistema operacional? Marque todos os sistemas nos quais o erro ocorreu para você.

Windows

### Em que tipo de função ocorre o erro?

Comandos

### Você desligou a Íris de maneira não convencional, como desconectar o PC da tomada?

- [X] Sim, a Íris foi desligada de forma não convencional

### Você editou a Íris em tempo real sem reiniciar após a edição?

- [X] Sim, fiz edições na Íris enquanto ela estava em execução (Inserir detalhes nas Informações Adicionais)

### Você tentou usar o mesmo número em dois ou mais Bots ao mesmo tempo?

- [X] Sim, estou usando o mesmo número em dois ou mais Bots ao mesmo tempo

### Você está usando algum servidor, VPN, proxy ou serviço similar?

Outros (Inserir detalhes nas Informações Adicionais)

### Há mais alguma informação que você gostaria de compartilhar? Descreva as Informações Adicionais.

![image](https://github.com/KillovSky/Iris/assets/83303546/99291b98-57f0-4acc-b869-7902be51af6b)

**Comment by KillovSky** [comment]
Use `Git Bash`, no Windows 10 e 11 **NÃO UTILIZE CMD, POWERSHELL OU QUALQUER OUTRO TERMINAL!*

Windows 10?

Git Bash: ✅

CMD, PowerShell, +: ❌
