### ISSUE TITLE
npm i (fiz a instalaçao correta tanto do nodejs quanto do python)

### ISSUE THREAD

**Issue by MatheusOFC** [KillovSky/Iris#619]
### Você está usando a versão mais recente da Íris?

- [X] Sim, estou utilizando a versão mais recente da Íris

### Você seguiu corretamente as instruções de instalação?

- [X] Sim, segui todas as instruções de instalação conforme os guias

### Você tentou atualizar os módulos usando o comando "npm update"?

- [X] Sim, estou tentando com os módulos completamente atualizados

### Qual é a versão do NodeJS que você está usando?

20.11.1

### Qual é a versão do NPM que você está usando?

10.2.4

### Qual é a versão do Python que você está usando?

3.12.2

### Qual é o seu sistema operacional? Marque todos os sistemas nos quais o erro ocorreu para você.

Windows

### Em que tipo de função ocorre o erro?

Mensagens, Comandos, Outros (Inserir detalhes nas Informações Adicionais)

### Você desligou a Íris de maneira não convencional, como desconectar o PC da tomada?

- [X] Sim, a Íris foi desligada de forma não convencional

### Você editou a Íris em tempo real sem reiniciar após a edição?

- [X] Sim, fiz edições na Íris enquanto ela estava em execução (Inserir detalhes nas Informações Adicionais)

### Você tentou usar o mesmo número em dois ou mais Bots ao mesmo tempo?

- [X] Sim, estou usando o mesmo número em dois ou mais Bots ao mesmo tempo

### Você está usando algum servidor, VPN, proxy ou serviço similar?

VPS, Outros (Inserir detalhes nas Informações Adicionais)

### Há mais alguma informação que você gostaria de compartilhar? Descreva as Informações Adicionais.

![Captura de Tela (3)](https://github.com/KillovSky/Iris/assets/77314121/1e52aef0-8a6c-476a-8d6f-f088d4b28e33)

**Comment by MatheusOFC** [comment]
algumas caixa obrigatória marquei só pra envia o problema

**Comment by KillovSky** [comment]
Você não possui python, siga o procedimento corretamente por gentileza e depois reporte aqui, note que o erro apresentado, além da falta de requisitos, é de permissão, pois você está escrevendo dentro da pasta raiz da pasta de usuários, um local categorizado como inseguro pelo Windows 10 e 11, ou seja, o Windows, Antivírus ou algum programa barrou a sua instalação por questões de segurança, mas não se preocupe, a Íris nunca teve e nunca terá quaisquer vírus, desde que você baixe pela Github oficial.

A correção disso seria instalar em uma pasta segura, como na área de trabalho ou dentro de uma pasta dentro da pasta "Documentos" do seu computador.

`C://Users/Nome/Documentos/GitHub/Iris` é um exemplo totalmente funcional e correto, inclusive, utilizo assim por aqui.

Se mesmo assim falhar, reinstale o Nodejs na versão **LTS** e não current e verifique novamente seus requisitos, desative o antivírus se preciso.

Se mesmo assim não funcionar, instale WSL, baixe Ubuntu 22.04 a partir dele e baixe a Íris pelo WSL.

`wsl --install -d Ubuntu-22.04`

A Íris poderá ser editada após isso simplesmente abrindo o Explorador de Arquivos do Windows e acessando o atalho Ubuntu e localizando a pasta `root`, local em que a Íris estará.

Uma dica: Ela roda melhor em WSL com Ubuntu 22.04 do que no Windows 10 nativo! Olhe o canal oficial dela no WhatsApp!
