### ISSUE TITLE
[NPM/NODE] -> Erro na Inicialização (Instalação de Módulos)

### ISSUE THREAD

**Issue by pablorere** [KillovSky/Iris#622]
### Você está usando a versão mais recente da Íris?

- [X] Sim, estou utilizando a versão mais recente da Íris

### Você seguiu corretamente as instruções de instalação?

- [X] Sim, segui todas as instruções de instalação conforme os guias

### Você tentou atualizar os módulos usando o comando "npm update"?

- [X] Sim, estou tentando com os módulos completamente atualizados

### Qual é a versão do NodeJS que você está usando?

22.11

### Qual é a versão do NPM que você está usando?

10.9.0

### Qual é a versão do Python que você está usando?

Python 3.12.6

### Qual é o seu sistema operacional? Marque todos os sistemas nos quais o erro ocorreu para você.

Windows

### Em que tipo de função ocorre o erro?

Outros (Inserir detalhes nas Informações Adicionais)

### Você desligou a Íris de maneira não convencional, como desconectar o PC da tomada?

- [X] Sim, a Íris foi desligada de forma não convencional

### Você editou a Íris em tempo real sem reiniciar após a edição?

- [X] Sim, fiz edições na Íris enquanto ela estava em execução (Inserir detalhes nas Informações Adicionais)

### Você tentou usar o mesmo número em dois ou mais Bots ao mesmo tempo?

- [X] Sim, estou usando o mesmo número em dois ou mais Bots ao mesmo tempo

### Você está usando algum servidor, VPN, proxy ou serviço similar?

Servidor, Outros (Inserir detalhes nas Informações Adicionais)

### Há mais alguma informação que você gostaria de compartilhar? Descreva as Informações Adicionais.

node:internal/modules/cjs/loader:1252
  throw err;
  ^

Error: Cannot find module 'command-exists'
Require stack:
- C:\Users\pablo\Documents\Iris-main\Iris-main\lib\Initialize\checker.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
    at Function._load (node:internal/modules/cjs/loader:1075:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (C:\Users\pablo\Documents\Iris-main\Iris-main\lib\Initialize\checker.js:7:23)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\pablo\\Documents\\Iris-main\\Iris-main\\lib\\Initialize\\checker.js'

**Comment by KillovSky** [comment]
Poste um print da tela do terminal COMPLETA após rodar o comando `npm i` e
irei analisar qual foi o problema.

Mas é de certo que é erro do `npm i`, provavelmente alguma coisa ta errada
por ai, seja falta de instalação de algum programa, erros de permissão ou
demais.

Em qui., 28 de nov. de 2024, 22:40, pablorere ***@***.***>
escreveu:

**Comment by KillovSky** [comment]
Poste um print da tela do terminal COMPLETA após rodar o comando `npm i` e irei analisar qual foi o problema.

Mas é de certo que é erro do `npm i`, provavelmente alguma coisa ta errada por ai, seja falta de instalação de algum programa, erros de permissão ou demais.

### Além disso, há relatos de problemas no canvas com o `Node.js` na versão atual, experimente fazer downgrade para a versão 20 ou 21, como consta nos tutoriais da Íris.

**Comment by KillovSky** [comment]
Etiquetas e título do post adaptados para uma melhor resposta e visualização na busca, mas caso o problema seja outro, me reservo a poder mudar os titulos e tags novamente, irei aguardar sua resposta ; )

**Comment by KillovSky** [comment]
Fechada devido a falta de resposta ou atividade do autor.
