### ISSUE TITLE
Erro /botfoto

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#63]
![image](https://user-images.githubusercontent.com/44541791/125290042-45741600-e2f6-11eb-950e-7a9f339e1295.png)
![image](https://user-images.githubusercontent.com/44541791/125291082-65f0a000-e2f7-11eb-890e-848994dacc16.png)
![image](https://user-images.githubusercontent.com/44541791/125290285-88ce8480-e2f6-11eb-9cb1-171c7890d000.png)

Como botar foto no Bot

**Comment by KillovSky** [comment]
Houve uma queda de muitos comandos da wa automate devido a uma possível atualizacão deles ou do **servidor do WhatsApp**, por hora, você pode tentar adicionando o código abaixo na frente do ```bkmypic == null``` mas antes do `)`, irei tentando corrigir todos os problemas que eu encontrar durante esse periodo.

```javascript
 || typeof bkmypic === 'object'
```

**Comment by maradona4** [comment]
Ok
