### ISSUE TITLE
Erro /level

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#64]
![image](https://user-images.githubusercontent.com/44541791/125469835-7de86aca-2bc3-400d-8c5a-9e9da7c636f4.png)

Grupos Zap
Admin: Eu
Membros: Boruto
Tem problema erro, ele tem xp
/nivel esta funcionar 
[Stats]
Nick: Boruto
XP: 283/375
lvl: 3
Msg: 11
Coin: 30

console: 
![image](https://user-images.githubusercontent.com/44541791/125470417-57042589-c19b-4f73-a012-b98ced460bae.png)

**Comment by KillovSky** [comment]
Isso aconteceu somente uma vez ou sempre acontece com ele?

**Comment by maradona4** [comment]
acho e bugs

**Comment by KillovSky** [comment]
> acho e bugs

Isso não responde a pergunta mas de toda forma, esse erro é no puppeteer que é usado pela wa automate, como já informei no outro, devido a um update muitos comandos pararam e todos precisam somente esperar que eles voltem naturalmente.
Como o comando funcionou com você, isso é considerado um `bug isolado` (erro que uma pessoa recebe e outras não - minha Íris está funcionando sem problemas nesse comando).
