### ISSUE TITLE
Bot não respondeu

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#65]
![image](https://user-images.githubusercontent.com/44541791/125651074-9943fcdd-a4ef-4c2f-b501-7fb6cb31ef23.png)

![Sem título](https://user-images.githubusercontent.com/44541791/125651254-4bf5f5fa-e283-4036-95bb-321b393966f8.png)

**Comment by KillovSky** [comment]
Aposto que quando você rodou outros comandos eles foram funcionais certo? Isso é apenas um caso de "suspensão" em si".
Em casos criticos simplesmente reiniciar corrige, e claro, se você não tiver mudado o prefix, se mudou cairia exatamente no seu problema, outra coisa que pode causar isso é ativar o ```Watch File``` da Íris, da qual **NÃO É RECOMENDADO** para longas quantidades de tempo como uma VPS, se for seu caso, de toda forma, é algo rarissimo de acontecer.

**Comment by maradona4** [comment]
agr já funciona, eu teste "remover grupos de bots" dps voltar adicionar bot agora funcionar comandos de volta /menu

**Comment by KillovSky** [comment]
Excelente! ^^

**Comment by maradona4** [comment]
:D
