### ISSUE TITLE
Comando de download parou

### ISSUE THREAD

**Issue by EmanuelPeixoto** [KillovSky/iris#70]
não é o mesmo problema do tópico anterior, eu já reinstalei tudo e mesmo assim n adianta, na versão anterior estava ok
![Screenshot_1](https://user-images.githubusercontent.com/86881881/126636448-651e2505-eacf-4120-b5eb-58d4e65ee398.png)

**Comment by PedroBatistop** [comment]
Na linha 817, onde lê-se `filesize < ${Number(config.Download_Size)}M`, substitua por `filesize < ${Number(config.Max_Download_Size)}M`.

**Comment by EmanuelPeixoto** [comment]
Funcionou, obgd
