### ISSUE TITLE
erro no comando /bed /fuse /sepia /spank /distract

### ISSUE THREAD

**Issue by EmanuelPeixoto** [KillovSky/iris#71]
Obtive erros no comando /bed → ENOENT, No such file or directory 'ERROR: 401' - Você pode ignorar.
Obtive erros no comando /sepia → ENOENT, No such file or directory 'ERROR: 401' - Você pode ignorar.
Obtive erros no comando /spank → ENOENT, No such file or directory 'ERROR: 401' - Você pode ignorar.
Obtive erros no comando /distract → ENOENT, No such file or directory 'ERROR: 401' - Você pode ignorar.
talvez tenha mais comandos que estejam assim, tou relatando aq pq talvez ajude em resolver

**Comment by PedroBatistop** [comment]
Boa tarde, poderia enviar o log completo do erro? pode ser print do terminal... Preciso de uma visão mais detalhada do erro.

**Comment by EmanuelPeixoto** [comment]
> Boa tarde, poderia enviar o log completo do erro? pode ser print do terminal... Preciso de uma visão mais detalhada do erro.

Só aparece isso

**Comment by KillovSky** [comment]
Error 401, um erro relacionado a um bloqueio de acesso a algo, mas essa mensagem de `no such file...` me diz que houve uma falha de acesso ao arquivo, mais especificadamente, parece ser as suas variaveis.
Você fez alguma edicão, instalou a Iris nova por cima da antiga ou está com modulos desatualizados? Se sim, atualize, reinstale ou desfaça edições.
Se não, verifique se o erro não está relacionado a permissão de pasta no computador ou VPS, ou seja, rode a Iris em locais como a area de trabalho, pasta downloads ou documentos, caso seja um local restrito como a **system32**, parece surreal mas, sim, muitos usuarios instalaram a Iris na pasta system32 ou na pasta root do Linux, por causa disso deram muitos erros de permissão, verifique seu local também.
Se nada resolver pode ser um erro relacionado ao canvas ou wa-automate e isso deverá ser automaticamente corrigido ou você deverá esperar uma atualizaão dos mesmos.
Estarei no aguardo de noticias sobre.

**Comment by KillovSky** [comment]
> > Boa tarde, poderia enviar o log completo do erro? pode ser print do terminal... Preciso de uma visão mais detalhada do erro.
> 
> Só aparece isso

Desejamos que mostre uma screenshot, pois lá exibe o erro completo e a linha responsavél, a forma que você enviou apenas nos diz sobre o erro 401.

**Comment by EmanuelPeixoto** [comment]
mudei a pasta para a rea de trabalho, continuou como estava, aí quando coloquei de volta no C: voltou ao normal

**Comment by KillovSky** [comment]
> mudei a pasta para a rea de trabalho, continuou como estava, aí quando coloquei de volta no C: voltou ao normal

Okay, que estranho, então o erro era realmente de permissão, mas se está funcionando é perfeito, obrigado pela Issue.
