### ISSUE TITLE
/stalkig para depois de usar algumas vezes

### ISSUE THREAD

**Issue by EmanuelPeixoto** [KillovSky/iris#72]
![Screenshot_2](https://user-images.githubusercontent.com/86881881/126645609-cc1eb7d3-e085-4139-95fa-9e349f136523.png)

**Comment by KillovSky** [comment]
O parametro user é relacionado a quem enviou a mensagem, certifique-se de ter a versão mais recente dos módulos.
Caso seja relacionado ao servidor do stalkig, isso quer dizer que não achou o usuario que procurava, mas me faltou definir uma mensagem de erro, agradeço por informar essa falta, esteja atento pelo proximo update, vou tentar fazer uma correção de diversos problemas.

**Comment by EmanuelPeixoto** [comment]
> O parametro user é relacionado a quem enviou a mensagem, certifique-se de ter a versão mais recente dos módulos.
> Caso seja relacionado ao servidor do stalkig, isso quer dizer que não achou o usuario que procurava, mas me faltou definir uma mensagem de erro, agradeço por informar essa falta, esteja atento pelo proximo update, vou tentar fazer uma correção de diversos problemas.

Tudo atualizado e usando o mesmo perfil do Instagram

**Comment by EmanuelPeixoto** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/86881881/126686100-efc5eb46-0f32-44b8-85f7-eb3b5c699e29.png)

**Comment by KillovSky** [comment]
> > O parametro user é relacionado a quem enviou a mensagem, certifique-se de ter a versão mais recente dos módulos.
> > Caso seja relacionado ao servidor do stalkig, isso quer dizer que não achou o usuario que procurava, mas me faltou definir uma mensagem de erro, agradeço por informar essa falta, esteja atento pelo proximo update, vou tentar fazer uma correção de diversos problemas.
> 
> Tudo atualizado e usando o mesmo perfil do Instagram

Você fez alguma edição? Pois a linha 802 cai no `break` de um comando adulto e não no stalkig que está muito distante dele, por isso me mostre a sua linha `802`.
Sobre q index ali, você ativou o `watch file` mas esqueceu de por a `require` no lugar do `kconfig`? Não acho que isso possa afetar o parametro `user` mas se fez isso, use a `require` conforme descrito no arquivo.

**Comment by EmanuelPeixoto** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/86881881/126686503-d4def10c-3335-4773-8467-f884c68c4f09.png)
 a modificação que diz foi colocar o case ttp e attp como comentário e colocar o outro sem bugs que você disponibilizou

**Comment by KillovSky** [comment]
> ![Screenshot_4](https://user-images.githubusercontent.com/86881881/126686503-d4def10c-3335-4773-8467-f884c68c4f09.png)
>  a modificação que diz foi colocar o case ttp e attp como comentário e colocar o outro sem bugs que você disponibilizou

Agora entendi perfeitamente, o erro foi em obter a foto do usuario, troque a linha `await kill.sendFile...` para ```await kill.reply(from, mess.insta(ig), id)``` e me diga se funcionou, também pode ser ```await kill.sendText(from, mess.insta(ig))```.

**Comment by EmanuelPeixoto** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/86881881/126689125-23240370-e9cd-4af2-ac49-9fde3b26dff3.png)
![Screenshot_6](https://user-images.githubusercontent.com/86881881/126689128-533e394d-e898-46ef-98d5-23d0b62adfad.png)
usando o primeiro comando

**Comment by EmanuelPeixoto** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/86881881/126689188-d1a196ce-d6c4-4664-bf52-948d5d43a71f.png)
![Screenshot_2](https://user-images.githubusercontent.com/86881881/126689192-692f81ab-35b8-4535-89a3-6662967ecbf8.png)
usando o segundo comando

**Comment by KillovSky** [comment]
> mesmo com o código sem nenhuma modificação ele ia, mas depois de uns 3 usos, ele parava, mesmo reiniciando o computador ou o bot, ele continua com o problema, aí talvez mais tarde ele volte ao normal

Segundo o @PedroBatistop, o instagram tem uma limitacão na quantidade de usos, irei ver como posso ajustar isso ou remover essa limitação, agradeço muito por informar!

**Comment by EmanuelPeixoto** [comment]
Eu que agradeço por ceder pra gnt um bot tão bom
