### ISSUE TITLE
Falha na inicialização por n dar "spawn" no chrome peloq parece

### ISSUE THREAD

**Issue by zYanK** [KillovSky/iris#76]
Error: failed to launch the browser process! Spawn C:\Program Files(x86)\Google\Chrome\Application\Chrome.exe ENOENT

**Comment by KillovSky** [comment]
Esse erro é referente a não encontrar o chrome, caso você não tenha instalado, instale-o.
Se ja instalou o Chrome, mova a pasta atual dele para a pasta que você recebeu no erro, isso permitira uma inicializacão, ou claro, abra a `function.js` e remova o `useChrome`, o que **NÃO** é recomendado.
Caso falhe, adicione esse parametro na `functions.js`:

`executablePath: 'Local do seu chrome',

Isso deve substituir o local de uso do Chrome.
