### ISSUE TITLE
/play

### ISSUE THREAD

**Issue by wesley0209** [KillovSky/iris#77]
![play](https://user-images.githubusercontent.com/83685462/127224456-de1847e4-1014-44f8-8456-80e8d23c2601.jpg)

Comando /play nao esta funcionando

**Comment by KillovSky** [comment]
Isso e por que você não possui os programas `Visual C++` instalados, baixe-os no site da `microsoft`, tanto a versão `x64` quanto a versão `x32`, instale todas, desde a `2008` a versão `2019` e qualquer outra que exista, um instalador com todos esses pacotes se chama `vc redist`.

**Comment by wesley0209** [comment]
Deu certo, muito obrigado
