### ISSUE TITLE
Erro ao iniciar

### ISSUE THREAD

**Issue by MatheusSan03** [KillovSky/iris#78]
Ele estava funcionando normalmente, tive que reiniciar o computador e iniciar o bot ele dá esse erro.

![sadasd](https://user-images.githubusercontent.com/78276706/127227358-3e94c535-7184-41cb-b00c-ff746cc8683c.png)

**Comment by KillovSky** [comment]
A sua reinicialização foi mal executada e causou uma corrupcão dos arquivos de XP.
Acesse a pasta `lib/config/gerais/backup` e selecione um dos arquivos de XP (`level-numero.json`), coloque ele na pasta `lib/config/gerais` e apague o arquivo `level.json`, após isso você deve renomear o novo arquivo de `level-numero.json` para `level.json`.
Isso fará uma restauracão do XP e a Iris iniciará tranquilamente.
Sempre que for reiniciar ou desligar, recomenda-se desligar a Iris pelo WhatsApp usando o comando `shutdown`.
