### ISSUE TITLE
[lock] /help

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#81]
![image](https://user-images.githubusercontent.com/44541791/127548260-106fae29-06ae-4dec-aa7c-6a5c67bd4792.png)

![image](https://user-images.githubusercontent.com/44541791/127548299-9fe49538-0f1f-4606-aad7-5230c840eb08.png)

![image](https://user-images.githubusercontent.com/44541791/127548499-bfeb9fc1-2b34-4aa1-9f82-bda3237135f2.png)

**Comment by KillovSky** [comment]
Definitivamente NÃO É um bug.
Isso ocorre pois a wa-automate não pode enviar mensagens para pessoas que NÃO fazem parte dos seus contatos.
Salve seu proprio número ou mande uma mensagem no privado da BOT, isso deve fazer funcionar.

**Comment by maradona4** [comment]
Entendi
