### ISSUE TITLE
/ATTP BUG

### ISSUE THREAD

**Issue by anonimo850** [KillovSky/iris#82]
ONTEM EU RESOLVI O BUG DO ATTP COM AQUELES CODIGOS QUE FORAM PASSADOS EM (Issues) Mas hoje apresentou outro Problema Do nada
![Capturar](https://user-images.githubusercontent.com/80079258/127568360-b151fb2e-5cb9-479e-a26f-f7501006a817.PNG)

**Comment by maradona4** [comment]
abre seu pastar "iris" 
Tambem abre "config.js"

cliclar teclado: CTRL - F 
Escrever:   case 'ttp'

Copiar codigo
case 'ttp':
	if (args.length == 0) return await kill.reply(from, mess.noargs() + 'palavras/words/números/numbers.', id)
	await axios.get(`https://api.xteam.xyz/ttp?file&text=${encodeURIComponent(body.slice(5))}`, { responseType: 'arraybuffer' }).then(async (response) => {
		const attp = Buffer.from(response.data, 'binary').toString('base64');
		await kill.sendImageAsSticker(from, attp, { author: config.author, pack: config.pack, keepScale: true })
	})
	break
	
case 'attp':
	if (args.length == 0) return await kill.reply(from, mess.noargs() + 'palavras/words/números/numbers.', id)
	await kill.reply(from, mess.wait(), id)
	await axios.get(`https://api.xteam.xyz/attp?file&text=${encodeURIComponent(body.slice(6))}`, { responseType: 'arraybuffer' }).then(async (response) => {
		const attp = Buffer.from(response.data, 'binary').toString('base64');
		await kill.sendImageAsSticker(from, attp, { author: config.author, pack: config.pack, keepScale: true })
	})
	break

**Comment by KillovSky** [comment]
Como visto acima, uma correcão sai na proxima atualização com o código acima já inserido.

Ref. #62
