### ISSUE TITLE
Gif lag

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#84]
![image](https://user-images.githubusercontent.com/44541791/127759643-396f7873-8115-499d-96da-734c00be9f26.png)

Tem problema lag Figurinhas GIF

**Comment by KillovSky** [comment]
Isso acontece somente em celulares com uma DPI pequena, olhe pelo PC, você verá que o sticker é perfeito e sem erros, mas um fix disso para os celulares vem em breve.

**Comment by maradona4** [comment]
Ok
