### ISSUE TITLE
Quero ser um boot

### ISSUE THREAD

**Issue by Milionari0** [KillovSky/iris#85]
Quero ser um boot como faço?

**Comment by KillovSky** [comment]
[Instalar](https://github.com/KillovSky/Iris/discussions/28)

*LEIA E ASSISTA POR COMPLETO* o tutorial que serve a ti de como instalar, boa sorte.
Se você usa `Android` e não tem experiencia com o Termux, Goorm ou até mesmo edições e programação, não tem muita paciencia ou outros, não é uma boa ideia usar a Íris e sim procurar um BOT que rode *NATURALMENTE* no termux.
Se você possui um PC, aprender a utilizar a Íris é relativamente bem fácil.
