### ISSUE TITLE
erro no comando /video

### ISSUE THREAD

**Issue by luizrn** [KillovSky/iris#86]
estou tendo um erro ao tentar baixar um vídeo do yt usando o comando /video [nome], retorna certinho a pesquisa com o link, porém na segunda etapa de mandar o vídeo, retorna isso (Puts, isso ultrapassa nosso limite de envio, mesmo na pior qualidade ele ainda é superior a 16MB, não irei poder te enviar, desculpe.), já experimentei aumentar o limite ate 150mb, porém o vídeo nao pesa nem 5mb e olhando o console retorna este erro, pode me ajudar?
![image](https://user-images.githubusercontent.com/10822915/127929413-e4b3d20e-8f2c-4490-b605-b8177670f4b0.png), ja testei também outros videos de 1mb

**Comment by KillovSky** [comment]
Leia o #70.

**Comment by luizrn** [comment]
funcionou obg
