### ISSUE TITLE
Bot não responde as mensagens

### ISSUE THREAD

**Issue by OSAMA0412** [KillovSky/iris#88]
Boa noite, estou tentando usar o bot novamente apos alguns meses no qual na epoca funcionava normalmente, instalei tudo nescessario inseri as API dei update nas vulnerabilidades, inicio o bot normalmente porem assim que eu insiro o comando para o bot ele não responde, chega a aparecer "digitando..." porem não envia nada, no console consta que ele recebeu mensagem mas não da retorno
![InkedScreenshot_11_LI](https://user-images.githubusercontent.com/80080357/127941924-124ce1cd-22ee-48cd-9ea5-141a31ce1c9c.jpg)

**Comment by KillovSky** [comment]
No privado você recebe resposta?

**Comment by OSAMA0412** [comment]
> No privado você recebe resposta?

Ele não responde nem em grupo nem privado está recebendo e visualizando

**Comment by KillovSky** [comment]
> > No privado você recebe resposta?
> 
> Ele não responde nem em grupo nem privado está recebendo e visualizando, e não apresenta erro algum no console 

Na #65 foi corrigido saindo e entrando de novo nos grupos, aparentemente pode ser a mesma issue, tente-a.
Também tente desconectar o WhatsApp WEB e conectar novamente.

**Comment by OSAMA0412** [comment]
> > > No privado você recebe resposta?
> > 
> > 
> > Ele não responde nem em grupo nem privado está recebendo e visualizando, e não apresenta erro algum no console
> 
> Na #65 foi corrigido saindo e entrando de novo nos grupos, aparentemente pode ser a mesma issue, tente-a.
> Também tente desconectar o WhatsApp WEB e conectar novamente

Só removi do grupo e já funcionou, obrigado pelo suporte, pode ser útil colocar num faq isso
