### ISSUE TITLE
Bot não responde

### ISSUE THREAD

**Issue by EvertonCdC** [KillovSky/iris#91]
coloquei ela em um grupo e tao mandando 2 msg e ja cai como flood, msm nas configs o antiflood estando a 1000 mil, o bot digita mas não manda nada, oq fazer?

**Comment by KillovSky** [comment]
Issue duplicada, sempre que possuir uma duvida, veja se já existe uma issue com o mesmo tema.

1000 no anti-flood significaria 1000 segundos para rodar a cada comando executado, tente apagar a pasta logs e reconectar no WhatsApp, para isso basta apagar o `Iris.data`.
Também atualize seus modúlos e tente em outros grupos e conversas, se você editou os códigos desfaça e por fim, se nada disso funcionar, reinstale do zero na **AREA DE TRABALHO** e teste com outro número, em um WhatsApp não modificado e que não seja o beta.

#88

**Comment by EvertonCdC** [comment]
Eu tinha pesquisado e não achei, mas funcionou, obg.
