### ISSUE TITLE
 GLib-GIO-WARNING

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#93]
![image](https://user-images.githubusercontent.com/44541791/128065706-e472233e-df76-4248-bb2b-1113d5d877d8.png)

UWP Warning?

**Comment by KillovSky** [comment]
O erro não é relacionado a Iris e sim a um problema entre o módulo `Sharp` e o `Microsoft One-Drive`, você instalou a Iris na pasta do `One-Drive`?
Se sim ou se não, tente desligar o `One-Drive` e mover a pasta para outro local que deve funcionar perfeitamente, mas de modo geral, creio que isso não afeta a funcionabilidade.

**Comment by maradona4** [comment]
Pastar usuario
![image](https://user-images.githubusercontent.com/44541791/128254418-3c72b30e-5d97-4321-b623-5b80e807d929.png)

![image](https://user-images.githubusercontent.com/44541791/128254485-f3ce31f3-e3f5-42f9-bdfb-4a1623041db5.png)

**Comment by KillovSky** [comment]
Tente na area de trabalho, mas é basicamente o que eu disse ali, não se trata de bug na Iris.
