### ISSUE TITLE
Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#94]
![image](https://user-images.githubusercontent.com/44541791/128426861-99464844-371b-4e68-b20d-99b5954eda08.png)

**Comment by KillovSky** [comment]
De forma geral, é um erro na sua VPS, não na Iris, não possuo uma ideia de solução pois não utilizo VPS, chuto que você está usando a AWS Lambda da Amazon, mas posso te dar umas dicas.

Primeiramente, verifique as configurações da sua VPS, especialmente as de memoria e permissão.
(Como faço isso? Bem, eu não sei, tente procurar sobre ou falar com a amazon.)

Enfim, as ideias.

1 - Seu node está desatualizado e isso causou uma falha de instalação do puppeteer.

2 - Você não possui **chrome.**

3 - Tente abrir com `sudo` (acho que essa vai falhar).

4 - Tente instalar em um local sem tanto bloqueio de permissão, procure por `chmod` para criar um local assim.

5 - Tente tirar o `useChrome` ou definir como `false`.

6 - Tente reinstalar a Iris.

7 - Tente recriar a VPS.

8 - Tenha total certeza que está usando as atualizações mais recentes da sua VPS, você sempre deve rodar `apt update` e `apt upgrade` após instalar ou criar uma maquina Linux, os comandos servem para atualizar os programas do Linux, pode ser necessário inserir `sudo` antes do `apt`.

9 - Fale com a sua provedora de VPS para saber sobre bloqueios de execução de aplicativos, em especial, o Chrome/Chomium.

10 - Minha última ideia de como corrigir é que você use o parametro `executablePath` para definir manualmente o local do navegador, o local em si é relativo e você precisa procurar por conta propria.
Para definir o `executablePath`, insira isso junto as **options** na `functions.js`.

```javascript
executablePath: '/Local_Do_Navegador',

Você pode também usar navegadores baseados no chromium, como o `Microsoft Edge`.

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/128426861-99464844-371b-4e68-b20d-99b5954eda08.png)
> 

De forma geral, é um erro na sua VPS, não na Iris, não possuo uma ideia de solução pois não utilizo VPS, chuto que você está usando a AWS Lambda da Amazon, mas posso te dar umas dicas.

Primeiramente, verifique as configurações da sua VPS, especialmente as de memoria e permissão.
(Como faço isso? Bem, eu não sei, tente procurar sobre ou falar com a amazon.)

Enfim, as ideias.

1 - Seu node está desatualizado e isso causou uma falha de instalação do puppeteer.

2 - Você não possui **chrome.**

3 - Tente abrir com `sudo` (acho que essa vai falhar).

4 - Tente instalar em um local sem tanto bloqueio de permissão, procure por `chmod` para criar um local assim.

5 - Tente tirar o `useChrome` ou definir como `false`.

6 - Tente reinstalar a Iris.

7 - Tente recriar a VPS.

8 - Tenha total certeza que está usando as atualizações mais recentes da sua VPS, você sempre deve rodar `apt update` e `apt upgrade` após instalar ou criar uma maquina Linux, os comandos servem para atualizar os programas do Linux, pode ser necessário inserir `sudo` antes do `apt`.

9 - Fale com a sua provedora de VPS para saber sobre bloqueios de execução de aplicativos, em especial, o Chrome/Chomium.

10 - Minha última ideia de como corrigir é que você use o parametro `executablePath` para definir manualmente o local do navegador, o local em si é relativo e você precisa procurar por conta propria.
Para definir o `executablePath`, insira isso junto as **options** na `functions.js`.

```javascript
executablePath: '/Local_Do_Navegador',
```

Você pode também usar navegadores baseados no chromium, como o `Microsoft Edge`.

Se nada da lista funcionar, temo que eu não consiga te ajudar, então talvez procurar soluções externas seja otimo, se puder, mudar sua VPS também é uma opção.*

**Comment by maradona4** [comment]
Entendi
