### ISSUE TITLE
teria algum jeito de desativar o bot por um tempo especifico em um único grupo?

### ISSUE THREAD

**Issue by EmanuelPeixoto** [KillovSky/iris#95]
teria algum jeito de desativar o bot por um tempo especifico em um único grupo?

**Comment by KillovSky** [comment]
> teria algum jeito de desativar o bot por um tempo especifico em um único grupo?

Basta ler o menu e você saberá que temos um comando chamado `/Mute`, mas de forma geral, limitar por tempo igual o `cassino`, não, todavia você pode usar o `/MutePV` com a ID do Grupo para mutar eles sem precisar estar no grupo e desmutar quanto quiser sem ninguém saber que você mutou.
Para fazer com que um grupo seja totalmente ignorado sem precisar digitar comandos, abra a `config.js` na linha [191](https://github.com/KillovSky/iris/blob/main/config.js#L191) e apenas insira a `groupId` que você pode adquirir com o `/Grupos`.
