### ISSUE TITLE
o bot ne

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#97]
queria saber se tem como colocar mais de um numero no bot e queria saber se tem como solocar variavel na mensagen de boas vindas personalizado com `${}`

**Comment by dodouuglas** [comment]
e queria saber como fuciona o comando !Upload do bot

**Comment by PedroBatistop** [comment]
Boa noite, é possível sim colocar mais de um número no bot, editando o "Owner" da seguinte maneira:

`"Owner": ["55XX123456789@c.us", "55XX987654321@c.us"],`

Ele fica no arquivo config.json na pasta

**Comment by PedroBatistop** [comment]
Boa noite, é possível sim colocar mais de um número no bot, editando o "Owner" da seguinte maneira:

"Owner": ["55XX123456789@c.us", "55XX987654321@c.us"],

Ele fica no arquivo config.json na pasta `lib > config > Gerais.` Você pode colocar mais de dois também, atente-se para a vírgula e as aspas.

Para customizar sua mensagem de welcome e por cima desativar a mensagem padrão da Íris, você deve rodar o comando `/greet`, a mensagem, o "|" e na frente dele escolher se deseja desativar a welcome padrão, por exemplo, `"/Greet Bem vindo! | on"`, o on desativa o welcome padrão, o off deixa ativado junto com a sua mensagem.

O comando /upload envia arquivos locais da sua máquina, como por exemplo `/upload c:/users/Pedro/Desktop/FotoFofa.png FotoFofa.png` enviará o arquivo png nomeado "FotoFofa" da área de trabalho.

**Comment by PedroBatistop** [comment]
Dê uma olhada na #46

**Comment by dodouuglas** [comment]
> Boa noite, é possível sim colocar mais de um número no bot, editando o "Owner" da seguinte maneira:
> 
> `"Owner": ["55XX123456789@c.us", "55XX987654321@c.us"],`
> 
> Ele fica no arquivo config.json na pasta `lib > config > Gerais.` Você pode colocar mais de dois também, atente-se para a vírgula e as aspas.
> 
> Para customizar sua mensagem de welcome e por cima desativar a mensagem padrão da Íris, você deve rodar o comando `/greet`, a mensagem, o "|" e na frente dele escolher se deseja desativar a welcome padrão, por exemplo, `"/Greet Bem vindo! | on"`, o on desativa o welcome padrão, o off deixa ativado junto com a sua mensagem.
> 
> O comando /upload envia arquivos locais da sua máquina, como por exemplo `/upload c:/users/Pedro/Desktop/FotoFofa.png FotoFofa.png` enviará o arquivo png nomeado "FotoFofa" da área de trabalho.

e pq eu queria mudar la nos arquivos para o bot marcar quem entrou tipo seja bem vindo `${purshname}`

**Comment by KillovSky** [comment]
> > Boa noite, é possível sim colocar mais de um número no bot, editando o "Owner" da seguinte maneira:
> > 
> > `"Owner": ["55XX123456789@c.us", "55XX987654321@c.us"],`
> > 
> > Ele fica no arquivo config.json na pasta `lib > config > Gerais.` Você pode colocar mais de dois também, atente-se para a vírgula e as aspas.
> > 
> > Para customizar sua mensagem de welcome e por cima desativar a mensagem padrão da Íris, você deve rodar o comando `/greet`, a mensagem, o "|" e na frente dele escolher se deseja desativar a welcome padrão, por exemplo, `"/Greet Bem vindo! | on"`, o on desativa o welcome padrão, o off deixa ativado junto com a sua mensagem.
> > 
> > O comando /upload envia arquivos locais da sua máquina, como por exemplo `/upload c:/users/Pedro/Desktop/FotoFofa.png FotoFofa.png` enviará o arquivo png nomeado "FotoFofa" da área de trabalho.
> 
> e pq eu queria mudar la nos arquivos para o bot marcar quem entrou tipo seja bem vindo `${purshname}`

```javascript
await kill.sendTextWithMentions(event.chat, `Seja bem vindo @${event.who.replace('@c.us', '')}!`)
```

Insira na `index.js` que vai funcionar.
