### ISSUE TITLE
Anti Porn

### ISSUE THREAD

**Issue by maradona4** [KillovSky/iris#98]
![image](https://user-images.githubusercontent.com/44541791/128571640-d8345a73-f4cf-447d-8bba-e8ef86cf49da.png)
![image](https://user-images.githubusercontent.com/44541791/128571805-50a8ceee-64c1-43b1-94f8-dda8ddcc4da1.png)

Meu grupos esse funcao ja ativada 18+ Anti Link e Anti Porn
Mas bot nao remover ? esse link Porn

meu grupos nsfw esse funcao desativar

**Comment by KillovSky** [comment]
> ![image](https://user-images.githubusercontent.com/44541791/128571640-d8345a73-f4cf-447d-8bba-e8ef86cf49da.png)
> ![image](https://user-images.githubusercontent.com/44541791/128571805-50a8ceee-64c1-43b1-94f8-dda8ddcc4da1.png)
> 
> Meu grupos esse funcao ja ativada 18+ Anti Link e Anti Porn
> Mas bot nao remover ? esse link Porn
> 
> meu grupos nsfw esse funcao desativar

Por algum motivo, o módulo `isPorn` não detectou como pornografia, não sei em si se isso pode ser considerado bug até que aconteça com mais pessoas, pois na minha visão, foi um erro temporario e isolado, acontece com outros links pornograficos ou acontece de novo e sempre no mesmo link?

**Comment by maradona4** [comment]
Entendi
