### ISSUE TITLE
documentaçao

### ISSUE THREAD

**Issue by dodouuglas** [KillovSky/iris#99]
gostaria de saber como usa o evento https://docs.openwa.dev/classes/api_Client.Client.html#onMessageDeleted ja q eu n vi nd q fale q e pago

**Comment by KillovSky** [comment]
Interessante, não havia visto que isso era um recurso gratuito, especialmente pois revisei tudo de la varias vezes, enfim...

Isso e um parametro de if, não posso te fornecer um codigo total pois é algo complicadinho, mas de forma geral, ele te da os dados da `object` chamada `message`, que é o que usamos na `config.js`.
Você deve inserir isso na `index.js`, creio eu, que dentro da `onMessage`, não tenho certeza pois ainda não usei tal parametro mas irei fazer um update com ele assim que possivel, lhe darei muitas utilidades hehehe

```javascript
kill.onMessageDeleted.then((msg) => { console.log(msg) })
```

Veja a resposta da `msg` e crie um código com base nela, os parametros que você vai receber na `message` estão detalhados [aqui](https://docs.openwa.dev/interfaces/api_model_message.Message.html), boa sorte.

**Comment by KillovSky** [comment]
> gostaria de saber como usa o evento https://docs.openwa.dev/classes/api_Client.Client.html#onMessageDeleted ja q eu n vi nd q fale q e pago

Interessante, não havia visto que isso era um recurso gratuito, especialmente pois revisei tudo de la varias vezes, enfim...

Isso e um parametro de if, não posso te fornecer um codigo total pois é algo complicadinho, mas de forma geral, ele te da os dados da `object` chamada `message`, que é o que usamos na `config.js`.
Você deve inserir isso na `index.js`, de preferência abaixo do código da `kill.onMessage`*, não tenho certeza pois ainda não usei tal parametro mas irei fazer um update com ele assim que possivel, lhe farei ter muitas utilidades hehehe

```javascript
kill.onMessageDeleted((msg) => { console.log(msg) })
```

Veja a resposta da `msg` e crie um código com base nela, os parametros que você vai receber na `message` estão detalhados [aqui](https://docs.openwa.dev/interfaces/api_model_message.Message.html), boa sorte*.

**Comment by PedroBatistop** [comment]
(NÃO OFICIAL) Função que grava as últimas 20 mensagens apagadas, podendo definir exceções de chats (pvs ou grupos) que vão ter as mensagens apagadas gravadas:

crie um arquivo "deleted.json" = `[{"exceptions":[], "msgs":[]}]`

Adicione isso abaixo da kill.onMessage na index.js:

```
	kill.onMessageDeleted(async (msg) => {
		const moment = require('moment-timezone')
		var deleted = JSON.parse(fs.readFileSync('./lib/config/Utilidades/deleted.json'))
		msg.t = moment(msg.t * 1000).format('DD/MM/YY HH:mm:ss')
		if (!deleted[0].exceptions.includes(msg.from)) {
			var contato = await kill.getContact(msg.from)
			var nome = contato.pushname == null ? 'wa.me/' + msg.from.replace('@c.us', '') : contato.pushname
			console.log('[DELETED]', msg.body, 'AS', color(msg.t, 'yellow'), 'DE', nome, '-', msg.from.replace('@c.us', ''))
			deleted[0].msgs.push(msg)
			console.log(deleted[0].msgs.length)
			if (deleted[0].msgs.length > 19) { deleted[0].msgs.shift() }
			await fs.writeFileSync('./lib/config/Utilidades/deleted.json', JSON.stringify(deleted))
		}	})
```

Comando para te enviar no Whatsapp as últimas 20 mensagens apagadas, para excluir ou incluir chats na função de gravar mensagens apagadas:

(adicione na parte "JSONS" da config.js)
`var deleted = JSON.parse(fs.readFileSync('./lib/config/Utilidades/deleted.json'))`

(adicione na config.js)
```
				case 'deleted':
				if (!isOwner) return await kill.reply(from, mess.sodono(), id)
				if (arks.includes('-exclude')) {
					deleted[0].exceptions.push(from)
					console.log(deleted[0].exceptions)
					await fs.writeFileSync('./lib/config/Utilidades/deleted.json', JSON.stringify(deleted))
					return await kill.reply(from, mess.disabled(), id)
				}
				if (arks.includes('-include') && deleted[0].exceptions.includes(from)) {
					let pos = deleted[0].exceptions.indexOf(from)
					deleted[0].exceptions.splice(pos, 1)
					await fs.writeFileSync('./lib/config/Utilidades/deleted.json', JSON.stringify(deleted))
					return await kill.reply(from, mess.enabled(), id)
				}
				var msgdels = 'Mensagens apagadas:\n\n'
				for (let i = 0; i < deleted[0].msgs.length; i++) {
					var contato = await kill.getContact(deleted[0].msgs[i].from)
					var nome = contato.pushname == null ? 'wa.me/' + deleted[0].msgs[i].from.replace('@c.us', '') : contato.pushname
					var contato2 = await kill.getContact(deleted[0].msgs[i].to)
					var nome2 = contato2.pushname == null ? 'wa.me/' + deleted[0].msgs[i].to.replace('@c.us', '') : contato2.pushname
					msgdels += 'De: ' + nome + '\n'
					msgdels += 'Para: ' + nome2 + '\n'
					msgdels += 'Quando: ' + deleted[0].msgs[i].t + '\n'
					msgdels += 'Mensagem: ' + deleted[0].msgs[i].body + '\n\n'
				}
				await kill.reply(from, msgdels, id)
				break
```

Use "/deleted" para ver a lista
Use "/deleted -exclude" para não gravar as mensagens apagadas do chat onde o comando foi dado
Use "/deleted -include" para gravar as mensagens apagadas do chat onde o comando foi dado

**Comment by KillovSky** [comment]
> (NÃO OFICIAL) Função que grava as últimas 20 mensagens apagadas, podendo definir exceções de chats (pvs ou grupos) que vão ter as mensagens apagadas gravadas:
> 
> crie um arquivo "deleted.json" = `[{"exceptions":[], "msgs":[]}]` na pasta Utilidades
> 
> Adicione isso abaixo da kill.onMessage na index.js:
> 
> ```
> 	kill.onMessageDeleted(async (msg) => {
> 		const moment = require('moment-timezone')
> 		var deleted = JSON.parse(fs.readFileSync('./lib/config/Utilidades/deleted.json'))
> 		msg.t = moment(msg.t * 1000).format('DD/MM/YY HH:mm:ss')
> 		if (!deleted[0].exceptions.includes(msg.from)) {
> 			var contato = await kill.getContact(msg.from)
> 			var nome = contato.pushname == null ? 'wa.me/' + msg.from.replace('@c.us', '') : contato.pushname
> 			console.log('[DELETED]', msg.body, 'AS', color(msg.t, 'yellow'), 'DE', nome, '-', msg.from.replace('@c.us', ''))
> 			deleted[0].msgs.push(msg)
> 			console.log(deleted[0].msgs.length)
> 			if (deleted[0].msgs.length > 19) { deleted[0].msgs.shift() }
> 			await fs.writeFileSync('./lib/config/Utilidades/deleted.json', JSON.stringify(deleted))
> 		}	})
> ```
> 
> Comando para te enviar no Whatsapp as últimas 20 mensagens apagadas, para excluir ou incluir chats na função de gravar mensagens apagadas:
> 
> (adicione na parte "JSONS" da config.js)
> `var deleted = JSON.parse(fs.readFileSync('./lib/config/Utilidades/deleted.json'))`
> 
> (adicione na config.js)
> ```
> 				case 'deleted':
> 				if (!isOwner) return await kill.reply(from, mess.sodono(), id)
> 				if (arks.includes('-exclude')) {
> 					deleted[0].exceptions.push(from)
> 					console.log(deleted[0].exceptions)
> 					await fs.writeFileSync('./lib/config/Utilidades/deleted.json', JSON.stringify(deleted))
> 					return await kill.reply(from, mess.disabled(), id)
> 				}
> 				if (arks.includes('-include') && deleted[0].exceptions.includes(from)) {
> 					let pos = deleted[0].exceptions.indexOf(from)
> 					deleted[0].exceptions.splice(pos, 1)
> 					await fs.writeFileSync('./lib/config/Utilidades/deleted.json', JSON.stringify(deleted))
> 					return await kill.reply(from, mess.enabled(), id)
> 				}
> 				var msgdels = 'Mensagens apagadas:\n\n'
> 				for (let i = 0; i < deleted[0].msgs.length; i++) {
> 					var contato = await kill.getContact(deleted[0].msgs[i].from)
> 					var nome = contato.pushname == null ? 'wa.me/' + deleted[0].msgs[i].from.replace('@c.us', '') : contato.pushname
> 					var contato2 = await kill.getContact(deleted[0].msgs[i].to)
> 					var nome2 = contato2.pushname == null ? 'wa.me/' + deleted[0].msgs[i].to.replace('@c.us', '') : contato2.pushname
> 					msgdels += 'De: ' + nome + '\n'
> 					msgdels += 'Para: ' + nome2 + '\n'
> 					msgdels += 'Quando: ' + deleted[0].msgs[i].t + '\n'
> 					msgdels += 'Mensagem: ' + deleted[0].msgs[i].body + '\n\n'
> 				}
> 				await kill.reply(from, msgdels, id)
> 				break
> ```
> 
> Use "/deleted" para ver a lista
> Use "/deleted -exclude" para não gravar as mensagens apagadas do chat onde o comando foi dado
> Use "/deleted -include" para gravar as mensagens apagadas do chat onde o comando foi dado

Obrigado, é perfeito!

**Comment by PedroBatistop** [comment]
código atualizado.
